### ISSUE TITLE
agones-allocator service should scale up independent to gameserverallocation extension API server

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1018]
**Is your feature request related to a problem? Please describe.**

The agones-allocator service acts as a reverse proxy, which directs the allocation requests without validation to GameServerAllocation extension APIServer to handle. 

agones-allocator and GameServerAllocation can be used for different purpose, and therefore potentially scale differently. In the current model if agones-allocator scales up to handle the increase in the incoming traffic, GameServerAllocation needs to scale up as well to handle traffic from agones-allocator.

**Describe the solution you'd like**
 The allocation logic should be factored out of [GameServerAllocation](https://github.com/googleforgames/agones/blob/master/pkg/gameserverallocations/controller.go) and turned to a stand alone library that both components reference. 

![image](https://user-images.githubusercontent.com/46979170/63812029-f4173500-c8dd-11e9-8807-fb240ba5b195.png)

**Comment by markmandel** [comment]
I think we can close this? We did this a while back, yes?

**Comment by pooneh-m** [comment]
Correct it is done.
