### ISSUE TITLE
Upgrade the SDK to proto3 along with the dependencies

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1026]
The Agones SDK is still on proto2.

**Comment by markmandel** [comment]
I don't think this is true? I'm pretty sure grpc was proto3 since the beginning?

What makes you think this is true?

**Comment by markmandel** [comment]
https://github.com/googleforgames/agones/blob/master/sdk.proto says proto3 at the top

**Comment by roberthbailey** [comment]
The only places I see proto2 are in the vendor_fixes directory: https://github.com/googleforgames/agones/search?q=proto2&unscoped_q=proto2

**Comment by pooneh-m** [comment]
the generated go file is still using [proto2](https://github.com/googleforgames/agones/blob/d6cb00728ae73d2f2c45e118e9d33ba57ccea480/pkg/sdk/sdk.pb.go#L40)

**Comment by pooneh-m** [comment]
Thanks. So the [package](https://github.com/googleforgames/agones/blob/master/build/build-sdk-images/go/Dockerfile#L32-L33) that generates the go code is v1.2, which is "proto package" v2. I got confused about the version of the package and the proto.

**Comment by pooneh-m** [comment]
I am already [upgrading](https://github.com/googleforgames/agones/pull/1027) the proto package to v3 and it is backward compatible.
