### ISSUE TITLE
Metrics: Players

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1035]
Dependent on #1033 

**Is your feature request related to a problem? Please describe.**
Need to integrate player tracking into metrics for aggregate dashboards.

**Describe the solution you'd like**
Metrics tracking and dashboards on:
- [ ] Game Server capacities
- [ ] Number of players per GameServer
- [ ] Empty player slots per GameServer
- [ ] Player connection length (how long they stay connected)
- [ ] Any others I can't think of right now.

**Describe alternatives you've considered**
Forcing users to do this on their own. A lot of work for what should be common metric requirements for a large part of our user base.

**Additional context**

**Comment by cyriltovena** [comment]
Metrics and tracking are usually different systems

**Comment by geeckmc** [comment]
+1

**Comment by markmandel** [comment]
I think we can close this, as we have tracking work in #2716 and there is actually also metrics for the alpha player tracking now as well.

**Comment by markmandel** [comment]
I think we can close this as well, since #2765 did some of the work, and we have counts and lists currently underway.
