### ISSUE TITLE
Metric: Game Server Frame Rate over time

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1036]
**Is your feature request related to a problem? Please describe.**
Every dedicated game server needs to track if it's running at the optimal, stable framerate, and also be able to alert if something is failing. We don't have any functionality to accomplish this right now.

**Describe the solution you'd like**
Some kind of integration into the Game Server SDK to track framerate, that sends this data out as metrics, and an accompanying dashboard.

I see there being two potential solutions (naming / organisation could be changed - sacrificial draft):

1) `SDK.frame()` - needs to be called every frame. Counts the framerate and averages it over time. Basically we control how this is calculated. More work for us, but we control it. 

2) `SDK.frameRate(int framesPerSecond)` - needs to be called every second, with the current frames per second, as reported by the engine. This is less work for us, but each user will need to calculate it themselves - which not all engines do. (what happens if someone calls this more than once per second?)

We could also potentially have both? But I'm leaning towards No. 1 as it's easier all around for us, and likely easier to integrate into commercial engines as a drop in component. But 2 is also handy if users are integrating with us via a sidecar container with their game server.

We may also want to expose the calculated frameRate through the SDK as well - as both debugging and information for the gameserver as well.

**Describe alternatives you've considered**
Honestly, couldn't think of anything better?

**Additional context**
https://answers.unity.com/questions/64331/accurate-frames-per-second-count.html
https://answers.unrealengine.com/questions/813911/how-to-get-the-fps-in-c.html?sort=oldest

**Comment by roberthbailey** [comment]
Would it make sense to build a more generic framework for collecting metrics rather than trying to plumb individual metrics through the SDK.

**Comment by markmandel** [comment]
I think we will need this anyway - but for metrics that are ubiquitous, I think it makes sense to have a standard path for them to go through, so we can build layers on top of that - i.e. dashboards etc.

Or did you mean something different? Everything has to be collected from within the GameServer somehow. We could namespace the metrics part mind you, or some kind of separation from the main SDK package? Is that what you are referring to?

**Comment by markmandel** [comment]
I'll add another note - I just wrote out a bunch of metrics tickets -- I am definitely not an expert in metrics, I just wanted us to track this metric information, and so wrote tickets to identify the work. I most _definitely_ defer to those that have more experience in metrics and monitoring to dictate how this should all be setup, and what is ideal. Please take this as a sacrificial draft.

**Comment by roberthbailey** [comment]
/cc @bbf 

If everything flows through the sidecar I'm worried a bit about it becoming overloaded and a SPOF. Right now it's in the path for the control plane for the game server, controlling the lifecycle of the game server. Adding metrics isn't the same as making it part of the data path, but it does introduce a whole bunch of new requirements in terms of responsiveness and availability. 

If we, for example, send it a frame rate message every second, plus a player count every N seconds plus a health ping every M seconds plus generic metrics every O seconds we will start to send it a lot more traffic than we do today (primarily just the health ping).

**Comment by markmandel** [comment]
I don't disagree. Maybe there should be a separate sidecar for gameserver specific metrics? (which gets us back to #1007, interestingly). 

Should we have a top level ticket re: metrics is in order, to discuss these type of design decisions?

**Comment by markmandel** [comment]
Closing!
