### ISSUE TITLE
Pass arbitrary metrics from gameserver -> opencensus

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1037]
**Is your feature request related to a problem? Please describe.**
There are always game specific metrics that also need to be tracked. To be duplicating the effort that already exists in Agones to connect some kind of metrics SDK into a game server seems like a waste of effort. 

**Describe the solution you'd like**

Some kind of way of exposing OpenCensus (eventually Open Telemetry) to the game server binary through the SDK in some fashion. Honestly not sure what the best way is - requires some investigation.

One thought is to build our own abstracted metrics API that (may) be close to OpenCensus - this allows us to replace the metrics backend if we need to (i.e. when OpenCensus becomes OpenTelemetry), without having to impact users. This is more work for us, but gives us portability.

**Describe alternatives you've considered**
N/A

**Additional context**
https://opencensus.io/
https://opentelemetry.io/

**Comment by geeckmc** [comment]
+1

**Comment by markmandel** [comment]
@domgreen How do ingest without reinventing the wheel?

**Comment by markmandel** [comment]
Capturing conversation from chat:

> Mark Mandel
The more we talk about this, the more I'm convinced this should be a standalone OSS project that has a sidecar (probably open telemetry) and grpc/rest interface (maybe rest+proto?) And proper game engine sdks that do appropriate Async/threaded operations to send data to keep it off the main loop (edited) 
>
> Mark Mandel
I don't think it has to be integrated with Agones at all. In fact it's probably more applicable if it isn't.

**Comment by markmandel** [comment]
Also, one could potentially also argue #2716 covers enough of this to for this issue to also be covered as well.
