### ISSUE TITLE
Proposal: Allocator service to return 400+ http status for failure 

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1040]
**Is your feature request related to a problem? Please describe.**
When allocating a game server, if there is an issue that the game server cannot be allocated, the allocator service response is 200 http status with the state of either ["unallocated" or "contention"](https://github.com/googleforgames/agones/blob/master/cmd/allocator/v1alpha1/allocation.proto#L58-L69). For a RESTful API, the http status represents the status of the result and receiving 200 for an unsuccessful response is contradicting. In kubernetes world, status is a good representation of the state of a CRD, but this is not be the standard for REST APIs. 

**Describe the solution you'd like**
The allocation REST API should return a meaningful http status in case of failure instead of 200. My proposal is to return 429 http status ([ResourceExhausted](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/errors.go#L37-L38) grpc code) for unallocated state and 409 for contention.

**Comment by markmandel** [comment]
So I didn't realise that gRPC has codes that translate to HTTP Status codes through the grpc-gateway.

I think that was the blocking issue in my mind - but now I realise this, I'm 100% on board.
