### ISSUE TITLE
SDK package should be versioned

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1043]
Currently the sdk package is not versioned. They should be versioned in case there are breaking changes in the future.
https://github.com/googleforgames/agones/blob/master/sdks/go/sdk.go#L16
https://github.com/googleforgames/agones/blob/master/sdk.proto

**Comment by markmandel** [comment]
How do you think we should be versioning?

Ideally, these sdks should never, ever break.

**Comment by pooneh-m** [comment]
It is not expected that the SDK would have a breaking change, but that's the assumption that almost everyone make when building a product and history proven that it will happen at one point. Using a package name that reflects the version and putting sdks in the version directory is one approach.

**Comment by roberthbailey** [comment]
@pooneh-m - do you expect that someone would need to import multiple versions of the SDK into a single build (so that they would need different package names)? Or that if we made a breaking change the sidecar would export both the old and new grpc endpoints simultaneously (maybe even on different ports)?

I wouldn't mind having the gRPC API between the sdk and the sidecar have a version in the name (e.g. v1) but now that we have released 1.0 of Agones I'm not sure how we actually change the SDK proto in a backwards compatible way to achieve this. It seems like adding versioning to the sdk package would itself be a breaking change....

What if we left the current proto unversioned and if/when we need a breaking change we create a v2 of the interface (e.g. `sdk2.proto`) and add a concrete version at that point?

**Comment by pooneh-m** [comment]
> @pooneh-m - do you expect that someone would need to import multiple versions of the SDK into a single build (so that they would need different package names)? Or that if we made a breaking change the sidecar would export both the old and new grpc endpoints simultaneously (maybe even on different ports)?
> 

No, we don't expect multiple SDK versions in a single build, but if a breaking change is introduced to SDK, the old stable version should still work and users should be able to choose either versions.

> I wouldn't mind having the gRPC API between the sdk and the sidecar have a version in the name (e.g. v1) but now that we have released 1.0 of Agones I'm not sure how we actually change the SDK proto in a backwards compatible way to achieve this. It seems like adding versioning to the sdk package would itself be a breaking change....
> 
> What if we left the current proto unversioned and if/when we need a breaking change we create a v2 of the interface (e.g. `sdk2.proto`) and add a concrete version at that point?

Makes sense to introduce package versioning for sdk after v2 to avoid breaking change to v1.

**Comment by markmandel** [comment]
This related to the conversation [in the feature stages documentation](https://github.com/googleforgames/agones/pull/1080#discussion_r329839415).

How does this also work technically? Do we need to run multiple port endpoints with gRPC, or can we do an include from a main.proto for all the versions? which will serve all the packages from a single endpoint?

I've never done this, so I'm not sure how it could work.

**Comment by roberthbailey** [comment]
Mark - I think you said you were doing some investigation about serving multiple gRPC endpoints; did you find anything relevant?

**Comment by markmandel** [comment]
Still trying to get an answer actually. Basically, can you import a proto with a different package that has another service in it?

I suppose I could make a test case, and see what happens!

**Comment by markmandel** [comment]
Aha, so I found the right stackoverflow post:
https://stackoverflow.com/questions/52634217/access-multiple-grpc-services-over-the-same-connection

This shows we can both register multiple services with the same endpoint, and also configure a singular connection with multiple clients - at least with Go.

Even if we end up having 2 connections to the same local endpoint, I don't think it's a drastic issue?
