### ISSUE TITLE
Create Agones resources in non-default namespace

### ISSUE THREAD

**Issue by Yingxin-Jiang** [googleforgames/agones#1084]
After installing Agones, Agones resources, such as fleets and gameServers, can be created in default namespace. 

To create resources in another namespace, users need to:
1) create the namespace
2) create agones-sdk service account and bind the service account to ClusterRole agones-sdk
It's not easy to figure out the second step.

Would it be helpful to allow user to provide one or more non-default namespaces during Agones installation?

**Comment by markmandel** [comment]
See:
https://agones.dev/site/docs/installation/helm/#configuration
`gameservers.namespaces` configuration option.

Does that do what you are looking for?

**Comment by Yingxin-Jiang** [comment]
Great. I will try that. Thanks!

**Comment by Yingxin-Jiang** [comment]
Yes, that's exactly what I was looking for. Thanks
