### ISSUE TITLE
provisioning and attaching volume after container allocation

### ISSUE THREAD

**Issue by itthought** [googleforgames/agones#1089]
Hi,
I have one use case. Is there any way to attache volume when container is allocating to some user?

**Comment by markmandel** [comment]
You would need to attach the volume when you define the container. Once the GameServer's pod has started, you can't edit it to attach a specific volume.

https://kubernetes.io/docs/concepts/storage/volumes/ should help you get started.

**Comment by markmandel** [comment]
I'm going to close this, as it hasn't been updated in 23 days. Please reopen if you have a follow up.
