### ISSUE TITLE
Better documentation for BufferPolicy in fleetautoscaler 

### ISSUE THREAD

**Issue by Yingxin-Jiang** [googleforgames/agones#1104]
**Is your feature request related to a problem? Please describe.**
Missing documentation for BufferPolicy in fleetautoscaler, defined in  https://github.com/googleforgames/agones/blob/master/pkg/apis/autoscaling/v1/fleetautoscaler.go#L85?

**Describe the solution you'd like**
Please provide better documentation for BufferPolicy defined in fleetautoscaler. For example, (1) when should percentage bufferSize be used; (2) what are the recommendations for maxReplicas and minReplicas when bufferSize is absolute or percentage; (3) is it okay to set maxReplicas and minReplicas as optional etc..

**Comment by aLekSer** [comment]
There is auto-generated documentation, which is here:
https://agones.dev/site/docs/reference/agones_crd_api_reference/#BufferPolicy

**Comment by Yingxin-Jiang** [comment]
I read the documentation before creating the issue. 
For MinReplicas, it says "... If zero, it is ignored... ". Does this mean MinReplicas is an optional parameter? If I have MinReplicas=0, BufferSize=20%, MaxReplicas=100, how many game servers will be in ready state?

**Comment by markmandel** [comment]
From: https://agones.dev/site/docs/reference/fleetautoscaler/

> minReplicas is the minimum fleet size to be set by this FleetAutoscaler. if not specified, the minimum fleet size will be bufferSize if absolute value is used. When bufferSize in percentage format is used,

What is this when `bufferSize` is a percentage? I couldn't work it out from the code.

**Comment by aLekSer** [comment]
Returning back to this ticket

**Comment by markmandel** [comment]
I'm pretty sure this is complete, yeah? We can close it?

**Comment by markmandel** [comment]
Closing. Please let me know if it needs to re-opened.
