### ISSUE TITLE
Swagger: WatchGameServer() definition is not generated properly in sdk.swagger.json

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1106]
There is an issue with v1.5.0 version of GRPC Gateway library which is used to generate `sdk.swagger.json` file. 

**What happened**:

Test I created in #1079 could not parse properly the newline terminated JSONs stream which is a response to  `gameserver/watch` endpoint.
Investigation of this issue source and ways of retaliation could be found in the #1079 ticket.

**What you expected to happen**:
Properly sdk.swagger.json should be generated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
We could update the GRPC Gateway to the most recent version in Agones repo.
I have attached the version of `sdk.swagger.json` which was generated with it.

**Environment**:
- Agones version: 1.0
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): N/A
- Troubleshooting guide log(s):
- Others:

**Comment by aLekSer** [comment]
One more issue which we should tackle after upgrading `GRPC-gateway` is that there is no swagger generators which would properly generate go client for the `x-stream-definitions`:
```
  "x-stream-definitions": {
    "sdkGameServer": {
      "type": "object",
      "properties": {
        "result": {
          "$ref": "#/definitions/sdkGameServer"
        },
        "error": {
          "$ref": "#/definitions/runtimeStreamError"
        }
      },
      "title": "Stream result of sdkGameServer"
    }
  }
```

**Comment by aLekSer** [comment]
Attaching sdk.swagger.json generated with the most recent version of GRPC Gateway.
[sdk.swagger.json.txt](https://github.com/googleforgames/agones/files/3712429/sdk.swagger.json.txt)

**Comment by markmandel** [comment]
I think we can close this now, yes?

I have a working client for this, both Go and Unity (#1234).

**Comment by markmandel** [comment]
Going to close this, I think this is now fixed. Please reopen if it's still an issue.
