### ISSUE TITLE
The default resync period is too low

### ISSUE THREAD

**Issue by maisem** [googleforgames/agones#1109]
**Is your feature request related to a problem? Please describe.**
The problem is kind of related to #1107. If there are a lot of resources created by agones, the controllers end up resyncing the entire world every 30s.
This causes all the resources to be readded to the queue every 30s, potentially masking code bugs related to reacting to the correct set of events. Ideally everything should react to changes in the world.

**Describe the solution you'd like**
I propose that the default resync period should be >1 hour. This will make the agones controllers more event driven than time driven.

**Comment by markmandel** [comment]
I'm curious what makes this an actual problem? Are we seeing CPU spikes, slowdowns, or other such issues?

The controller is meant to be self healing, so if it goes down, it should do a full resync regularly just to check that things are in the state they should be. 1 hour seems like a long time.

30 seconds is what Kubernetes uses [in it's examples](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-controller/main.go#L62-L63) - which did seem appropriate given the highly dynamic nature of what we are working on (far more dynamic than most Kubernetes resources).

**Comment by markmandel** [comment]
I'm going to close this issue, as it hasn't seemed to come up as an concern since it was initially brought up. Please re-open or create a new issue if it becomes a concern again.
