### ISSUE TITLE
Refactor Docker files for gRPC between SDK and allocation

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1115]
**Is your feature request related to a problem? Please describe.**
There are generic functionalities for generating code that are included as part of the sdk build collateral. More specifically, ```build-sdk-images/tool/base``` and ```build-sdk-images/[lang]/Dockerfile``` are also referenced by ```includes/allocation.mk``` and copied to ```build-allocation-images``` respectively.

**Describe the solution you'd like**
There should be refactoring to move the common docker files to be referenced by SDK and allocation make files.

**Comment by aLekSer** [comment]
There seems to be an issue with naming of base image for allocator:
https://github.com/GoogleCloudPlatform/agones/blob/e3cb6f2f3f58a742501d0fa2453a8253cf86aeea/build/build-allocation-images/go/Dockerfile#L13-L14
`agones-build-allocation-base` in `build/includes/allocation.mk`
ARG BASE_IMAGE=agones-build-allocator-base:latest
@pooneh-m @akremsa can you take a look?

**Comment by aLekSer** [comment]
This one was fixed.
