### ISSUE TITLE
Allow issues to be assigned to collaborators

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#1120]
Prow is constantly complaining that it can't assign PRs to folks because they aren't a collaborator on the repository (and the same thing also prevents us from manually assigning issues or PR reviews to people). We need to figure out a way to fix this.

I think we can do this in one of two ways:

1. Set a low bar for adding folks to the googleforgames github org. 
1. Set a low bar for adding folks as collaborators to the agones repo.

In both cases, I think we need a low bar because we want to make it really easy to add folks that are actively contributing so that they (and we) can interact with github more seamlessly. 

The [requirements to be a member of the Kubernetes community](https://github.com/kubernetes/community/blob/master/community-membership.md#community-membership) are pretty onerous and similar to what we ask folks to do to be an _approver_ for agones. This feels too heavy weight (in my opinion), but maybe a streamlined version of that process would make sense (we should definitely require having 2nd factor enabled though). 

__Caveat__: I'm not sure if there are any legal / other issues that prevent us from adding folks to the github org or to the repo. If so, let's work on those and see what we can do to make the experience better for everyone. 

/assign @thisisnotapril

**Comment by roberthbailey** [comment]
This is blocking https://github.com/googleforgames/agones/pull/1119.

**Comment by markmandel** [comment]
I'm not seeing any downsides to having a low barrier to entry for read access on the Agones repo.

Seems like an easy win, unless there are downsides I'm not thinking of? As long as it's only read access, I assume it's fine.

**Comment by thisisnotapril** [comment]
It's easy to make folks contributors to the repo. I'll create an issue template, and then folks who want to be added can request it easy.

**Comment by thisisnotapril** [comment]
@roberthbailey I've added Steven as a collaborator; so once he accepts should be all good to go!

**Comment by thisisnotapril** [comment]
Closing - issue template created; let's direct all future collaborators there
