### ISSUE TITLE
Rebuild example images for the 1.1 release

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#1126]
For the 1.1 release I've introduced changes to the SDKs to make the sdkserver port dynamically configurable. We need to rebuild all of the official example images to pick up the SDK changes. 

I think the normal release checklist updates the golang example-udp image, but for this release we should update all of them. 

/cc @markmandel

**Comment by markmandel** [comment]
FYI - the normal release checklist doesn't update any of the images, just makes sure the release notes track any updates accurately.

So if we want to update all the examples, then a separate ticket like this is the way to do it :+1:

**Comment by roberthbailey** [comment]
I'm happy to help updating the images (now that I have all of the SDK changes in).

**Comment by markmandel** [comment]
@roberthbailey where you going to tackle this? Or should I take it on?

(Or we can do it Monday)

**Comment by roberthbailey** [comment]
/assign

I can start working on it.
