### ISSUE TITLE
CI: Build cache cpp-sdk-build contains unnecessary archives

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1136]
Currently the following files are added to build cache for every new build:
```
agonessdk-1.0.0-b8432d1-linux-arch_64.tar.gz
```
**What happened**:

**What you expected to happen**:

The moment it happened is here:
https://github.com/googleforgames/agones/blob/88f1d4eebf96584322efa2dfb981a672590a4bc0/sdks/cpp/Makefile#L38
I expect that  `package_path` (`.install`) would be used to store all the archives. And `.build` would contain only files needed for the build.

**How to reproduce it (as minimally and precisely as possible)**:
`du -sh ./sdks/cpp/.build`
`make archive`
`du -sh ./sdks/cpp/.build` - becomes significantly bigger but should not.

**Anything else we need to know?**:

**Environment**:
- Agones version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
This is why the cpp build cache is 6+ GB at the moment.

Worth noting, changing this position of these artifacts will affect the cloudbuild.yaml and also the `do-release` target (and maybe some others) so it's worth a review to see what can be found.
