### ISSUE TITLE
GKE: Update documentation + Automation to disable node automatic updates for gameserver node pools

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1137]
```
Starting November 8, 2019, we will enable node autoupgrades by default for new clusters and node pools created with the Google Cloud Platform Console, gcloud command line (CLI), and the Google Kubernetes Engine (GKE) API. We are making this change to ensure your clusters have the most recent default Kubernetes version, bug fixes, and security patches.
```

Since this could break in-game play, we should have our examples and automation disable it by default, for at least the gameserver nodepools (maybe agones-system as well?)

This might be a good opportunity to update the Terraform scripts for GKE + Agones, and remove/replace the deployment manager scripts in the development tooling while we are at it.

**Comment by roberthbailey** [comment]
November 8th is ~1 week after we cut the 1.1 release, so it would make sense to update the install instructions before the 1.1 release to address this.

**Comment by roberthbailey** [comment]
> This might be a good opportunity to update the Terraform scripts for GKE + Agones, and remove/replace the deployment manager scripts in the development tooling while we are at it.

I'm not going to have time to tackle this part right now. I think it's ok if development clusters created via deployment manager have auto upgrades enabled until we can fix it, since I expect that they get recycled more frequently.

**Comment by roberthbailey** [comment]
@aLekSer - do you have interest in replacing deployment manager with terraform?

**Comment by aLekSer** [comment]
Yes, I can do that. However I think version with gcloud tool should stay/renamed.

**Comment by aLekSer** [comment]
Currently producing a version of `make gcloud-test-cluster` and `make clean-gcloud-test-cluster` targets with Terraform (to get rid of deployment-manager).

**Comment by markmandel** [comment]
This has been done!
