### ISSUE TITLE
Move terraform modules from ./build to ./install

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1150]
`./build` is more for development tooling. It probably makes more sense/be more intuitive to have it under `./install`

Maybe something like `./install/terraform`

**Comment by amitlevy21** [comment]
Hi @markmandel !
Can I work on this?

**Comment by markmandel** [comment]
@aLekSer I don't think you've started on this, yeah?

Outside of that, I don't see any issue :+1:

**Comment by aLekSer** [comment]
@amitlevy21 yes, go ahead, it would be helpful someone review what I have done along doing this transition to new directory.

**Comment by amitlevy21** [comment]
@aLekSer  so you have already moved the files and would like me to review the changes after you open a PR?

**Comment by aLekSer** [comment]
@amitlevy21 I mean different - if you make this PR and look through the file structure (in a `build` directory) I have used that would be great. I have not made this transition to `install`, so you can start.

**Comment by amitlevy21** [comment]
What about build/cluster.tf and build/helm.tf? Should I move them as well?
So far I moved only the build/modules folder to install/modules. I ran `make terraform-init` which successfully init terraform in the container and `make test`. Would that suffice to ensure I have made the right changes?

**Comment by aLekSer** [comment]
@amitlevy21 Thanks for taking this ticket.
I think it would better to place all of them under `./install/terraform/` For instance `./install/terraform/modules`.
`make terraform-init` is part of the job.
`make gcloud-terraform-cluster`, `make gcloud-terraform-install` and after all run `make gcloud-terraform-destroy-cluster`.
Another way of how we can deploy using terraform could be found here:
[Install with Terraform](https://agones.dev/site/docs/installation/terraform/)
No need to run `make test`, after installation you should at least be able to create a fleet.
When you open a PR I would able to run all these 4 Make targets and give a feedback.
