### ISSUE TITLE
Quickstart: Create a Fleet Autoscaler with Webhook Policy

### ISSUE THREAD

**Issue by moesy** [googleforgames/agones#1151]
https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/

The "Getting Started" sections apply Kubernetes resources through files stored on gist. When we get to the "Create X509 Root and Webhook certificates" section however the final step:

```
# Copy the output of the command above and replace the caBundle field in your text editor:
vim $GOPATH/src/agones.dev/agones/examples/webhookfleetautoscalertls.yaml
```
requires the user to edit the ```webhookfleetautoscalertls.yaml``` file before applying it to a cluster. 

To provide greater clarity to users it might be helpful to call out installing golang and fetching the agones package in the prerequisites section. Alternatively the steps could be changed download the file from gist and make a local edit.

**Comment by roberthbailey** [comment]
I like your suggestion of downloading the file. Then we can point to the version of the file in the proper release branch (e.g. download `https://raw.githubusercontent.com/googleforgames/agones/release-1.0.0/examples/webhookfleetautoscalertls.yaml`) and we will know that the file is compatible with the other files in the walkthrough (and the instructions, which can change between releases).

**Comment by aLekSer** [comment]
That's right we should review and updates documents on FleetAutoscaler.

/assign alekser
