### ISSUE TITLE
Update example containers to fix security vulnerabilities

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#1154]
While working on https://github.com/googleforgames/agones/issues/1126 and verifying that the new images were successfully uploaded, I noticed that many of our images have vulnerabilities that are identified by Google's automated image analysis.

Most of the vulnerabilites are probably just because we are using older dependencies in the base image layers (e.g. linux distro with outdated glibc) and should be easy to fix by going through the Dockerfiles and updating them to pick up patches.

**Comment by aLekSer** [comment]
Have enabled containers security analysis, now I am able to see them. Useful links to enable this feature:
https://cloud.google.com/container-registry/docs/enabling-disabling-container-analysis
https://cloud.google.com/container-registry/docs/get-image-vulnerabilities

**Comment by markmandel** [comment]
Just looking through the examples - with the exclusion of the Unity sample (which requires a Unity licence to update, which requires so work to get 😄 ) everything else looks relatively up to date.

I'm figuring we close this, and if need be open a specific ticket to update the Unity example ?

**Comment by roberthbailey** [comment]
> I'm figuring we close this, and if need be open a specific ticket to update the Unity example?

sounds good to me.

**Comment by markmandel** [comment]
Looks like we marked this stale in July 😄 - going close it, since there is no objections.
