### ISSUE TITLE
Secure connection to gameserver

### ISSUE THREAD

**Issue by Cyansilver** [googleforgames/agones#1182]
Hi,

As I understand, the client will connect directly with game server through IP and port without load balancer. So I wonder how we secure the connection between them?

Thank you

**Comment by roberthbailey** [comment]
What kind of security are you thinking of? Authentication, authorization, something else?

**Comment by Cyansilver** [comment]
hi @roberthbailey ,

I'm thinking about the encrypting data with ssl cert like when the api called through a domain with https

**Comment by roberthbailey** [comment]
That is up to the game server to implement. Some games will run over UDP (where you could use [DTLS](https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security)) and other will use TCP (where TLS could be used). Some games may not want encrypted data and others may view it as a requirement. Agones will work with either type of game server but isn't opinionated on whether the game server uses encryption or not.

**Comment by Cyansilver** [comment]
I see, thank you
