### ISSUE TITLE
[helm] Missing imagePullSecrets Option in agones-ping Deployment

### ISSUE THREAD

**Issue by lystor** [googleforgames/agones#1185]
Hello

It is impossible to deploy agones-ping service with private Docker Registry due to missing imagePullSecrets: option in agones-ping deployment.

Agones controller has support of imagePullSecrets option (see https://github.com/googleforgames/agones/pull/358)

Please add it to agones-ping too.

Thank you

**Environment**:
- Agones version: 1.1.0

**Comment by roberthbailey** [comment]
Good catch!

Do you think that we could expect the same pull secret to work for all agones images or does each one need a separate parameter? I would lean towards having a single pull secret but I'm curious if you think we need multiple ones. Thanks.

**Comment by lystor** [comment]
I think the single pull secret should be used.

**Comment by roberthbailey** [comment]
Are you interested in making a PR to fix this? It should be similar to the one you referenced above.

**Comment by aLekSer** [comment]
I can do this update.

/assign alekser
