### ISSUE TITLE
Undocumented dependencies for make run-sdk-conformance-local

### ISSUE THREAD

**Issue by rib** [googleforgames/agones#1199]
**What happened**:
Looking at [**The Simple Rust Example**](https://github.com/googleforgames/agones/tree/master/examples/rust-simple) I tried to follow the [instructions for testing locally](https://github.com/googleforgames/agones/tree/master/examples/rust-simple#testing-locally-without-docker) but found that running ` make run-sdk-conformance-local TIMEOUT=120 TESTS=ready,watch,health,gameserver,shutdown` fails ro run due to some undocumented requirements to first build licenses via `make build-licenses` and `dependencies-src.tgz` files via `make build-required-src-dist`

Initial error seen:
```
Step 4/6 : COPY --chown=agones:root ./bin/LICENSES ./bin/dependencies-src.tgz /home/agones/
COPY failed: stat /var/lib/docker/tmp/docker-builder115697281/bin/LICENSES: no such file or directory
```
Next error seen after running `make build-licenses`:
```
Step 4/6 : COPY --chown=agones:root ./bin/LICENSES ./bin/dependencies-src.tgz /home/agones/
COPY failed: stat /var/lib/docker/tmp/docker-builder026686807/bin/dependencies-src.tgz: no such file or directory
```

**What you expected to happen**:
Expected that running ` make run-sdk-conformance-local TIMEOUT=120 TESTS=ready,watch,health,gameserver,shutdown` would automatically build whatever it depends on, including the `LICENSES` and `dependencies-src.tgz` files if missing.

**How to reproduce it (as minimally and precisely as possible)**:

First make sure to delete any pre-existing agones-sdk docker image:
```bash
docker rmi -f gcr.io/agones-images/agones-sdk:1.1.0-f891609
```

Then run `make run-sdk-conformance-local` in a pristing 1.1.0 repo:
```bash
git clone  git@github.com:googleforgames/agones.git -b release-1.1.0 agones-1.1.0
cd agones-1.1.0/build
make run-sdk-conformance-local TIMEOUT=120 TESTS=ready,watch,health,gameserver,shutdown
```

**Anything else we need to know?**:
Workaround:
```bash
cd build
make build-licenses
make build-required-src-dist
make run-sdk-conformance-local TIMEOUT=120 TESTS=ready,watch,health,gameserver,shutdown
```

**Environment**:
- Agones version: 1.1.0 and master
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): N/A
- Troubleshooting guide log(s): N/A
- Others: N/A

**Comment by aLekSer** [comment]
@rib  Thank you for such a descriptive ticket and for a provided workaround.
\assign

**Comment by aLekSer** [comment]
Same applies to  `make run-sdk-conformance-test-go`. Was not discovered because of sequence of builds in Cloud Build CI.
