### ISSUE TITLE
devloping application to Access Agones via the Kubernetes API with compile error

### ISSUE THREAD

**Issue by jasoncheung53** [googleforgames/agones#1212]
**What happened**:
I am new to agones, just following the example in https://agones.dev/site/docs/guides/access-api/ .
when i trying to build it, it show an error.
in line `agonesClient, err := versioned.NewForConfig(config)`

`cannot use config (type *"k8s.io/client-go/rest".Config) as type *"agones.dev/agones/vendor/k8s.io/client-go/rest".Config in argument to versioned.NewForConfig`

Am i missing any steps on doing this, please let me know thanks!

**What you expected to happen**:
build successful

**Environment**:
- Agones version: v1.2.0-rc
- k8s.io version: same version as Agones vendor folder's k8s.io

**Comment by aLekSer** [comment]
We might need to add this example into the repo to help others in building it.
Other way would be to update the code to the most recent version of the libraries.
If you create a separate directory with this example go file and do:
```
go mod init
go build
```
It would generate the following error:
```
# k8s.io/client-go/rest
../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher                                                                        
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
```

**Comment by aLekSer** [comment]
You can check out an example I have created:
https://github.com/googleforgames/agones/pull/1213

You could make and run an example (change the REPOSITORY to your repo url):
```
cd ./examples/sdk-client
make build 
make push
kubectl apply -f ./batch.yaml --namespace agones-system 
```

**Comment by jasoncheung53** [comment]
Nice work, its much easier to try out!

And the update on `agonesv1.GameServerSpec` `Ports` complete the example, since this part is missing in docs/guides example. Thanks a lot!

BTW I also do a quick fix, I just make agones.dev require k8s.io from my gopath with correct version instead of require it from it's vendor folder.

**Comment by markmandel** [comment]
Looks like this question has been answered. I'm going to close this issue. Please reopen if you have follow up.
