### ISSUE TITLE
Create and document rules of thumb for log levels in agones code

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#1223]
As per https://github.com/googleforgames/agones/pull/1220 we should come up with some general thoughts on what should be info and what should be debug for log lines in the agones code. 

As mentioned during the last community meeting, too much logging can become expensive.

**Comment by aLekSer** [comment]
Some statistics of the log messages (total 300 rows were recorded), messages with count > 5:

| Message  | Count |
| --------- | ----- |
| Processing | 48 |
| Enqueuing | 40 |
| Enqueuing immediately | 38 |
| syncGameServerSet | 27 |
| Reconciling GameServerSet | 27 |
| syncGameServerSet finished | 27 |
| Synchronising | 22 |
| Update Fleet Status | 20 |
| Added webhook handler | 9 |
| Starting workers... | 8 |
| Wait for cache sync | 6 |

https://docs.google.com/spreadsheets/d/1UYy6XELta2AU6X1P223xIlGsr2-aJXTpJEIdAZVVH4o/edit?usp=sharing

**Comment by aLekSer** [comment]
More real statistics from @KamiMay 
https://github.com/googleforgames/agones/issues/1218#issuecomment-564064461

**Comment by markmandel** [comment]
I really like the https://reflectoring.io/logging-levels/ article that @pooneh-m suggested in the other thread! I'm quite tempted to link to that in the development guide and practically call it a day.

One rule I think should be add though - full dumps of an object (such as a `GameServer`), or JSON packet into logrus should only be done on `Debug` or `Trace` levels.

We do this a bunch! (or I did this a bunch I should say :blush: ).

**Comment by markmandel** [comment]
Maybe this is a tad heavy handed, but he vague rule of thumb I've been working on for the Agones controller at least is - if it has to do with the controller itself - starting, stopping, config etc - that's an Info level event.

If it has to do with a transient resource (fleet, gameserver etc) then that ends up being a Debug level event.

**Comment by aLekSer** [comment]
@akremsa, can you please look is there some places which should be logged with level down or up? And probably make a change to `contributing.md` to document all of those.

**Comment by akremsa** [comment]
Ok, I will take a look.

**Comment by markmandel** [comment]
@akremsa the sdkserver should be a great place to start. I feel like there is a large chunk of `Info` logging that could be moved to `debug` :+1:

**Comment by markmandel** [comment]
This looks like it's completed! If nobody objects, I'll close this next week.
