### ISSUE TITLE
GKE: Preemptible node pools make game server unreachable

### ISSUE THREAD

**Issue by dav-otero** [googleforgames/agones#1245]
**What happened**:
Using a modified version of the terraform scripts to create an agones cluster, I created one node pool to host all the game servers with PREEMPTIBLE enabled in Google Compute.

More information about preemptible node pools.
https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms

I had many fleets deployed on that node pool. After one day, I realized that the game servers were correctly running, but they were unreachable (using a game client to connect through UPD).

Investigating with @markmandel, I found out that the `kubectl get gs` was returning an IP and Port that, looking into the node were the game server was running (using `kubectl describe node <node>`), the IP was not matching. It seems that the IP that the GS was reporting was the IP of the node BEFORE the Preemption happened (happens every 24h based on Google documentation).

Investigating a way to "force" a preemption to reproduce the issue, I found this Google documentation:
https://cloud.google.com/compute/docs/instances/setting-instance-scheduling-options#testingpolicies

Simulating a maintenance event, I was able to reproduce the issue. It can be done like this:
```
gcloud compute instances simulate-maintenance-event <node1> <node2> ... <nodeN>
```

After executing this command with all the nodes that were part of the preemptible node pool, I end up with game servers that running in nodes were the External IP was changed. But the GS were reporting the old IP.

**What you expected to happen**:
Game Servers should always report the External IP of the Node they are being executed on. Preemptible nodes are terminated once a day and they potentially change their external IP. If this is the case, Game Servers should be able to update its External Ip so they can be reached from the game clients normally.

**How to reproduce it (as minimally and precisely as possible)**:
- Using GKE, create a node pool with Preemtible enabled.
- Deploy some fleets in that node pool so they are distributed in different nodes
- Wait for the Preemption to happen (it happens once a day)
- Alternatively, simulate a maintenance event (as described above) on all nodes in that node pool
- Check the game servers Ip and Port (using kubectl get gs) and compare with the correspoding External Ip reported in the node they are being executed (using kubect describe node <node>)
- You will find out that some will not match

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.0
- Kubernetes version (use `kubectl version`): 1.17.0
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): terraform (small modification of the agones terraform scripts)
- Troubleshooting guide log(s):
- Others:

**Comment by dav-otero** [comment]
I don't added to the description, but it might be worth to note that the Preemptible node pool has 3 nodes. The fleets in that node pool are distributed accross all the nodes.

One thing I have tried this morning is to send the maintenance event just to one node of the 3 in the pool. The IP was updated correctly on all the GSs  for that node. After that I did in in the second node, and the result was correct againg. But then I did it in the 3rd node, and the result was not right: some GSs updated the IP correctly, but some note. Here you can see the problem (the expected result is that all GS running in the same node has the same IP but different port):

```$ kubectl get gs | grep gke-dev-cluster-ci-default-91fdc9e5-zpgl

fleet-v-0-10-2315-ckrh7-dkf2s        Ready   34.77.225.168   7454   gke-dev-cluster-ci-default-91fdc9e5-zpgl   30m
fleet-v-0-10-2315-si-8-x8mwf-g2hpz   Ready   34.77.204.148   7217   gke-dev-cluster-ci-default-91fdc9e5-zpgl   14m
fleet-v-0-10-2319-si-5-rd7xk-mqnvc   Ready   35.240.88.197   7524   gke-dev-cluster-ci-default-91fdc9e5-zpgl   5h
fleet-v-0-10-2319-si-9-dnh6b-t72tm   Ready   34.77.225.168   7921   gke-dev-cluster-ci-default-91fdc9e5-zpgl   56m
fleet-v-0-10-2322-si-8-rcjqv-6qnkm   Ready   34.77.204.148   7187   gke-dev-cluster-ci-default-91fdc9e5-zpgl   14m
fleet-v-0-10-2337-si-7-cn6c6-tnlqt   Ready   34.77.225.168   7267   gke-dev-cluster-ci-default-91fdc9e5-zpgl   30m```

**Comment by markmandel** [comment]
/assign @markmandel 

My current theory, is to add in https://github.com/googleforgames/agones/blob/master/pkg/gameservers/health.go a check on Pod addition, such that, if the Pod isn't `Starting` or `Creating`, and the Pod nodeName doesn't match the GameServer status nodeName, then move the Pod to Unhealthy -- basically the GameServer Pod got recreated elsewhere, which we want to never happen.

This is my theory anyway, I've not replicated the issue locally yet.

**Comment by markmandel** [comment]
Replicated! The node comes back up with the same set of pods on it -- but the IP is different. Those pods should delete events, but I don't _think_ that is happening.

I think we will need to compare the IP, port and nodename when a pod comes up, just to safe.

**Comment by markmandel** [comment]
Just doing some more testing. The Pod never fires any delete / update event (that I can see) when the PVM cycles. :confounded:

**Comment by markmandel** [comment]
Work underway at: https://github.com/markmandel/agones/tree/bug/pvm-maintenance

Pretty sure I have a working solution, just need to finish it off.

**Comment by dav-otero** [comment]
Good news! 👍
