### ISSUE TITLE
How to configure GameServers with secure websockets?

### ISSUE THREAD

**Issue by raoneel** [googleforgames/agones#1246]
Hi, I've recently started exploring using Agones + GKE for a node.js setup where clients connect to servers via secure websockets (wss://). I've gotten this setup to work with regular websockets, but I'm not sure about the best way forward with the secure side.

My thought was to use the [HTTPS load balancers](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) but this won't work with my setup where I want each client to directly connect to a GameServer. 

I then saw issue #1182 and tried to make each GameServer set up its own SSL connection with a certificate/private key. I would get a static IP for a Node, get a domain to point to this IP, and then provision a certificate for this domain. This worked for a single node. However, this breaks once you scale up to multiple nodes, which all have different IP addresses. I would have to somehow configure my domain to dynamically point to all of these node IP addresses.

My next thought was a setup where each GameServer gets a unique, external URL. I could then provision a HTTPS certificate against this URL. Let's say my domain (with SSL) is *.server.example.com. Routing to a pod would be GAME_SERVER_NAME.server.example.com. Every time a new pod is created, a corresponding URL with this scheme would be created. I could then connect securely to a pod using this URL. How would I set something like this up? If there is a better way to accomplish this, can someone point me in the right direction?

Thanks!

**Comment by markmandel** [comment]
/cc @benmcmahan if you want to expand, please feel free.

This came up on Slack a little while ago recently, so I'll copy/paste the transcript here, for posterity:

> Ben McMahan Sep 19th at 2:29 PM
> Hey all, I have a question about getting secure websockets working.  Since the paradigm seems to be generate gameservers on demand and then point the gameclient to that server directly, how do we establish a secure connection on the web.  It seems like we need a domain name for a certificate, but if we don't know what machine address we'll get, how do we set that up?  Or am I thinking about this the wrong way?
> 
> Mark Mandel  3 months ago
> This has come up a bunch, and it's a tricky problem to solve in general.
> Best answers we've seen:
> 1) Create a dynamic DNS with a wildcard cert for a subdomain, and have that subdomain essentially contain the IP
> 2) Run nginx proxies on the front end to basically do the same thing, resolving to internal DNS/IP entries inside the cluster.
> 
> Mark Mandel  3 months ago
> For which you still need a wildcard cert
> 
> Mark Mandel  3 months ago
> And it doesn't have to be nginx, pick a proxy provider, or write your own
> 
> Ben McMahan  3 months ago
> Okay, i was currently looking into the nginx solution, but the dynamic dns sounds interesting too, thanks for the pointers.  It gives me a direction to explore.
> 
> Ben McMahan  3 months ago
> So far the nginx proxy service I'm hosting looks like it'll work, we'll see how it scales though as all wss traffic will have to go through it.
> 
> Ben McMahan  3 months ago
> sigh, found a way to get a dynamic proxy in nginx but not how to keep that connection alive (dynamic means no upstream, upstreams what you need to keep it alive). I'll keep looking.
> 
> Ben McMahan  3 months ago
> figured it out, I have to set session affinity in the ingress, it was actually google cloud killing it not nginx
> 
> Mark Mandel  3 months ago
> this would make a really nice "solution" or "guide" documentation PR if you work it out
> 
> Mark Mandel  3 months ago
> maybe a "solutions" section?
> 
> Ben McMahan  3 months ago
> in the agones documentation?
> 
> Mark Mandel  3 months ago
> yah

**Comment by raoneel** [comment]
Thanks, this is exactly what I needed! I'm using the dynamic DNS approach and I think it should work pretty well. As new instances are created, they will add a new DNS record which will point to the instance IP. Only downside here is that I need wait a bit for the DNS servers to update, but it seems to happen fairly quickly (<30s with Cloud DNS).

**Comment by NullSoldier** [comment]
If you all ever post a tutorial, for this, im looking at this solution to reduce latency for my usage of agones.

1. Game server boots up
2. Game server tells dynamic DNS to register itself there with its IP
3. Game server gets CERTS to terminate WSS at the game server
4. Client connects to *.rolltabel.app
