### ISSUE TITLE
Collaborator Request

### ISSUE THREAD

**Issue by nguyenlecorp** [googleforgames/agones#1247]
If you'd like to become a collaborator of the Agones repo on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join. Once accepted you'll be able to have issues assigned to you! 

### GitHub user id
- List your GitHub user id

### Company affiliation
- List your company name, or indicate Individual if you're not affiliated with a company

### Requirements

- [x] I have reviewed the [contribution guidelines](https://github.com/googleforgames/agones/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Agones Slack workspace](https://join.slack.com/t/agones/shared_invite/enQtMzE5NTE0NzkyOTk1LWU3ODAyZjdjMjNlYWIxZTAwODkxMGY3YWEyZjNjMjc4YWM1Zjk0OThlMGU2ZmUyMzRlMDljNDJiNmZlMGQ1M2U)

**Comment by markmandel** [comment]
Hi! Thanks for submitting!

Can you please fill out your Company affiliation section as well. (Github user id would be nice, but we can see that above :smile: )

Since we are here, are there particular things you would be looking to work on?
