### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by quantum-craft** [googleforgames/agones#1259]
**What happened**:
There is typo in README.md of agones/examples/unity-simple/README.md:
...
| Shutdown | Shutdown() |
 | """Gaame"""Server | GameServer() |
...

**What you expected to happen**:
Should be:
...
| Shutdown | Shutdown() |
 | """Game"""Server | GameServer() |
...

**How to reproduce it (as minimally and precisely as possible)**:
Always

**Anything else we need to know?**:

**Environment**:
- Agones version: master branch
- Kubernetes version (use `kubectl version`): any
- Cloud provider or hardware configuration: any
- Install method (yaml/helm): any
- Troubleshooting guide log(s): n/a
- Others:

**Comment by roberthbailey** [comment]
Hi @quantum-craft - thanks for finding the typo. Do you want to send a PR to fix the typo?
