### ISSUE TITLE
Update Example Images with the latest everything

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1261]
Bring Agones example images with all the latest things:
1. Languages used (for example, we're still using Go 1.11 in a bunch of places)
2. SDK
3. Operating system (for example, bring Alpine images up to 3.11)

To be completed:

- [x] simple-udp
- [x] allocator-service
- [x] simple-tcp
- [x] unity-simple
- [x] rust-simple
- [x] autoscaler-webhook
- [x] xonotic
- [x] cpp-simple
- [x] nodejs-simple
- [x] crd-client

**Comment by markmandel** [comment]
Due to #1293 all the image versions got incremented. I figured it would make sense to do this work at the same time as we re-build each of these, and make sure they all still work (pretty sure the node one is currently broken)

**Comment by aLekSer** [comment]
Also we could consider #909 - rebase images from alpine to gcr.io/distroless/static ?

**Comment by markmandel** [comment]
> Also we could consider #909 - rebase images from alpine to gcr.io/distroless/static ?

I think the spirit of that ticket was more for the Agones images themselves.

I don't know if we want to do that for example images? Using Alpine does make it easier to introspect what is happening in the images (e.g. by running a shell in them), which is useful for learning.

Some images also run Debian (Xonotic, Supertuxkart), and moving them to scratch I expect would be super, super hard.

**Comment by aLekSer** [comment]
/assign @akremsa
Alexey is working on this right now

**Comment by markmandel** [comment]
I believe everything except for Unity should be complete.

**Comment by markmandel** [comment]
Let's start this one allll over again :smile: 

Once #1900 gets completed, we should do the following updates to example images:

- [ ] Update Unity on the Unity Sample, possibly upgrade Ubuntu base image to latest LTS
- [ ] #1890 - Deprecate and remove the udp-server and tcp-server images
- [ ] Rebuild the autoscaler webhook example with new go version
- [ ] Rebuild the simple-game-server example with the new go version
- [ ] Update Super Tux Kart version (should have that AI connection fix now). Also has a new go version.
- [ ] Rebuild the Xonotic example with the new go version

**Comment by markmandel** [comment]
Should we close this issue? It seems like a bit of a mess now.

It might be better to create new issues as needed instead. What do we think?

Marking as stale to see if anyone disagrees on closing the issue.

**Comment by markmandel** [comment]
Marked stale last month. Going to close and we can reopen specific tickets as needed.
