### ISSUE TITLE
simple-udp

### ISSUE THREAD

**Issue by OneFighter** [googleforgames/agones#1268]
start  gameserver simple-udp,
run   nc -u ip port 
write msg can not get response, that's why?

1.
 kubectl get gameserver
NAME               STATE   ADDRESS         PORT   NODE                             AGE
simple-udp-ztkwb   Ready   34.69.138.226   7757   gke-lance-pool-1-20197f35-r3mj   57m

2.
root@test-1:/home/lancalm105# nc -u 34.69.138.226 7757
hello
world
exit

**Comment by aLekSer** [comment]
More details is needed. Please follow the original NewIssue template. Also why are you using `nc -t`?
This could be a network issue, also there a need to have properly set firewall for 7000-8000 ports.
What way have you chosen to install Agones?

**Comment by OneFighter** [comment]
> More details is needed. Please follow the original NewIssue template. Also why are you using `nc -t`?
> This could be a network issue, also there is a need to have properly set firewall for 7000-8000 port range.
> The traffic could also be blocked by your ISP. So you could additionally verify that you are able to communicate and connect using `nc -u IP port` from the same GKE cluster.
> What way have you chosen to install Agones?
use GKE install Agones

**Comment by OneFighter** [comment]
> More details is needed. Please follow the original NewIssue template. Also why are you using `nc -t`?
> This could be a network issue, also there is a need to have properly set firewall for 7000-8000 port range.
> The traffic could also be blocked by your ISP. So you could additionally verify that you are able to communicate and connect using `nc -u IP port` from the same GKE cluster.
> What way have you chosen to install Agones?


Thank you!
       That's problem has been resolved,  not open firewall for 7000-8000 port

**Comment by aLekSer** [comment]
Glad to see that the problem were resolved, you could use slack #users group for a small questions.
