### ISSUE TITLE
Install but never remove CRDs in the Helm chart, per Helm v3 behaviour

### ISSUE THREAD

**Issue by TBBle** [googleforgames/agones#1280]
**Is your feature request related to a problem? Please describe.**

Helm v3 has taken the position that Helm is now only involved in CRD installation, and does not attempt or expect to manage CRD uninstallation:

> There is not support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.

This is much nicer for situations where, e.g., due to a change in an immutable variable, there is no choice but to uninstall/reinstall Agones, but you don't want to corrupt other Helm charts that create Agones CRDs due to the auto-deletion of objects defined by a CRD on removal.

In our case, every time we have to uninstall/reinstall Agones (due to config changes or upgrades, which seem to want to modify immutable `spec.selector` in the various `Deployments`), any installed chart with `Fleet` or `FleetAutoscaler` resources has them silently deleted out from under them, and in my last attempt, GameServers had been created in a namespace not currently known to Agones, and hence were overlooked by the cleanup-on-uninstall hook, leaving the GameServer CRD unable to be removed.

There doesn't seem to be any way in Helm v2 except the `crd-install` hook, to install CRDs so that they are left behind when the chart is uninstalled, and do not cause 'Resource already exists' conflicts on re-installation.

Helm v3 replaces the `crd-install` hook with a _crds_ directory, next to _templates_, from which *non-templated* CRDs are read, and *only* installed. "Resource exists" conflicts on such CRDs are only considered warnings, not errors.

**Describe the solution you'd like**

* Use the `crd-install` hook to install CRDs in Helm v2. (Revert 938e23e19798b188b5c2a1923407457536680c96)

* Do not implement the CRD deletion hooks, so that they are not uninstalled except by explicit administrator action. (`agones.crds.cleanupOnDelete` probably still makes sense). (Partial revert of #437)

* Add the CRDs to the `crd` directory so that Helm v3 can manage them in the same way automatically, and also will be able to honour the `helm install --skip-crds` parameter. (New feature)

**Describe alternatives you've considered**

One alternative I'm aware of is to move to requiring Helm v3 and using the `crds` directory, but not the `crd-install` hook. This way we would avoid any problematic `crd-install` hook behaviours, particularly related to sub-charts. (Helm v3 honours CRDs in subcharts, but since they are non-templates, and existing CRDs do not cause installation failure, this behaviour is non-problematic).

Any option that leaves the CRDs in the `templates` directory (without a `crd-install` hook) means that Helm deletes them as a matter of course on uninstallation, and leaves any other deployment that had declared Fleets, FleetAutoscalers, silently corrupted.

If that uninstall fails, e.g., due to left-over GameServers, Helm cannot reinstall the chart until the CRDs are cleaned out by-hand, as they exist but are no longer chart-managed.

**Additional context**

The dual behaviour of `crd-install` and the crds directory comes from [the same change in stable/prometheus-operator chart](https://github.com/helm/charts/commit/89b233eef6dbc1b6fac418bde3a5a6f4e14406d4) as it seems Helm v3 no longer honours `crd-install` hooks even for APIVersion 1 charts. The Helm background can be seen at https://github.com/helm/helm/pull/6243.

Note that this means the CRDs would no longer be templated, and so they should probably come out identical to those installed by a [manual install](https://agones.dev/site/docs/installation/install-agones/yaml/), which seems desirable to me, since CRDs *probably* should be immutable.

**Comment by markmandel** [comment]
Thanks for writing this up! There are lots of factors at play here that likely make this feature request not likely to be implemented, based on investigation done previously - but let's work through them to see if they are still valid.

Original PR for context: https://github.com/googleforgames/agones/pull/441

## Helm 3

Until we have data that users at large have moved to Helm 3, we likely won't move our support over from Helm 2 :arrow_right: 3. This requires investigation however, as its possible Helm 3 supports Helm 2, or that users are making the migration. No investigation has happened yet. Help here on a migration strategy would definitely be much appreciated.

## CRDs are immutable

This is great in theory :smile: but in our experience is simply not possible in practice. Fields will added to CRDs all the time, and when CRDs or new features are in alpha/beta states as per our [documentation](https://agones.dev/site/docs/guides/feature-stages/#custom-resource-definitions-crds) can be changed at any point and time. So we need a solution that allows us to be able to modify CRDs.

## Install / Uninstall of Agones
> In our case, every time we have to uninstall/reinstall Agones (due to config changes or upgrades, which seem to want to modify immutable spec.selector in the various Deployments)

I'd like to know more about this. While we don't test upgrades of old version of Agones straight from one version to another (say 1.2.0 -> 1.3.0), we do a Helm upgrade on every CI run, and I've never seen this before. If there is a way tosolve this issue, would that nullify this concern?

## Workarounds that exist now

We do have `agones.crds.install` and `agones.crds.cleanupOnDelete` options on the current [helm installation configuration](https://agones.dev/site/docs/installation/install-agones/helm/#configuration), for pretty much this reason, and several others. If you want to manually control your CRD lifecycle via helm, or if the cleanup hook runs, you can do that as a separate chart or process yourself as well.

**Comment by TBBle** [comment]
Apart from the `crd-install` hook, a chart that works with Helm v2 ("APIVersion v1") should work unchanged with Helm v3. There were a few bugs around *creating* those charts in Helm 3.0.0, I believe they're mostly-squished with Helm 3.0.2. I definitely don't advocate migrating to Helm v3 ("APIVersion v2") chart format until Helm v2 is EOL ([November 2020](https://helm.sh/blog/2019-10-22-helm-2150-released/#helm-2-support-plan)) due to the wide usage of Helm v2, even *old* versions of Helm v2.

**Comment by TBBle** [comment]
The uninstall/reinstall need has probably become clearer with Helm v3, because one behaviour that did change is that the {{--force}} parameter used to work around (amongst other things) immutable objects, changed from "If patching the resource fails, delete it and recreate it", to "`PUT` instead of `PATCH`".

This was done to avoid downtime due to surprisingly deleting and recreating Deployments and Statefulsets that would otherwise remain active across an upgrade, but has hit issues with a lot of charts when an APIVersion changes, or that include immutable fields in their templates.

The Helm issue tracking this behaviour change is https://github.com/helm/helm/issues/7082, proposing the old `--force` behaviour be reintroduced as `--recreate`.

Howerver, `--recreate` may not help in this case, as depending on the implementation, the CRDs would themselves be deleted and recreated, deleting the existing objects (or worse, eternally blocking the helm operation waiting for GameServers to be cleaned up by a currently-uninstalled controller), and producing exactly the problem I'm trying to avoid with not doing a uninstall/reinstall of the Helm chart.

All that said, I can't right now recreate the failure around the `Deployment` `spec.selector`, despite changing exactly what I changed yesterday (i.e. same version, just changing one parameter), which replicated on 3/3 clusters at the time. So it might be that this isn't as strong a problem as I thought, or possibly something was wrong with my install, or even there is an undiscovered bug in the Helm v2 to Helm v3 metadata migration.

At this point, our project only uses the stable-API CRDs, (which I *do* hope are immutable, apart from the docs?) so for future deployments (particularly more production-like deployments, where I can't just delete someone's dev deployment and send them an apology IM...) I'll try and ensure we use the `agones.crds.install=false` and `agones.crds.cleanupOnDelete=false` settings, and manage the CRDs manually.

And I'll keep an eye on our next version update, in case the immutable field issue appears again, and try and track down where the issue is coming from. I certainly don't see any relevant changes in the Agones chart templates, so it's not an *obvious* issue.

**Comment by TBBle** [comment]
So it's not lost (I didn't link it above) the Helm v3 approach to CRDs is documented at [Custom Resource Definitions](https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/) and https://github.com/helm/helm/issues/5871#issuecomment-522096388

There was a suggestion at https://github.com/helm/helm/pull/6243#pullrequestreview-276609696 of a plugin to experiment with CRD upgrades/uninstalls, and there's an open feature request at https://github.com/helm/helm/issues/6581 to deploy newly-added CRDs when upgrading a chart.

**Comment by TBBle** [comment]
I've just written https://github.com/helm/helm/issues/5871#issuecomment-581145634 to try and build out a generic use-case for the _crds/_ directory in Helm v3 to include the use-cases @markmandel has described above, and also make sure "don't uninstall CRDs" is a workable default when using Helm v3.

**Comment by markmandel** [comment]
@TBBle thanks for taking on the task of liaising with the Helm team on this issue!

**Comment by EricFortin** [comment]
We are also looking at managing CRDs outside of the Agones deployment as per helm recommended best practices regarding CRDs. We are also using helm3 and would like to be able to use the `--skip-crds` option. I was looking at a way to support both ways of working but moving more toward helm3 since helm2 is reaching EOL and I looked at other projects to see how they were doing just that.

A nice solution is to have CRDS in the helm3 crds folder and then have a `crds.yaml` template that globs all the CRDS from the folder to install them when using helm2. At the moment, the `agones.crds.install` default is `true`. In order to implement that change, it would need to be changed to `false` so that we don't try to install them twice and that the `skip-crds` really take effect. Cert-manager doesn't install CRDs by default either. I asked helm project if there was a way to know within the chart what version was used to install a chart so that we don't have to change the default and just skip the `crds.yaml` when using helm3 but it doesn't seem to be possible.

How would you feel about that breaking change?

**Comment by markmandel** [comment]
@EricFortin not sure I understand the value add here? (Also not sure how much we want to invest in supporting Helm2 at this stage either)

As per the Helm 3 best practices guide:

> Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle.

So I'm not sure if there really is a "best practice" :smile: Istio does separate charts, there does not seem to be consensus.

Let me ask this in a different way - what blocking issues are you running into with using agones.crds.install=false, and installing the CRDs manually if you so require?

**Comment by EricFortin** [comment]
I was under the impression that we wanted to support Helm2 still, I have no problem with dropping it either. As per your question, nothing blocks me from using current value settings but I have to make an exception compared to other charts that are built around Helm3 way of handling CRDs exclusion.

**Comment by TBBle** [comment]
While there isn't _yet_ a full-lifecycle best-practice for CRD management, there's an attempt to capture what we do know, and what we know doesn't work, at https://github.com/helm/community/pull/138 (a kind-of successor to and summary of https://github.com/helm/helm/issues/5871 which I linked earlier).

Experience/input on this topic would be very-much appreciated there, I believe. The Agones use-case is one of the easier ones to support well, but it's not _easy_ yet, and there are other use-cases that mean we can't simply require that the CRDs are multi-versioned and either back/forward API-compatible or shipped with migration webhooks.

**Comment by markmandel** [comment]
I'm thinking we should close this issue - it's been a few years, and (a) there isn't any change in how Helm is handling CRDs and (b) it seems unlikely we will change our overall CRD installation strategy as it is currently, as it's been running for a while now, with what seems to be minimal issue.

Going to mark as stale unless anyone has strong objections to closing this in a week or so.

**Comment by markmandel** [comment]
Closing since it's been a month being stale.
