### ISSUE TITLE
Move /site to go.mod and Go 1.12/1.13

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1295]
https://github.com/googleforgames/agones/tree/master/site

We do some gopath shenanigans to create and deploy the site:
https://github.com/googleforgames/agones/blob/master/build/includes/website.mk#L50
https://github.com/googleforgames/agones/blob/master/site/cloudbuild.yaml#L42

Which we don't need to do anymore (and bit me the other day during release). 

We could move this to a go.mod and also update the App Engine version to a later version of go (currently 1.11) with minimal difficulty, and it would make this process much easier.

**Comment by markmandel** [comment]
@heartrobotninja still keen on taking this on?

**Comment by heartrobotninja** [comment]
Yep! I can start on that in a little bit.

**Comment by markmandel** [comment]
Thanks!

/assign @heartrobotninja

**Comment by aLekSer** [comment]
@heartrobotninja, we can help on this ticket.
