### ISSUE TITLE
Multi-cluster Allocation: Does "Establish Trust" reverse the clusters?

### ISSUE THREAD

**Issue by TBBle** [googleforgames/agones#1301]
In this scenario, it seems "cluster A" is the Agones cluster that other systems send `GameServerAllocation`s to, and "cluster B" (34.82.195.204 in the example) is another cluster that "cluster A" is able to make multi-cluster allocation requests to.

However,
> To accept allocation requests from other clusters, agones-allocator for cluster A should be configured to accept the client’s certificate from cluster B and the cluster B’s client should be configured to accept the server TLS certificate, if it is not signed by a public Certificate Authority (CA).

That seems backwards. The examples *appear* to be configuring cluster B (second example) to accept a client certificate from cluster A (seen in first example), and configuring cluster A (first example) to accept the server TLS certificate of cluster B.

However, I haven't tried to set this up, so it's possible I'm overlooking or misunderstanding something in this.

**Comment by pooneh-m** [comment]
Thanks @TBBle for reporting the issue. I can see the confusion. The GameServerAllocationPolicy CRD in the example is defined for cluster A to forward requests to cluster B. However the TLS establishment in the example is for cluster B to send requests to cluster A. I'll fix the documentation and will add a diagram to clarify.

**Comment by asaurytski-exadel** [comment]
Hi !
whether will work Space Engineers Ded server in agones ?
