### ISSUE TITLE
Site: Prioritise search results on agones.dev better

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1327]
**Is your feature request related to a problem? Please describe.**
When I make a query to search for the documentation page which contains, for example, "metrics", I receive pages from old version website or not explaining the topic:
```
https://0-8-0.agones.dev/.../0.7.0-latency-measuring-fleet-autoscaling- webhooks-and-metrics/
https://agones.dev/site/docs/installation/install-agones/helm/
https://0-8-0.agones.dev/site/docs/guides/metrics/
```
But no current version on the first page:
```
https://agones.dev/site/docs/guides/metrics/
```
This happens both on search by Relevance and by Date.

**Describe the solution you'd like**
I want to get `https://agones.dev/site/docs/guides/metrics/`
at the top and all `0-8-0.agones.dev` skipped or at the bottom.
`https://performance.agones.dev` this subdomain should be skipped also (`https://performance.agones.dev/site/docs/guides/client-sdks/local/`)

**Describe alternatives you've considered**
Skip or deprioritise all previous version pages.

**Additional context**
Sort 
1. By date <img width="994" alt="SortByDate" src="https://user-images.githubusercontent.com/5626814/74054698-8d02be00-49ef-11ea-974f-9ea22f89789f.png">
1. By Relevance:
<img width="808" alt="SortByRelevance" src="https://user-images.githubusercontent.com/5626814/74054709-912edb80-49ef-11ea-8cdd-2b2870825f99.png">

**Comment by aLekSer** [comment]
I have played a bit with Custom Search Engine. It seems that we need to add and upload annotations for every old subdomain used and do this with previous release version website also say `1-2-0.agones.dev`.
https://developers.google.com/custom-search/docs/annotations?hl=en 
We can use either `score` for better ranking:
  <Annotation about="*.agones.dev/site/blog/*" score="0.05">
    <Label name="_cse_dhl4jwcqxxx"/>
  </Annotation>
```
or exclude completely the subdomain:
```
  <Annotation about="0-8-0.agones.dev/site/*">
    <Label name="_cse_exclude_dhl4jwcxxx"/>
  </Annotation>
```
this way we would get result from current release version first:
<img width="427" alt="Agones Custom Search Way to enhance" src="https://user-images.githubusercontent.com/5626814/74326240-17a23f00-4d9b-11ea-967f-ca6c03947b62.png">

This XML file should be uploaded here `https://cse.google.com/cse/setup/advanced?cx= <gcs_engine_id>`

**Comment by markmandel** [comment]
I'm not sure where the original GCSE was setup, but I created a new one here:
https://cse.google.com/cse?cx=016691298986124624340:x7qv2dywdao

Just need to update the Config.toml post release to use this version.

**Comment by aLekSer** [comment]
The new one is configured much better and will close this issue.
