### ISSUE TITLE
Documentation for gRPC Based Multicluster Allocator

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1333]
Now we have switched to a gRPC based allocator https://agones.dev/site/docs/advanced/multi-cluster-allocation/#allocate-multi-cluster is now incorrect, as the documentation provided still uses HTTPS.

I wonder if we can use something like https://github.com/grpc-ecosystem/polyglot or https://github.com/fullstorydev/grpcurl to replace the curl command?

**Comment by markmandel** [comment]
@pooneh-m is this possible to be fixed before RC on Tuesday? Otherwise we're going to have erroneous documentation :disappointed:

**Comment by markmandel** [comment]
Also, the links in https://github.com/googleforgames/agones/blob/master/site/content/en/docs/Advanced/multi-cluster-allocation.md to the github URLs.

Should use a `ghlink` shotcode, will 404 once the link checker cache expires, as they point to master rather than a release branch, and we moved that CRD to v1

**Comment by pooneh-m** [comment]
Thanks @markmandel. The change is only for documentation. In case I couldn't update documentation by RC date, we should have time before the release to update documentation, correct?
Thanks for `ghlink` pointer

**Comment by markmandel** [comment]
Sounds good. Ideally it would be great to have before RC, so people could check it out, but if not, before stable, during the feature freeze week works too.

**Comment by pooneh-m** [comment]
Thanks. I'll do my best :)
