### ISSUE TITLE
Game Server allocation based on maps

### ISSUE THREAD

**Issue by Ludea** [googleforgames/agones#1340]
**Is your feature request related to a problem? Please describe.**
On persistant game, game Server can be use to allocate only 1 map. 
Into a fleet, each gs represent a map.
If there is 5 maps, 5 gs allocated.
 If there is no player into the map, it can be de allocated

**Describe the solution you'd like**
Could allocate gs with label 
**Describe alternatives you've considered**

**Additional context**
It is juste an idea, to support persistant World. I don't know if you plan to design / support this?

**Comment by markmandel** [comment]
Thanks for your comments! I'm wondering if this could be already accomplished through either (a) existing functionality or (b) upcoming functionality.

But a few questions:

> Into a fleet, each gs represent a map.

Why not a map per fleet? Would you want to autoscale a map based on player count? e.g. #1034

> If there is no player into the map, it can be de allocated

This could also be done through the [SDK.Allocate()](https://agones.dev/site/docs/guides/client-sdks/#allocate) and [SDK.Ready()](https://agones.dev/site/docs/guides/client-sdks/#ready) functions from within a Game Server currently.

> Could allocate gs with label

You can also do this now ([reference](https://agones.dev/site/docs/reference/gameserverallocation/)), but I'm not sure if that covers your use case. I assume you might be wanting to allocate based on player capacity? e.g. #1239

> It is juste an idea, to support persistant World. I don't know if you plan to design / support this?

Are there blocking issues that aren't going to be covered for persistent worlds in what I've referenced above?

Would definitely love to provide more support for persistent worlds, so please let me know if I missed anything :+1:

**Comment by Ludea** [comment]
> Why not a map per fleet? Would you want to autoscale a map based on player count? e.g. #1034
I start drived by 1 fleet = the World.
World is divised by map =`gs`.
- When map is full or maybe >80% (players capacity) create and allocate a new `gs`
- When map is empty or < 20% (players capacity) deallocate and delete `gs`
So yes all sdk function already exist.

I don't think about 1 map = 1 fleet
I see scaling fleet based on [#1034 ](https://github.com/googleforgames/agones/issues/1034)
It could be an interesting design choice.

The 2 solutions can be viable ?

**Comment by Ludea** [comment]
I see https://agones.dev/site/docs/getting-started/create-fleetautoscaler/, mixed with player capacity, i think it is a better choice.
So I close this issue, and wait until this feature is available

**Comment by markmandel** [comment]
Cool. Thanks for talking it through! Glad to know we are on the right track at least :+1:
