### ISSUE TITLE
Using Allocator service without TLS

### ISSUE THREAD

**Issue by Cyansilver** [googleforgames/agones#1343]
Hi,

I would like to allocate a new game server from my match maker service. This service should be in the same k8s cluster with agones so I wonder if there are any ways to call Allocator service without tls?

Thank you.

**Comment by aLekSer** [comment]
An Allocator service is on Alpha version at the moment.
You can use [GameServerAllocation](https://agones.dev/site/docs/reference/gameserverallocation/) to allocate a gameserver which is on stable version.

**Comment by pooneh-m** [comment]
Exactly, also agones-allocator serivce is a LoadBalancer service with external IP. It is used for when the allocation call is from outside the cluster.

**Comment by markmandel** [comment]
You can also see an example here: https://github.com/Laremere/space-agon
