### ISSUE TITLE
Approver access for @aLekSer

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1354]
### GitHub Username

@aLekSer

### Requirements
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have read the [contributor guide](https://github.com/googleforgames/agones/blob/master/CONTRIBUTING.md)
- [x]  I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markmandel 
- @cyriltovena 

### List of contributions to the Agones project
- PRs [reviewed](https://github.com/googleforgames/agones/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Aalekser+-author%3AaLekSer+) / [authored](https://github.com/googleforgames/agones/pulls?utf8=%E2%9C%93&q=is%3Apr++author%3AaLekSer+)
- Issues [responded to](https://github.com/googleforgames/agones/issues?utf8=%E2%9C%93&q=commenter%3Aalekser+is%3Aissue+), [created](https://github.com/googleforgames/agones/issues/created_by/aLekSer)

**Comment by cyriltovena** [comment]
Yes for me !

**Comment by roberthbailey** [comment]
+1 from me

**Comment by markmandel** [comment]
Access has been updated! Congratulations!

**Comment by aLekSer** [comment]
I am glad to hear that. Thank you all for the support!
