### ISSUE TITLE
Build cpp-simple server failed

### ISSUE THREAD

**Issue by Cyansilver** [googleforgames/agones#1357]
Hi,

I'm trying to build the cpp simple server via this file https://github.com/googleforgames/agones/blob/v1.3.0/examples/cpp-simple/Dockerfile. But there are many errors about protobuf like below
> /usr/local/agones/lib/libagones.a(sdk.pb.cc.o): In function `agones::dev::sdk::Empty::GetMetadata() const':
sdk.pb.cc:(.text+0x26c): undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*)'

I'm not sure if I missed anything?

For more information:
- Installed grpc via this guide (https://github.com/grpc/grpc/blob/master/BUILDING.md)
```
git clone -b v1.20.0 https://github.com/grpc/grpc \
    && cd grpc \
    && git submodule update --init \
    && mkdir -p cmake/build \
    && cd cmake/build \
    && cmake -DBUILD_SHARED_LIBS=ON -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DCMAKE_BUILD_TYPE=Release ../.. \ 
    && make \
    && make install \
    && mv *.so /usr/local/lib/
```
- Installed protobuf via this guide (https://github.com/protocolbuffers/protobuf/blob/master/src/README.md)
```
git clone https://github.com/protocolbuffers/protobuf.git \
    && cd protobuf \
    && git checkout tags/v3.11.2 \
    && git submodule update --init --recursive \
    && ./autogen.sh \
    && ./configure \
    && make && make install && ldconfig
```
- Generate the code from protoc file again via this script (https://github.com/googleforgames/agones/blob/v1.3.0/build/build-sdk-images/cpp/gen.sh) because my version is newer (libprotoc 3.11.2).
- Build the cpp sdk as in the Dockerfile
- Build the cpp-simple server as in the Dockerfile then meet the errors

**Comment by markmandel** [comment]
Please follow this guide: https://agones.dev/site/docs/guides/client-sdks/cpp/#building-the-libraries-from-source

As that is the supported installation path for the Agones C++ SDK.

**Comment by markmandel** [comment]
Looks like this question has been answered. I'm going to close this issue for now.

Please let us know if you have follow ups.
