### ISSUE TITLE
What to do if the assigned port is occupied by another program？

### ISSUE THREAD

**Issue by CodingSinger** [googleforgames/agones#1362]
I see that the assignable ports in the code are specified by minPort and maxPort, but what if some of these ports are occupied by other programs?

**Comment by markmandel** [comment]
They will fail and the Gameserver will be deleted and a new one creased to try a new random port within the range (assuming your are using a fleet).

But ideally, choose a range that you know to be free in your system.

I am curious, why do you ask?

**Comment by CodingSinger** [comment]
Thank for your reply. ok, I only see a map that records the port and whether it is occupied, but how do I know which node these ports belong to?

**Comment by markmandel** [comment]
I'm sorry, I don't understand the question?

GameServers report what address (ip + port) they are on as part of their status. 

May I recommend you go through the [Agones quickstart](https://agones.dev/site/docs/getting-started/) - that will likely answer your questions.

**Comment by markmandel** [comment]
Looks like there are no follow ups to this question. So going to close it to clean things up.
