### ISSUE TITLE
Terraform: clean up duplicate tf config files.

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1372]
There are multiple `helm.tf` files in the repo with the similar purpose:

1. Create a development cluster with current .tf file, all local disk changes applies.
1. Intended to be used as a submodule in that case terraform will clone the whole repo and master version would be used. 

**What happened**:
Redundant files. Developers and users could work on a different clusters.

**What you expected to happen**:
I think we should have one file of each type with proper variables to specify the behaviour.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
There are also multiple cluster.tf files. on in the ./install/terraform and one in ./install/terraform/gke

It seems like the one in ./install/terraform would be redundant, since it's GKE specific.

**Comment by aLekSer** [comment]
There are currently 5 terraform deployment scenario co-exist in the repo:

1. `make gcloud-terraform-cluster` (equivalent of `make gcloud-test-cluster`) `install/terraform/helm.tf` and `install/terraform/cluster.tf`
1. `./examples/terraform-submodules/gke-local/` similar to above use relative path, need to be invoked from the repo structure (`../../../install/terraform/modules/gke` and `../[..]/helm` are used).
1. `./examples/terraform-submodules/gke/` Don't need a file structure itself, can be copied anywhere, but performing two clones of the whole `agones` repo. Could not be avoided for modules. 
1. `./examples/terraform-submodules/aks/`
1. `./examples/terraform-submodules/eks/`
I am willing to leave all of them functional after fixing this ticket.
