### ISSUE TITLE
Terraform: No Agones helm installation when cluster parameter (e.g. Name) has changed (and it being recreated)

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1377]
Agones helm resource is not recreated if the cluster module was changed.

`terraform apply` twice on the next file (with changing the name of a cluster, or a zone), and helm module would not be updated, and thus there is a success apply without Agones on second time: https://github.com/GoogleCloudPlatform/agones/blob/5319b13d87bd9427fe36bf53a12c13c6773b061e/examples/terraform-submodules/gke/module.tf#L63

**What happened**:
There is an option to create a cluster with Agones, then update a cluster, and no Agones would be set up on second apply:
```
make gcloud-terraform-cluster
```
or using 
```
terraform apply -var project="<YOUR_GCP_ProjectID>" [-var agones_version="1.0.0"]`
```
described [here - Install with Terraform](https://agones.dev/site/docs/installation/terraform/gke/)

**What you expected to happen**:
Helm and Agones would be installed every time with `terraform apply`
**How to reproduce it (as minimally and precisely as possible)**:

```
make gcloud-terraform-cluster
vi ./examples/terraform-submodules/gke-local/main.tf // update something
make gcloud-terraform-cluster
```

**Anything else we need to know?**:
Logs:
```
//First `terraform apply` logs:                   
Apply complete! Resources: 6 added, 0 changed, 1 destroyed.                      
//Second apply, cluster was changed  (say name or node_count parameter)                                                                                                   
Apply complete! Resources: 3 added, 0 changed, 3 destroyed.     
$ kubectl get crds | grep agones | wc -l
0
```
I expect that both helm and cluster would be recreated.
**Environment**:
- Agones version: 1.4-rc
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: 
- Install method (yaml/helm): Terraform 0.12.21
- Troubleshooting guide log(s):
- Others:

**Comment by aLekSer** [comment]
There is an option to taint some resources, but probably we can mark this resources as linked - create one after another.

**Comment by markmandel** [comment]
@aLekSer is this fixed with the move to Helm 3?

**Comment by aLekSer** [comment]
Hello @markmandel  give me 30 minutes to provide more details.

**Comment by aLekSer** [comment]
The results are similar:
```
//First `terraform apply` logs:                   
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.               
//Second apply, cluster was changed  (say `zone` parameter)      
Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
$ kubectl get crds | grep agones | wc -l
0
```

**Comment by aLekSer** [comment]
Now that Terraform 0.13 released it contains `depends_on` for modules:
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0130-august-10-2020

**Comment by aLekSer** [comment]
So far got an error:
```
Error: Module does not support depends_on

  on module.tf line 119, in module "helm_agones":
 119:   source = "../../../install/terraform/modules/helm3"

Module "helm_agones" cannot be used with depends_on because it contains a
nested provider configuration for "helm", at
../../../install/terraform/modules/helm3/helm.tf:19,10-16.

This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
```

**Comment by aLekSer** [comment]
Previous error fixed here:
https://github.com/aLekSer/agones/tree/terraform/depends_on
However this does not change the fact that GKE reinstalled only, without reinstalling Helm Agones module.

**Comment by aLekSer** [comment]
Test what happens with updating GKE Kubernetes version only if this has the same: recreate the cluster without recreating CRDs for Agones.

**Comment by markmandel** [comment]
Maybe this should be renamed to:

"No Agones helm installation when cluster name changed via Terraform"

Or something like that?
