### ISSUE TITLE
Custom protocol support

### ISSUE THREAD

**Issue by WenchaoXia** [googleforgames/agones#1392]
**Is your feature request related to a problem? Please describe.**
I have a UE4 server, and a custom protobuf rpc implemention. I don't find a way to enable gRPC client in UE4, and want use my RPC implemention in agones.

**Describe the solution you'd like**
Allow custom communication plugin, with which allocator service and game server talk to agones service/sdk.

**Describe alternatives you've considered**
Integration of gRPC client in UE4.

**Additional context**
HTTP from allocator service to agones is slow when workloadis high.

**Comment by markmandel** [comment]
Agones does not provide any protocol support other than letting you select whether you want a TCP or UDP port protocol ([GameServer Reference](https://agones.dev/site/docs/reference/gameserver/)).

So it is up to you to configure your RPC protocol through the provided UDP or TCP port.

**Comment by roberthbailey** [comment]
Are you asking for a more "native" SDK for UE4 that doesn't use HTTP and instead uses gRPC to communicate between your game and the sdk server sidecar?

**Comment by markmandel** [comment]
I think this question is answered. I'm going to close it for now to clean things up, but please feel free to reopen if you have follow ups :+1:
