### ISSUE TITLE
Add allocator server certificate creation as part of the helm installation

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1407]
**Is your feature request related to a problem? Please describe.**
The server certificate that is used by the allocator service requires SAN. The service's external IP address is only assigned when the service is deployed. Therefore, an additional step is required after the installation to [replace the allocator service certificate](https://agones.dev/site/docs/advanced/allocator-service/#server-tls-certificate). 

**Describe the solution you'd like**
To remove the additional step, the script should be added as part of the post installation step in helm.

**Comment by markmandel** [comment]
We should definitely still have an option to turn this off - just thinking of on-prem or Nodeport setup, wherein the external lb is not spun up as part of the Service definition.

**Comment by roberthbailey** [comment]
At this point we are not planning on implementing this feature.
