### ISSUE TITLE
Is there a choice to use Agones with k8s providers that does not support "hostPort"?

### ISSUE THREAD

**Issue by zhongfugao** [googleforgames/agones#1416]
**Is your feature request related to a problem? Please describe.**
I have tried Agones with GKE where it works perfect, but as i try it with several other k8s providers, i have been told they do not support "hostPort" configuration in Pod yaml. And as i learned about Agones, this will block the game server to be connected from client.

**Describe alternatives you've considered**
I would like to see if it is possible to be resolved by using "NodePort" or other networking solutions instead of using "HostPort".

**Comment by markmandel** [comment]
This is extremely unlikely. Especially since HostPort is supported on the GKE, EKS and AKS, as well as others.

What Cloud provider are you referring to?

**Comment by roberthbailey** [comment]
NodePort isn't likely to be a good alternative, since requires creating a kubernetes service for each gameserver which isn't going to scale very well.

**Comment by zhongfugao** [comment]
> This is extremely unlikely. Especially since HostPort is supported on the GKE, EKS and AKS, as well as others.
> 
> What Cloud provider are you referring to?

i see. i have checked providers in China like Aliyun, and they confirmed me that they don't support that yet.

**Comment by zhongfugao** [comment]
> NodePort isn't likely to be a good alternative, since requires creating a kubernetes service for each gameserver which isn't going to scale very well.

**Comment by zhongfugao** [comment]
> NodePort isn't likely to be a good alternative, since requires creating a kubernetes service for each gameserver which isn't going to scale very well.

Thank you!

**Comment by zhongfugao** [comment]
local provider limitations. close it now.
