### ISSUE TITLE
agones-allocator couldn't be connected via a C++ gRPC client

### ISSUE THREAD

**Issue by faifai0429** [googleforgames/agones#1421]
**What happened**:
agones-allocator couldn't be connected via a C++ gRPC client but works for the example allocator-client using the same set of key and certificate

**What you expected to happen**:
C++ gRPC client can ask agones-allocator to allocate a game server

**How to reproduce it (as minimally and precisely as possible)**:
1. Follow https://agones.dev/site/docs/advanced/allocator-service/ to generate required key/cert for the mTLS gRPC client
2. Compile gRPC v1.20.1/v1.27.3 using the source from git
3. Mimic the example allocator-client written in go with C++
4. Compile the .proto files in proto/allocation and proto/googleapis for gRPC C++
5. Running the below code and WaitForConnected() will eventually timeout 

```
std::string Director::ReadFile(const char* FileName) const
{
	std::string Buffer;

	std::ifstream IFstream(FileName, std::ios_base::binary | std::ios_base::in);

	if (IFstream.is_open())
	{
		std::cout << "Reading file " << FileName << std::endl;

		Buffer = std::string
		(
			std::istreambuf_iterator<char>(IFstream),
			std::istreambuf_iterator<char>()
		);
	}
	else
	{
		std::cout << "Failed to read file " << FileName << std::endl;
	}

	return Buffer;
}

bool Director::ConnectToAgonesAllocator()
{
	grpc::SslCredentialsOptions SSLCredentialsOptions;

	SSLCredentialsOptions.pem_root_certs	=	std::move(ReadFile(Director::AgonesServiceCertificateFileName));
	SSLCredentialsOptions.pem_private_key	=	std::move(ReadFile(Director::AgonesClientKeyFileName));
	SSLCredentialsOptions.pem_cert_chain	=	std::move(ReadFile(Director::AgonesClientCertificateFileName));

	const std::shared_ptr<grpc::ChannelCredentials> SSLChannelCredentials = grpc::SslCredentials(SSLCredentialsOptions);

	pAgonesAllocatorGRPCChannel = grpc::CreateChannel(Director::AgonesAllocatorEndPoint, SSLChannelCredentials);

	const grpc_connectivity_state AgonesAllocatorGRPCConnectivityState = pAgonesAllocatorGRPCChannel->GetState(false);

	if (pAgonesAllocatorGRPCChannel && AgonesAllocatorGRPCConnectivityState != grpc_connectivity_state::GRPC_CHANNEL_SHUTDOWN)
	{
		const gpr_timespec TimeoutTimepoint = gpr_time_add
		(
			gpr_now(GPR_CLOCK_REALTIME),
			gpr_time_from_seconds(500, GPR_TIMESPAN)
		);

		std::cout << "Connecting to the Agones allocator service..." << std::endl;

		bIsAgonesAllocatorConnected = pAgonesAllocatorGRPCChannel->WaitForConnected(TimeoutTimepoint);

		if (bIsAgonesAllocatorConnected)
		{
			std::cout << "Connected to the Agones allocator service" << std::endl;

			pAgonesAllocatorStub = v1alpha1::AllocationService::NewStub(pAgonesAllocatorGRPCChannel);

			return true;
		}
	}

	std::cout << "Failed to connect to the Agones allocator service" << std::endl;

	return false;
}

```
**Anything else we need to know?**:

**Environment**:
- Agones version: v1.4.0
- gRPC version: v1.20.1
- VS2017 Compiler
- Kubernetes version (use `kubectl version`): client v1.17.0, server v1.13.12-gke.25
- Cloud provider or hardware configuration:
   Windows 10 Pro x64
- Install method (yaml/helm):
   YAML
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Thanks for submitting @faifai0429 but I think we're going to need more information, as there are a variety of reasons this could be failing:

1. Is the endpoint you are pointing at wrong?
1. Is one of your certs misconfigured?
1. Since `WaitForConnect` doesn't provide any error details you may want to try invoking a RPC command regardless, and get back a https://grpc.github.io/grpc/cpp/classgrpc_1_1_status.html value, and interrogate that to see if sheds some more light.

**Comment by faifai0429** [comment]
> Thanks for submitting @faifai0429 but I think we're going to need more information, as there are a variety of reasons this could be failing:
> 
> 1. Is the endpoint you are pointing at wrong?
> 2. Is one of your certs misconfigured?
> 3. Since `WaitForConnect` doesn't provide any error details you may want to try invoking a RPC command regardless, and get back a https://grpc.github.io/grpc/cpp/classgrpc_1_1_status.html value, and interrogate that to see if sheds some more light.

For 1 and 2, as mentioned, the example allocator-client written in go in the agones examples folder works using the same endpoint and certs. 

For 3, I tried to make a PostAllocation() call, it returns an error status with error message failed to connect to all addresses

**Comment by markmandel** [comment]
> For 1 and 2, as mentioned, the example allocator-client written in go in the agones examples folder works using the same endpoint and certs.

Can we log the endpoint details, and the filenames of the certs, just to double check?

**Comment by faifai0429** [comment]
> > For 1 and 2, as mentioned, the example allocator-client written in go in the agones examples folder works using the same endpoint and certs.
> 
> Can we log the endpoint details, and the filenames of the certs, just to double check?

There are no logs logged by the agones-allocator pods, I have checked that filenames and the certs are correct.

**Comment by pooneh-m** [comment]
What is the AgonesAllocatorEndPoint? Does it have the port (e.g. external-ip:443)?

**Comment by faifai0429** [comment]
> What is the AgonesAllocatorEndPoint? Does it have the port (e.g. external-ip:443)?

Yes sure, external-ip:443

**Comment by faifai0429** [comment]
I have also tried to use C# to make a call, the same result as C++. I am afraid the agones-allocator only talks to a go gRPC client?

**Comment by pooneh-m** [comment]
Good question. agones-allocator does not have a golang specific dependency. I'll set up my machine to write a sample C# code and try it out. Stay tuned! In the meantime, please instrument your code to find out what is causing the timeout.

**Comment by markmandel** [comment]
What is the error you are getting back from the C# library? More details and a stacktrace would be good to know.

gRPC is annoyingly cross compatible :smile: so I would be very surprised if there was a language dependency here.

We are on gRPC version v1.20.1 currently, but future versions should be fine.

**Comment by faifai0429** [comment]
> What is the error you are getting back from the C# library? More details and a stacktrace would be good to know.
> 
> gRPC is annoyingly cross compatible 😄 so I would be very surprised if there was a language dependency here.
> 
> We are on gRPC version v1.20.1 currently, but future versions should be fine.

I have tried exactly v1.20.1 but have no luck. I suppose gRPC from its principle, should work across platforms and languages.

Anyway, I got this message from catching the exception when calling PostAllocate() from the C# below: 
```
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="channel is in state TRANSIENT_FAILURE")
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 78
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\DefaultCallInvoker.cs:line 46
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 51
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\ClientBase.cs:line 174
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 48
   at V1Alpha1.AllocationService.AllocationServiceClient.PostAllocate(AllocationRequest request, CallOptions options) in C:\mf\Binaries\Win64\Plugin\grpc\grpc-prefix\src\grpc\examples\csharp\Helloworld\GreeterClient\AllocationGrpc.cs:line 85
   at V1Alpha1.AllocationService.AllocationServiceClient.PostAllocate(AllocationRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\mf\Binaries\Win64\Plugin\grpc\grpc-prefix\src\grpc\examples\csharp\Helloworld\GreeterClient\AllocationGrpc.cs:line 81
   at GreeterClient.Program.Main(String[] args) in C:\mf\Binaries\Win64\Plugin\grpc\grpc-prefix\src\grpc\examples\csharp
```

C# code:
```
public static void Main(string[] args)
{
	string AgonesAllocatorEndpoint = "127.0.0.1:443";

	string AgonesServiceCertificate = File.ReadAllText("AgonesService.crt");

	string AgonesClientKey = File.ReadAllText("AgonesClient.key");

	string AgonesClientCertificate = File.ReadAllText("AgonesClient.crt");

	SslCredentials SSLCredential = new SslCredentials(AgonesServiceCertificate, new KeyCertificatePair(AgonesClientKey, AgonesClientCertificate));
	
	Channel Channel = new Channel(AgonesAllocatorEndpoint, SSLCredential);

	AllocationService.AllocationServiceClient Client = new AllocationService.AllocationServiceClient(Channel);

	AllocationRequest Request = new AllocationRequest();
	LabelSelector Selector = new LabelSelector();
	Selector.MatchLabels.Add("agones.dev/fleet", "game-server-fleet");
	Request.RequiredGameServerSelector = Selector;
	
	Thread.Sleep(2000);

	try
	{
		AllocationResponse Response = Client.PostAllocate(Request);

		Console.Write(Response.State.ToString());

	} catch(Exception e)
	{
		Console.Write(e.ToString());
	}

	// Channel.ConnectAsync().Wait();

	Channel.ShutdownAsync().Wait();

	Console.WriteLine("Press any key to exit...");

	Console.ReadKey();
}
```

**Comment by pooneh-m** [comment]
string AgonesAllocatorEndpoint = "external-ip:443"; wouldn't work. Find the **external-ip** of your cluster from:
```
kubectl get services agones-allocator -n agones-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
```

**Comment by faifai0429** [comment]
> string AgonesAllocatorEndpoint = "external-ip:443"; wouldn't work. Find the **external-ip** of the agones-allocator service in your cluster from:
> 
> ```
> kubectl get services agones-allocator -n agones-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
> ```

I wrote it intentionally just to avoid giving the real IP on where the agoes-allocator is hosted

**Comment by pooneh-m** [comment]
You are using SslCredentials for authentication, while you should be using [certificate authentication at TLS level](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-3.1#client-certificate-authentication).

**Comment by faifai0429** [comment]
I guess the code mentioned above is exactly how you do mTLS authentication in C# and C++?

**Comment by faifai0429** [comment]
https://github.com/grpc/grpc/issues/15890

https://github.com/grpc/grpc-node/issues/157

Maybe it's a hint?

**Comment by faifai0429** [comment]
**grpc/ssl handshake fails with a golang server and a c++ client**
https://github.com/grpc/grpc/issues/15890 

**Client call with self signed certificates don't verify properly**
https://github.com/grpc/grpc-node/issues/157

**Cannot get Go GRPC client talking to C++ server**
https://github.com/grpc/grpc-go/issues/1120

and a lot more you can google it

Maybe it's a hint? All of them have an authentication problem given a **go based server** and other language's client. In the third links, it seems to provide an insight that in gRPC version 1.20, it had a problem with the :authority that makes go and other language gRPC service are not able to communicate with each other. Hope the Agones team can test it out with a client written in other language.

**Comment by faifai0429** [comment]
**grpc/ssl handshake fails with a golang server and a c++ client**
https://github.com/grpc/grpc/issues/15890 

**Client call with self signed certificates don't verify properly**
https://github.com/grpc/grpc-node/issues/157

**Cannot get Go GRPC client talking to C++ server**
https://github.com/grpc/grpc-go/issues/1120

and a lot more you can google it

Maybe it's a hint? All of them have an authentication problem given a **go based server** and other language's client. In the third links, it seems to provide an insight that in gRPC version 1.20, it had a problem with the :authority that makes go and other language gRPC service are not able to communicate with each other (Agones is employing v1.20.1 at the moment). Hope the Agones team can test it out with a client written in other language, feel free to use the C++ and C# code above.

**Comment by pooneh-m** [comment]
I did try your code and I got a different errors, which seems to be happening when listing channels returns empty result. I haven't figured out the root cause yet. Here is the error I get:

```
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Empty update")
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
```
Then I tried to use GrpcChannelOptions with debug logger enabled:
```
        public static AllocationService.AllocationServiceClient CreateClientWithCert(
            string baseAddress,
            X509Certificate2 certificate)
        {

            var loggerFactory = LoggerFactory.Create(logging =>
            {
                logging.AddConsole();
                logging.SetMinimumLevel(LogLevel.Debug);
            });

            // Add client cert to the handler
            var handler = new HttpClientHandler();
            handler.ClientCertificates.Add(certificate);
            handler.ServerCertificateCustomValidationCallback = 
                HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

            // Create the gRPC channel
            var channel = GrpcChannel.ForAddress(baseAddress, new GrpcChannelOptions
            {
                HttpClient = new HttpClient(handler),
                LoggerFactory = loggerFactory
            });

            return new AllocationService.AllocationServiceClient(channel);
        }
```
I got different error with more debugging info. 

```
dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'https://34.82.82.7/v1alpha1.AllocationService/PostAllocate'.
dbug: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request)
dbug: Grpc.Net.Client.Internal.GrpcCall[8]
      gRPC call canceled.
Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request.")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at V1Alpha1.AllocationService.AllocationServiceClient.PostAllocate(AllocationRequest request, CallOptions options) in /usr/local/google/home/pooneh/github/agones.dev/agones/examples/allocator-client-csharp/obj/Debug/netcoreapp3.1/AllocationGrpc.cs:line 86
   at V1Alpha1.AllocationService.AllocationServiceClient.PostAllocate(AllocationRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in /usr/local/google/home/pooneh/github/agones.dev/agones/examples/allocator-client-csharp/obj/Debug/netcoreapp3.1/AllocationGrpc.cs:line 82
   at AllocatorClient.Program.Main(String[] args) in /usr/local/google/home/pooneh/github/agones.dev/agones/examples/allocator-client-csharp/Program.cs:line 35Press any key to exit...
fail: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call: An error occurred while sending the request.'.
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
```
I'll be doing more investigation. In the meanwhile, if you find the root cause please update the thread.

**Comment by faifai0429** [comment]
Basically I can do nothing on my side but changing to invoke it via Kubernetes API with CURL

**Comment by pooneh-m** [comment]
Thanks, I am also following up on the issue: https://stackoverflow.com/questions/60823164/grpc-client-in-c-sharp-does-not-work-with-grpc-server-in-go-with-mtls-support
Not response yet.
I will open an issue on https://github.com/grpc/grpc-dotnet to root cause. The handshake is successful but golang server seems to be rejecting the grpc call after the handshake.

**Comment by markmandel** [comment]
https://stackoverflow.com/questions/55364545/is-it-possible-to-accept-self-signed-certificates-in-grpc-core also seems relevant. We're also getting reports of issues with C# as well.

**Comment by pooneh-m** [comment]
I wrote a C# sample code that uses a self-signed certificate and it succeeds with the go server: https://github.com/pooneh-m/grpc-sample/tree/master/hellomtls
Only when I set the GetConfigForClient it fails for C# client, which is the case for the agones-allocator golang server. GetConfigForClient is used for automatically refresh the ClientCAs when there is a change without restarting the servers.

**Comment by HakShak** [comment]
We aren't using this specific project, but we have an internal project which uses a C++ client and golang server mTLS configuration. We have run into this problems as well with the path of: 

C++ client->Public AWS ELB->Kubernetes->Terminate mTLS on pod

However, when we change the path to this it works:

C++ client->**Private** AWS ELB->Kubernetes->Terminate mTLS on pod

The running theory is that the transition between a public CIDR to a private one creates this problem but we haven't been able to find an error specifically about that other than the peripheral `:authority` tickets here and there for the golang implementation.
