### ISSUE TITLE
aCollaborator Request

### ISSUE THREAD

**Issue by sonvo90** [googleforgames/agones#1426]
If you'd like to become a collaborator of the Agones repo on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join. Once accepted you'll be able to have issues assigned to you! 

### GitHub user id
- List your GitHub user id

### Company affiliation
- List your company name, or indicate Individual if you're not affiliated with a company

### Requirements

- [ ] I have reviewed the [contribution guidelines](https://github.com/googleforgames/agones/blob/master/CONTRIBUTING.md)
- [ ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [ ] I have joined the [Agones Slack workspace](https://join.slack.com/t/agones/shared_invite/enQtMzE5NTE0NzkyOTk1LWU3ODAyZjdjMjNlYWIxZTAwODkxMGY3YWEyZjNjMjc4YWM1Zjk0OThlMGU2ZmUyMzRlMDljNDJiNmZlMGQ1M2U)

**Comment by aLekSer** [comment]
Spam
