### ISSUE TITLE
Dynamic hostport allocation

### ISSUE THREAD

**Issue by Cyansilver** [googleforgames/agones#1430]
I'm reading the code https://github.com/googleforgames/agones/blob/master/pkg/gameservers/portallocator.go but still don't get how Agones can do dynamic hostport allocation for a pod?

Thank you

**Comment by markmandel** [comment]
Thanks for dropping by our project! :wave: But I'm sorry, but I'm not sure what the question is? 

Are you looking to work on a feature that includes port allocation? In which case, I would suggest first writing a design ticket, as per our [contributing guidelines](https://github.com/googleforgames/agones/blob/master/CONTRIBUTING.md), and we can help guide you towards the implementation details.

**Comment by markmandel** [comment]
Doing some cleanup. Please reopen if you want to continue the conversation.
