### ISSUE TITLE
Terraform, GKE - add autoscaling Node Pools option

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1467]
**Is your feature request related to a problem? Please describe.**

In order GKE Cluster to be more cost-efficient there should be an option to scale down GameServers Node Pool size.
Some of Agones users who used gcloud to provision their clusters has already autoscaling for Node Pools turned on. This functionality also is supported by Packed `GameServerAllocation` Scheduling.

**Describe the solution you'd like**
[container_node_pool#autoscaling](https://www.terraform.io/docs/providers/google/r/container_node_pool.html#autoscaling) or
[container_cluster#cluster_autoscaling](https://www.terraform.io/docs/providers/google/r/container_cluster.html#cluster_autoscaling)

Currently we are using strict [node_count](https://www.terraform.io/docs/providers/google/r/container_node_pool.html#node_count) parameter, which should be omitted when we are using `autoscaling` parameter.
So we could add this configuration separately to what we have now.

**Describe alternatives you've considered**
If it is possible merge both options together and depending on variable use autoscaling or strict node pool size.

**Additional context**
Using the Cluster Autoscaler with Agones - #368
and Kubernetes Node Autoscaling #145

**Comment by zmerlynn** [comment]
@chiayi is working on this but not a collaborator here so I can't assign.
