### ISSUE TITLE
Outdated and incomplete instructions on installing Agones using Helm

### ISSUE THREAD

**Issue by felipeota** [googleforgames/agones#1494]
- It gives you a command to run install agones on a namespace "agones-system" but doesn't tell you to create it, the YAML version does

- It gives a parameter --name in the command to create it but it is no longer available in the latest version of Helm, 3.1.0

**Comment by markmandel** [comment]
This sounds relevant to #1436 

Wondering if this should be considered duplicate? (might make sense to merge the tickets)

**Comment by felipeota** [comment]
In that case, until that is solved, maybe specifying in the perquisites that the helm version should be below 3.
