### ISSUE TITLE
grpc-gateway powered REST API for MultiCluster Allocation

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1495]
**Is your feature request related to a problem? Please describe.**

For users for which gRPC isn't a viable option, it would be handy to have a REST based API as well for the gPRC API.

**Describe the solution you'd like**

We use grpc-gateway to generate the REST API, but also use the same certificates to authenticate the endpoint as we would for the gRPC endpoint.

We can also generate a swagger.json so that people can generate REST clients as well.

**Describe alternatives you've considered**

Having no REST endpoint. But we're seeing bugs around SSL cert management in other languages, and this would provide a workaround for any other issues we have in the future.

**Additional context**

I would recommend completing #1331 first.

It might also be worth updating grpc-gateway at some point as well, we're quite a few releases behind.

**Comment by Davidnovarro** [comment]
REST API should be ok.

**Comment by robbieheywood** [comment]
+1 - we'd really like this!
