### ISSUE TITLE
Create a GameServer

### ISSUE THREAD

**Issue by hulong121** [googleforgames/agones#1538]
**What happened**:
when i want to create a sample game server using the following command "kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-1.5.0/examples/simple-udp/gameserver.yaml" on Minikube, i got an error "The GameServer "simple-udp-xvnhn" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`"

**What you expected to happen**:
i expected to see  a successful output

**How to reproduce it (as minimally and precisely as possible)**:
just do it follow https://agones.dev/site/docs/getting-started/create-gameserver/

**Anything else we need to know?**:
i download the sample code from github, but still got an error message after i run kubectl apply -f gameserver.yaml, if i use examples/simple-udp/gameserver.yaml, the error is "resource name may not be empty"(if i added the name field into metadata in gameserver.yaml, the error changed, it's "The GameServer "gds-example" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`"), if i use examples/gameserver.yaml, the error is "The GameServer "gds-example" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`"
maybe gameserver can't be run on Minikube even a sample?

**Environment**:
- Agones version: latest
- Kubernetes version (use `kubectl version`):latest
- Cloud provider or hardware configuration:google cloud compute engine, ubuntu 18.0.4LTS
- Install method (yaml/helm):yaml
- Troubleshooting guide log(s):
- Others:

**Comment by aLekSer** [comment]
@hulong121 Which version of Kubernetes do you use? 1.18?
Can you please create a Kubernetes cluster with version 1.14 which was tested and supported by Agones.
This might be related to the bug https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/210

**Comment by hulong121** [comment]
yes, i used 1.18, i'm trying to delete it and start with 1.14.10, and now it's ok, thanks

**Comment by sun-wenming** [comment]
Can the problem be solved in 1.18?

**Comment by LukeWood** [comment]
^ Same question here.  is this solveable in 1.18?

**Comment by markmandel** [comment]
We are working on the next version of Agones to support 1.18 right now https://github.com/googleforgames/agones/issues/1971
