### ISSUE TITLE
HealthCheckLoop Never invoked in C# SDK

### ISSUE THREAD

**Issue by stevenflautner** [googleforgames/agones#1583]
**What happened**:
Agones Game Server becomes Unhealthy because Health is never signaled by the SDK.
HealthCheckLoop function is never invoked in Agones Game Server SDK for C#

**What you expected to happen**:
HealthCheckLoop function should be invoked by the SDK in [AgonesSDK.cs](https://github.com/googleforgames/agones/blob/release-1.5.0/sdks/csharp/sdk/AgonesSDK.cs) and since it being private there's no way to call it externally.

```
		private async Task HealthCheckLoop()
		{
			while(!cts.IsCancellationRequested)
			{
				if(HealthEnabled)
					await HealthAsync();
				await Task.Delay(HealthInterval * 1000);
			}
		}
```

**How to reproduce it (as minimally and precisely as possible)**:
Use the AgonesSDK for C#

**Anything else we need to know?**:

**Environment**:
- Agones version: SDK 1.0.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by aLekSer** [comment]
There is a lack of SDK conformance tests as well as Unit Tests for this functionality. So there is a need to fix C# SDK.

**Comment by aLekSer** [comment]
For now you can call `HealthAsync`.  https://github.com/googleforgames/agones/blob/0850d9ec9fcc036c4c8e67d356eac76a22a9a1fa/sdks/csharp/sdk/AgonesSDK.cs#L275
`HealthCheckLoop` is redundant, I could not find such functionality in Golang SDK.

**Comment by Davidnovarro** [comment]
PR #1598 closes this issue.

**Comment by markmandel** [comment]
@Davidnovarro this is a bug against the C# SDK. https://github.com/googleforgames/agones/pull/1598 is a PR against the Unity SDK, they are different SDKs.
