### ISSUE TITLE
Update Rust and Nodejs simple examples - build target is failing

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1600]
`make build-example-rust-simple` fails with the following logs:
<details>
  <summary>Error logs</summary>
 
  ```bash
error[E0658]: use of unstable library feature 'ptr_cast'
  --> /Users/alexander.apalikov/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:65:66
   |
65 |     unsafe { slice::from_raw_parts(slice::from_ref(val).as_ptr().cast(), size) }
   |                                                                  ^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/60602

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
  ```
  
</details>

**What happened**:

`make build-example-rust-simple` is dependent on local `rustc` version.

**What you expected to happen**:
I expect the rust build process should be fired inside the container to make sure version is correct.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ rustc -V 
1.36.0
$ make build-example-rust-simple
```
**Anything else we need to know?**:

**Environment**:
- Agones version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by aLekSer** [comment]
Also I was not able to build `nodejs-simple` example:
<details>
  <summary>Error logs</summary>
  
  ```bash
npm WARN nodejs-simple No repository field.
npm WARN nodejs-simple No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-01T11_45_30_595Z-debug.log
The command '/bin/sh -c cd examples/nodejs-simple &&     npm install && npm rebuild' returned a non-zero code: 1
make[2]: *** [build] Error 1
make[1]: *** [build-example] Error 2
make: *** [build-example-nodejs-simple] Error 2
by-it00060:build alexander.apalikov$ make build-example-nodejs-simple
  ```
  
</details>

**Comment by steven-supersolid** [comment]
Ah more node-gyp issues. Will try and take a look this weekend

**Comment by markmandel** [comment]
I think this can be closed now, since I'm fairly sure we've updated the examples since this ticket was created?

**Comment by markmandel** [comment]
Closing!
