### ISSUE TITLE
Feature Request: Allow 'serverCa' to come from secret/configmap in GameServerAllocationPolicy CRD

### ISSUE THREAD

**Issue by robbieheywood** [googleforgames/agones#1614]
**Is your feature request related to a problem? Please describe.**
Currently, you have to specify the `serverCA` field in plain text in the [GameServerAllocationPolicy CRD](https://github.com/googleforgames/agones/blob/release-1.6.0/pkg/apis/multicluster/v1/gameserverallocationpolicy.go). We have this value stored in a configMap in our cluster, and so it leads to the laborious step of having to read the secret out of the cluster, base64 encode it and then place it into the GameServerAllocationPolicy resource. It would be nicer if we could just specify a configMap (or secret) name for specifying the serverCa.

**Describe the solution you'd like**
The ability to specify a secret or configmap name for the `serverCa`, rather than having to put the value in plain text into the custom resource. I think this could be done either by adding a new field `serverCaSecret` or by editing to `serverCa` field to allow a secret name to be specified (although not sure how this could be done in a backwards compatible way).

**Describe alternatives you've considered**
See above

**Additional context**
n/a

**Comment by pooneh-m** [comment]
I was planning to deprecate this flow in the long term as the cert management solutions on the cluster don't support changing 'ca.crt', but if there is a usecase for it, we will keep it. Please give it a try and if it works well for your scenario, I'll add the documentation back. Here is [the code](https://github.com/googleforgames/agones/blob/master/pkg/gameserverallocations/allocator.go#L382-L393) that supports both flows.

**Comment by robbieheywood** [comment]
@pooneh-m - I've just tried this out and it worked well for us - it's actually easier than specifying something like `serverCaSecret`, which is great 🎉 

For context, we actually use Vault to store/manage these certificates rather than CertManager. We then use [Vault Agent](https://www.vaultproject.io/docs/agent) to place these secrets directly into `/home/allocator/tls` and `/home/allocator/client-ca` for the Allocator to use (rather than loading from a kubernetes secret). For this use case, the solution you suggest works really well. I'd definitely appreciate adding the documentation in and keeping this flow in future 😄

**Comment by pooneh-m** [comment]
Thanks @robbieheywood for validating. Do you mind adding the documentation based on your experience? Is the documentation enough for closing this bug?

**Comment by pooneh-m** [comment]
As a separate topic, it would also be nice to have a scenario section on different solutions for certificate management, like as you mentioned Vault Agent or CertManager. Vault Agent came up [twice](https://github.com/googleforgames/agones/issues/1599#issuecomment-637698593) recently.

**Comment by robbieheywood** [comment]
@pooneh-m - I agree that updating the documentation is enough to close this feature request. I've raised https://github.com/googleforgames/agones/pull/1619 to do this - it'd be great if you could have a look.
