### ISSUE TITLE
When I have deleted fleet.How to delete gameservers created by fleet

### ISSUE THREAD

**Issue by sun-wenming** [googleforgames/agones#1628]
**Describe the solution you'd like**
When I have deleted fleet.How to delete gameservers created by fleet.
I can't find anything about deletion from the documentation

**Describe alternatives you've considered**
In the official document, add about how to delete

**Comment by markmandel** [comment]
When you delete the Fleet, the GameServers it controls are deleted along with it (assuming they are not Allocated)

https://agones.dev/site/docs/reference/fleet/ might be a good place to specifically mention this.

**Comment by sun-wenming** [comment]
ok. thx.
