### ISSUE TITLE
Collaborator Request

### ISSUE THREAD

**Issue by moesy** [googleforgames/agones#1640]
If you'd like to become a collaborator of the Agones repo on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join. Once accepted you'll be able to have issues assigned to you! 

### GitHub user id
- moesy

### Company affiliation
- Google Cloud

### Requirements

- [X] I have reviewed the [contribution guidelines](https://github.com/googleforgames/agones/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Agones Slack workspace](https://join.slack.com/t/agones/shared_invite/enQtMzE5NTE0NzkyOTk1LWU3ODAyZjdjMjNlYWIxZTAwODkxMGY3YWEyZjNjMjc4YWM1Zjk0OThlMGU2ZmUyMzRlMDljNDJiNmZlMGQ1M2U)

**Comment by markmandel** [comment]
I did this one :+1:
