### ISSUE TITLE
Document how Istio & Agones can work together

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1661]
**Is your feature request related to a problem? Please describe.**

We get regular user questions around Agones not working, and ultimately it's because Istio is installed and is interfering with Agones operation.

**Describe the solution you'd like**

Write some documentation on how to install Istio so it works nicely with Agones and doesn't hinder its operation.

**Describe alternatives you've considered**
None.

**Additional context**
This gets asked so much, we've added this to our initial troubleshooting guide within Slack (and should do the same on the website as well).

**Comment by rcreasey** [comment]
I’ll take a look!

**Comment by markmandel** [comment]
There we go - assigned!

**Comment by gsagula** [comment]
:cry:

**Comment by wSedlacek** [comment]
So I did some research into this.

First, it must be understood that Agones design is using NodePorts directly to pods.
This is clearly detailed in the FAQ, https://agones.dev/site/docs/faq/#network
This design intentionally bypasses any ingress or gateway giving the shortest path between the game server and the client.

Second it is important to understand the Istio proxy itself only supports TCP and simply forwards UDP traffic.
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

So using Agones with Istio would mean:
1) Using Istio as you would for all your inter-cluster and other servers including your matchmaking server.
2) Using Istio for other traffic like API request to the matchmaking server.

Then you could either:
a) Use the node ports that Agones provides from game server allocation OR
b) Create additional services after allocating a GameServer (likely in the Matchmaking server that created the GameServerAllocation)

The documentation on working with minikube what a service selecting a game server might look like.
https://agones.dev/site/docs/installation/creating-cluster/minikube/#create-a-service
