### ISSUE TITLE
k8s.io/client-go v0.18.0

### ISSUE THREAD

**Issue by ht290** [googleforgames/agones#1682]
**Is your feature request related to a problem? Please describe.**
It would be great if agones go-client can use `k8s.io/client-go v0.18.0`.

**Describe the solution you'd like**
Use `k8s.io/client-go v0.18.0`

**Describe alternatives you've considered**
I suppose we could use the native k8s go-client was CRD?

**Additional context**

**Comment by aLekSer** [comment]
I am closing this as we have a predefined [upgrade process](https://agones.dev/site/docs/installation/#usage-requirements:. 
```
Warning
Later versions of Kubernetes may work, but this project is tested against 1.15, and is therefore the supported version. Agones will update its support to n-1 version of what is available across the majority of major cloud providers - GKE, EKS and AKS, while also ensuring that all Cloud providers can support that version.
```
https://github.com/googleforgames/agones/issues/1649 would use client-go 13.0 .
