### ISSUE TITLE
Proposal: provide allocator-client.default secret in gameserver namespace

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1686]
**Is your feature request related to a problem? Please describe.**
There are multiple steps for enabling multi-cluster allocation and one of the steps is creating an allocation client certificate. 

**Describe the solution you'd like**
This can be improved if Agones would create a self-signed TLS client certificate stored in k8s secret, named `allocator-client.default`. The secret would be available on the game server namespace by default, similar to agones-sdk service account and act as multi-cluster allocation client secret if in the `GameServerAllocationPolicy` the `secretName` is unspecified. 

Istio also has a similar functionality that would create `istio.default` TLS secret in every namespace in a k8s cluster.

**Comment by pooneh-m** [comment]
@markmandel can you please take a look. I want to replace the multi-cluster allocation [client certificate](https://agones.dev/site/docs/advanced/multi-cluster-allocation/#establish-trust) creation by having a default secret created in the game server namespace. This is what istio citadel does (to have a default secret created) and it simplifies usage. The secret can be managed by a certificate manager solution on the cluster in the future.

**Comment by markmandel** [comment]
So something like when we generate self-signed certs for the agones controller? ([source](https://github.com/googleforgames/agones/blob/master/install/helm/agones/templates/extensions.yaml#L14))

if so, that seems to make a lot of sense!

**Comment by pooneh-m** [comment]
This is also a related customer request: https://github.com/googleforgames/agones/issues/1698

**Comment by roberthbailey** [comment]
It looks like this was fixed by https://github.com/googleforgames/agones/pull/1702. Please re-open if there is outstanding work to do.
