### ISSUE TITLE
Migrate away from Pull Panda

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#1689]
_Email title: Action needed: Pull Assigner and Pull Reminders_

# A Pull Panda update
Since we [announced the acquisition](https://github.blog/2019-06-17-github-acquires-pull-panda/) of Pull Panda last year, we’ve been working hard to bring its features into your GitHub experience. Now, Pull Assigner and Pull Reminders are available on GitHub as [code review assignment](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team) and [scheduled reminders](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-team).

As we now have a GitHub-native experience, both **Pull Assigner and Pull Reminders will no longer operate as of October 14, 2020**. You’ll find migration steps below to make the transition to code review assignments and scheduled reminders.

Note, Pull Analytics will continue operating as it does today.

Next steps
* If you’re using Pull Assigner, learn more about how to configure and use [code review assignments](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team).
* If you’re using Pull Reminders, a migrate option will appear on pull reminder notifications in Slack once your organization is connected to a Slack workspace (see [steps](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-organization)). Most personal and channel reminder settings will migrate without any additional action, but in some cases, you may need to answer questions or adjust some settings. You’ll be guided through the process step by step. Learn more about [team reminders](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-team) and [personal reminders](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-scheduled-reminders).

Let us know if you have any questions.

**Comment by roberthbailey** [comment]
I got a reminder email about this today, since the **October 14th** date is coming up soon.

**Comment by roberthbailey** [comment]
So it's well past October now. Is there anything we actually need to do for this or can we close it as obsolete?

@thisisnotapril

**Comment by markmandel** [comment]
I'm amused I'm still getting these reminders most days:

![image](https://user-images.githubusercontent.com/298370/102518564-4e458780-4046-11eb-8634-98ff6f63aa9a.png)

**Comment by roberthbailey** [comment]
I still get those too....

**Comment by markmandel** [comment]
It's making me question the validity of the statement :rofl:

**Comment by markmandel** [comment]
We're not getting pull panda requests anymore, and we just upgraded to the latest Github+Slack integration thingo.
