### ISSUE TITLE
Allow specifying agones-allocator nodePort via Helm values

### ISSUE THREAD

**Issue by endragor** [googleforgames/agones#1699]
**Is your feature request related to a problem? Please describe.**
We use minikube within a Vagrant VM for development. The main server could be launched locally (on host machine), which requires that services within the VM are accessible from the host machine. minikube doesn't support LoadBalancer services, so we have to specify NodePort for allocator-service. However, by default it allocates a random port, while it would be convenient to have it fixed. It is possible to do that in Kubernetes via `nodePort` option, but it is not exposed in the Helm chart.

**Describe the solution you'd like**
Expose `nodePort` option for allocator service which would be used if `serviceType` is `NodePort`.

**Comment by pooneh-m** [comment]
Please take a look at the [helm configurations](https://agones.dev/site/docs/installation/install-agones/helm/#configuration) for `agones.allocator.http.serviceTyp` and `agones.allocator.http.port`:

**Comment by endragor** [comment]
Thank you, I'm aware about them. There is no way to configure `nodePort` though, which is what this request is about.

**Comment by pooneh-m** [comment]
Thanks for the clarification. Makes sense. `nodePort` is not supported yet.
Also, there are two other solutions for allocating a game server. Would `GameServerAllocation` k8s extension API solve your problem: https://agones.dev/site/docs/guides/gameserver-lifecycle/

**Comment by endragor** [comment]
I've found a workaround for this particular issue (just supplying the generated nodePort as a part of the main server configuration), but still decided to file it in case someone else needs this in the future.

**Comment by pooneh-m** [comment]
Thanks for sharing your solution. Glad to hear that it worked for you!
To be clear, by "main server configuration", are you using `agones.allocator.http.port`? Can you be more specific on your installation steps?

**Comment by roberthbailey** [comment]
This seems like a straightforward extension to the helm chart, if someone would like to contribute a PR to implement it I'd be happy to review it.
