### ISSUE TITLE
/watch/gameserver doesn't start with returning the current state

### ISSUE THREAD

**Issue by endragor** [googleforgames/agones#1703]
GET /watch/gameserver request doesn't start with returning the current state of the game server and instead only provides updates that appeared after the request was made. This makes it hard to use without creating race conditions. If the server is already Allocated, then it won't learn that from /watch/gameserver. Even if you GET /gameserver before that, see that it's not Allocated, and then start watching, it's possible the state was changed between the two requests, so you'll wait forever (or until another update luckily occurs). So currently the only safe way to watch the allocation state is to periodically poll GET /gameserver and /watch/gameserver is dangerous to use on its own.

This could be fixed by making /watch/gameserver start with returning the current state and then provide updates to it.

- Agones version: 1.7.0
- Install method: helm

**Comment by aLekSer** [comment]
Hello @endragor  There is a FeatureGate implemented which is right for this use case.
`SDKWatchSendOnExecute`
https://agones.dev/site/docs/guides/feature-stages/#feature-gates
https://agones.dev/site/docs/guides/client-sdks/#watchgameserverfunctiongameserver

**Comment by endragor** [comment]
Oh, thanks for the pointer. So this is already implemented and the described behavior will be the default in future versions.
