### ISSUE TITLE
Helm chart: allow to specify loadBalancerIP

### ISSUE THREAD

**Issue by endragor** [googleforgames/agones#1709]
**Is your feature request related to a problem? Please describe.**
Helm chart does not allow to specify loadBalancerIP for Agones services, which causes problems when you recreate them, potentially changing the IP, which may require updating DNS/certs/configs.

**Describe the solution you'd like**
Allow providing `loadBalancerIP` that would be used if the `serviceType` is `LoadBalancer`.

**Comment by roberthbailey** [comment]
@endragor - this sounds like a nice improvement. Do you have the bandwidth to try updating the chart definition to add a new parameter?
