### ISSUE TITLE
Helm chart: generateTLS=false uses certificates from the repository

### ISSUE THREAD

**Issue by endragor** [googleforgames/agones#1710]
**What happened**:
`generateTLS=false` uses Helm's `.File.Get` which retrieves certificates from the repository rather than using the user-provided ones, as the Agones documentation claims.

**How to reproduce it (as minimally and precisely as possible)**:
Run this without providing any certs:
```
helm install agones --namespace agones-system --set agones.allocator.generateTLS=false agones/agones --version 1.7.0
```
According to the documentation generateTLS=false uses your certificates from `certs` folder, so this should fail when you don't provide anything. In fact, it uses the [cert folder stored in this repo](https://github.com/googleforgames/agones/tree/a1336de48c813c9667c10f73cb01dbaa04a01bd8/install/helm/agones/certs), which makes it dangerous to use, as you don't want anything TLS-related from a public repository in your environment.

The correct solution would delete certs from this repository and use the user-provided values if `generateTLS=false`.

**Comment by akremsa** [comment]
I will take a look

**Comment by aLekSer** [comment]
There is a bug which does not allow us to do what is mentioned in  this [Agones Helm installation](https://agones.dev/site/docs/installation/install-agones/helm/#tls-certificates)
https://github.com/helm/helm/issues/3276

**Comment by akremsa** [comment]
To make sure that the behavior is exactly as described in a ticket I did the following steps:
1) I created a folder like _"test/certs/allocator"_.
2) Using [this](https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/#2-create-x509-root-and-webhook-certificates) tutorial I've generated 2 certificates: server.crt and server.key.
3) From the root of the new _test_ folder I've called:
 `helm install agones --namespace agones-system --set agones.allocator.generateTLS=false agones/agones --version 1.7.0`
But using `kubectl get secret allocator-client-ca -n agones-system -o yaml` I see that secrets which are used are from the repo, not my local folder. Also, as mentioned above, if you run _helm install_ command from a random folder where _certs_ folder is absent there is no error thrown.

As a solution we can do the following:
1) Remove the phrase _"However if you really need to avoid restarts we suggest that you turn off tls automatic generation (agones.controller.generateTLS to false) and provide your own certificates (certs/server.crt,certs/server.key)."_ from https://agones.dev/site/docs/installation/install-agones/helm/#tls-certificates
2) Mention in the documentation that if you want to provide your own certificates - use install.yaml and provide you secrets there.

@markmandel what do you think about this proposal?

**Comment by endragor** [comment]
I solved this locally by simply providing certs as base64 values when `generateTLS` is `false`. In other words, certificates/keys can be added directly as Helm values, they do not have to be files.

In my install script after generating the certificates I invoke:
```
helm install agones --namespace agones-system -f agones-values.yml \
    --set agones.allocator.TLSClientCert=`base64 -i certs/allocator/client-ca/client.crt` \
    --set agones.allocator.TLSCert=`base64 -i certs/allocator/server.crt` \
    --set agones.allocator.TLSKey=`base64 -i certs/allocator/server.key` \
    ../../agones --version 1.7.0
```

Setting `generateTLS` to `true` is not an option because of #1698. So it seems the Helm chart is not currently usable as-is if you need the allocator service - you have to apply tweaks to make it work.

**Comment by aLekSer** [comment]
@endragor Nice that you have a fix for that. Could you please share a Pull Request?
This is useful, we could follow this way `--set agones.allocator.tlskey` I assume.

**Comment by markmandel** [comment]
@pooneh-m sounds like this is something you should weigh in on

**Comment by pooneh-m** [comment]
Thanks for reporting the issue @endragor. Great suggestions.

Here is my proposal: 
1. Remove the cert from `certs/allocator/*` in the repository.
2. If `agones.allocator.generateTLS=false`, only create/update `allocator-tls` and `allocator-client-ca` secrets if related certs files in `certs/allocator/*` are available (for backward compatibility).
3. Otherwise, use existing prepopulated k8s secrets `allocator-tls` and `allocator-client-ca` on the cluster.

Does it solve your problem?

**Comment by roberthbailey** [comment]
https://github.com/googleforgames/agones/pull/2177 added an option to helm (`disableSecretCreation`) to allow you to bring your own certificates (although you need to install them ahead of time).
