### ISSUE TITLE
Documentation: GameServer updates are not supported. No pods are created after switching image for GameServer

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1724]
**What happened**:
No pod got restarted and rescheduled after updating GameServer to a new image.

**What you expected to happen**:
Create a new pod for GameServer if its image parameter was updated.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-1.7.0/examples/simple-udp/gameserver.yaml
kubectl edit gameservers <name>
// Change image from udp-server:0.21 to udp-server:0.20
kubectl describe gameserver <name>
// See 0.20
kubectl describe pod <name>
// See 0.21
```

**Anything else we need to know?**:

**Environment**:
- Agones version:  1.8.0-dev
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): 
- Others:

**Comment by markmandel** [comment]
We really don't actually support editing GameServer spec (although a controller does make a small change to port values on update, because of old reasons).

So not sure if this is really a bug per se. I'm also concerned that if we add an extra validation webhook to GameServer, it may be a performance issue, since GameServers are on the hotpath - it would require some performance testing to confirm or not.

**Comment by aLekSer** [comment]
@markmandel As a side issue - I found an infinite loop in the code. Which I am able to reproduce with a simple test:
```func TestPortAllocatorAllocate(t *testing.T) {
	t.Parallel()
	fixture := dynamicGameServerFixture()

	t.Run("test allocated port counts", func(t *testing.T) {
... line 64:
		// single port dynamic
		fd := fixture.DeepCopy()
		fd.Spec.Ports[0].PortPolicy = ""
		pa.Allocate(fd)
		assert.Nil(t, err)
...
}
```
Will make a PR to fix this soon. We can have an empty string PortPolicy and no validations on Update. Could lead to this issue.

**Comment by aLekSer** [comment]
I assume at least docs should contain that gameservers could not be updated.

**Comment by markmandel** [comment]
> I assume at least docs should contain that gameservers could not be updated.

Yeah, that totally makes sense!
