### ISSUE TITLE
Agones roles have insufficient permissions defined for clusters where OwnerReferencesPermissionEnforcement is enabled

### ISSUE THREAD

**Issue by thoraxe** [googleforgames/agones#1740]
**What happened**:
When trying to deploy a `GameServer`, I received an error.

**What you expected to happen**:
A `GameServer` should deploy.

**How to reproduce it (as minimally and precisely as possible)**:
* create a k8s cluster
* enable `OwnerReferencesPermissionEnforcement` plugin
* install agones
* create a gameserver

**Environment**:
- Agones version: 1.7
- Kubernetes version (use `kubectl version`): 1.6 but likely any recent version
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
`pods "simple-udp-jcc4d" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>`

In the `agones-controller` role, explicitly adding the finalizers permissions (eg: `gameservers/finalizers`) at least is a workaround. I am not sure if that is the correct fix.

**Comment by roberthbailey** [comment]
He @thoraxe -

Is the step `enable OwnerReferencesPermissionEnforcement plugin` possible on managed k8s environments (GKE, EKS, AKS, etc)?

Can you explain how you installed k8s so that we can reproduce and verify a fix?

Thanks!

**Comment by aLekSer** [comment]
I assume that we can reproduce an issue using `kube-apiserver-minikube` pod, so we need to do `kubectl exec` to it.
https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by thoraxe** [comment]
> Is the step enable OwnerReferencesPermissionEnforcement plugin possible on managed k8s environments (GKE, EKS, AKS, etc)?

I'm not sure. This was tested on OpenShift which has it enabled by default.

https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/ describes admission controllers generally and then https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement describes Owner References specifically.

Given that baked-in admission controllers are configured at the `kube-apiserver` flag level, I would guess that you can't turn these on for GKE/EKS/AKS unless you get to specify in those environments which admission controllers you want enabled or disabled.

If you can configure admission controllers with minikube, then you should be able to validate this behavior.

**Comment by markmandel** [comment]
If we can get step by step instructions to replicate the issue on minikube that would be awesome.

**Comment by thoraxe** [comment]
I'll need to play with this and try to do it with Minikube and report back with a clear reproducer.

If I get enough cycles I may be able to PR the owner references themselves.

**Comment by thoraxe** [comment]
reproducer using Kubernetes-in-Docker (KIND):
https://gist.github.com/thoraxe/6991886f3eaeb345fd0af474efada8d0

**Comment by sebastienblanc** [comment]
👀 
Just got hit by this one as well while trying to use it on OpenShift. 
@thoraxe Do you know if we can disable this admission controller as a temporary workaround ? I really would like run this on OCP before Tuesday ;)

**Comment by thoraxe** [comment]
@sebastienblanc the workaround we used was to add the owner references to the relevant place.

Note you cannot use 4.5 or 4.6 because the Agones CRD doesn't yet have the new format. I think you have to use 4.3. Match whatever k8s version in OCP to the supported k8s version in Agones. I don't know if the recent Agones release fixed the CRD format issue. 

@markmandel do you recall where we added the owner refs?

**Comment by markmandel** [comment]
The livestream will tell us!

**Comment by sebastienblanc** [comment]
I was about to watch it !

Le sam. 31 oct. 2020 à 16:59, Mark Mandel <notifications@github.com> a
écrit :

**Comment by markmandel** [comment]
https://youtu.be/nBJX2zKtzho

Just found out in my Twitter stream 👍🏻

**Comment by roberthbailey** [comment]
Has anyone tried this lately? Is it still an issue?

**Comment by thoraxe** [comment]
This is still a problem with k8s 1.21 and agones 1.15:
https://gist.github.com/thoraxe/6991886f3eaeb345fd0af474efada8d0 (updated)

**Comment by roberthbailey** [comment]
Thanks. With a repro using kind, it will be much easier to look into solving this.
