### ISSUE TITLE
Allocate UDP and TCP on the same port with dynamic port policy

### ISSUE THREAD

**Issue by Bmandk** [googleforgames/agones#1744]
**Is your feature request related to a problem? Please describe.**
The server I'm using with Agones use both UDP and TCP on the same port. When using Dynamic allocation and creating a port entry for each on the GameServer, they will be exposed on different ports, making me unable to connect to the server.

**Describe the solution you'd like**
Be able to set both UDP and TCP on the port.

**Describe alternatives you've considered**
Another possibility is to check whether the same ports with different protocols have been set on the same container, and then assume that they should be on the same host port as well.

**Additional context**

**Comment by fooock** [comment]
I think this is the same issue described in #1523

**Comment by markmandel** [comment]
Yeah, sounds like this is duplicate. Any objection to me marking this as duplication + closing this @Bmandk and moving the conversation to the above marked ticket?

**Comment by Bmandk** [comment]
Ah, missed that while searching for similar issues. Exactly the same issue, go ahead.

**Comment by markmandel** [comment]
Closing!
