### ISSUE TITLE
Allow for tolerations or nodeAffinity for game servers

### ISSUE THREAD

**Issue by jicowan** [googleforgames/agones#1747]
**Is your feature request related to a problem? Please describe.**
I do not see a way to run game servers on specific instance types.  Can I include nodeAffinity or a toleration in the `template` section? I could try to do this with an admission controller like Gatekeeper that patches the pod's nodeAffinity or nodeSelector when deployed into a particular namespace, e.g. xbox, but I'd rather not if I don't have to. 

**Describe the solution you'd like**
I would like to be able to schedule game servers onto specific instances or node pools/groups using nodeAffinity or tolerations.  I didn't see a way to do this in the game-server spec.

**Comment by markmandel** [comment]
The `GameServer` has full access to the entire PodTemplateSpec:
https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServerSpec

So you can set any value there that you want on your Pod, including node selectors, affinity, etc, or use taints etc.

I assume that will solve your problem?

**Comment by jicowan** [comment]
Sure will!  Thanks @markmandel.
