### ISSUE TITLE
Support for WebRTC gameservers

### ISSUE THREAD

**Issue by MichaelMarkieta** [googleforgames/agones#1756]
**Is your feature request related to a problem? Please describe.**
Browsers do not support UDP transport protocols. WebRTC has shown that it is one ideal alternative to TCP based communication (with websockets being the most popular for multiplayer browser games).

**Describe the solution you'd like**
Gameserver protocols should be extended to include support for WebRTC.

**Describe alternatives you've considered**
TCP Websockets, or move to Nakama for WebRTC support.

**Comment by markmandel** [comment]
Since WebRTC uses either UDP or TCP, what is blocking you from using WebRTC with Agones?

**Comment by MichaelMarkieta** [comment]
My understanding of WebRTC needs upgrading! This is certainly something I am keen to dig deeper into as I haven't found any WebRTC agones examples, which I think would be valuable for increasing adoption of WebRTC for browser based games.

**Comment by markmandel** [comment]
Sounds good. So no objection to me closing this issue, since we don't need to do anything on the Agones side?
