### ISSUE TITLE
Identify Agones-supporting namespaces by namespace label

### ISSUE THREAD

**Issue by TBBle** [googleforgames/agones#1768]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when we add a new developer to our team, and their namespace fails to run our project stack correctly because we forgot to update the Agones Helm configuration to include their namespace.

I'm also slightly frustrated that I can't give Agones the list of desired namespaces before those namespaces exist, although that's more-reasonable because it needs to create the `agones-sdk-access` RoleBinding in the namespace anyway.

I'm also disappointed when we add a new namespace to Agones, and due to an oversight, cut-and-paste error, or having two people making changes at once, an existing namespace is removed from the list, and someone else's deployment stops working.

**Describe the solution you'd like**

It'd be nice if we could (optionally) configure Agones to scan for namespaces with a certain label, so that its configuration does not need to be changed when the set of namespaces it needs to manage is changed.

In a multi-tenant cluster, I can see that if the Agones installation is managed separately, and users are able to add labels to their own Namespaces, Agones should _not_ honour namespace labels, so this should not be the default behaviour.

I'm thinking something like `gameservers.namespaceSelector` which would operate as a [`LabelSelector`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#labelselector-v1-meta), e.g. [`namespaceSelector` in the `NetworkPolicyPeer`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#networkpolicypeer-v1-networking-k8s-io) or the various [Webhook](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#validatingwebhook-v1-admissionregistration-k8s-io) resources. 

That also ensures that the labels used are specific to that cluster/organisation, so we don't end up with tutorials on the Internet referencing some example label as "the label to use", as happened with the [`prometheus.io/scrape` annotation](https://github.com/prometheus/prometheus/commit/03a9e7f72e072c6d29f422425d8acd91a957836b).

As a side-effect, of implementing this, it would also be reasonable for Agones to have not-yet-existing `gameservers.namespaces` entries, and since it'd be dealing with "new namespace created" events anyway, it could just ignore those entries at startup and react to them as they are created.

**Describe alternatives you've considered**

Perhaps being able to provide wildcards in the `gameservers.namespaces` list? That would fix things for me (`user-*` covers the 'new users join the team' case by our local, not-enforced namespace policy). That seems like at-best a workaround.

**Additional context**

There's a discussion at https://github.com/kubernetes/kubernetes/issues/88253 about supporting literal-name matches for `NetworkPolicy`'s `namespaceSelector`, and particularly canvasses some of the security issues or concerns, e.g. https://github.com/kubernetes/kubernetes/issues/88253#issuecomment-602571247.

----

Edit: After writing this up, I realised that the agones-sdk-access `RoleBinding` in the namespaces is [deployed by the Helm chart](https://github.com/googleforgames/agones/blob/638a7fddecd23ec24881a738a59c45e0f8b0db7d/install/helm/agones/templates/serviceaccounts/sdk.yaml#L47-L67), not by the Agones Controller. So to achieve this, we'd need to move that functionality into Agones itself, or somehow make this work without modifying namespaces other than the one Agones is running in.

It's possible I've got some other faulty assumptions here, and the Agones Controller itself doesn't care about the namespace list. Poking around, I can't see anywhere that the Agones Controller is aware of the namespace list, so perhaps there are better ways to address my use-case than suggested above.

**Comment by markmandel** [comment]
Thanks for the write up @TBBle!

I would say that this seems to fall into the realm of/be a duplicate of [Creating an Agones Operator](https://github.com/googleforgames/agones/issues/744).

The reason we don't do this with Agones, is that it would require extra permissions for Agones itself - mainly being able to add and remove service accounts and change RBAC permissions on the fly -- which is a pretty big permission change, and one that is able to wreak some havoc if incorrectly applied or is compromised.

For your specific use case (development only, where security is less of a concern), maybe it makes sense for you to build a small controller that works for your particular development flow (would likely make a great third party tool), and it could be a base to build off for an Operator down the line?

WDYT?

**Comment by roberthbailey** [comment]
@TBBle - We have a community meeting this Thursday, and this would be a great topic to discuss if you can make it.

**Comment by TBBle** [comment]
So I can find it later: http://bit.ly/agonescommunity

**Comment by markmandel** [comment]
> Perhaps a change to the Helm chart paramter to allow "whole-cluster" as well as teh current "specific namespaces" modes, which is how, e.g., Prometheus Operator and Jaeger Operator are implemented, IIRC. "whole-cluster" would create a ClusterRoleBinding instead, and is intended for single-tenant or shared-Agones environments.

Coming back around to this, can you point to the the documentation for where Prometheus and Jaeger operators do this - it would be good to see the prior art for reference.

One point here - the above mentioned items are Operators that manage the installation of a separate system, so this feels like it would fall under an Agones Operator that handles the installation of Agones (which we also talk about in #744) so it might be better solved with an actual Agones Operator?

**Comment by TBBle** [comment]
It probably does fall under an Operator behaviour, yes. I still haven't actually read-up on the Agones Operator plans/ideas yet.

Anyway, for Prometheus Operator, it's [values ending in `namespaceselector:`](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml). From the docs of [serviceMonitorNamespaceSelector](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec), it's a metav1.LabelSelector; [the values.yaml mistakenly links to NamespaceSelector](https://github.com/prometheus-community/helm-charts/issues/367). This is the approach we'd want an Agones Operator to take, as it limits the scope from which it will seek `Agones` objects or `AgonesNamespae` objects.

For Jaeger Operator, in all-namespaces mode, it creates a ClusterRoleBinding and ClusterRole, instead of a RoleBinding and Role, for the Controller service account, using the [`rbac.clusterRole` configuration parameter](https://github.com/jaegertracing/helm-charts/tree/master/charts/jaeger-operator).

I think that the Jaeger Operator approach could work now to improve my use-case, where I trust all the users on the dev cluster, and would happily give every namespace the ability to create `GameServer` objects. However, it presents similar implementation difficulties as exposing a LabelSelector, as unlike Jaeger Operator, the SA we're talking about needs to be used by the GameServer, and so must live in the namespace of the Pod, not the namespace of the controller.

So both examples have a usable UX, but I think neither point to implementation approaches we can use directly in the Agones controller or Helm chart.

**Comment by markmandel** [comment]
I was just thinking this would be a great small third party project - create a small operator that adds the required RBAC permissions for Agones to every namespace it finds in a cluster, and then people could drop it into development clusters to solve this issue.
