### ISSUE TITLE
Updated C# documentation to use NuGet package

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1769]
**Is your feature request related to a problem? Please describe.**

Now that #1753 has been finished and we have a [1.8.0](https://www.nuget.org/packages/AgonesSDK/1.8.0) Nuget package, we should update the [C# SDK Documentation](https://agones.dev/site/docs/guides/client-sdks/csharp/) to use this package.

**Describe the solution you'd like**

Updated documentation, that is appropriate for C# (I've no idea 😃)

**Describe alternatives you've considered**

Leave it alone, since it works, but that's not ideal for C# users.

**Additional context**

N/A

**Comment by markmandel** [comment]
Calling my C# friends: @rcreasey @Reousa @yoshd and @pooneh-m - if any of you have cycles :wave:

**Comment by Reousa** [comment]
Do the docs need updating on how to use the NuGet package specifically, or on how to use the new features in general?

**Comment by markmandel** [comment]
You are 100% right, it doesn't have the Player Tracking docs in it either.

![200](https://user-images.githubusercontent.com/298370/91105538-23fa3500-e625-11ea-9970-d3a83116a96b.gif)

**Comment by Reousa** [comment]
Will get on it over the weekend 👍

**Comment by Reousa** [comment]
How/where is the Alpha docs to be included, in it's own page, in the same page or somewhere else?

**Comment by markmandel** [comment]
Same page is good, you can use the REST SDK as a reference:
https://agones.dev/site/docs/guides/client-sdks/rest/#player-tracking :+1:
