### ISSUE TITLE
Change the multi-cluster allocation feature to stable version

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1780]
**Is your feature request related to a problem? Please describe.**
Multi-cluster allocation is currently in [Beta version](https://github.com/googleforgames/agones/blob/master/site/content/en/docs/Guides/feature-stages.md). `GameServerAllocationPolicy` CRD and `agones-allocator` service APIs, which the feature depends on are already in stable version. 

There has been some usage and feedback for the feature that it seems we are ready to move forward with the feature to mark it as a stable feature.

**Describe the solution you'd like**
Change the documented version for multi-cluster allocation to stable.

**Comment by roberthbailey** [comment]
After the discussion at the community meeting last week, my understanding was that if there were no objections to the proposal within ~1 week we should proceed moving to stable.

**Comment by markmandel** [comment]
> After the discussion at the community meeting last week, my understanding was that if there were no objections to the proposal within ~1 week we should proceed moving to stable.

Sounds like a plan to me! :+1:

**Comment by pooneh-m** [comment]
In the meantime if there is a concern please raise here.
