### ISSUE TITLE
Upgrade gRPC version

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1797]
We should upgrade gRPC. k8s.io/apiserver would like it to be 1.23.0 (even though we don't use that part of the code), so probably makes sense to align it with what libraries we use are requesting.

(Unless anyone can think of a good reason to go straight to latest?)

https://github.com/googleforgames/agones/blob/master/build/README.md#make-gen-sdk-grpc will be required here to update gRPC based SDKs and make sure they work. Might be worth splitting that work up as well as separate PRs.

_Context: https://github.com/googleforgames/agones/pull/1794#discussion_r483975174_

**Comment by markmandel** [comment]
One other thought on this - if we want to upgrade [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) (maybe to v2?) we should upgrade gRPC to the appropriate version first.

**Comment by markmandel** [comment]
Reopening this, to cover gRPC SDK tooling.

We did update gRPC for the SDK server, but haven't yet done any of the work to upgrade the codegen for the client sdks and related. They may not change, but usually there is some change in the generated code from gRPC between versions. At the very least we should check.

* [ ] update the SDK [base image grpc version](https://github.com/googleforgames/agones/blob/main/build/includes/sdk.mk#L30) and rebuild the image. (this can take a while, have had to do it manually and push it to gcr because cloud build doesn't like how long it takes).
* [ ] regen allocated API endpoints: [make gen-allocation-grpc](https://github.com/googleforgames/agones/blob/main/build/includes/allocation.mk#L55) (looks like this one isn't documented)
* [ ] regen all client sdks: [make gen-sdk-grpc](https://github.com/googleforgames/agones/blob/main/build/README.md#make-gen-sdk-grpc)
* [ ] Fix all the things until they pass 😄

**Comment by dbotha** [comment]
@markmandel This upgrade would be very welcome 😅 Currently I have to apply a minor patch to gRPC to get the c++ SDK to compile under Alpine Linux: https://github.com/googleforgames/agones/commit/d93e0571e5ef3c82a388efb3d706f723c2d368bc

This wouldn't be required under more recent versions of gRPC. See resolved issue https://github.com/grpc/grpc/issues/19964

Kind regards,

Deon

**Comment by markmandel** [comment]
Just noting that there are still a few more checkboxes in the list that need completing before we can close this out.
https://github.com/googleforgames/agones/issues/1797#issuecomment-868089034

We might be able to close off "Probably worth doing a global find for "1.20.1" to see if there is anything else that needs updating." - @SaitejaTamma did you end up doing a search? If so, we can tick this item off.

**Comment by SaitejaTamma** [comment]
Yes, we can tick this off

**Comment by roberthbailey** [comment]
@markmandel - with the recent gRPC updates, can we close this tracking ticket?

**Comment by markmandel** [comment]
Yes! Let's do it!
