### ISSUE TITLE
Update default branch to `main`

### ISSUE THREAD

**Issue by domgreen** [googleforgames/agones#1798]
**Is your feature request related to a problem? Please describe.**
Industry is moving away from terms such as master, slave, blacklist, whitelist as they have negative connotations. Many other open source projects are moving to `main` where possible.

Having done this internally projects on GitHub that I have migrated work fine with merging, branching and typical workflows.

**Describe the solution you'd like**
Update default branch to `main` and ensure any unseen automation continues to work.

**Describe alternatives you've considered**
- Could choose another default branch name if `main` doesnt work eg. `default`.
- Keep using `master` (not desirable)

**Additional context**
- https://github.com/github/renaming
- https://www.bbc.co.uk/news/technology-53050955

**Comment by markmandel** [comment]
100% in support of this. 

Personally, was waiting for: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories- just to make things easier for everyone and not break existing tooling.

**Comment by domgreen** [comment]
That's great to hear 👍

**Comment by markmandel** [comment]
Thanks for writing the ticket, so we don't forget :+1:

**Comment by markmandel** [comment]
https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/

Tooling now exists 👍🏻

I'd recommend that we make the change right after the next stable release, just in case anything breaks and we need to fix it, it will give us plenty of time.

**Comment by markmandel** [comment]
This has been done!

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
or if you use upstream to point at the main repo

```
git branch -m master main
git fetch upstream
git branch -u upstream/main main
```
