### ISSUE TITLE
Update apiextensions.k8s.io/v1beta1 to v1 for all CRDs

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1799]
This should be done as part of Upgrade to Kubernetes 1.17.

**What should be done**

We have non structural schema errors on some CRDs:
```
kubectl describe crd gameserverallocationpolicies.multicluster.agones.dev 
...
 Message:               spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root
    Reason:                Violations
    Status:                True
    Type:                  NonStructuralSchema
  Stored Versions:
    v1
Events:  <none>
```
So we need to add `type: object` root element in validation schema field.

`spec.validation`  need to be moved to a new `spec.versions.schema` section.
A working CRD example could be found here: 
https://github.com/googleforgames/agones/issues/1194#issuecomment-686560198

Next Go import should be updated `"k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1"`
More details could be found in this PR https://github.com/kubernetes/kubernetes/pull/79604 .

Robert's comment: CRDs went to v1 in 1.16, so I think we should wait until we move to 1.17 before we switch to using the v1 api type.

**Comment by markmandel** [comment]
Another thing to do in here - CRD v1 has defaulting support via the schema. Before closing this issue, we should look at if we can move defaulting to schemas, and possibly do away with some/part of our Mutating Webhooks.

**Comment by markmandel** [comment]
Have moving of pretty much everything I can find from `v1beta1` :arrow_right: `v1` in a WIP branch.

Will push more up when #1909 is merged.
