### ISSUE TITLE
[Unreal SDK] Is SDK possible to develop with level transitions in mind?

### ISSUE THREAD

**Issue by dotcom** [googleforgames/agones#1800]
**Is your feature request related to a problem? Please describe.**
AgonesComponent is reconstructed on level transitions using ServerTravel during Multiplayer. Is it possible to write with level transitions in mind?

When a level transition occurs, GameMode will be reconstructed.
Therefore, if you are attaching AgonesComponent to GameMode, AgonesComponent's BeginPlay() will also be executed again.
So, If bDisableAutoConnect=false (default), this means it will return to the Ready() state on ServerTravel.
If I set bDisableAutoConnect=ture instead, I have to execute HealthPing() again.

**Describe the solution you'd like**
stop inheriting ActorComponent to use it in GameInstance.

**Additional context**
I can't think of a good way to coexist with Blueprint.
If I'm wrong and there's a better way, please let me know.
Please share if you have any other good ideas on this.

Thank you.

**Comment by domgreen** [comment]
Thanks for submitting this, to be honest I would have to look in more detail or ask some of Unreal devs about the details of [GameInstance](https://docs.unrealengine.com/en-US/API/Runtime/Engine/Engine/UGameInstance/index.html) as it is not something I have a great deal of experience with.

Tbh, the solution you came up with sounds pretty straight forward as you would just call `UAgonesComponent::Connect`  on the first time you load the component and set `bDisableAutoConnect` to `false` in the config. All other instantiations of the Component would continue to health ping as expected.

Maybe some more detail around your situation and why your proposed solution isnt ideal would help.

**Comment by dotcom** [comment]
Thank you for your comment.

My concern is that if you attach a Component per GameMode, HealthPing may stop loading during the next level.
This is bad for long loadings.
```
First level's GameMode::EndPlay() -> loading (no HealthPing) -> Next level's GameMode::BeginPlay()
```

I'll continue to think about this issue, but first, I'm going to pullReq the following changes, what do you think?

The current Connect() will run Ready() and HealthPing().
This is a bit inconvenient when we want to continue HealthPing, but not do Ready(), during level transitions.
I would break this down into 2 options, bAutoReady, bAutoHealthPing
