### ISSUE TITLE
Only refresh certificates if the fsnotify event is relevant

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#1816]
**Is your feature request related to a problem? Please describe.**
Right now the certificates for the certs directory and client-ca are refreshed on any event fired from the fsnotify watcher: https://github.com/googleforgames/agones/blob/master/cmd/allocator/main.go#L147-L156

The watcher fires multiple events when a new k8s secret is installed into the directory. From the logs I see:

Create
Chmod
Rename
Remove
Remove
Remove

all being logged within 100ms for a single update to the cert. 

The current code takes a mutex, re-reads the file system, re-parses the certs, and drops the mutex for each event. It would make it easier to tell what is happening in the system if we only did the work to refresh certificates when necessary. 

**Describe alternatives you've considered**
Leave it alone; the refresh is currently working.

**Comment by roberthbailey** [comment]
The code for refreshing certs was added in https://github.com/googleforgames/agones/pull/1145 and https://github.com/googleforgames/agones/pull/1777.

**Comment by zmerlynn** [comment]
Just noting the range from the initial comment: https://github.com/googleforgames/agones/blob/23b60beb39f0bcc2a141be8cacf99989f327912e/cmd/allocator/main.go#L147-L156, currently at: https://github.com/googleforgames/agones/blob/dc3eb37f05e5c567e3d642ef4a77f0e59e993446/cmd/allocator/main.go#L274-L283
