### ISSUE TITLE
Upgrade Hugo + Docsy to latest versions

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1819]
Once Hugo and/or Docsy can handle autoprefixer@10.0.0, let's upgrade both Docsy and Hugo to the latest versions.

Also just nice to be on the latest.

Context:
_Originally posted by @markmandel in https://github.com/googleforgames/agones/pull/1818#issuecomment-692955740_

**Comment by markmandel** [comment]
Code synatx highlighting might be a nice new feature:
https://www.docsy.dev/docs/adding-content/lookandfeel/#code-highlighting-with-prism

**Comment by markmandel** [comment]
https://www.docsy.dev/docs/adding-content/lookandfeel/#diagrams-with-mermaid
https://mermaid-js.github.io/mermaid/#/

This could replace some of our dot and plantuml image generation, making the site simpler to update.

**Comment by roberthbailey** [comment]
Mark updated Hugo already: https://github.com/googleforgames/agones/pull/2085

I'm going to look at upgrading docsy.

**Comment by markmandel** [comment]
Not quite sure if I was clear when we chatted -- but I would clone Docsy to a completely different directory, not try and do it in the Agones working folder.

Sounds like you ended up in the same place 👍🏻
