### ISSUE TITLE
Metrics: link to helm repository is deprecated, install command as well 

### ISSUE THREAD

**Issue by usernum-gcp** [googleforgames/agones#1829]
Metrics: link to helm repository is deprecated, install command as well

**Comment by roberthbailey** [comment]
Hi @usernum-gcp - thanks for filing this issue. Could you add a bit more detail so we can fix this? e.g. If the link is in documentation, could you add a link to the specific page?

Thanks!

**Comment by usernum-gcp** [comment]
https://agones.dev/site/docs/guides/metrics/#installation

Let’s install Prometheus using the helm stable
<https://github.com/helm/charts/tree/master/stable/prometheus> repository.

helm upgrade --install --wait prom stable/prometheus --namespace
metrics \    --set server.global.scrape_interval=30s \    --set
server.persistentVolume.enabled=true \    --set
server.persistentVolume.size=64Gi \    -f ./build/prometheus.yaml



*BR,*

*Andrey Feldman*

*anfeldman@google.com* <anfeldman@google.com>

*mobile: 972 54 5390873*

*Google Cloud Customer Engineer, AppDev Specialist *

"For every complex problem there is an answer that is clear, simple, and
wrong"  [Google It]

**Comment by aLekSer** [comment]
The same goes for Grafana stable https://github.com/helm/charts/tree/master/stable/grafana . It is deprecated also.

**Comment by markmandel** [comment]
<lazyweb> anyone know what the new one is? (if they do, a PR would be aces :smile:)

**Comment by usernum-gcp** [comment]
Hi Mark,

I followed the link on the deprecated page
https://github.com/prometheus-community/helm-charts
the below helm install worked for me.

*helm install prometheus prometheus-community/prometheus --namespace
metrics --set server.global.scrape_interval=30s --set
server.persistentVolume.enabled=true --set server.persistentVolume.size=8Gi
-f ./build/prometheus.yaml*
Grafana stable worked for me without issues
*helm install --wait grafanav2 stable/grafana --version=5.0.13 --namespace
metrics \\n  --set adminPassword=***** -f ./build/grafana.yaml*



*BR,*

*Andrey Feldman*

*anfeldman@google.com* <anfeldman@google.com>

*mobile: 972 54 5390873*

*Google Cloud Customer Engineer, AppDev Specialist *

"For every complex problem there is an answer that is clear, simple, and
wrong"  [Google It]
