### ISSUE TITLE
Which version of Unreal Engine Game Server Client Plugin is this?

### ISSUE THREAD

**Issue by ARtSSt** [googleforgames/agones#1832]
Which version of Unreal Engine is this?
4.23
4.25??

**Comment by domgreen** [comment]
Developed and works with `4.25.1` ... not tested backwards comparability (or forwards) yet.

**Comment by markmandel** [comment]
Is this something we should document?

**Comment by ARtSSt** [comment]
Most Definitely, Unreal is very finicky version to version, Unity can be as well, please also include the exact release you have built for and tested that is very helpful. 
Thankyou for the quick response.

**Comment by mbc-audiovisuales** [comment]
> Developed and works with `4.25.1` ... not tested backwards comparability (or forwards) yet.

Can't find UE version 4.25.1 on github to compile from source nor downladable on Epic Games desktop app. Found 4.25.0 on github, and 4.25.4 on Epic Games desktop app.

Are you sure you used 4.25.1?
