### ISSUE TITLE
Helm installation timeout on EKS

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1839]
**What happened**:
Agones Helm installation fails with timeout on EKS as `agones-ping-udp-service` does not get an external-ip allocated for it. When installing Agones with `agones.ping.udp.expose=false` the helm installation succeeds. 
```
kubectl get service -n agones-system
NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)            AGE
...
agones-ping-udp-service     LoadBalancer   10.100.160.84    <pending>                                                                 50000:31071/UDP    48m
```

**What you expected to happen**:
If this is an expected behavior, this should be documented. Otherwise, it should be investigated why EKS does not allocate external IP for UDP.

**How to reproduce it (as minimally and precisely as possible)**:
Install Agones 1.9 on EKS using Helm 3.

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.9 it is also observed on 1.5 that the `agones-ping-udp-service` does not get an external-ip on EKS.
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: EKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
I have a vague memory of someone saying something about an annotation required for the UDP to work on EKS?

Or am I remember something totally wrong?

**Comment by aLekSer** [comment]
This might help a bit: https://agones.dev/site/docs/installation/creating-cluster/eks/#allowing-udp-traffic
I have not tested EKS instructions on the page above, but I do test those that run with Terraform, you can try Terraform instead:
https://agones.dev/site/docs/installation/terraform/eks/
`nc -u <IP> <port>` was working after using Terraform only installation.

**Comment by roberthbailey** [comment]
It looks like the issue Mark remembers is https://github.com/googleforgames/agones/issues/1148

**Comment by TBBle** [comment]
This was new enough that the UDP support had been backported to 1.16, so it _should_ have just needed the annotation to use an NLB instead of the default CLB:

You can see the necessary Helm parameter in #1491, requiring Agones 1.6 or later:

```
agones:
  ping:
    udp:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

**Comment by zmerlynn** [comment]
I believe this was subsumed by #1148.
