### ISSUE TITLE
Unable to create agones resource.  x509: certificate relies on legacy Common Name field

### ISSUE THREAD

**Issue by xxjunxx** [googleforgames/agones#1840]
I have set up the local cluster using `kubeadm init --pod-network-cidr=10.244.0.0/16`

When I follow the tutorial to create a gameserver, I got this error.

```
~$ kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-1.9.0/examples/simple-udp/gameserver.yaml
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/
googleforgames/agones/release-1.9.0/examples/simple-udp/gameserver.yaml": 
Internal error occurred: failed calling webhook "mutations.agones.dev": 
Post "https://agones-controller-service.agones-system.svc:443/mutate?timeout=30s": x509: 
certificate relies on legacy Common Name field, use SANs or temporarily enable Common 
Name matching with GODEBUG=x509ignoreCN=0
```

**Comment by vinnusaurus** [comment]
Any answer to this?

**Comment by vinnusaurus** [comment]
> I have set up the local cluster using `kubeadm init --pod-network-cidr=10.244.0.0/16`
> 
> When I follow the tutorial to create a gameserver, I got this error.
> 
> ```
> ~$ kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-1.9.0/examples/simple-udp/gameserver.yaml
> Error from server (InternalError): error when creating "https://raw.githubusercontent.com/
> googleforgames/agones/release-1.9.0/examples/simple-udp/gameserver.yaml": 
> Internal error occurred: failed calling webhook "mutations.agones.dev": 
> Post "https://agones-controller-service.agones-system.svc:443/mutate?timeout=30s": x509: 
> certificate relies on legacy Common Name field, use SANs or temporarily enable Common 
> Name matching with GODEBUG=x509ignoreCN=0
> ```

any answer to this?

**Comment by sfro** [comment]
For anyone else getting stuck on this, it might be that you are using a too new version of Kubernetes (v1.19 probably). See https://agones.dev/site/docs/installation/#usage-requirements
