### ISSUE TITLE
Remove support / docs for helm v2

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#1853]
https://github.com/googleforgames/agones/issues/1436 migrated Agones from helm v2 to helm v3. But we still have [documentation for helm v2](https://agones.dev/site/docs/installation/install-agones/helm/#helm-2). 

We should remove the docs and clean up any code / charts that were kept for backwards compatibility. 

According to https://helm.sh/blog/helm-v2-deprecation-timeline/ helm v2 is hitting end-of-life is ~1 month (November 13, 2020).

**Comment by markmandel** [comment]
I think that the only thing we will need to do is remove the documentation.

Our charts work across both Helm 2 and Helm 3 - so I don't think we actually need to change anything code wise.

**Comment by roberthbailey** [comment]
It looks like both https://github.com/googleforgames/agones/blob/fe14aea2c7a054d048ebcfce036ae2693fa57627/build/e2e-image/Dockerfile and https://github.com/googleforgames/agones/blob/fe14aea2c7a054d048ebcfce036ae2693fa57627/build/build-image/Dockerfile use helm v3.

**Comment by roberthbailey** [comment]
However, we have https://github.com/googleforgames/agones/tree/master/install/terraform/modules/helm (which is helm 2 configs for terraform) in addition to the helm 3 configs at https://github.com/googleforgames/agones/tree/release-1.9.0/install/terraform/modules/helm3.

**Comment by markmandel** [comment]
Ah yep, I had forgotten about the Terraform pieces. Good catch!

**Comment by roberthbailey** [comment]
It looks like this was all cleaned up with #1859. 

/close
