### ISSUE TITLE
Agones Game Server Client SDKs

### ISSUE THREAD

**Issue by Natanil** [googleforgames/agones#1854]
You mistakenly write the explanation of Alpha().IsPlayerConnected(playerID) to Alpha().GetPlayerCount() explanation : 
 
Alpha().GetPlayerCount()
This function returns if the playerID is currently connected to the GameServer. This is always accurate from what has been set through this SDK, even if the value has yet to be updated on the GameServer status resource.

Alpha().IsPlayerConnected(playerID)
This function returns if the playerID is currently connected to the GameServer. This is always accurate from what has been set through this SDK, even if the value has yet to be updated on the GameServer status resource.

**Comment by markmandel** [comment]
Thanks for the catch! if you get a chance, please file a PR!

**Comment by Natanil** [comment]
Dear mark i am living in iran which is completely sanctioned by the US government and i think i don't have permission to get the CLA and i cant even use the google cloud recently.
I hope one day iranian developers have right to participate like others do. 
Thanks for your contribution to such amazing useful platform .
