### ISSUE TITLE
Unity gameserver becomes Unhealthy after deploy on Kubernetes

### ISSUE THREAD

**Issue by MikhailKavalenka** [googleforgames/agones#1860]
**What happened**:

New created Unity gameserver becomes Unhealthy.

**What you expected to happen**:

New created gameserver becomes Ready after Agones SDK.Ready() called.

**How to reproduce it (as minimally and precisely as possible)**:

1. Download repo with examples.
2. Build unity-simple Server Build in Unity
3. Build docker image (with Dockerfile in repo)
4. Push image
5. Create Gameserver (gameserver.yaml in repo changed to reference on pushed image)
6. kubectl get gs:

> NAME                        STATE       ADDRESS        PORT   NODE                                                AGE
> unity-simple-server-x4qqj   Unhealthy   34.69.35.248   7078   gke-my-first-cluster-1-default-pool-27e2b603-1271   40s

**Anything else we need to know?**:

I started Agones server instance locally and it works fine with my Unity build.
But when I launch the build from image with _docker run_ it says:

> Curl error 7: Failed to connect to localhost port 9358: Connection refused

Not sure it should actually work with docker image locally though =)

Also I tried to deploy image straight from example _(https://raw.githubusercontent.com/googleforgames/agones/release-1.9.0/examples/unity-simple/gameserver.yaml)_ and it works fine, Agones SDK called and server is Ready.

**Environment**:
- Agones version:
release-1.9.0

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-gke.801", GitCommit:"3a26ac58e2a1ce0170c304c4134149ce3526eb8a", GitTreeState:"clean", BuildDate:"2020-09-28T17:32:58Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
iMac-APM2:unity-simple Misha$ 

- Cloud provider or hardware configuration: Google
- Install method (yaml/helm):
YAML
- Troubleshooting guide log(s):
- Others:
Will be great to understand what am I doing wrong, we are trying to launch high scale mobile multiplayer and Agones seems really suits this purpose =)

Thanks in advance!

**Comment by markmandel** [comment]
Unfortunately Agones is not supported on Kubernetes 1.18.
https://agones.dev/site/docs/installation/#usage-requirements

Please try again on the supported Kubernetes version.

**Comment by MikhailKavalenka** [comment]
@markmandel , Thanks for the fast response!

Well, kubectl version gives me Client and Server version. If I create a cluster with 1.16.13-gke version, should Agones be supported then? Or should I delete and install 1.16 kubectl version on my machine?

Anyway, the examples images work fine for me, not sure it is the version problem (
Any help appreciated.

**Comment by markmandel** [comment]
I would recommend aligning your kubectl version with your kubernetes cluster version, just because the tooling then aligns, but I think that is up to you.

**Comment by MikhailKavalenka** [comment]
Thanks, will try and let you know the result then.

**Comment by MikhailKavalenka** [comment]
@markmandel 
Finally tried with a new clean cluster and clean local kubectl v1.16 configs, the result is the same, unfortunately, the gameserver goes down with Unhealthy status after it is created on the cluster =(

Kubernetes version:
_Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:48:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
iMac-APM2:~ Misha$_

**Comment by MikhailKavalenka** [comment]
@markmandel 
The second attempt on the new cluster succeeded =)
It seems like Docker installation with kubernetes made configs little dirty, reinstalled Docker and cleaned the kubectl configs. Now I see my server up and running.
Could not connect to its external address from client though.
Anyway I suppose the issue was on my side and is resolved now.

Thank you =)

**Comment by markmandel** [comment]
Awesome - glad you got it working!

Don't forget to configure your firewall rules!!!
https://agones.dev/site/docs/installation/creating-cluster/gke/#creating-the-firewall

**Comment by markmandel** [comment]
Closing the issue, as it seems to now be resolved :raised_hands:
