### ISSUE TITLE
Allocation Endpoint - Better load balancing for gRPC connection

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1872]
**Is your feature request related to a problem? Please describe.**

The Kubernetes load balancer doesn't load balance a single gRPC connection across multiple pods, so when doing Allocations via the gRPC endpoint, a single client will only ever connect and use a single allocation Pod.

**Describe the solution you'd like**

Have the system load balance across each of the allocation pods, without requiring the external integration team (i.e. the end user) to do extra work.

Some research:
    1. https://grpc.io/blog/grpc-load-balancing/
    1. https://blog.nobugware.com/post/2019/kubernetes_mesh_network_load_balancing_grpc_services/
    1. https://kubernetes.io/blog/2018/11/07/grpc-load-balancing-on-kubernetes-without-tears/
    1. https://itnext.io/proxyless-grpc-load-balancing-in-kubernetes-ca1a4797b742
    1. https://cloud.google.com/solutions/exposing-grpc-services-on-gke-using-envoy-proxy

The Envoy based solution from Google Cloud looks to me to be the most viable.

The potentially interesting part would be that the TLS certificates would then be handled by Envoy rather than the Allocation endpoint itself.

**Describe alternatives you've considered**

Leave things as is. Allocation seems to be performing reasonably well (or at least it should do once #1863 is merged)

**Additional context**

Initially discussed here: https://github.com/googleforgames/agones/pull/1867#discussion_r512122210

**Comment by markmandel** [comment]
This would now have to cover both gRPC and HTTP endpoints - as we handle both now in the 1.11.0 RC that came out yesterday.

**Comment by roberthbailey** [comment]
@ilkercelikyilmaz FYI
