### ISSUE TITLE
helm install fails since helm3 requires a name

### ISSUE THREAD

**Issue by ilkercelikyilmaz** [googleforgames/agones#1886]
**What happened**:
```helm install agones/agones --version 1.10.0-rc``` fails with the following error 
```Error: must either provide a name or specify --generate-name```
**What you expected to happen**:
This should not fail
**How to reproduce it (as minimally and precisely as possible)**:
```helm install agones/agones --version 1.10.0```
**Anything else we need to know?**:
Looks lik this is helm3 related.
**Environment**:
- Agones version: 1.10.0-rc
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
To give additional context - this is from recent release notes:
https://agones.dev/site/blog/2020/11/03/1.10.0-release-candidate/

I assume the standard instructions work for you correctly?
https://agones.dev/site/docs/installation/install-agones/helm/#installing-the-chart
