### ISSUE TITLE
Deprecate and remove the udp-server and tcp-server images

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#1890]
Since https://github.com/googleforgames/agones/pull/1771 merged we are now releasing _three_ dummy golang game server images with every release. e.g. for the [1.9.0](https://agones.dev/site/blog/2020/09/29/1.9.0-kubernetes-1.16-nuget-and-tcp-udp/) release we included:

* simple-game-server:0.1
* tcp-server:0.4
* udp-server:0.21

These all share essentially the same code, and the simple-game-server is a combination of the other two. We should work to deprecate the tcp-server and udp-server images and stop releasing them. 

At a minimum, we need to:

* Announce that the images will stop being maintained and released
* Update our documentation to reference the simple-game-server image
* Update our test code to use the simple-game-server image
* Update the release checklist to stop building the udp and tcp images
* Remove the code and dockerfiles for the udp and tcp images

**Comment by roberthbailey** [comment]
We discussed this during the monthly community meeting today. Deprecating the tcp-server would be a good start since it is used less widely than the udp-server.

**Comment by markmandel** [comment]
To note in #1894 we have the ability to create windows images for both simple-tcp and simple-udp - we will need to port that over to the simple-game-server implementation when we do this work (although it doesn't seem complicated)
