### ISSUE TITLE
validations.agones.dev and mutations.agones.dev don't declare side effects

### ISSUE THREAD

**Issue by jonbuckley33** [googleforgames/agones#1891]
**What happened**: [validations.agones.dev](https://github.com/googleforgames/agones/blob/d6cb00728ae73d2f2c45e118e9d33ba57ccea480/install/helm/agones/templates/extensions.yaml#L58) and [mutations.agones.dev](https://github.com/googleforgames/agones/blob/d6cb00728ae73d2f2c45e118e9d33ba57ccea480/install/helm/agones/templates/extensions.yaml#L112) fail to declare whether they have any [side effects](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects), so [dryRun](https://kubernetes.io/docs/reference/using-api/api-concepts/#make-a-dry-run-request) requests fail. 

**What you expected to happen**: validations.agones.dev and mutations.agones.dev should declare whether they have side effects so that dryRun requests can decide whether to include the webhooks.

**Anything else we need to know?**:

I've looked at the [implementations](https://github.com/googleforgames/agones/blob/f678d49133b46d275626fedaee7d238111e6de42/pkg/gameservers/controller.go#L271) of the webhooks, and it looks like neither have side effects, so I suggest `sideEffects: None`. If the maintainers can confirm this is true and is expected to hold for the foreseeable future,  I'm happy to send a patch adding the yaml.

**Environment**:
- Agones version: 1.9.0

**Comment by markmandel** [comment]
Thanks for the report! Just so I am clear, what version of Kubernetes is this an issue on?

**Comment by jonbuckley33** [comment]
My pleasure! I'm running Kubernetes 1.16. I believe server-side dryrun was [enabled by default in Kubernetes 1.13](https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/#how-to-enable-it)

**Comment by markmandel** [comment]
Got it! And what benefit are we looking to gain here from getting dry-run functionality working? Is this a debugging tool, or something else?

Not trying to say we should make this change, just trying to work through the use case -- exploring all the applicability.

Also, is that failing somehow on some platform? What functionality is it stopping not having this set to `sideEffects: None`? Do we need to test this somehow in CI?

**Comment by verb** [comment]
Thanks for looking into this. To add a little more context, dry-run requests are used by `kubectl diff` to detect whether production has diverged from objects in source configuration, so `kubectl diff` will fail for any resources that have webhooks that haven't configured `sideEffect`. We use `kubectl diff` to detect when objects in clusters have changed.

**Comment by markmandel** [comment]
AAAH! Very interesting! I've not seen kubectl diff! That makes perfect sense.

To your original point: 
> I've looked at the implementations of the webhooks, and it looks like neither have side effects, so I suggest sideEffects: None.

I can't think of any webhooks that do anything other than validate or mutate the AdmissionReview data - so this sounds like it should be fine. A PR would definitely be appreciated!

I'm wondering if this work should get wrapped up with the `Move API references from beta to v1` section of #1824 - or just done at the same time?

**Comment by jonbuckley33** [comment]
> I'm wondering if this work should get wrapped up with the Move API references from beta to v1 section of #1824 - or just done at the same time?

Can you explain these options a bit more? Does the decision change how we fix the issue?

**Comment by markmandel** [comment]
With the next cycles release (1.11.0) we wanted to move the Webhooks definitions from `admissionregistration.k8s.io/v1beta1` to `admissionregistration.k8s.io/v1` - so just wondering if that all should happen in a single operation with this change.

I.e if you are in there messing with the ValidatingWebhookConfiguration and MutatingWebhookConfiguration - you might as well migrate us to v1 while you are in there :smile:

**Comment by verb** [comment]
fwiw, for the specific case of setting `sideEffects` to `None` there's no difference between `v1beta1` and `v1`, so there's no requirement to upgrade first to `v1` like there might be if the value changed between the versions.

**Comment by markmandel** [comment]
Yeah, not saying the work is dependent, just saying it might be nice to do both pieces at once.

Don't have to though!

**Comment by jonbuckley33** [comment]
Thanks for the fix, Robert! :) (Sorry I didn't get to it before -- I got sidetracked with some other work.)
