### ISSUE TITLE
Tencent TKE uses agones and encounters problems

### ISSUE THREAD

**Issue by OneFighter** [googleforgames/agones#1898]
Execute instructions：kubectl get gameservers

Show in GKE:
NAME               STATE   ADDRESS        PORT   NODE                                            AGE
simple-udp-7bqh2   Ready   35.223.54.47   7316   gke-physics-server-default-pool-d81d82da-fsz6   72s

Show in TKE:
NAME                     AGE
udp-server-4zwz5         8m

Why are these(STATE, ADDRESS, PORT, NODE) not shown on TKE?

**Comment by markmandel** [comment]
Please fill out the bug report template in full:
https://github.com/googleforgames/agones/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Unfortunately without at least those details, there is no way to debug your issue. :disappointed:

**Comment by OneFighter** [comment]
> Please fill out the bug report template in full:
> https://github.com/googleforgames/agones/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
> 
> Unfortunately without at least those details, there is no way to debug your issue. 😞

Thank you! The problem has been solved, the problem caused by the wrong version of kubectl.
