### ISSUE TITLE
Tencent TKE has problems using agones

### ISSUE THREAD

**Issue by OneFighter** [googleforgames/agones#1903]
After installing agones using TKE, I used the simple-udp example.

**What happened**:  
![1605754807(1)](https://user-images.githubusercontent.com/3481057/99615650-c1afa580-2a56-11eb-8490-528b3dbd5322.jpg)
![1605754711(1)](https://user-images.githubusercontent.com/3481057/99615656-c5432c80-2a56-11eb-9cfe-0ee54ca224c8.jpg)

As shown in FIG.
The port is not mapped to the node server.
No response message when using {nc -u Ip Port}.

When I use Agones in GKE, everything is normal.

I don’t know why Tencent TKE can’t work. Who can help me solve it?

**Environment**:
- Agones version:  release-1.10.0

- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.3-tke.11", GitCommit:"43d7ff3fae76c311692393308feeca4ceb740ebc", GitTreeState:"clean", BuildDate:"2020-10-12T03:37:10Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:  Tencent TKE
- Install method (yaml/helm):  yaml

**Comment by markmandel** [comment]
Does TKE give nodes public IPs?

**Comment by OneFighter** [comment]
> Does TKE give nodes public IPs?

Yes!
![3](https://user-images.githubusercontent.com/3481057/99638364-136d2580-2a81-11eb-9944-ada3bcd64fe5.jpg)
![4](https://user-images.githubusercontent.com/3481057/99638369-149e5280-2a81-11eb-9bec-ef4974604d4b.jpg)

**Comment by markmandel** [comment]
Okay, and if you do a `kubectl describe node <id>` is the ExternalIP address available on the Node?

https://github.com/googleforgames/agones/blob/master/pkg/gameservers/gameservers.go#L42-L57

**Comment by OneFighter** [comment]
ExternalIP is normal.

![6](https://user-images.githubusercontent.com/3481057/99753967-62b76280-2b22-11eb-8c7b-be4c19d16684.png)

**Comment by markmandel** [comment]
Okay cool - so the GameServer has the correct public IP address then - seems like, but figured I'd confirm.

**Comment by OneFighter** [comment]
In what way does agones map the container port to the node?

**Comment by markmandel** [comment]
https://agones.dev/site/docs/faq/#how-is-traffic-routed-from-the-allocated-port-to-the-gameserver-container answers that question.

But can you confirm on my question above about the public IP on the GameServer?

If so, it sounds like a firewall issue.

**Comment by OneFighter** [comment]
Yes, the GameServer has the correct public IP address.

**Comment by markmandel** [comment]
I've no idea how TKE works, but have you set any kind of firewall rule that allows you have UDP access to the game servers on the port range that Agones uses?

**Comment by OneFighter** [comment]
This problem has been solved, because TKE does not support hostPort by default

**Comment by JJhuk** [comment]
@OneFighter How to enable hostPort in tke? I got same problem

**Comment by OneFighter** [comment]
> @OneFighter How to enable hostPort in tke? I got same problem
You need to find Tencent's tke technicians to handle hostport support separately

**Comment by JJhuk** [comment]
> @OneFighter How to enable hostPort in tke? I got same problem
> You need to find Tencent's tke technicians to handle hostport support separately

Thanks to Reply quickly :)
