### ISSUE TITLE
Make a rust SDK crate

### ISSUE THREAD

**Issue by luna-duclos** [googleforgames/agones#1932]
**Is your feature request related to a problem? Please describe.**
For people using rust on their gameservers, we should provide a rust SDK they can use via crates.io.

**Describe the solution you'd like**
The currently present rust SDK should be on crates.io, and we should likely do a pass to see if we can update it to prost + tokio

**Describe alternatives you've considered**
Not applicable.

**Additional context**
We discussed this on twitch.

**Comment by markmandel** [comment]
We should really do this! @Kalaiselvi84 please have a look at https://doc.rust-lang.org/cargo/reference/publishing.html, and see how you feel about taking this on.

**Comment by Kalaiselvi84** [comment]
Will create a Buganizer ticket for this issue and start work

**Comment by markmandel** [comment]
https://crates.io/crates/agones 🥳
