### ISSUE TITLE
create gameserver error: x509

### ISSUE THREAD

**Issue by shenjiajia1225** [googleforgames/agones#1939]
Sorry for posting here. I just want some help. 
  I build agones-1.11.0 on my local machine including images. Before installing agones by YAML, I only replace remote image to local image in install.yaml. It seems ok after installing done when using cmd 'kubectl get pods -n agones-system'. All pods are running. But when I create a gameserver (examples/simple-udp), kubectl return error msg:
         Error from server (InternalError): error when creating "gameserver.yaml": Internal error occurred: failed calling webhook "mutations.agones.dev": Post "https://agones-controller-service.agones-system.svc:443/mutate?timeout=10s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
  HOW to fix this problem? I am not familiar with SANs and just start using k8s and agones. Thanks very much!!!

  My local env: centos7.9 x64; minikube v1.16.0; kubectl v1.20; go1.15.5
  Furthermore, I do not use 'make build', but use 'make build-XXX-binary' and 'make build-XXX-image' ensuring all in local.

**Comment by markmandel** [comment]
On mobile, but:

- Any reason you are building from source? Easier to get started with the pre-built images.
- If you do want to build from source, the easy, supported answer is to build using our build image. Go 1.15 removed support for deprecated SSL certificates, so I expect you ran into that when installing from YAML. If you want details search for the issue on upgrading to Go 1.15.

**Comment by shenjiajia1225** [comment]
Thanks markmandel !!!
  Because of some policy reason, I can not visit some websites such as downloading pkgs from golang.org or pushing images to gcr.io.  
  Also I want to try if agones can support room-base gameserver just like HearthStone(by Blizzard) or Texas Hold . From some public videos and docs about agones, I think one gameserver in agones is like a big room for all users(forgive me, mybe I am wrong about it), but I need more rooms (several users pre-room) in one gameserver. That's why I try to build all locally.
  I have aleady tried Go1.15.5 and Go1.14.2 to build binary and installed from YAML(using local images), but both get the same error msg when creating gameservers.
  Should I change the version of minikube , agones and Go?

**Comment by markmandel** [comment]
Hard to say, without knowing you are running a supported version of Agones.

I am wondering now if the latest version of Minikube was built with Go 1.15 - and we need to update the certs for the install.yaml

Are you also building Minikube from source?

**Comment by shenjiajia1225** [comment]
No, I downloaded minikube from https://github.com/kubernetes/minikube/releases/download/v1.16.0/minikube-linux-amd64. It seems built by Go1.15, but I am not sure. (https://github.com/kubernetes/minikube/tree/v1.16.0)
Thank you again :) . I should try minikube 1.14.2 and agones 1.11.0 with Go1.14.2.

**Comment by shenjiajia1225** [comment]
I tried minikube1.14.0, Go1.14.4 and agones1.11.0, the same error msg.
Minikube was running on centos7 in virtualbox while host machine os was win10.
minikube start cmd: minikube start --registry-mirror=https://registry.docker-cn.com . Not same with in doc, becase I can not visit gcr.io.

**Comment by markmandel** [comment]
Which version of Kubernetes are you running? 

I just noticed this was missing from your bug report.

Make sure it's aligned with s supported version: https://agones.dev/site/docs/installation/#usage-requirements

**Comment by shenjiajia1225** [comment]
I tested both on minikube1.14.0 and minikube1.16.0, and running without --kubernetes-version v1.14.10 (started failed with this parameter because of downloading some pkg failed) . So maybe this was the reason why I failed.

**Comment by shenjiajia1225** [comment]
Is there any doc about how to create server.crt / server.key, ca.crt, tls.crt / tls.key, tls-ca.crt, and generate caBundles which were used in install.yaml ?

**Comment by markmandel** [comment]
You need to specify the version of Kubernetes when starting Minikube, as the latest Kubernetes version is not supported with Agones.

**Comment by shenjiajia1225** [comment]
OK. Thank you!

**Comment by shenjiajia1225** [comment]
Hi markmandel, I met another problem.

I specified the version --kubernetes-version v1.14.10 and started minikube successful by using cmd: 
    minikube start --kubernetes-version v1.14.10 --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers

But install agones1.11.0 by install.yaml was failed. Error msg was:
  unable to recognize "install.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
  unable to recognize "install.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
  unable to recognize "install.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
  unable to recognize "install.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
  unable to recognize "install.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
  unable to recognize "install.yaml": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1"
  unable to recognize "install.yaml": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1"

When I changed ***.k8s.io/v1 to ***.k8s.io/v1beta1 and reinstalled, also failed. Error msg was:
  ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[0]): unknown field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[0]): missing required field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition
  ......(more)
  ValidationError( ... unknown field "x-kubernetes-int-or-string
  ...
  ValidationError( ... unknown field "x-kubernetes-preserve-unknown-fields"

**Comment by shenjiajia1225** [comment]
I specified --kubernetes-version v1.17.16 when starting minikube and all worked right including the simple-udp!!
My local env:
  minikube v1.16.0 (start with --kubernetes-version v1.17.16)
  building agones and simple-udp with go1.14.4
I guess maybe agones can be supported by the latest version of k8s except the certificate.
I hope that there will be some documents about how to create server.crt / server.key, ca.crt, tls.crt / tls.key, tls-ca.crt, and generate caBundles which were used in install.yaml.
Thanks!~

**Comment by markmandel** [comment]
You can see the .sh file that generates the certs here:
https://github.com/googleforgames/agones/tree/master/install/helm/agones/certs

It's possible we could replace this with the [Helm generated yaml](https://github.com/googleforgames/agones/blob/master/install/helm/agones/templates/extensions.yaml#L154-L160)

Might be interesting to experiment with having `generateTLS` be true and see what happens when generating the YAML from the helm chart.
https://agones.dev/site/docs/installation/install-agones/yaml/#installing-agones

Sounds like we'll need to update our cert gen when we go to support later versions of Kubernetes. If you want to help with that effort, that would also be greatly appreciated! :smile: 

For now, I'm going to close this issue, as it looks like we've solved this issue. Please re-open if there anything we haven't covered.
