### ISSUE TITLE
Unable to COMPILE after added agones plugin in UE4.26

### ISSUE THREAD

**Issue by Gamedebix** [googleforgames/agones#1940]
Unable to compile ue project after adding agones plugin .Error message is shown below----

Error	C2440	'initializing': cannot convert from 'TSharedRef<IHttpRequest,ESPMode::ThreadSafe>' to 'TSharedRef<IHttpRequest,ESPMode::NotThreadSafe>'

	****/Plugins\Agones\Source\Agones\Private\AgonesComponent.cpp	55	

**Environment**:
- Agones version:  version 1.12.0

**Comment by markmandel** [comment]
@domgreen any ideas?

Is it just me, or is Unreal not backward compatible between versions? 😬

**Comment by domgreen** [comment]
I've not updated our game to `4.26` as yet ... but this is a breaking change. Know that a few plugins have broken and needed to be fixed on the version bump ... hopefully should be a quick fix. 

Should ensure the fix is backwards compatible when PR'd.

Will pop it into my internal slack and see if anyone knows a fix (might be a few days as most ppl are on holidays still).

**Comment by domgreen** [comment]
From a quick google looks like we need to set the `ESPMode::ThreadSafe` on the shared pointer ... will have a go at this in the morning and see if it still compiles in 4.25 then if it does we can get someone to test in 4.26 as well :+1: 

Source:
https://docs.unrealengine.com/en-US/API/Runtime/HTTP/Interfaces/IHttpRequest/index.html

**Comment by comerford** [comment]
I have a 4.26 engine based build up for testing, we are not yet switched over but I can test easily once we have a fix to try

**Comment by domgreen** [comment]
@comerford have added a hacky fix #1944 would you mind checking out the branch and compiling the plugin inside your project.

This should just work (TM) as it is now telling the compiler to choose the type rather than explicitly doing it ourselves.

Thanks :+1:

**Comment by comerford** [comment]
going to do this today as soon as I can figure out how I have broken my Windows Jenkins build images :D

**Comment by Gamedevix** [comment]
Checked with fresh pull still Not compiling with 4.26. I Switched from ue4.25 in which agones was working fine. Problem is here don't know how to fix dear @markmandel @comerford 

TSharedRef<IHttpRequest> UAgonesComponent::BuildAgonesRequest(const FString Path, const FHttpVerb Verb, const FString Content)
{
	FHttpModule* Http = &FHttpModule::Get();
	**TSharedRef<IHttpRequest> Request = Http->CreateRequest();**

**Comment by comerford** [comment]
@Gamedevix - you will need to cherry pick the commit from @domgreen into your plugin, not just pull, since it has not been merged yet pending testing. Alternatively since it is a change to a single file you could edit, or just download the [raw file](https://raw.githubusercontent.com/domgreen/agones/ue4.26_httprequest/sdks/unreal/Agones/Source/Agones/Private/AgonesComponent.cpp) and replace your AgonesComponent.cpp to test

**Comment by Gamedevix** [comment]
Not working dear i tested it @comerford  

Error	C2440	'return': cannot convert from 'TSharedRef<IHttpRequest,ESPMode::ThreadSafe>' to 'TSharedRef<IHttpRequest,ESPMode::NotThreadSafe>'

**Comment by domgreen** [comment]
Raised an issue on the UDN here around this issue to see what best practice might be https://udn.unrealengine.com/s/question/0D52L00005AlAcdSAF/426-breaks-httpcreaterequest

If no response we might be best refactoring that code so it is slightly different (possibly passing in the delegates).

**Comment by Gamedebix** [comment]
@domgreen  I tried same http request to call my game backend servers in 4.26 it is not working .I came to the  conclusion that 4.26 has some serious issues with HTTP module .This has nothing to do with agones compatibility with UE  as agones works fine with earlier unreal releases..

**Comment by eddiebeazer** [comment]
> @comerford have added a hacky fix #1944 would you mind checking out the branch and compiling the plugin inside your project.
> 
> This should just work (TM) as it is now telling the compiler to choose the type rather than explicitly doing it ourselves.
> 
> Thanks 👍

I just updated to 4.26.1 and manually updated the files changed in #1944 and I was able to get it working again.  Strangely it did not work for me with 4.26.0
