### ISSUE TITLE
Mirror Labels + Annotation onto the underlying Pod

### ISSUE THREAD

**Issue by matclayton** [googleforgames/agones#1941]
**Is your feature request related to a problem? Please describe.**
We want to use pod labels to build kubernetes services pointing to specific Gameservers.

**Describe the solution you'd like**
We'd like to use the agones rest api, and set a pod label, however these are only set on the gameserver and not the underlying pod. It would be nice if the labels / annotations set via the api were applied to both the pod and the gameserver.

**Describe alternatives you've considered**
Updating the Kubernetes Service to accept a Gameserver instead of a pod, however this seems very painful.

**Comment by markmandel** [comment]
Could you explain your use case further for this? From our Slack conversations it seems like this might be out of scope for a game server use case - and therefore out of scope for Agones.

I would probably recommend writing your own custom controller to install into a cluster to provide this functionality, at least at first glance.

**Comment by matclayton** [comment]
Of course! For context we’re using this for rtmp server. but I could see this also being useful in a game server context when combined with the player apis. We essentially have a TCP server which has “player” capacity limits we need to obey to keep a decent QoS.

We essentially want to avoid using allocators, and have a tcp connection hit a dns entry, and immediately be routed an available game server. This is because we don’t have the benefit of controlling the client side code unlike a game server.

The way we’ve achieved this is to add a kubernetes service and end points pointing at the underlying pods selected by the labels set by agones on the pods. HAProxy ingress picks up the endpoint set, and automatically limits the number of connections to each pod as required. We have this working in production and it’s fantastic.

What we’d like to do now is for the setLabel (and annotation) api to set the labels and annotations on both the game server and the pod (where the default agones labels are already set) as this would allow us to build much more advanced services with agones.

One example is we’d like to set a label on the pod which would allow us to build a service just talking to a subset of pods, but we can’t do that easily unless we have a programmatic way of changing the labels on the pod (not gameserver) at runtime.

Another example of something we’re playing around with is adding a pod label+service per player connected. This essentially gives us an internal dns entry for each connected user, and would allow us to provide a service discovery layer to locate a users particular datastream. This opens up all sorts of interesting product options, but fundamentally it comes down supporting adding labels / annotations to the pods as well as the gameserver.

Neither of these are game server specific but I do think if the label/annotation apis were to set both on the gameserver and pod, some interesting new use cases might be made available and it would open up never methods of service discovery with minimal (if any) bloat. We can easily hack around this by using the kubernetes clients to add these labels, however given agones already exposes nice apis for setting labels and annotations itself, it felt like that is a much cleaner solution, and would enable others to also integrate with agones in other ways.

Another side benefit were also seeing is all of our monitoring systems think in terms of pods not game servers. So the labels provide a nice synergy there, and being able to set them programmatically extends the ways we can slice the data up.

**Comment by markmandel** [comment]
Given that this doesn't specifically apply to game server workloads, I'm not sure this extra K8s API hit makes sense to be integrated directly into Agones (unless we suddenly get an influx of people who say this is a requirement).

That being said, a third party controller that did this work would be great to have listed in in our [Third Party Libraries and Tools](https://agones.dev/site/docs/third-party-content/libraries-tools/) if you want to write an open source library :+1: 

There are likely some edge cases of which labels shouldn't be changed that may need to be handled for Agones and/or your specific game - so I'll let you decide if something custom / OSS works best for your workload.

> Another side benefit were also seeing is all of our monitoring systems think in terms of pods not game servers. So the labels provide a nice synergy there, and being able to set them programmatically extends the ways we can slice the data up.

This is likely the best benefit that I can see - but I expect for metrics, dynamic labels probably don't make much sense (would love to hear dissenting opinions?), and adding static labels to your Pod is available as an option through the `GameServer` [specification through the current configuration](https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServer).

So I think unless many people disagree here, I think I will leave this as an exercise for the reader :smile: 

https://github.com/Octops/agones-event-broadcaster - might be a good example for making a controller to reference through!

Does that make sense?

**Comment by markmandel** [comment]
It's been over a year since this initial suggestion - I still think we shouldn't have this as a core part of Agones, but could be an interesting third party library. So I'm going to mark this as stale, and close in a week or so unless anyone objects.

**Comment by markmandel** [comment]
Closing since no objections.
