### ISSUE TITLE
[Go SDK] PlayerConnect() at capacity panics

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1957]
**What happened**:

When attempting to call `sdk.alpha.PlayerConnect(id)` when `initialCapacity` was set to 0 causes a panic.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9b61d1]
goroutine 1 [running]:
agones.dev/agones/sdks/go.(*Alpha).PlayerConnect(0xc000134cc0, 0xd67031, 0xe, 0xc0000b46e0, 0x14, 0x0)
        /go/pkg/mod/agones.dev/agones@v1.11.0/sdks/go/alpha.go:55 +0xe1
```

**What you expected to happen**:

Should not panic, and return both `ok` with a false value and the error.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a GameServer with an initialCapacity of 0 (or use an already full GameServer)
- Attempt to call `PlayerConnect(id)`

**Anything else we need to know?**:

There are a few places here:
https://github.com/googleforgames/agones/blob/master/pkg/sdkserver/sdkserver.go#L571

That return null for the ok value, and it should always return a value, otherwise a panic will occur.

We should also test for this in our e2e test:
https://github.com/googleforgames/agones/blob/master/test/e2e/gameserver_test.go#L867

Should also look to see if we can do unit tests on this and/or local SDK tests, as it seems like the same issue exists there too:
https://github.com/googleforgames/agones/blob/master/pkg/sdkserver/localsdk.go#L402

**Environment**:
- Agones version: 1.11
- Kubernetes version (use `kubectl version`): 1.17
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): N/A
- Troubleshooting guide log(s): N/A
- Others:

Thanks to @danieloliveira079 for reporting the issue in Slack.

**Comment by jiwonaid** [comment]
I found more panics when I was looking into the e2e test code.
Please take a look.
