### ISSUE TITLE
Move RollingUpdateOnReady to Beta

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1970]
Context:
https://development.agones.dev/site/docs/guides/feature-stages/#feature-gates

The "Fix for RollingUpdate Scale down and additional details" has been in alpha since 1.9.0, so unless anyone has any objections, I think this can be moved to Beta.

**Comment by roberthbailey** [comment]
I'm planning to move this to beta before the next Agones release.

**Comment by roberthbailey** [comment]
RollingUpdateOnReady was promoted to Beta in https://github.com/googleforgames/agones/pull/2033.
