### ISSUE TITLE
Collaborator Request

### ISSUE THREAD

**Issue by rolfedh** [googleforgames/agones#1972]
If you'd like to become a collaborator of the Agones repo on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join. Once accepted you'll be able to have issues assigned to you! 

### GitHub user id
- rolfedh

### Company affiliation
- I'm contributing as an individual, not as an employee. I work at Red Hat as a Senior Technical Writer.

### Requirements

- [y] I have reviewed the [contribution guidelines](https://github.com/googleforgames/agones/blob/master/CONTRIBUTING.md)
- [y] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [y] I have joined the [Agones Slack workspace](https://join.slack.com/t/agones/shared_invite/enQtMzE5NTE0NzkyOTk1LWU3ODAyZjdjMjNlYWIxZTAwODkxMGY3YWEyZjNjMjc4YWM1Zjk0OThlMGU2ZmUyMzRlMDljNDJiNmZlMGQ1M2U)

**Comment by thisisnotapril** [comment]
Thank you @rolfedh! You should be all set now. Glad to have you joining the project!

**Comment by rolfedh** [comment]
> Thank you @rolfedh! You should be all set now. Glad to have you joining the project!

Thanks, @thisisnotapril. I'm looking forward to it! Please push any requests my way.
