### ISSUE TITLE
Flaky: Hugo occasionally fails: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1981]
**What happened**:

Very occasionally, Hugo will fail in CI with the following error:

```
fatal error: concurrent map read and map write

goroutine 166 [running]:
runtime.throw(0x1e2fd5a, 0x21)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc002a4b428 sp=0xc002a4b3f8 pc=0x4f1712
runtime.mapaccess1_faststr(0x1b27300, 0xc000cbebd0, 0xc0002b532f, 0x18, 0xc001122298)
	/usr/local/go/src/runtime/map_faststr.go:21 +0x43c fp=0xc002a4b498 sp=0xc002a4b428 pc=0x4cfc1c
github.com/gohugoio/hugo/tpl/internal/go_templates/texttemplate.(*state).walkTemplate(0xc002a4bb78, 0x1d8ce20, 0xc001120e00, 0x194, 0xc000b4e540)
	/root/project/hugo/tpl/internal/go_templates/texttemplate/exec.go:399 +0x8e fp=0xc002a4b580 sp=0xc002a4b498 pc=0xf0403e
```

**What you expected to happen**:

Not to do that.

**How to reproduce it (as minimally and precisely as possible)**:

Run Hugo a lot.

**Anything else we need to know?**:

I'm not sure if it's actually been fixed in Hugo yet:
https://github.com/gohugoio/hugo/issues/7293 seems to be the tracking issue.

**Environment**: Cloud Build
- Agones version: dev
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): N/A
- Troubleshooting guide log(s): 
- Others:

**Comment by roberthbailey** [comment]
It looks like this is fixed in huge 0.81.0, which requires golang 1.16 or above.
