### ISSUE TITLE
Example from Access Agones via Kubernetes API failing to compile

### ISSUE THREAD

**Issue by jmatospob** [googleforgames/agones#1982]
**What happened**:
Fail to compile and run API Example from 'Access Agones via the Kubernetes API'

Error from dependency:

`go: downloading github.com/googleapis/gnostic v0.5.4
../../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.5.4), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
../../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/kubernetes/scheme/register.go:26:2: module k8s.io/api@latest found (v0.20.2), but does not contain package k8s.io/api/auditregistration/v1alpha1
../../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/kubernetes/scheme/register.go:54:2: module k8s.io/api@latest found (v0.20.2), but does not contain package k8s.io/api/settings/v1alpha1
jpinto@JoseXPS:~/projects/space.game/agones$ go run main.go 
go: downloading agones.dev/agones v1.11.0
go: finding module for package k8s.io/api/settings/v1alpha1
go: finding module for package k8s.io/api/auditregistration/v1alpha1
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
../../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.5.4), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
../../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/kubernetes/scheme/register.go:26:2: module k8s.io/api@latest found (v0.20.2), but does not contain package k8s.io/api/auditregistration/v1alpha1
../../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/kubernetes/scheme/register.go:54:2: module k8s.io/api@latest found (v0.20.2), but does not contain package k8s.io/api/settings/v1alpha1
`

**How to reproduce it (as minimally and precisely as possible)**:
I created a main.go with the example on this page https://agones.dev/site/docs/guides/access-api/
go mod init agones
go build main.go

**Environment**:
go version 1.15

** go mod after **
`	agones.dev/agones v1.12.0
	k8s.io/api v0.20.2
	k8s.io/apimachinery v0.20.2
	k8s.io/client-go v11.0.0+incompatible
`

I was trying to build this as a debug for my old application that I was trying to update dependencies including agones to latest

Any help appreciated

**Comment by markmandel** [comment]
To clarify:

Is the issue that you can't compile the example found here: https://github.com/googleforgames/agones/tree/release-1.12.0/examples/crd-client

Or is the issue that you've written your own code and it won't compile?

(We should update the crd client to the newer version at some point though - that would be a handy extra ticket / PR though)

**Comment by jmatospob** [comment]
I didn't write any code, just copy the code from here and it's not that example

https://agones.dev/site/docs/guides/access-api/

copied here: 

https://gist.github.com/jmatospob/d24730276fadc01ba9ae55f8713d730c

**Comment by markmandel** [comment]
> I didn't write any code, just copy the code from here and it's not that example

Sorry, I'm still not following what you mean here.


If you take the example, exactly as is, does that compile for you?


I _think_ what your are ultimately saying is that we should upgrade this example to the latest Agones version? Is that correct?

**Comment by jmatospob** [comment]
How to reproduce it (as minimally and precisely as possible):
I created a main.go with the example on this page https://agones.dev/site/docs/guides/access-api/
go mod init agones
go build main.go

I'm not sure you should upgrade the example, is that whats wrong?
