### ISSUE TITLE
Upgrade Terraform templates to support version 0.13+

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1993]
**Is your feature request related to a problem? Please describe.**

There are breaking changes in Terraform when moving from Terraform 0.12 :arrow_right: to 0.13 and above.
https://www.terraform.io/upgrade-guides/0-13.html

**Describe the solution you'd like**

At some point we should upgrade (and document the upgrade) for our Terraform scripts, and ensure they still work as well.

**Describe alternatives you've considered**

Leave the scripts supporting 0.12.

**Additional context**

N/A

**Comment by roberthbailey** [comment]
Terraform 0.14 is now out and comes with another upgrade guide: https://www.terraform.io/upgrade-guides/0-14.html

**Comment by roberthbailey** [comment]
This is superseded by https://github.com/googleforgames/agones/issues/2142.
