### ISSUE TITLE
Flaky: C# conformance test because of invalid version string

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2018]
**What happened**:

C# Sdk conformance flakes occasionally

```
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error : '1.13.0-0640590' is not a valid version string. [/go/src/agones.dev/agones/sdks/csharp/test/csharp-sdk-test.csproj]
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error : Parameter name: value [/go/src/agones.dev/agones/sdks/csharp/test/csharp-sdk-test.csproj]
includes/sdk.mk:88: recipe for target 'run-sdk-command' failed
```

**What you expected to happen**:

It to pass

**How to reproduce it (as minimally and precisely as possible)**:

Have a git hash that is not a valid NuGet Package version:
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning

**Anything else we need to know?**:

**Environment**: Cloud Build / Linux
- Agones version: Dev
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): N/A
- Others:

It _might_ be better to have a `{version}+{hash}` rather than a `{version}-{hash}` for the test.

**Comment by gongmax** [comment]
I think it failed against the rule ["Numeric identifiers MUST NOT include leading zeroes"](https://semver.org/#spec-item-9)

**Comment by gongmax** [comment]
The easiest fix I can think of is to append a character before the [git commit short hash](https://github.com/googleforgames/agones/blob/main/build/Makefile#L35) in the version. Will that introduce other issues? I'm not sure whether something else relies on format of the version.

**Comment by markmandel** [comment]
I'm trying to work out where the version gets introduced to the csharp SDK, and I'm struggling.

**Comment by igooch** [comment]
@Reousa  @rcreasey do you have any insight into this issue?
