### ISSUE TITLE
Support full filtering expressions on the Allocator Service

### ISSUE THREAD

**Issue by highlyunavailable** [googleforgames/agones#2028]
**Is your feature request related to a problem? Please describe.**

I'm attempting to use the allocator service to allocate across multiple clusters. I want to be able to filter the allocated gameservers by multiple criteria, e.g. "version: v1.1" AND "release: live". At the moment, the allocator service only supports simple label matching, so I can't do that.

**Describe the solution you'd like**

I would like to be able to submit JSON selector objects that follow the format supported in the actual `GameServerAllocation` (That is, Kubernetes selectors) for each of my allocation requests, since multiple criteria must be in a single expression to be considered for matching as a single unit.

A (complex) format might look like this:

```json
{
   "preferred": [
      {
         "matchLabels": {
            "version": "v1.2.34"
         },
         "matchExpressions": [
            {
               "key": "environment",
               "operator": "In",
               "values": [
                  "live"
               ]
            },
            {
               "key": "fleet",
               "operator": "In",
               "values": [
                  "fleet-a",
                  "fleet-b"
               ]
            }
         ]
      }
   ]
}
```

which maps to the YAML

```yaml
preferred:
  - matchLabels:
      version: v1.2.34
    matchExpressions:
      - {key: environment, operator: In, values: [live]}
      - {key: fleet, operator: In, values: [fleet-a, fleet-b]}
```

**Describe alternatives you've considered**

In an ideal world (broader scope than this feature request) I'd like to be able to submit JSON in the actual format of the YAML as described in the [GameServerAllocation Specification](https://agones.dev/site/docs/reference/gameserverallocation/) and not have to worry about converting to/from a custom object type that only loosely tracks the actual specification.

That said, since this is already supported at the game server allocation level, my considered alternative is to re-write the allocator service with a different API surface (as described above) to support this and other features like returning the full game server object upon allocation instead of a custom type that only loosely represents the gameserver.

**Additional context**

From the [Slack conversation](https://agones.slack.com/archives/C9DGM5DS8/p1615998376013200?thread_ts=1615838596.028500&cid=C9DGM5DS8).

**Comment by markmandel** [comment]
Just making a note here that this is where the proto definition lives:
https://github.com/googleforgames/agones/blob/main/proto/allocation/allocation.proto#L85-L88

We could add this section, just need to decide what the right format is to capture and/or convert.

The K8s api reference is here:
https://github.com/googleforgames/agones/blob/main/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L1065-L1092

**Comment by roberthbailey** [comment]
@pooneh-m FYI

**Comment by roberthbailey** [comment]
@ilkercelikyilmaz FYI

**Comment by markmandel** [comment]
Reopening, because it was in my head, and I've done it.
