### ISSUE TITLE
Allocation endpoint: Deprecate `metaPatch` for `metadata`

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2042]
Context:
https://github.com/googleforgames/agones/blob/release-1.13.0/proto/allocation/allocation.proto#L53

We have a concept disconnect currently between a `GameServerAllocation` and the Allocation Service, in that when passing labels or annotations on a GameServerAllocation it is done with a `metadata` element, and the Allocation Service it is done with a `metaPatch`.

I've seen a few users get caught up by this (and we have docs for it now too).

I would advocate we deprecate (but keep the functionality) of `metaPatch` in the gRPC Allocation service proto and replace it with `metadata` to avoid a change in concept name all the way from `GameServerAllocation` ➡️  Allocation Endpoint

Probably something like:

```proto
message AllocationRequest {
  // The k8s namespace that is hosting the targeted fleet of gameservers to be allocated
  string namespace = 1;

  // If specified, multi-cluster policies are applied. Otherwise, allocation will happen locally.
  MultiClusterSetting multiClusterSetting = 2;

  // The required allocation. Defaults to all GameServers.
  LabelSelector requiredGameServerSelector = 3;

  // The ordered list of preferred allocations out of the `required` set.
  // If the first selector is not matched, the selection attempts the second selector, and so on.
  repeated LabelSelector preferredGameServerSelectors = 4;

  // Scheduling strategy. Defaults to "Packed".
  SchedulingStrategy scheduling = 5;
  enum SchedulingStrategy {
    Packed = 0;
    Distributed = 1;
  }

  // Deprecated: Please use metadata instead.
  MetaPatch metaPatch = 6;

  // metadata is optional custom metadata that is added to the game server at
  // allocation You can use this to tell the server necessary session data
  MetaPatch metadata = 7;
}
```

And then I believe we could handle the conversion of both in the [converter](https://github.com/googleforgames/agones/blob/release-1.13.0/pkg/allocation/converters/converter.go) library.

**Comment by markmandel** [comment]
@pooneh-m you originally wrote this, WDYT? Just trying to simplify things, but also not break backward compatibility.

Apologies I didn't see this in my initial review 😞

**Comment by pooneh-m** [comment]
Thanks for the catch. Sounds good on deprecation and replacement, if renaming avoids confusion and not adding to it for the the behavior difference across the two fields.

**Comment by lambert-wang** [comment]
Do we also want to deprecate and rename the metapatch field in [GameServerAllocationSpec](https://github.com/googleforgames/agones/blob/6a3322091c8388da42fcf29478214d62de82c63b/pkg/apis/allocation/v1/gameserverallocation.go#L82)?

**Comment by markmandel** [comment]
OIC where that came from now. The json spec is `json:"metadata` -- so I probably don't think we need to beak the data structure `GameServerAllocationSpec` at this time, but I can see how that would also be confusing if you were building that data structure from scratch. Unless people think strongly otherwise? (maybe in a separate ticket?)

I wonder what I was thinking at the time when I did that 🤔
