### ISSUE TITLE
Update simple-game-server to 0.3

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2045]
Now that https://github.com/googleforgames/agones/pull/2037 merged we need to push a new image of the simple game server (it will be the first multi-arch image).

/cc @jeremyje 
/assign @roberthbailey

**Comment by markmandel** [comment]
Included with this, do we want to update:
https://github.com/googleforgames/agones/blob/main/examples/simple-game-server/Makefile#L109

Which is what prints out the image tag for release notes as well?

**Comment by roberthbailey** [comment]
If I update line 38 of that file I (to build and push the new image) I think that will do it, right?

**Comment by markmandel** [comment]
To probably phrase things in a more coherent manner - in the release notes, do we need to do anything special to say "these images are both linux and windows containers" ?

**Comment by roberthbailey** [comment]
@jeremyje and I had a chat about that this morning, and I think the conclusion is that we can mention it in the release notes but we shouldn't need to point to the linux & windows versions of the containers, just the multi-arch container. 

@jeremyje said that "debian, alpine, ubuntu all use multi arch now" (in addition to a bunch of other common containers like golang) so we don't think this will be concerning for any of our users.

**Comment by roberthbailey** [comment]
This was done in https://github.com/googleforgames/agones/pull/2048 and https://github.com/googleforgames/agones/pull/2049.
