### ISSUE TITLE
Scale subresource does not support HPA

### ISSUE THREAD

**Issue by bburghaus** [googleforgames/agones#2051]
The `labelSelectorPath` field of the scale subresource must be provided for HPA to work properly (https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource)

Currently that field is set to `.status.labelSelector`
https://github.com/googleforgames/agones/blob/40fba6b6fa01cb492051b9ef0f59c4170b0f6c2a/install/helm/agones/templates/crds/fleet.yaml#L130-L136

but there is no `labelSelector` field in the Fleet status struct
https://github.com/googleforgames/agones/blob/40fba6b6fa01cb492051b9ef0f59c4170b0f6c2a/pkg/apis/agones/v1/fleet.go#L69-L84

The `labelSelector` needs to be added to status, or added as `.spec.labelSelector`

**Comment by markmandel** [comment]
Sounds like decent bit of cleanup, but I'm very curious: Why do you want to use a HPA?

Doesn't seem compatible with Agones?

**Comment by bburghaus** [comment]
We're investigating using HPA with custom metrics, and we like the scaling behavior options it provides. We also prefer the "out-of-the-box" nature of HPA where most teams have familiarity with it, rather than maintaining our own webhook for the agones autoscaler.

**Comment by markmandel** [comment]
How do you see HPA scale down working?

**Comment by markmandel** [comment]
Another fun wrinkle: Fleets don't have a selector, so I'm not sure what would even be the correct value to use here.

On the Agones side, I'm not sure this is going to work.

Maybe you can explain what your use case / pain points are, and we can come at our another way?

**Comment by bburghaus** [comment]
One example is third party outages. HPA providing a cool down period allows us to keep some of those gameservers running for a time, rather than having the agones autoscaler scale all the way down which will cause a number of issues once the outage is resolved.

Those tunable features on top of a buffer is what makes HPA appealing to us.

**Comment by markmandel** [comment]
> One example is third party outages. HPA providing a cool down period allows us to keep some of those gameservers running for a time, rather than having the agones autoscaler scale all the way down which will cause a number of issues once the outage is resolved.

That's an interesting use case. 🤔 

One thing I'm noting here is that that's a value that is configured at the cluster level - which is not very handy for anyone who isn't running their own custom cluster -- which leads me back to the idea that it would be better to solve this in core Agones.

There's some discussion in #1955 that maybe could be expanded on to include custom resyncs for scale up vs scale down, maybe per Fleet? This feels very dependent on how you want your game to respond, given its set of dependencies.

**Comment by markmandel** [comment]
Marked this as stale 23 days ago, looks like we can close this now.
