### ISSUE TITLE
Update recommended machine type for GKE

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2055]
n1 machine types are being phased out. We should update our recommended machine type, either to n2 or e2. 

I think e2 should be fine for the getting started guides, and presumably anyone using agones for production is already changing the machine type from the default in any case.

**Comment by roberthbailey** [comment]
Need to update:

* https://agones.dev/site/docs/installation/creating-cluster/gke/
* https://agones.dev/site/docs/installation/terraform/gke/
* https://github.com/googleforgames/agones/blob/main/build/includes/google-cloud.mk
* https://github.com/googleforgames/agones/blob/main/build/README.md
* https://github.com/googleforgames/agones/blob/main/build/includes/terraform.mk
* https://github.com/googleforgames/agones/blob/main/test/load/allocation/grpc/README.md
* A number of terraform files

**Comment by mthssdrbrg** [comment]
> n1 machine types are being phased out. We should update our recommended machine type, either to n2 or e2.
> 
> I think e2 should be fine for the getting started guides, and presumably anyone using agones for production is already changing the machine type from the default in any case.

Out of curiosity, has this been (publicly) announced anywhere? Or is it more an artifact of n2 being the "next-gen-n1" and it (n1) is expected to go away (at some point)?

**Comment by roberthbailey** [comment]
> Out of curiosity, has this been (publicly) announced anywhere?

I haven't found anything definitive, but https://cloud.google.com/compute/docs/machine-types#general_purpose lists N1 at the bottom of the list (they are the oldest type), and while it says `E2 machine types are available in all regions and zones` and `N2 machine types are only available in select zones and regions` and `N2D machine types are only available in select regions and zones`, the page is conspicuously doesn't say anything about N1 machine types.

**Comment by mthssdrbrg** [comment]
> > Out of curiosity, has this been (publicly) announced anywhere?
> 
> I haven't found anything definitive, but https://cloud.google.com/compute/docs/machine-types#general_purpose lists N1 at the bottom of the list (they are the oldest type), and while it says `E2 machine types are available in all regions and zones` and `N2 machine types are only available in select zones and regions` and `N2D machine types are only available in select regions and zones`, the page is conspicuously doesn't say anything about N1 machine types.

Ah okay, makes sense, thanks! :)
