### ISSUE TITLE
Update Unreal Engine Plugin

### ISSUE THREAD

**Issue by jbonnett92** [googleforgames/agones#2059]
Today I tested the plugin with Unreal Engine 4.26.2.
Can you update this please?

**Comment by domgreen** [comment]
Hey @jbonnett92 could you elaborate on the ticket? Is something not working as expected or is it a documentation thing?

**Comment by jbonnett92** [comment]
@domgreen So I dropped the `sdks/unreal/Agones` folder into the `C:\Program Files\Epic Games\UE_4.26\Engine\Plugins` folder and tried opening Unreal Engine. Though when I start it I get this: 
![image](https://user-images.githubusercontent.com/3740700/114950759-a604cb80-9e4b-11eb-8c69-f3e8756d6c82.png)

**Comment by domgreen** [comment]
It is recommended to run it as a "project plugin" rather than a "engine plugin" within the project you are using it in.

However, the error is correct the manifest is built with another version of the engine (4.25), dropping it in the project will compile it for you :+1:

**Comment by domgreen** [comment]
I might add a README.md to the SDK that mentions this if it is something ppl are running into

**Comment by jbonnett92** [comment]
@domgreen Ok though I need to use the features of the latest version. Please can we update the plugin?

**Comment by domgreen** [comment]
@jbonnett92 i might be misunderstanding something, if you drop the plugin into your project does it still have the error above?

I currently cant see anywhere that the plugin is being restricted to older versions :thinking: I know there are others running it with 4.26.2 but as project plugins.

We also don't ship the dlls with the SDK so would need to be compiled anyway for it to work correctly.

**Comment by jbonnett92** [comment]
Adding to the project I get this:
![image](https://user-images.githubusercontent.com/3740700/115096079-a53b6a80-9f1b-11eb-825f-6281a93eb74b.png)
And then this:
![image](https://user-images.githubusercontent.com/3740700/115096092-aff5ff80-9f1b-11eb-95c8-4dcbd39851e6.png)

**Comment by jbonnett92** [comment]
Ok it turns out I didn't add the VS components I needed to when I installed VS.

**Comment by domgreen** [comment]
> Ok it turns out I didn't add the VS components I needed to when I installed VS.

Glad it's sorted.

Would you mind sharing what those components are so we can document 👍
