### ISSUE TITLE
Example crd-client/go.mod can not be compiled

### ISSUE THREAD

**Issue by sisso** [googleforgames/agones#2061]
**What happened**:
Can not compile agones/examples/crd-client on release 1.13.  Looking into the mod.go it is still using agones 1.12.

**What you expected to happen**:
Compile 

**How to reproduce it (as minimally and precisely as possible)**:
- clone version 1.13
- update the agones/examples/crd-client/go.mod to use agones 1.13
- go run . in the folder

**Anything else we need to know?**:

**Environment**:
- Agones version:  1.13
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by roberthbailey** [comment]
I just tested this and it now compiles as expected.
