### ISSUE TITLE
Azure AKS support for public IP per Node/VM

### ISSUE THREAD

**Issue by dzmitry-lahoda** [googleforgames/agones#2083]
**Is your feature request related to a problem? Please describe.**

Azure AKS supports public IP per Node/VM

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#enable_node_public_ip

**Describe the solution you'd like**

Agones should work out of the box with this setup.

**Describe alternatives you've considered**

I tried to follow the official guide several times. No luck on 1.40. May be I am just bad at this. But if AKS already has public IPs, why not use these to avoid mistakes?

**Additional context**

I have tried to nc public IPs of given VMs by ports provided by gameserver, no response.

I have tried to run this https://github.com/googleforgames/agones/blob/main/install/terraform/modules/aks/aks.tf or follow guide https://agones.dev/site/docs/installation/creating-cluster/aks/ . I see that official TF scritps to do not setup public network, so should setup manually. So I have tried to create cluster manually, but failed to setup public IP to VM. May be. 

Because in any configuration I am trying I get the same. Gameserver from getting startes gets internal IP.

![image](https://user-images.githubusercontent.com/757125/116733586-f2780b80-a9f4-11eb-9a71-2f84d35cbe67.png)

**Comment by markmandel** [comment]
I suspect there have been updates to AKS since the guide was written. If there is a better way, we would love contributions to improve things!

> I have tried to nc public IPs of given VMs by ports provided by gameserver, no response.

Curious thought: Did you also setup firewall rules to match those nodes?

**Comment by dzmitry-lahoda** [comment]
The current guide will not work for sure.  AKS now is created with autoscaled nodes, so there are not network interfaces to set up public ip. But can change the current guide with additional CLI parameters to use the old approach with manual VM creation, which seems was the behavior the day's guide was written.

**Comment by dzmitry-lahoda** [comment]
I have changed CMD to set public IPs on VMs in scale set
```
az aks create --resource-group $AKS_RESOURCE_GROUP --name $AKS_NAME --node-count 1 --generate-ssh-keys --node-vm-size Standard_A4_v2 --kubernetes-version 1.18.14  --enable-node-public-ip 
```

**Comment by dzmitry-lahoda** [comment]
![Uploading image.png…]()

**Comment by dzmitry-lahoda** [comment]
![image](https://user-images.githubusercontent.com/757125/116774636-a49beb80-aa66-11eb-8daf-e1a391ad9c82.png)

**Comment by dzmitry-lahoda** [comment]
Restarted `az aks stop --name myAKSCluster --resource-group myResourceGroup` cluster to make sure UDP rules applied.

**Comment by dzmitry-lahoda** [comment]
ifconfig in that cluster with busybox has no indicaitons of publicip
```
PS D:\git\crey\client\client-k8s> kubectl logs busybox2

eth0      Link encap:Ethernet  HWaddr 72:84:05:00:97:9A  
          inet addr:10.244.0.8  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:446 (446.0 B)  TX bytes:42 (42.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
``

**Comment by dzmitry-lahoda** [comment]
Wow. It worked. So GS binds to internalip, but Azure forwards it to pulic and back
![image](https://user-images.githubusercontent.com/757125/116775223-92bc4780-aa6a-11eb-827c-d8cf42634452.png)

**Comment by dzmitry-lahoda** [comment]
![image](https://user-images.githubusercontent.com/757125/116775392-85ec2380-aa6b-11eb-91e2-e92daebb1c73.png)

**Comment by dzmitry-lahoda** [comment]
@markmandel I think autoscaled auto public IP for windwos dockers guide should be a separate page for ASK in wiki with link to use SDK to get ips?

**Comment by dzmitry-lahoda** [comment]
or on each page were it is relevant, put if `windows` steps

**Comment by dzmitry-lahoda** [comment]
I got windows running. have terraform script something. removed taint of agones/system from windows pool to avoid agones to put itself on cluster. have to rebuild simple gameserver docker - for some reason that docker was not found in google.

**Comment by markmandel** [comment]
> @markmandel I think autoscaled auto public IP for windwos dockers guide should be a separate page for ASK in wiki with link to use SDK to get ips?

I've no idea how AKS works, so you tell me what we should have 😄 

Just to be clear, are you specifically working on Linux containers or Windows containers?

We have some Windows specific instructions for GKE:
https://agones.dev/site/docs/installation/creating-cluster/aks/

We could do something similar for AKS? WDYT?

**Comment by WeetA34** [comment]
Hello

FYI, External-IP is filled with VM Public IP since AKS 1.18.19 (and probably 1.19.11 and 1.20.7)

**Comment by markmandel** [comment]
> Hello
> 
> FYI, External-IP is filled with VM Public IP since AKS 1.18.19 (and probably 1.19.11 and 1.20.7)

Does this mean we can close this ticket, or is more work needed?

**Comment by dzmitry-lahoda** [comment]
Yeah, I tested with version mentioned in docs as supported, and was unlucky to got into issue.

**Comment by dzmitry-lahoda** [comment]
anyway, i have updated Terraform to run with Public IP out of box and update CLI docs to same. So something was fixes:)
