### ISSUE TITLE
Introduce a way to allocate internal IPs

### ISSUE THREAD

**Issue by Cubxity** [googleforgames/agones#2087]
**Is your feature request related to a problem? Please describe.**
I would like to create an internal GameServer using Agones, but it seems like you can only allocate GameServers with a host port. This is useful for creating internal Minecraft servers behind a proxy like Velocity or BungeeCord. 

**Describe the solution you'd like**
To create some sort of "headless" port allocation with Agones. Eg.
```yaml
ports:
  - name: default
    portPolicy: Headless
    containerPort: 25565
    protocol: TCP
```
And this will only create an internal endpoint to the GameServer.

**Describe alternatives you've considered**
It is possible to use the external IP, but to limit the access to the backend, it's easier to not expose it. Backend servers tend to be "offline", meaning it does not authenticate players. This is a big security risk for backends that are exposed. However, with modern forwarding protocol that Velocity introduced, the communication between the proxy and the backend can be authenticated using a token. See [here](https://velocitypowered.com/wiki/deployment/security/).

**Additional context**
In Minecraft, in order to send players around, you need to put the backends behind a proxy. The proxy acts as a middleman to switch the backend that the player is connected to.

**Comment by markmandel** [comment]
Sorry, maybe I'm not understanding -- but what would this headless port policy actually do?

A couple of questions:

1. What happens if you don't specify a port on your config, do you end up with that you need?
2. Can you use a cluster with a private IP?

**Comment by Cubxity** [comment]
So basically, I would like to be able to allocate an internal ip/port inside of the cluster for the gameserver, without exposing it publicly. 

1. I need the `containerPort` to be specified. Though the actual allocated port doesn't matter, as long as I can retrieve it.

2. Yes, but the proxy server would have to be on a public ip.

**Comment by markmandel** [comment]
> I need the containerPort to be specified. Though the actual allocated port doesn't matter, as long as I can retrieve it.

Why? 

If you are inside the cluster, you can connect directly through the pod, either through it's internal IP which is able to be looked up, or through a variety of [DNS tricks](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)

**Comment by Cubxity** [comment]
What I would like to achieve is just like a Headless service in Kubernetes. I would like to be able to communicate with the GameServer in the cluster only. The backend/internal servers will be behind a proxy GameServer that is exposed on the host. The GameServer should not be exposed via host at all due to security reasons. 

Here's a diagram:

![Diagram](https://user-images.githubusercontent.com/27609129/117046466-412cea80-ad00-11eb-8a55-aac9db9a4bbd.png)

**Comment by markmandel** [comment]
Kubernetes already solves this for you.

> Every Pod gets its own IP address. This means you do not need to explicitly create links between Pods and you almost never need to deal with mapping container ports to host ports. This creates a clean, backwards-compatible model where Pods can be treated much like VMs or physical hosts from the perspectives of port allocation, naming, service discovery, load balancing, application configuration, and migration.

https://kubernetes.io/docs/concepts/cluster-administration/networking/

**Comment by Cubxity** [comment]
> Kubernetes already solves this for you.
> 
> > Every Pod gets its own IP address. This means you do not need to explicitly create links between Pods and you almost never need to deal with mapping container ports to host ports. This creates a clean, backwards-compatible model where Pods can be treated much like VMs or physical hosts from the perspectives of port allocation, naming, service discovery, load balancing, application configuration, and migration.
> 
> https://kubernetes.io/docs/concepts/cluster-administration/networking/

I understand that. But I would like to utilize Agones SDK for managing GameServers and scaling them.

**Comment by markmandel** [comment]
> I understand that. But I would like to utilize Agones SDK for managing GameServers and scaling them.

I'm sorry, but I'm not seeing the blocking issue from combining Agones with inter-pod communications?

**Comment by Cubxity** [comment]
> I'm sorry, but I'm not seeing the blocking issue from combining Agones with inter-pod communications?
My bad, I thought that you needed to specify the ports in Agones.
