### ISSUE TITLE
Explain how namespace parameter works for allocations

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2090]
**Is your feature request related to a problem? Please describe.**
It isn't clear to me what setting that namespace field in a `GameServerAllocation` means.

**Describe the solution you'd like**
I don't see a reference to namespace in https://agones.dev/site/docs/reference/gameserverallocation/ or https://agones.dev/site/docs/guides/gameserver-lifecycle/. 

But it is alluded to in https://agones.dev/site/docs/getting-started/create-fleet/ and also https://agones.dev/site/docs/advanced/multi-cluster-allocation/. 

This feel like an area where our docs could be better.

**Describe alternatives you've considered**
_n/a_

/cc @pooneh-m

**Comment by roberthbailey** [comment]
@pooneh-m said:

> The GameServerAllocation has a namespace field as part of [ObjectMeta](https://github.com/googleforgames/agones/blob/main/pkg/apis/allocation/v1/gameserverallocation.go#L48). If not set, it defaults to "default" namespace. Agones attempts to allocate from the specified or default namespace, but not all the namespaces.

I thought that Agones might try to allocate from all namespaces (or at least all namespaces it was configured to manage via the helm setting) if the field was left off.

**Comment by markmandel** [comment]
That's a fair comment. We should be explicit that a `GameServerAllocation` only searches within the same namespace that it is created in.

**Comment by eminguyen** [comment]
I'll be working on this!
