### ISSUE TITLE
Add "copy to clipboard" buttons to example commands on the website

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2096]
**Is your feature request related to a problem? Please describe.**
It's easy to make a mistake when copy/pasting from the agones documentation site. One example is when setting up the allocator service: https://agones.dev/site/docs/advanced/allocator-service/

**Describe the solution you'd like**
This could be solved by adding a button that allows the user to copy to clipboard, rather than relying on them selecting the command themselves. If we do this, we should look at other pages that would also benefit from having commands be easily copied (although we may need to create other bugs since the surface area is pretty large). 

**Describe alternatives you've considered**
Leave as-is, maybe simplify the service setup so that it takes fewer steps?

**Comment by markmandel** [comment]
https://github.com/google/docsy/issues/292 seems like it's taken care of inside Docsy?

Might be time to upgrade #1819 ?

**Comment by roberthbailey** [comment]
That sounds like a good way to fix this.

**Comment by markmandel** [comment]
The new https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes looks super handy too!
