### ISSUE TITLE
Creating a GameServerAllocation returns a 200 Ok instead of a 201 Created

### ISSUE THREAD

**Issue by kaboing** [googleforgames/agones#2108]
**What happened**: I use the kubernetes c# client to create a GameServerAllocation. I received an exception with the message ""Operation returned an invalid status code 'OK'". 
Using kubectl, I can see that the GameServerAllocation was indeed created. 

**What you expected to happen**: I expect the c# client not to throw an exception. 

**How to reproduce it (as minimally and precisely as possible)**: Create a GameServerAllocation with the official kubernetes c# client, use the `CreateNamespacedCustomObjectWithHttpMessagesAsync` to get the exception. Also, you can use any other client and check the http status code response. 

**Anything else we need to know?**: It seems that the c# client only accepts a `201 Created` status back from Agones, instead a `200 Ok` is sent. It seems that the go client, for instance, is more forgiving for this. 

**Environment**:
- Agones version: 1.14.0
- Kubernetes version (use `kubectl version`): 1.18.14
- Cloud provider or hardware configuration: Azure
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Looks like this should be a pretty easy one to change:

Logic is here:
https://github.com/googleforgames/agones/blob/main/pkg/gameserverallocations/controller.go#L137

I expect this that the K8s CRD interface will return a 201, so it works for everything else.

**Comment by markmandel** [comment]
Started work on this, was a pretty easy fix. Just started testing to make sure it didn't break anything.
