### ISSUE TITLE
fleet-tcp.yaml miss the spec of `ports.protocol`

### ISSUE THREAD

**Issue by bigbelly1028** [googleforgames/agones#2113]
Sample YAML for fleet TCP usage seems wrongly configured:
https://raw.githubusercontent.com/googleforgames/agones/release-1.14.0/examples/simple-game-server/fleet-tcp.yaml
After testing, there should be a 'protocol: TCP' after line 25, otherwise, it will fail to respond when applying to Kubernetes.

**Comment by markmandel** [comment]
Ah! Excellent catch!

Since you've got the example right there with the fix, would you be interesting in filing a PR to make the change?

**Comment by Rohansjamadagni** [comment]
Hi @markmandel I would like to submit a PR, this is my first time contributing to this project!

**Comment by markmandel** [comment]
> Hi @markmandel I would like to submit a PR, this is my first time contributing to this project!

This is a great first issue!

**Comment by Rohansjamadagni** [comment]
Which Branch should I submit a PR to? Thanks.
