### ISSUE TITLE
Weighted allocation scheduling

### ISSUE THREAD

**Issue by tenevdev** [googleforgames/agones#2114]
**Is your feature request related to a problem? Please describe.**
The resource usage (CPU, memory) of a game server changes depending on game-specific events. With the existing available allocation scheduling strategies, this may result in sub-optimal allocations which ultimately means I need to over-provision because I can't avoid the worst case through allocation scheduling.

**Describe the solution you'd like**
I want to influence the order of game servers in `ListSortedReadyGameServers` from the SDK and from state transitions. The description for the function is that game servers are "sorted by most allocated to least". The implementation uses the *count* which is a good default strategy. Each game server should have an allocation *weight*. The current implementation then becomes the case where all game servers have a constant and equal allocation weight. The concept of a weight in scheduling algorithms is pretty common, e.g. see CFS in Linux. To clarify, I'm not proposing a new allocation strategy, just a new parameter which affects the sort order of game servers and the default behaviour remains the same as it was.

**Describe alternatives you've considered**
1. Request CPU and memory for each game server to cover the requirements of the worst case. This is my current solution but it results in very low machine utilisation.
2. Vertical pod autoscaler (e.g. https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) seems like it could do the job, but "restart-free update of pod requests" is not available yet. Even if it were able to upgrade requests "in-place", I think it's a complementary feature to the concept of an allocation weight, similar to how CFS considers both resource usage and nice values.
3. Roll our own scheduler on top of basic Agones features. We wouldn't be able to use it together with the other advanced features (e.g. fleet auto-scaler).

**Additional context**
Just to expand a bit on the "from the SDK and from state transitions" part, but I'm happy to write a more in-depth design if more people accept the feature request. This is about when the allocation weight of a game server needs to change and I could think of two cases:
1. The "async" case is where a game server or external service decides that the weight needs to change. This can be communicated via the SDK, for example by setting a well-known label or annotation with the existing API calls. This will allow us to hook up arbitrary in-game data to the weight, for example as a function of the number of players and NPCs.
2. The "static" case is where a game server transitions from Ready to Allocated. I think this is important if the controller needs to do multiple allocations in a short span of time (or in the same batch) and needs to consider the *initial* allocation weight of a game server which has been just allocated (it needs to re-order the list, I think). The initial allocation weight could be set as the same well-known label or annotation when the resource is created. For some use cases it may need to be computed, for example if it has to be based on the number of players that I'm planning to send to the game server, but I don't have the need for this yet.

**Comment by markmandel** [comment]
I'm not sure I 100% understand, as this reads to me like a conflation of two different things, and I'm not sure they are the same (or maybe I misunderstand).

1) How `GameServers` are chosen to be allocated through a `GameServerAllocation`, and the `Scheduling` strategy.
2) How game servers are scheduled based on their CPU or Memory requirements across nodes.

Given that you can't current change CPU and Memory requirements after creation (yet - see [this Kep that recently landed](https://github.com/kubernetes/enhancements/issues/1287), _finally_ 😄 ), I'm not sure how changing weights in Allocation will actually give you any kind of optimisation here? The Pod is _always_ going to take up the same amount of space as was originally specified.

**Comment by markmandel** [comment]
🤔 my concern here is that  we would essentially be re-implementing the above KEP, but in a different way, and then when the KEP comes through (and I think we should absolutely support the kep to change resource constraints through the SDK), we have multiple roads to the same place - and we have to shoulder the maintenance burden for both paths.

My other concern is that we would be giving people a tool that _kinda_ gives them modifiable resource constraints, except it's not real resource constraints, when really it should probably be resource constraints with actual limits, etc.

The heuristic against allocation also seems extremely confusing to me - the heuristic change on a neighbouring gameserver impacts whether another game server itself gets selected for allocation? Basically a game server is saying it can kinda take over a node? This acts sorta like resource constraints, without being resource constraints? This leads to a road where you don't actually use resource constraints as they are intended, and allow game servers to burst above their constraints, and it gets very worrisome to me.

I kinda get the impetus, but this approach seems kinda murky and hard to understand as an end user to be honest.

In a magic world 😄 where you could already dynamically adjust resource constraints, and Agones provided an SDK to do so from within a GameServer -- do you see that solving the same problem for you?

I'd love to see more input from other (companies?) on this - it's entirely possible that there is use for this outside of resource constraints, but it's possible I'm missing it.

**Comment by tenevdev** [comment]
I understand your concern @markmandel and I’m also looking forward to input from others because if the problem I describe is only affecting 1 user (me), then there is no point shifting the maintenance burden of a solution to all of Agones.

The last thing I’m going to write for now is to make the case for why weighted allocation scheduling is complementary to dynamic resource constraints in my view. In other words, why I think the two features can be used together and why one is not a re-implementation of another in a different layer of abstraction.

> In a magic world 😄 where you could already dynamically adjust resource constraints, and Agones provided an SDK to do so from within a GameServer -- do you see that solving the same problem for you?

I couldn't convince myself that it would solve the problem. I just came up with more questions than answers. Consider my example again, where I have 2 machines (call them 1 and 2) with 1 allocated and 1 ready game on each. One of the allocated games is under high load (call it A1) while the other one isn't (call it A2). With dynamic resource constraints, I am able to increase the requests for the first one and decrease the requests for the second. A new allocation request arrives, at this point I also know the number of players that will be connecting to the new server.

So what do you expect to happen to the pods with the ready game servers when the allocated game servers modify their resource constraints? For example, the ready server on machine 1 (R1) could get rescheduled on another node or decrease its resource requests to remain on the node. I sort of expect the agones controller to adjust the resource constraints for ready servers based on some user configuration, e.g. the minimum resources that a game server can tolerate until it needs to get rescheduled. Along with modifying the resource constraints, there would need to be some label set on the game server which indicates what those resource constraints are so that allocation requests could use it as a selector. By doing this, if I know that very few players will be connected to the server from the next allocation request, I can select one which has the label indicating low resources and vice versa. I think I just described weighted allocation scheduling again, but the weights are hard-coded to be the resource constraints. Of course, I could write my own controller to modify the resource constraints and set these labels and maybe that's good because it seems like a thing that has use cases more generic than Agones game servers. The drawback I see with an external controller is how it impacts the Packing strategy. I think you could do some clever stuff in the Agones controller if it is aware of the resource constraints and the weights. It would be able to close the gaps and balance the fleet so that it doesn't become very fragmented - much like garbage collectors do with memory.

This was a short explanation, I hope it makes sense. In summary my point is that we could implement the generic weighting in Agones now and later plug the dynamic resource constraints into it to make a very efficient and user-friendly default implementation.

**Comment by markmandel** [comment]
Sorry for the delay, was out sick for a while, but had some thoughts on how to at least get a start on things from outside of Agones, rather than changing Agones itself.

Some other comments first:

> So what do you expect to happen to the pods with the ready game servers when the allocated game servers modify their resource constraints

As a general rule, you probably wouldn't ever want to increase resource constraints (not sure if the Kep allows you too?) as if you can do it successfully, you run the risk of kicking off existing GameServers on the node, since there is no longer room -- I think realistically you would only ever decrease resource constraints. So you would always start at the maximum resource requirement and then scale down as needed to make more room for other GameServers on the same node.

In that world, the packing strategy would likely coalesce over time to point Allocations where possible to the nodes which has more GameServers -- which would be the ones whose resources have been scaled down.

Pragmatically, we'd probably want to see actual usage patterns before drawing conclusions though.

> weighted allocation scheduling

So the point of "Packed' is to try and use as little cloud resources as possible. We aren't really optimising for resource usage -- which is a different optimisation pattern, and has ripple on effects to Fleet scale up/down etc as well.

One thought I did have that would allow you to get partially of the way you want, and have a look at the impact, would be to take advantage of the `preferred` allocation selectors. ([reference](https://agones.dev/site/docs/reference/agones_crd_api_reference/#allocation.agones.dev/v1.GameServerAllocation)).

This would need to be combined with your own annotation scheme and custom controller that would apply labels to the GameServers that would be given one level or more of priority, based on your requirements -- so you could specify the priority option in your `preferred` selector, and then have the default back in `required` if there are no priority GameServers available.

I hope that made sense 😄

**Comment by tenevdev** [comment]
Thanks for your reply @markmandel, using the preferred selectors in allocation requests is actually a very reasonable suggestion for bespoke cases like this. I'm closing the issue because there aren't that many users who will need to write a custom controller to make it worth baking this feature into Agones.
