### ISSUE TITLE
SSL Cert expired on agones.dev

### ISSUE THREAD

**Issue by AngryDeveloper** [googleforgames/agones#2133]
**What happened**:
I tried to perform a `helm repo update`
```
❯ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "agones" chart repository (https://agones.dev/chart/stable):
	Get "https://agones.dev/chart/stable/index.yaml": x509: certificate has expired or is not yet valid: current time 2021-06-14T16:01:07-04:00 is after 2021-06-14T17:41:45Z
```

**What you expected to happen**:
`helm repo update` should have succeeded

**How to reproduce it (as minimally and precisely as possible)**:
Try to perform an `helm repo update`

**Anything else we need to know?**:
The agones.dev SSL certificates seems to be expired

**Environment**:
- Agones version: N/A
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): N/A
- Others: N/A

**Comment by markmandel** [comment]
Thanks for the ping, fixing now!

**Comment by markmandel** [comment]
Sorry that took a little while - as per all things of this ilk, everything conspired against us.

I've uploaded the new cert, should propagate out shortly. Looks like our usual reminders totally failed us.

**Comment by markmandel** [comment]
Okay, this is back up on my end - if you can confirm on your end, I'll close the ticket.

**Comment by AngryDeveloper** [comment]
Confirmed on my end too, thanks a lot :)
