### ISSUE TITLE
The documentation for game server allocations is inconsistent

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2136]
**What happened**: The documentation for the Required and Preferred fields for allocations is inconsistent in the repository:

- [API docs](https://github.com/googleforgames/agones/blob/main/pkg/apis/allocation/v1/gameserverallocation.go#L64-L83)
- [gRPC Allocation Request](https://github.com/googleforgames/agones/blob/main/proto/allocation/allocation.proto#L30-L58)
- [Website reference docs](https://agones.dev/site/docs/reference/gameserverallocation/)

**What you expected to happen**: We should explain in a consistent manner how Agones treats these fields. 

**How to reproduce it (as minimally and precisely as possible)**: Read the three pages linked above.

**Comment by roberthbailey** [comment]
It looks like the current specification was proposed in https://github.com/googleforgames/agones/issues/436 which has documentation matching the API docs and gRPC docs (but no longer our website reference docs).

**Comment by markmandel** [comment]
The website is the most descriptive, and accurate.

**Comment by roberthbailey** [comment]
It sounds like we should update the API docs and the gRPC comments. I think that the field names are a bit confusing, but since the APIs are v1, it probably isn't worth fixing the names in the APIs.

**Comment by markmandel** [comment]
> It sounds like we should update the API docs and the gRPC comments. I think that the field names are a bit confusing, but since the APIs are v1, it probably isn't worth fixing the names in the APIs.

I agree. Admittedly it's not something that we get many questions on - so I'm hoping that's an indicator that the documentation is easy to understand 😄

**Comment by roberthbailey** [comment]
It looks like #2188 made the api docs consistent with the website docs. Marking this as fixed.
