### ISSUE TITLE
fatal error: agones_global.h: No such file or directory

### ISSUE THREAD

**Issue by zenspirit** [googleforgames/agones#2140]
While compilation, I encountered error.
In the SDK include directory, no such a file can be found.

**Comment by markmandel** [comment]
Please provide the full set of steps taken, and output of logging.

Unfortunately this report doesn't provide enough information to be actionable.

**Comment by zenspirit** [comment]
Just try to build, then you will know there`s missing files. 
So simple. what else do you need ? 
 
-----Original Message-----

**Comment by markmandel** [comment]
I just tried our build process for CPP that is part of our CI system, and all passed.

As originally requested, please fill out our entire bug template, with detailed description of the steps you took and the exact output as well so we can reproduce.

**Comment by zenspirit** [comment]
Sorry, I don`t know where is the form or report. 
 
https://github.com/googleforgames/agones/blob/release-1.15.0/sdks/cpp/include/agones/sdk.h 
 
line 18,  it includes "agones_global.h", which does not exist.  
 
Where can I find this file?
 


-----Original Message-----

**Comment by aLekSer** [comment]
This might be generated by CMake https://github.com/googleforgames/agones/blob/main/sdks/cpp/cmake/agones_global.h.in
@dsazonoff can tell you more on this.

**Comment by dsazonoff** [comment]
Hello @zenspirit . Could you provide steps (command line) how you do a build? This file should be generated by CMake.

**Comment by markmandel** [comment]
We haven't had any update on this for a while, unless there is any objection, let's close this issue.

**Comment by zenspirit** [comment]
My apologies.  
I am not working on this project any more.  
Please close this ticket.  
 
 
-----Original Message-----

**Comment by markmandel** [comment]
No worries, thanks for the follow up!
