### ISSUE TITLE
Could I wait for autoscaling when ready GameServers are not enough?

### ISSUE THREAD

**Issue by zouyxdut** [googleforgames/agones#2145]
Assuming that I deployed a fleetautoscaler with `bufferSize=2`, so currently I have 2 ready Gameservers. If I allocate 3 Gameservers at a time, it may fail with the error "Could not find a Ready GameServer". Could I wait for the ready Gameservers scaled up to 3 so that the allocation can succeed?

**Environment**:
- Agones version: 1.14
- Kubernetes version (use `kubectl version`):1.21.1
- Install method (yaml/helm): helm

**Comment by markmandel** [comment]
Unfortunately this is not possible, since the K8s API has a hard timeout limit. The allocation system does retry periodically within that time limit however.

We recommend you implement your own queuing / retry mechanism into your matchmaker as neccessary.

**Comment by zouyxdut** [comment]
@markmandel Thx~

**Comment by markmandel** [comment]
Closing this, as I believe it has been answered. Please reopen if there are follow ups!
