### ISSUE TITLE
Question: Why not add the "cluster-​autoscaler.kubernetes.io/safe-to-evict": "false" annotation only to the allocated game servers?

### ISSUE THREAD

**Issue by YDKK** [googleforgames/agones#2153]
I'm new to the Agones and worrying about the `Packed` scheduling is not working well with the cluster-autoscaler when a fleet scaling down.

In my understanding, if a fleet managed by a fleet autoscaler with the "buffer=N" setting ended up with N nodes with only one game server, the number of nodes will not be reduced even if there were enough resources to run N game servers on a single node.
The cluster-autoscaler cannot move ready (not allocated) game servers to another nodes because the "cluster-​autoscaler.kubernetes.io/safe-to-evict": "false" annotation is added to the all game server pods.

I think it would be better to add the "cluster-​autoscaler.kubernetes.io/safe-to-evict": "false" annotation only when a game server is allocated (or reserved). That way the cluster-autoscaler will be able to move unallocated game servers to another nodes for cluster scale-down.

Question:
- Is my understanding correct?
- Is there any reason to add the "cluster-​autoscaler.kubernetes.io/safe-to-evict": "false" annotation not only to the allocated game servers but all game servers?

May be related with #484

**Comment by markmandel** [comment]
I believe this is all covered in this article:
https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/#fleet-scheduling

But TL;DR - race conditions.

**Comment by YDKK** [comment]
Thank you for responding!

> But TL;DR - race conditions 😄

OK, I understood it.

My main concern is that if once ready game servers are distributed across many nodes, the standard kube-scheduler with `PodAffinity` with a `preferredDuringSchedulingIgnoredDuringExecution` affinity with `hostname` topology will schedule new game server pods across all nodes evenly, and the number of nodes will not decrease easily.

**Comment by markmandel** [comment]
This is why we use both the PodAffinity and custom Fleet scaling logic to ensure things get as packed as possible in the cluster. Basically you end up with a full cluster always.

**Comment by YDKK** [comment]
Hmm...
OK, I understood that such cases are rare and that the Agones doesn't care these cases because we do packing on a best-effort basis.

I'll close this issue.
