### ISSUE TITLE
Remove pre-1.0 documentation from the agones.dev website

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2156]
**Is your feature request related to a problem? Please describe.**
Right now agones.dev has documentation for releases going back a long time, to pre-1.0 version. The drop down shows:

<img width="424" alt="Screen Shot" src="https://user-images.githubusercontent.com/7751204/123301691-c9459a00-d4d0-11eb-8804-546336935e23.png">

**Describe the solution you'd like**
We should drop all of the version prior to 1.0. We may also want to drop later versions (see https://github.com/googleforgames/agones/issues/1146) but we will leave that discussion to a separate issue.

**Comment by markmandel** [comment]
Makes sense to me! 0.12.0 came out in 2019, so I think we can safely drop it.

![image](https://user-images.githubusercontent.com/298370/123308977-33623d00-d4d9-11eb-80b3-eaeaa2b907c3.png)

**Comment by roberthbailey** [comment]
On the PR, @markmandel said:

> At some point we should also remove the corresponding services from App Engine, but we can do that at a later date.

I've removed the services for 0-9-0, 0-10-0, 0-11-0, and 0-12-0.
