### ISSUE TITLE
export-openapi.sh doesn't work with Kubernetes 1.19

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2159]
**What happened**: Running `make gen-embedded-openapi` exits with the error `jq: error (at <stdin>:0): Cannot index array with string "spec"`

**What you expected to happen**: The script to complete successfully.

**How to reproduce it (as minimally and precisely as possible)**: 

I also tried `make shell` and then ran the first two lines of the script:

```
kubectl proxy &
curl http://127.0.0.1:8001/openapi/v2 | jq 'del(.. | .["x-kubernetes-patch-strategy"]?, .["x-kubernetes-patch-merge-key"]?, .["x-kubernetes-list-type"]?)' | jq 'del(.. |  .["x-kubernetes-group-version-kind"]?, .["x-kubernetes-list-map-keys"]? )'
```

and it gave the same error.

**Anything else we need to know?**:

**Environment**:
- Agones version: HEAD
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): `make gcloud-test-cluster`
- Troubleshooting guide log(s):
- Others:

**Comment by roberthbailey** [comment]
@markmandel - can you take a look at this? My knowledge of `jq` doesn't go particularly deep.

**Comment by roberthbailey** [comment]
Through a bit of trial and error I found that if I removed the `.. |` at the beginning of the `del` commands on lines 55 & 56 the script doesn't fail immediately. 

But, it then gives the error: 

```
Processing io.k8s.api.core.v1.PodTemplateSpec
Processing io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
Processing io.k8s.apimachinery.pkg.apis.meta.v1.Time
Processing io.k8s.apimachinery.pkg.apis.meta.v1.Time
...
Expanding io.k8s.api.core.v1.PodDNSConfigOption.json
Expanding io.k8s.api.core.v1.PodReadinessGate.json
Expanding io.k8s.api.core.v1.PodSecurityContext.json
Expanding io.k8s.api.core.v1.PodSpec.json
Expanding io.k8s.api.core.v1.PodTemplateSpec.json
parse error: Invalid escape at line 1592, column 493
```

**Comment by markmandel** [comment]
I'll take a look! Weird, I wonder what changed 🤔

**Comment by markmandel** [comment]
Okay, so this is all kinds of fun.

1. The cluster has to be a basic GKE cluster, for reasons I'm not 100% sure of. I had Agones installed, and this caused a different errors, and then I removed it, and now things are passing the initial error.
2. There is a new invalid escape character in a description that i need to add some code to the bash script to clear out.
3. This needs to be documented 😄

**Comment by roberthbailey** [comment]
I was trying to add some "notes to self" to the k8s 1.19 upgrade task list (so that we would have a better idea for each step for next time) but having this documented somewhere we can point to (maybe https://github.com/googleforgames/agones/blob/main/build/README.md) would be awesome.
