### ISSUE TITLE
Replace export-openapi.sh with a golang program

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2162]
**Is your feature request related to a problem? Please describe.**
Based on the fact that it had to be changed for the Kubernetes 1.19 update, `export-openapi.sh` seems a bit fragile, and since it's written in bash it's pretty difficult to debug and/or write good error handling. 

**Describe the solution you'd like**
Rewrite the logic from `export-openapi.sh` in golang, presumably making it more robust. 

**Describe alternatives you've considered**
Leave the bash script and fix it during Kubernetes updates where it stops working. The script worked for Kubernetes 1.17 and 1.18 and then broke for 1.19. Maybe it will not need much maintenance going forward?

We could also wait and see if this continues to be a problem before investing in rewriting the script. If it keeps breaking, maybe it's more useful to try and make it more robust. 

/cc @markmandel

**Comment by markmandel** [comment]
I'm sure there are more libraries, but https://github.com/getkin/kin-openapi (or something like it), would probably make this much easier, as we could handle open-api types. The only risk I see is that Kubernetes uses a series of `x-kubernetes-*` attributes, that we would want to make sure get handled correctly.

But 100% agreed a go program would be less brittle!

**Comment by markmandel** [comment]
Currently being worked on in #3413
