### ISSUE TITLE
Update build scripts for Docker 20.10

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2173]
As @jeremyje mentioned in https://github.com/googleforgames/agones/issues/54#issuecomment-875724292, docker 19.03 is reaching end of life this month. 

See https://endoflife.software/applications/virtualization/docker-daemon 

We should update to docker 20.10 for our build process.

**Comment by markmandel** [comment]
I think we can we close this? Google Cloud Build does the docker upgrade for us.

**Comment by roberthbailey** [comment]
Sounds good to me.
