### ISSUE TITLE
Gameserver stopped with GOAWAY with error code ENHANCE_YOUR_CALM after about 30 minutes

### ISSUE THREAD

**Issue by nicolaegeorgescu** [googleforgames/agones#2191]
Hello,

My gameserver is C++ and i integrated the C++ Agones SDK version 1.15.0.
The Agones cluster runs version 1.12.0

The problem is after 30 minutes or so my servers are stopped. 

I am calling Health() every 70 seconds from the Gameserver and below is the health configuration in the fleet:
      health:
        initialDelaySeconds: 120
        periodSeconds: 120
        failureThreshold: 3

After multiple calls to Health() API that return true, i get the GOAWAY log, then Health() calls return false, and after 3-4 false ones the gameserver is shutdown for not being healthy.

What is causing the GOAWAY message that seems to block calls from the Gameserver afterwards?

===============================================================
Logs from the gameserver:

11:20:38.030	[LVL_NOTICE] Started GS id d3b5c996-eade-11eb-9b83-8aff15dd0228 
11:20:38.030	[LVL_INFO] Succesfully started listening SUCCESS on port 27021! 
11:20:38.030	[LVL_NOTICE] Connected to Agones in 1001ms! 
11:20:38.030	[LVL_NOTICE] Marking server as ready
11:20:38.030	[LVL_INFO] Health ping 1
11:20:39.517	{"ctlConf":{"Address":"localhost","IsLocal":false,"LocalFile":"","Delay":0,"Timeout":0,"Test":"","TestSdkName":"","GRPCPort":9357,"HTTPPort":9358},"featureGates":"Example=true\u0026NodeExternalDNS=false\u0026PlayerTracking=false\u0026RollingUpdateOnReady=false\u0026SDKWatchSendOnExecute=true","message":"Starting sdk sidecar","severity":"info","source":"main","time":"2021-07-22T11:20:32.647396168Z","version":"1.12.0"} 
11:20:39.517	{"gsKey":"mc5/fleet-fastmatch-gstest-2z7h2-r4grv","message":"Created GameServer sidecar","severity":"info","source":"*sdkserver.SDKServer","time":"2021-07-22T11:20:32.649168098Z"} 
11:20:39.517	{"gsKey":"mc5/fleet-fastmatch-gstest-2z7h2-r4grv","message":"Starting workers...","queue":"agones.dev.mc5.fleet-fastmatch-gstest-2z7h2-r4grv","severity":"info","source":"*sdkserver.SDKServer","time":"2021-07-22T11:20:32.749490346Z","workers":1} 
11:20:39.517	{"httpEndpoint":"localhost:9358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2021-07-22T11:20:33.715252906Z"} 
11:20:39.517	{"grpcEndpoint":"localhost:9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2021-07-22T11:20:32.711105051Z"} 
11:21:44.005	[LVL_INFO] Health ping 1 
11:23:06.452	[LVL_INFO] Health ping 1 
11:24:04.010	[LVL_INFO] Health ping 1 
11:25:14.003	[LVL_INFO] Health ping 1 
11:26:24.455	[LVL_INFO] Health ping 1 
......
11:40:24.539	[LVL_INFO] Health ping 1 
11:40:39.664	E0722 11:40:37.053090720 9 chttp2_transport.cc:1156] Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
11:41:34.336	[LVL_INFO] Health ping 0 
11:42:33.454	{"failureCount":1,"gsKey":"mc5/fleet-fastmatch-gstest-2z7h2-r4grv","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2021-07-22T11:42:32.75164749Z"} 
11:42:44.005	[LVL_INFO] Health ping 0 
11:43:54.475	[LVL_INFO] Health ping 0 
11:44:33.458	{"failureCount":2,"gsKey":"mc5/fleet-fastmatch-gstest-2z7h2-r4grv","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2021-07-22T11:44:32.751901541Z"} 
11:45:04.003	[LVL_INFO] Health ping 0 
11:46:15.466	[LVL_INFO] Health ping 0 
11:46:33.466	{"failureCount":3,"gsKey":"mc5/fleet-fastmatch-gstest-2z7h2-r4grv","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2021-07-22T11:46:32.752064205Z"} 
11:46:33.466	{"gameServerName":"fleet-fastmatch-gstest-2z7h2-r4grv","gsKey":"mc5/fleet-fastmatch-gstest-2z7h2-r4grv","message":"GameServer has failed health check","severity":"warning","source":"*sdkserver.SDKServer","time":"2021-07-22T11:46:32.752302051Z"} 
11:46:34.005	{"message":"shutting down sdk server","severity":"info","source":"main","time":"2021-07-22T11:46:33.676044548Z"}

**Comment by markmandel** [comment]
Thanks for reporting! We had this for a while with our node SDK (#1299), but that seemed to go away with the newer SDK.

Just having a quick look, it seems like https://grpc.github.io/grpc/core/md_doc_keepalive.html has some details we should look at.

**Comment by nicolaegeorgescu** [comment]
Thanks for the reply!
I read the initial ticket indeed, and it seemed to go away just like that, there was no clear fix reported.

I've read the documentation on grpc. Just to be sure, in this scenario the gameserver is the client, and the Agones controller/process is the server. I briefly checked in the gameserver lib 1.15.0 and it seems GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS is false, and GRPC_ARG_KEEPALIVE_TIME_MS is infinite for the client, which would invalidate both scenarios mentioned in the doc that could cause the problem. I will investigate more thoroughly, the values are not a simple define, they seem to be modified in the chttp2_transport.cc at runtime.

One more note, the GOAWAY issue easily happens when i just leave the gameservers in ready state, with no call to gameserverallocation.

**Comment by markmandel** [comment]
🤔 random thought - if you ping the health check more often, does the problem go away?

**Comment by nicolaegeorgescu** [comment]
It makes sense, the grpc keep alive might not kick in if higher level sends data. 

Unfortunately i tried with ping every 20, 10 an 1 second, and the issue still remains.

About grpc, i read the code a bit. Settings are done in chttp2_transport.cc in methods grpc_chttp2_config_default_keepalive_args and read_channel_args. 
I didn't find how channel arguments can be set from libs above so not sure what values are actually being set.

I did notice a potential issue in grpc_chttp2_config_default_keepalive_args at line #2669
      } else if (0 == strcmp(args->args[i].key,
                             GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS)) {
        const bool value = static_cast<uint32_t>(grpc_channel_arg_get_integer(
            &args->args[i],
            {is_client ? g_default_client_keepalive_permit_without_calls
                       : g_default_server_keepalive_timeout_ms,
             0, 1}));

The g_default_server_keepalive_timeout_ms should be replaced with g_default_server_keepalive_permit_without_calls.
Reading inside grpc_channel_arg_get_integer and grpc_integer_options it seems the default value is taken if outside the min-max set at 0-1.
But this potential bug, if it is a bug, would set GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS on the server to true instead of false. Which i am not sure causes issues, on the link you sent as reference(https://grpc.github.io/grpc/core/md_doc_keepalive.html) it's a problem if the server has False and client has True.

**Comment by markmandel** [comment]
We are running a slightly old version of gRPC on the client side stil (https://github.com/googleforgames/agones/issues/1797), it might be worth attempting to update it to [line up with what we are running server side](https://github.com/googleforgames/agones/blob/main/go.mod#L34), and see if that resolves the issue.

https://github.com/googleforgames/agones/blob/main/sdks/cpp/CMakeLists.txt#L99 (it is possible that the client side code will need to be regenerated though).
