### ISSUE TITLE
I can't establish a TCP connection to an allocated Game Server with DigitalOcean

### ISSUE THREAD

**Issue by andygruening** [googleforgames/agones#2207]
**What happened**:

I'm not sure if it is a bug or if I am just missing out on something.
My goal is to have the game servers running with agones/kubernetes to be able to connect to the individual game servers from an external game client on my/other peoples local machine.
I am creating a fleet of game servers, which are successfully starting and allocating. They are running on a DigitalOcean droplet/node (I am using their Kubernetes system). The IP address for the game servers (when using 'kubectl get gs') is identical to the ip address of the DigitalOcean droplet/node. When describing the servers, the ports were allocated correctly, but when I want to connect to the ports with the ip, I cannot establish a TCP connection (I was also testing it with 'Test-NetConnection' on Windows PowerShell).
DigitalOcean has 2 firewalls: ufw and their cloud firewalls. I made sure that ufw is disabled and the cloud firewall is allowing all incoming/outcoming tcp/udp ports (I tested that with other ports, which are accessible).
I also setup a LoadBalancer to expose the pod of the game server. That IP and port is accessible then, but it still doesnt connect me to my server logic and that doesnt really fit my usecase. And from what I read everywhere in the Agones guides etc, it's not required to have a LoadBalancer, isnt it?

**What you expected to happen**:

That I could connect to the given IP and Port of the game server from a client outside the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure if that just happens with Digital Ocean or also with other cloud providers, but reproducing it would simply mean to follow the official Agones guide to create a fleet and connect an allocated game server.

**Anything else we need to know?**:

There are no error messages in the game server logs and my server logic/application is running fine without problems. It's basically just that the port is not accessible, even though the firewall on DigitalOcean definitely allows the port range 7000-8000. I also tried to just remove the firewall entirely, but Im still not able to connect to the port. The given IP is pingable though (without firewall). 

I would assume that this means the port is just simply not in use. So am I missing something in my process? I really hope anyone can help me, thanks in advance!

**Environment**:
- Agones version: 1.16.0
- Kubernetes version (use `kubectl version`): v1.19.12 (Server Version)
- Cloud provider or hardware configuration: DigitalOcean Kubernetes
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
from `kubectl describe gs` :
https://pastebin.pl/view/4ee4cfac
- Others:
Fleet yaml file:
https://pastebin.pl/view/7791b4c3
Example of a game server state:
`gs-8bnsg-drp98   Allocated   <IP>   7536   pool-zyuka4817-85z3l (DigitalOcean Node)   5m27s`

**Comment by roberthbailey** [comment]
I know you said that you checked the firewall, but this really sounds like a firewall issue. Can you try connecting to the game servers from within the cluster? Can you connect to _any_ sort of server running on the droplets bound to a port in the allowed range? Did you verify that the firewall is allowing the correct protocol (udp vs. tcp)?

**Comment by markmandel** [comment]
Good advice from @roberthbailey - I would also ask, have you gone through:
https://1-15-0.agones.dev/site/docs/guides/troubleshooting/#something-went-wrong-with-my-gameserver

Confirm that everything is working at each level, so you can remove different factors for things going wrong.

**Comment by markmandel** [comment]
Marking as stale, since this has been almost a year. I assume this problem has been resolved.

**Comment by markmandel** [comment]
Going to close, since there was no response. Assume they found a solution.
