### ISSUE TITLE
Collaborator Request

### ISSUE THREAD

**Issue by cindy52** [googleforgames/agones#2210]
If you'd like to become a collaborator of the Agones repo on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join. Once accepted you'll be able to have issues assigned to you! 

### GitHub user id

cindy52

### Requirements

- [x] I have reviewed the [contribution guidelines](https://github.com/googleforgames/agones/blob/main/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @roberthbailey 

- @markmandel 

### List of contributions to the Agones project

- PRs reviewed / authored
- Issues responded to

**Comment by markmandel** [comment]
Invite sent! Let me know when you have accepted!

**Comment by roberthbailey** [comment]
LGTM!

**Comment by cindy52** [comment]
> Invite sent! Let me know when you have accepted!

Accepted. Thanks!
