### ISSUE TITLE
Allocator TLS cert with SAN DNS

### ISSUE THREAD

**Issue by WilSimpson** [googleforgames/agones#2213]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Allow for helm to configures Agones allocator TLS cert with a SAN DNS and not only a SAN IP.

**Describe alternatives you've considered**
Just using a SAN IP

**Additional context**
I believe it is easier to manage pointing a DNS to allocator load balancer IP rather than to managing a SAN IP in a agones TLS cert. I understand it shouldn't change often, or possibly at all, but on the off chance it does, it seems like a hassle and extra step to update the TLS cert SAN IP with helm.

**Comment by markmandel** [comment]
This feels to me like this should be handled not by helm, but a proper cert management solution, such as what is outlined here:
https://agones.dev/site/docs/advanced/allocator-service/#server-tls-certificate
https://cert-manager.io/

I don't think we as a project want to take on the burden of cert management and rotation etc that are externally available -- I'd leave that one to the security experts. 🤷🏻‍♂️

I get the convenience though.
