### ISSUE TITLE
Support Agones on ARM systems

### ISSUE THREAD

**Issue by wernerphysics** [googleforgames/agones#2216]
I'm running Agones in a local Minikube cluster on an M1 Mac. When I create a basic xonotic game server from this repo's examples, I get an Image Pull Error. The error details specify that the image "gcr.io/agones-images/agones-sdk" does not have a linux/arm64/v8 manifest. The issue seems to be that the Docker runtime when running on M1 Mac expects only ARM images.

My suggestion is to provide an ARM64 build of the Agones SDK in the GCR repo so that developers on ARM machines can run Agones/Minikube locally.

**Comment by markmandel** [comment]
I can see us needing to support ARM in the future long term, so this is a good ticket to track this work. 👍🏻 

Out of curiosity though: On an M1, can you _only_ run arm docker images? (i.e. minikube won't work with anything else?) or is there a path to running x86 images?

**Comment by wernerphysics** [comment]
I looked into the issue some more and in fact you can run x86 images on M1 Mac Minikube. It works transparently through the Rosetta2 compatibility layer.

The issue: when the pod is created, it pulls agones-sdk:1.16.0 without an additional tag, which on a default M1 Mac install requests the nonexistent ARM64 image. I got it to work by editing the pod spec to specifically pull the agones-sdk:1.16.0-linux_amd64 image. After this step, both containers in the xonotic-example pod are working.

For what it's worth, I think this only works because of Apple's x86 emulation. It would still be helpful to add the ARM image tag for users on ARM platforms without robust emulation support.

**Comment by markmandel** [comment]
>  It would still be helpful to add the ARM image tag for users on ARM platforms without robust emulation support.

I agree. Also combined with #2223 we should probably cross compile all the components.

**Comment by davidpdrsn** [comment]
@wernerphysics I'm having the same issue. Could you elaborate on what you meant by

> I got it to work by editing the pod spec to specifically pull the agones-sdk:1.16.0-linux_amd64 image.

I'm still sort new to k8s 😅

**Comment by markmandel** [comment]
If we want to do this in pieces, to start, let's get a ARM binary generated:
https://github.com/googleforgames/agones/blob/15678b65acd58c8fe9de8eb11e336375be3b4d79/build/Makefile#L382-L384

(Do you need an arm binary for [local sdk server development](https://agones.dev/site/docs/guides/client-sdks/loal/)?)

**Comment by markmandel** [comment]
Consolidating this with #2223 - making a note that to run on K8s clusters that are entirely ARM, we (may?) need to also provide a build of the controller as well (testing likely required).

**Comment by wernerphysics** [comment]
> @wernerphysics I'm having the same issue. Could you elaborate on what you meant by
> 
> > I got it to work by editing the pod spec to specifically pull the agones-sdk:1.16.0-linux_amd64 image.
> 
> I'm still sort new to k8s 😅

There's definitely a better way to do this (probably changing the default SDK when you Helm install Agones), but here's my quick and dirty fix. When the pod is running, edit the spec with something like `kubectl edit pod xonotic` and find the line where the Agones SDK image is specified, should look like `image: gcr.io/agones-images/agones-sdk:1.16.0`. Look at the images at `http://gcr.io/agones-images/agones-sdk`, and rewrite the pod spec to use the tag of the latest linux_amd64 image. This seemed to work for me, good luck!

**Comment by tuapuikia** [comment]
I manage to build the side car image (agones-sdk) for arm based server (AWS Graviton) and use the helm template to generate the yaml to use my private repo.

Other components still run on amd64 instance but planning to cross compile them and test it in coming weeks.

It's a good start. 😁

**Comment by markmandel** [comment]
@tuapuikia can you share what you did as a PR? Unfortunately it's only useful to the project if you share what it is you have done 😄

**Comment by tuapuikia** [comment]
Hi @markmandel,

My use case is to host a game server on the AWS Gravition instance to save cost and utilize the new powerful AWS instance type. 

Below is what I have done.

1. Deploy EKS + A1 and C6 custom instance groups.
2. Deploy Agones to my new EKS cluster.
3. Recompile example "supertuxkart" with ARM machine.
4. Deploy supertuxkart example to the new ARM worker node.
5. Compare the container and server performance between x86 vs ARM64.
6. Propose to use ARM64 in my company. (WIP) 

TF module https://github.com/tuapuikia/terraform-eks-arm

The patch of the makefile is still messy and not ready for PR.
What I have done is using docker "buildx" and Ubuntu/Linux binfmt to cross-compile the agones sdk server in order to get the arm64 docker image.

**Comment by markmandel** [comment]
Oops, work not complete yet, so let's not choose this.

**Comment by markmandel** [comment]
Question: Have we done the PING service?

**Comment by roberthbailey** [comment]
I don't think so. I only see arm tags for the sidecar, allocator, and controller:

https://github.com/googleforgames/agones/blob/849b4d3cd2877bc2c015937a8abc1e4717c8e0e4/build/Makefile#L244-L248

**Comment by markmandel** [comment]
I think that's the last bit then - @Ludea

**Comment by markmandel** [comment]
Oops, looks like the screenshot broke?

**Comment by Ludea** [comment]
![Screenshot_20220520-180243](https://user-images.githubusercontent.com/2116692/169568082-f330e749-7fad-4d62-b168-caf871f1563b.jpg)
Better

**Comment by markmandel** [comment]
So there should be a few ping pods as well. This is what it looks like on my GKE cluster:

```
markmandel@cloudshell:~ (agones-mark-dev)$ kubectl get pods -n agones-system
NAME                                   READY   STATUS      RESTARTS   AGE
agones-allocator-57bb5d9494-glk6h      1/1     Running     0          16h
agones-allocator-57bb5d9494-mfnfc      1/1     Running     0          16h
agones-allocator-57bb5d9494-vll82      1/1     Running     0          16h
agones-controller-695f675fc6-xxf2c     1/1     Running     0          16h
agones-delete-agones-resources-4cxmf   0/1     Completed   0          16h
agones-ping-6fd49fcfdc-6wcbn           1/1     Running     0          16h
agones-ping-6fd49fcfdc-z66zv           1/1     Running     0          16h
```

Also, lots of points for being able to run kubectl on your phone. 😁 

I'm willing to bet you have the Deployments in place for it, but the image pull for arm64 is failing.

**Comment by Ludea** [comment]
> Also, lots of points for being able to run kubectl on your phone. 😁
Thanks !

> I'm willing to bet you have the Deployments in place for it, but the image pull for arm64 is failing.

I hit https://github.com/googleforgames/agones/issues/2578 so I install https://github.com/googleforgames/agones/pull/2581 image tag. 
I set `agones.allocator.replicas=1` because Rpi3 have only 1GB memory^^ and `agones.ping.install`to false because I know ping image doesnt support arm64 img yet . 
So the last thing is to port ping img ?

**Comment by markmandel** [comment]
> So the last thing is to port ping img ?

I believe so! Will likely want to have a few of us test some scenarios on an ARM cluster, but I think that's the last step.

**Comment by markmandel** [comment]
oooh, I thought of one more thing!

https://github.com/googleforgames/agones/blob/main/examples/simple-game-server < that will need to also be updated, as that's the sample we use for all our e2e tests, so we'll need that too so that we can run the e2e tests on a arm cluster (and manual tests too).

(Should probably have done a checklist in the beginning)

**Comment by markmandel** [comment]
So just attempted to build `simple-game-server` and unfortunately it didn't work. Digging into what went wrong.

```
➜  simple-game-server git:(main) make build
Makefile:83: warning: overriding recipe for target 'push'
Makefile:79: warning: ignoring old recipe for target 'push'
Makefile:88: warning: overriding recipe for target 'push'
Makefile:83: warning: ignoring old recipe for target 'push'
cd /home/mark/workspace/agones && docker build -f /home/mark/workspace/agones/examples/simple-game-server/Dockerfile --tag=gcr.io/agones-images/simple-game-server:0.13-linux-amd64 .
Sending build context to Docker daemon  1.137GB
Step 1/11 : FROM golang:1.17.2 as builder
 ---> 9f8b89ee4475
Step 2/11 : WORKDIR /go/src
 ---> Using cache
 ---> 7cc04c3e643e
Step 3/11 : COPY . agones.dev/agones
 ---> Using cache
 ---> 64ff92bf4f49
Step 4/11 : WORKDIR /go/src/agones.dev/agones/examples/simple-game-server
 ---> Using cache
 ---> c55809501703
Step 5/11 : RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server .
 ---> Running in 0149925cc97b
go: downloading github.com/golang/protobuf v1.5.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.11.3
go: downloading golang.org/x/net v0.0.0-20210224082022-3d97a244fca7
go: downloading google.golang.org/genproto v0.0.0-20201110150050-8816d57aaa9a
go: downloading google.golang.org/grpc v1.27.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading google.golang.org/protobuf v1.26.0
go: downloading golang.org/x/sys v0.0.0-20210426230700-d19ff857e887
go: downloading golang.org/x/text v0.3.4
go: updates to go.mod needed; to update it:
        go mod tidy
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server .' returned a non-zero code: 1
make: *** [Makefile:122: build-linux-image-amd64] Error 1
```

**Comment by markmandel** [comment]
Looks like `go mod tidy` solved the issue. PR incoming.

**Comment by markmandel** [comment]
Spoke too soon. 

```
➜  simple-game-server git:(main) ✗ make build-linux-image-arm64
Makefile:83: warning: overriding recipe for target 'push'
Makefile:79: warning: ignoring old recipe for target 'push'
Makefile:88: warning: overriding recipe for target 'push'
Makefile:83: warning: ignoring old recipe for target 'push'
cd /home/mark/workspace/agones && docker build -f /home/mark/workspace/agones/examples/simple-game-server/Dockerfile --platform linux/arm64 --tag=gcr.io/agones-images/simple-game-server:0.13-linux-arm64 .
Sending build context to Docker daemon  1.137GB
Step 1/11 : FROM golang:1.17.2 as builder
 ---> 9f8b89ee4475
Step 2/11 : WORKDIR /go/src
 ---> Using cache
 ---> 0af6bf5e5318
Step 3/11 : COPY . agones.dev/agones
failed to get destination image "sha256:0af6bf5e5318126fb7f755b06a412e36836e95d6ef497c71a49a6d99753b3917": image with reference sha256:0af6bf5e5318126fb7f755b06a412e36836e95d6ef497c71a49a6d99753b3917 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
make: *** [Makefile:124: build-linux-image-arm64] Error 1
```

**Comment by markmandel** [comment]
I reckon I have the fixes in place to make it work - just testing now against both an ARM64 and a AMD64 clusters to make sure everything is golden.

**Comment by markmandel** [comment]
`gcr.io/agones-images/simple-game-server:0.13` should now have an arm and windows image on the registry. 👍🏻 

We should move all the e2e tests over to this image as well.

**Comment by markmandel** [comment]
Can we close this now? I think we're good? WDYT @roberthbailey ?

**Comment by roberthbailey** [comment]
Yes. We now have alpha support for ARM (documented [here](https://agones.dev/site/docs/installation/#supported-container-architectures)) and I think this can be closed. 

As with feature gate promotions, we can open tickets specifically targeted at moving from alpha towards stable going forward.
