### ISSUE TITLE
Is theres an Unreal Engine 4 example?

### ISSUE THREAD

**Issue by Jeffwan** [googleforgames/agones#2219]
**Is your feature request related to a problem? Please describe.**
Trying to see if there's an unreal sdk example? I can not find resources in https://github.com/googleforgames/agones/tree/master/examples 

**Describe the solution you'd like**
We need to host an unreal game server and would like to know some best practice from the community. We would like to make minimum changes to make it work on Agones

**Comment by markmandel** [comment]
Should we close this in favour of #2217

**Comment by Jeffwan** [comment]
ah. I should search the backlog first. Agree. Let me close this one and track the progress in #2217
