### ISSUE TITLE
sdkServer.logLevel in Gameserver config doesn't seem to be used in local mode

### ISSUE THREAD

**Issue by barankyle** [googleforgames/agones#2221]
**What happened**:
I'm trying to change sdkServer.logLevel when running the SDK server locally, but it doesn't appear to have any effect. Setting it to 'Debug' doesn't seem to print out any more messages than the default value of 'Info', and when setting it to 'Error', I still see the Info-level messages.

**What you expected to happen**:
Setting sdkServer.logLevel to Error would hide all the Info-level messages, and setting it to Debug would output more than just the Info-level messages

**How to reproduce it (as minimally and precisely as possible)**:
Run the sdk server locally and pass in the [example Gameserver config file](https://raw.githubusercontent.com/googleforgames/agones/d8748dfb82dde85994209b2b8505ef9ee652a818/examples/gameserver.yaml), only change sdkServer.logLevel from 'Info' to 'Error' (or 'Debug'):
`./sdk-server.linux.amd64 --local -f gameserver.yml`

Info-level logging statements will be output when logLevel is set to 'Error', and no additional logging statements will be output when logLevel is set to 'Debug'.

Additionally, when calling `curl -GET "http://localhost:9358/gameserver" -H "accept: application/json"`, the returned information doesn't contain anything about sdkServer (though I'm not sure if it's supposed to).

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.16.0
- Kubernetes version (use `kubectl version`): none (running locally with --local)
- Cloud provider or hardware configuration: none (running locally with --local)
- Install method (yaml/helm): Downloaded .zip of sdk-server files and extracted them
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
> 'm trying to change sdkServer.logLevel when running the SDK server locally, but it doesn't appear to have any effect.

So I'm super curious now 😄 . What's the use case? 

(I'm actually not sure if we even have any debug level logging in there? 🤔 )

**Comment by barankyle** [comment]
One of our engineers wanted to cut down on the noise of all the info-level messages like health pings when doing local development.

As for debug-level logs, maybe there aren't any! I assumed from the inclusion of that option that there were, but maybe it's just a forward-thinking option.

**Comment by markmandel** [comment]
Interesting, legit bug.

Looks like we should grab https://github.com/googleforgames/agones/blob/main/pkg/sdkserver/sdkserver.go#L207-L219 and port it into the [local SDK](https://github.com/googleforgames/agones/blob/main/pkg/sdkserver/localsdk.go), probably as part of `setGameServerFromFilePath` so that file reload works.
