### ISSUE TITLE
Request Releaser role for Agones Repository

### ISSUE THREAD

**Issue by cindy52** [googleforgames/agones#2232]
### GitHub Username
cindy52

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have read the [contributor guide](../../CONTRIBUTING.md)
- [x] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roberthbailey 
- @markmandel 

### List of contributions to the Agones project
- PRs reviewed / authored
- Issues responded to

**Comment by roberthbailey** [comment]
LGTM.

**Comment by markmandel** [comment]
Of course!
