### ISSUE TITLE
Multiple UE4Scene GameServers in one container

### ISSUE THREAD

**Issue by Jeffwan** [googleforgames/agones#2235]
**Is your feature request related to a problem? Please describe.**
We are moving one Game to Agones achitecture, one single GameServer container internally needs to start multiple processes and they leverage share memory to reduce overall memory usage. If we deploy single process in a separate container, the overall memory is much higher than the "shared mode". 

This deployment topology brings extra challenge to the agones architecture. 
When upstream sends a `GameAllocationRequest`,  in current design, we can not mark GameServer as `Allocated` because 1/n (Let's assume we start N servers in one container) is being used.  Scheduling unit has been changed from pod level to process level. 

Correspondingly, autoscaling logics have to be changed as well. It has to use signal like process request rate. 

I am curious if community has seen similar use case, what's the best practice to deal with similar case? 

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
We are in progress of changing topology and make one GS only container one UE4Scene. Still checking memory consumption changes. We think there's trade off between `rich container` vs `single GS per container`. But if the game team don't accept the refactoring, it's hard for us to use agones directly. 

**Additional context**

**Comment by WenchaoXia** [comment]
I have exactly same problem depoying servers, since a emty UE server will occupy about 100M memory( I think there is a lot of static data loaded at bootage). For my game, if Fork can't be used then the memory occupication is not acceptable. About two years ago I have looked into Agones, and this is the issue preventing use Agones. Is there any Update for this issue?

**Comment by markmandel** [comment]
@WenchaoXia see: https://agones.dev/site/docs/integration-patterns/high-density-gameservers/

It's currently in Alpha, but would love for you to take it for a spin, see if it fits your needs!
