### ISSUE TITLE
Move RollingUpdateOnReady to Stable

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2239]
RollingUpdateOnReady has been in Beta since 1.14.0 with no bug reports. We discussed during the community meeting today and decided to promote it to stable for the next release.

For reference, the promotion to beta was done in https://github.com/googleforgames/agones/issues/1970

**Comment by roberthbailey** [comment]
@Jeffwan - now that the 1.17 release has been finalized, it would be a good time to get started on this so that it can get done for the 1.18 release. Do you have time to work on it over the next couple of weeks?

**Comment by Jeffwan** [comment]
@roberthbailey Yeah. I think I can make it in next week

**Comment by roberthbailey** [comment]
@Jeffwan - we have about 2.5 weeks left before the next release candidate. If you don't think you'll have time to finish this task before then I'm happy to help out.

**Comment by Jeffwan** [comment]
@robbieheywood Sorry for late. https://github.com/googleforgames/agones/pull/2271 please help review it. I am not sure what docs I need to change? Can you give me some clues?
