### ISSUE TITLE
Broken links on https://agones.dev/site/docs/examples/

### ISSUE THREAD

**Issue by Splizard** [googleforgames/agones#2248]
Looks like the links to examples on the https://agones.dev/site/docs/examples/ page 
are broken and need to be updated.

**Comment by markmandel** [comment]
Once the release is completed, these links will work.

/cc @cindy52 just FYI.

**Comment by markmandel** [comment]
For now you should probably look at: https://1-16-0.agones.dev/site/

**Comment by Splizard** [comment]
fixed!
