### ISSUE TITLE
Installation error on Google Cloud GKE Autopilot

### ISSUE THREAD

**Issue by Splizard** [googleforgames/agones#2249]
**What happened**:
I followed the guide on https://cloud.google.com/game-servers/docs/quickstart however instead of the suggested cluster configuration, I decided to create a Google Cloud Autopilot cluster, when I tried to install Agones I recieved this error from:
`kubectl apply -f https://raw.githubusercontent.com/googleforgames/agones/release-1.16.0/install/yaml/install.yaml`
```
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "admissionregistration.k8s.io/v1, Resource=mutatingwebhookconfigurations", GroupVersionKind: "admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration"
Name: "agones-mutation-webhook", Namespace: ""
from server for: "https://raw.githubusercontent.com/googleforgames/agones/release-1.16.0/install/yaml/install.yaml": mutatingwebhookconfigurations.admissionregistration.k8s.io "agones-mutation-webhook" is forbidden: User cannot get resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope: GKEAutopilot authz: cluster scoped resource "mutatingwebhookconfigurations/" is managed and access is denied
```

**Environment**:
- Agones version: 1.16
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.900", GitCommit:"28ab8501be88ea42e897ca8514d7cd0b436253d9", GitTreeState:"clean", BuildDate:"2021-06-30T09:23:36Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```
- Cloud provider or hardware configuration: Google Cloud GKE Autopilot
- Install method (yaml/helm): yaml

**Questions**:
* Is Agones meant to be support Google Cloud GKE Autopilot?
* Could this be caused by my kubectl version?

**Comment by Splizard** [comment]
May I add that besides this error, it would appear that agones has been mostly installed and is running:
`kubectl get pods --namespace agones-system`
```
NAME                                 READY   STATUS    RESTARTS   AGE
agones-allocator-56ffb9b789-q45hn    1/1     Running   0          118m
agones-allocator-56ffb9b789-wk8zc    1/1     Running   0          118m
agones-allocator-56ffb9b789-xkc6l    1/1     Running   0          118m
agones-controller-6454b46b8d-m44rx   1/1     Running   0          118m
agones-ping-68b48cd886-hph9s         1/1     Running   0          118m
agones-ping-68b48cd886-jvfjb         1/1     Running   0          118m
```

**Comment by markmandel** [comment]
There's a variety of reasons why GKE autopilot won't work - the primary one being that they do arbitrarily delete nodes, since they are targeted at stateless workloads.

So unfortunately, I have to close this as `wontfix`.

**Comment by Splizard** [comment]
For the gameservers I have in mind they are tolerant to being arbitrarily deleted and can continue to function as long as they shortly reallocated, if they are given a signal they can even gracefully shutdown without disruption and migrate to a replacement gameserver. This makes the Autopilot system a good fit for my use case.

How stateful are the agones components?
What other work would be required to be compatible with Autopilot? 

I'd like to take a look at this if possible, I'm relatively new to the specifics of Kubernetes so I'd be grateful for any pointers on this.

**Comment by markmandel** [comment]
It's also not possible because Autopilot doesn't support core functionality of Agones such as hostPorts, mutation and validation webhooks, etc.

Sorry, there's no way for it to work. It's not built for this kind of workload.
