### ISSUE TITLE
Improve types in SDK protobuffers

### ISSUE THREAD

**Issue by Jake-Shadle** [googleforgames/agones#2252]
**Is your feature request related to a problem? Please describe.**
Many of the types used for fields in the [`GameServer`](https://github.com/googleforgames/agones/blob/57005f77f6fdb619d856acf4e434810c2ab59c1b/proto/sdk/sdk.proto#L110) could be made more precise.

**Describe the solution you'd like**
Duration fields such as [`GameServer.spec.health.period_seconds`](https://github.com/googleforgames/agones/blob/57005f77f6fdb619d856acf4e434810c2ab59c1b/proto/sdk/sdk.proto#L135) could be an actual [Duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration). This would also get rid of the unnecessary `_seconds` suffix since the units would be encoded in the type. The unused [`Duration`](https://github.com/googleforgames/agones/blob/57005f77f6fdb619d856acf4e434810c2ab59c1b/proto/sdk/sdk.proto#L102-L105) message could also just be removed now.

[`GameServer.status.state`](https://github.com/googleforgames/agones/blob/57005f77f6fdb619d856acf4e434810c2ab59c1b/proto/sdk/sdk.proto#L154) is a string, even though it is actually a closed set that could be much more precisely constrained to an enum.

[`GameServer.object_meta.creation_timestamp`](https://github.com/googleforgames/agones/blob/57005f77f6fdb619d856acf4e434810c2ab59c1b/proto/sdk/sdk.proto#L123) and deletion_timestamp could be [Timestamps](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#timestamp), again getting rid of the unnecessary comments about units etc since they are part of the type.

**Describe alternatives you've considered**
Just leaving the protobuffers as they are.

**Additional context**
Our agones Rust client [wraps](https://github.com/EmbarkStudios/rymder/blob/main/src/sdk/gameserver.rs) the `GameServer` messages so that we can get precise types that inform users at a type level what things are.

**Comment by roberthbailey** [comment]
@markmandel - These seem like valid suggestions, but we'd have to think about how to do them in a backward compatible way.

**Comment by markmandel** [comment]
Some thoughts:

1. Yep, very valid suggestions. Hindsight on things you know now, vs what you knew then is always 20/20 😄 
2. "GameServer.spec.health.period_seconds" - I would argue that it probably stay as an integer. the CRDs don't have the idea of a Duration, so the smallest unit of measure of time is a second. Making this as a duration might indicate that it can handle sub-second timespans.
3. I've no idea how we could do this while maintaining backward compatibility 😬 
4. For the Rust SDK specifically, I would posit we could translate to a better type system in the layer between generated Rust and the hand written SDK for better ergonomics (we do that in a few places).
