### ISSUE TITLE
How to  connect gRPC gameserver?

### ISSUE THREAD

**Issue by karamaru-alpha** [googleforgames/agones#2267]
**What happened**:
Can't connect gRPC gameserver on GKE.
(I prepared a sample project [here](https://github.com/karamaru-alpha/test-agones))

**How to reproduce it (as minimally and precisely as possible)**:
Please refer to the sample project [REAME.md](https://github.com/karamaru-alpha/test-agones/blob/main/README.md).

#### 1. Create cluster
```
$ gcloud container clusters create test-agones-cluster --cluster-version=1.20 --enable-autoscaling --num-nodes=3 --min-nodes=1 --max-nodes=5 --scopes=gke-default --no-enable-autoupgrade --machine-type=e2-micro --tags=game-server --zone=us-west1-a --node-locations=us-west1-a
```

#### 2. Create firewall
```
$ gcloud compute firewall-rules create game-server-firewall \
  --allow udp:7000-8000 \
  --target-tags game-server \
  --description "Firewall to allow game server udp traffic"
```

#### 3. Get static IP
```
$ gcloud compute addresses create test-agones-ip --region=us-west1
-> ${STATIC_IP}
```

#### 4. Install Agones
```
$ helm repo add agones https://agones.dev/chart/stable
$ helm repo update
$ kubectl create namespace agones-system
$ helm install my-release agones/agones --set "agones.allocator.http.loadBalancerIP=${STATIC_IP}" --namespace agones-system
```

#### 5. Apply fleet(hello gRPC server) and fleetautoscaler ([./agones/](https://github.com/karamaru-alpha/test-agones/tree/main/agones))
```
$ kubectl apply -f ./agones/
```

#### 6. Get ①tls.crt ②tls.key ③tls-ca.crt from secrets
mapping encoded ①~③ in local.
```
$ ls
-> ... tls-ca.crt tls.crt tls.key
```
<img width="800" alt="スクリーンショット 2021-09-18 1 33 29" src="https://user-images.githubusercontent.com/38310693/133823145-58e9b695-a662-4b2e-955e-a1904ae9269a.png">

### 7. Try to access but failing
<img width="978" alt="スクリーンショット 2021-09-18 1 30 22" src="https://user-images.githubusercontent.com/38310693/133822630-0ca16700-db09-461b-9223-361aa7db5e75.png">

**Anything else we need to know?**:

<details><summary>agones-allocator logs</summary><pre>
<img width="1403" alt="スクリーンショット 2021-09-18 1 48 52" src="https://user-images.githubusercontent.com/38310693/133825161-ec4dd476-3a1e-4c08-ac1f-d478da2eb0be.png">
</pre></details>

**Environment**:
- Agones version: 1.17
- Kubernetes version (use `kubectl version`): 1.20+
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm

**Comment by markmandel** [comment]
The tls cert you are using? How is that applied to your gRPC server?

**Comment by markmandel** [comment]
> Looks like your error message complains about TLS handshake error. You probably want to follow the doc here https://agones.dev/site/docs/advanced/allocator-service/#server-tls-certificate if you haven't read it.

I think @karamaru-alpha may have confused the allocation service for their own gRPC based game server?

**Comment by karamaru-alpha** [comment]
@markmandel 

>  The tls cert you are using? How is that applied to your gRPC server?

Should I apply cert to my gRPC gameserver like [this](https://github.com/islishude/grpc-mtls-example/blob/master/server/main.go)?

> I think @karamaru-alpha may have confused the allocation service for their own gRPC based game server.

May be yes...

**Comment by markmandel** [comment]
@karamaru-alpha meta question:

How familiar are you with ssl certificates and how they are written and applied?

**Comment by karamaru-alpha** [comment]
Sorry.
I should have set firewall in order to allow connection on tcp but I forgot it.
Thank you for your time.
