### ISSUE TITLE
Help for Utilizing Agones for Unity

### ISSUE THREAD

**Issue by JeredFig** [googleforgames/agones#2274]
Disclaimer - I have never posted on this site, if there is a format I should have followed I apologize, I was unable to find any guidelines.

There is very little information on the internet in general in setting up a custom Agones server for use with Unity on Google Cloud / GKE. If the website could be updated with any information whatsoever to assist with this or if anyone could put in a word as to how in the world to do this it would be greatly appreciated.

My attempts have involved essentially re-creating the Agones "unity-simple-server" example project hosted on github verbatim (changing as little as possible only to account for any errors) as a new unity project, building a docker image with said project, then creating a gke deployment with a yaml. This continuously leads to to an "Unhealthy" state after many upon many attempts to experiment with changing all factors involved with this process.

If anyone has successfully implemented the Unity SDK via GKE / Google Cloud and could share any info or their experience, it would be greatly appreciated.

Thank you for your time.

Additional note: I AM able to build the following example images provided by Agones for use in gameserver deployments:
gcr.io/agones-images/unity-simple-server:0.3
gcr.io/agones-images/udp-server:0.21
However, they strangely do not invoke the GameServer() method when sending the "GameServer" input from the Client to the Server despite my reading online that this method has been incorporated. This is just an FYI. Thanks.

**Comment by markmandel** [comment]
Thanks for the question:

First step, I want to make sure you go through the [Prerequisite Knowledge](https://agones.dev/site/docs/prerequisite-knowledge/) section of our website, just to make sure we all have the base level of knowledge.

Next step, I would recommend going through out [Troubleshooting: Something went wrong with my GameServer](https://agones.dev/site/docs/guides/troubleshooting/#something-went-wrong-with-my-gameserver) , and see if you can identify what is going wrong for you.

**Comment by JeredFig** [comment]
Thanks Mark.

I reviewed the pre-req knowledge and feel I am knowledgeable enough of this material.

I attempted some troubleshooting, mainly via "kubectl describe gs" and "kubectl describe pod".

These snapshots are examples of the errors I am getting from each command, respectively:

![a](https://user-images.githubusercontent.com/79998088/134572205-a7d967dc-4ce0-4918-98d0-9866f8378100.PNG)

![pod](https://user-images.githubusercontent.com/79998088/134572231-60a19d78-af80-4bd6-ad85-d28d867e28dd.PNG)

I hope this is adequate material to give you insight into what is going on. I'm sorry I'm coming from background of little coding experience from schooling and self-taught experience with C# and Unity over the past year, so attempting to diagnose this on my on is a very big hurdle for me as I feel I am having to learn everything from scratch.

**Comment by markmandel** [comment]
> I'm sorry I'm coming from background of little coding experience from schooling and self-taught experience with C# and Unity over the past year, so attempting to diagnose this on my own is a big hurdle for me as I feel I am having to learn everything from scratch.

That's totally fine, and happy to have you! But I strongly recommend going back through the prerequisite knowledge, and especially go through a bunch of the tutorials to get a good understanding of all the moving pieces. 

Agones is a layer built on top of several other open source projects - so it does require understanding of all the stacks in a row, and it can be a lot. It's not necessarily simple, so (a) don't feel discouraged and (b) this is why we have the prereq section.

I would definitely also recommend going through _all_ of the troubleshooting steps. I can see from the screenshots that there that there is a "restarting failed container" - which leads me to believe your gameserver container is failing. If you go through all the prescribed steps above, I think it will highlight the issue you are having.

As a note, we also have a Slack chat room, if you want to come join us on chat as well.
https://agones.dev/site/community/

**Comment by markmandel** [comment]
Marking as stale as this issue has been dormant for a while

**Comment by markmandel** [comment]
Closing, since no response.
