### ISSUE TITLE
The Documentation/Installation page on old releases shows an incorrect Kubernetes version

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2279]
**What happened**:

During a recent community meeting someone asked the best way to tell which version of Kubernetes is supported by each Agones release. @markmandel suggested looking at the older releases of the website, specifically the https://agones.dev/site/docs/installation/ page, to see what version they suggest.

However, I just checked a few old versions and noticed that they are showing the wrong version of Kubernetes!

From the blog releases, we can see that:
* [1.13.0](https://agones.dev/site/blog/2021/03/16/1.13.0-kubernetes-1.18-websocket-watch-sdk-empty-ports/) added support for Kubernetes 1.18
* [1.16.0](https://agones.dev/site/blog/2021/07/20/1.16.0-kubernetes-1.19-golang-1.15/) added support for Kubernetes 1.19
* [1.17.0](https://agones.dev/site/blog/2021/08/31/1.17.0-kubernetes-1.20-deprecated-required/preferred-add-sync-property-to-fleetautoscaler/) added support for Kubernetes 1.20

However, if you look at the Install documentation for these releases, we see a different story:
* [1.12.0](https://1-12-0.agones.dev/site/docs/installation/) says to use Kubernetes 1.18 (should be 1.17)
* [1.13.0](https://1-13-0.agones.dev/site/docs/installation/) says to use Kubernetes 1.18 (correct)
* [1.14.0](https://1-14-0.agones.dev/site/docs/installation/) says to use Kubernetes 1.18 (correct)
* [1.15.0](https://1-15-0.agones.dev/site/docs/installation/) says to use Kubernetes 1.19 (should be 1.18)
* [1.16.0](https://1-16-0.agones.dev/site/docs/installation/) says to use Kubernetes 1.20 (should be 1.19)

**What you expected to happen**:

I expect that the website for an old release shows the correct Kubernetes version to install for that release.

**Comment by markmandel** [comment]
Huh! That's super wierd!

🤔 I wonder if it's publishing the dev version of the site, which is showing the _next_ supported version.

uuugh - yeah it is: https://github.com/googleforgames/agones/blob/main/site/layouts/shortcodes/k8s-version.html

So we don't publish with env HUGO_ENV=production so we don't have duplicate content on search engines (dev content is set to not be indexable). (This is a docsy setting, which I think [changed recently](https://www.docsy.dev/docs/deployment/#build-environments-and-indexing))

A few thoughts:
1) May be worth updating hugo and docsy with and catch up with the breaking change. But it's not neccessary.
2) Could include a new env var that could be an `or` statement equivalent of: `{{- if or (eq (getenv "HUGO_ENV") "production") (eq (getenv "HUGO_ENV") "snapshot") }}` (as an idea) and replace all the conditionals, and also update the release checklist to set this env var as part of the command.

**Comment by roberthbailey** [comment]
I'm not sure I understand option 1. If we update hugo / docsy are you saying that will fix this for us?

Also, I don't think either option will fix the old releases pages, right? This seems like a good reason to tackle https://github.com/googleforgames/agones/issues/2237 (and we can add a note/warning that the old release docs may show an incorrect version).

**Comment by markmandel** [comment]
> I'm not sure I understand option 1. If we update hugo / docsy are you saying that will fix this for us?

Not separate options, just separate thoughts. Basically that if we are going to make a change, we may want to upgrade the tooling now as we will have to do it later. Not a fix, just saying the work streams might align, but it's not neccessary.

Also, won't fix previous versions - would need to backport the change to release branches and then redeploy.

**Comment by markmandel** [comment]
Adding some extra notes here for reference:
* https://github.com/googleforgames/agones/blob/main/build/includes/website.mk ⬅ where the `make` commands are for running and deploying the site (when fixing, be careful not to deploy to production!)
* The tricky part will be to fix this, without also breaking the deploys that happen on PR ([cloudbuild.yaml](https://github.com/googleforgames/agones/blob/main/cloudbuild.yaml)) and on merge to main ([cloudbuild.yaml](https://github.com/googleforgames/agones/blob/main/site/cloudbuild.yaml))

**Comment by igooch** [comment]
Agones Version | Kubernetes Version (release blog) | Kubernetes Version (installation docs)
-- | -- | --
1.27 | 1.23 | 1.23
1.26 | 1.23 | 1.23
1.25 | 1.22 | 1.22
1.24 | 1.22 | 1.22
1.23 | 1.22 | 1.22
**1.22** | **1.21** | **1.22**
1.21 | 1.21 | 1.21
1.20 | 1.21 | 1.21
1.19 | 1.21 | 1.21
**1.18** | **1.20** | **1.21**
1.17 | 1.20 | 1.20
**1.16** | **1.19** | **1.20**
**1.15** | **1.18** | **1.19**
1.14 | 1.18 | 1.18
1.13 | 1.18 | 1.18
**1.12** | **1.17** | **1.18**
1.11 | 1.17 | 1.17
**1.10** | **1.16** | **1.17**
1.9 | 1.16 | 1.16
1.8 | 1.15 | 1.15
1.7 | 1.15 | 1.15
1.6 | 1.15 | 1.15
**1.5** | **1.14** | **1.15**
1.4 | 1.14 | 1.14
1.3 | 1.13 | 1.13
1.2 | 1.13 | 1.13
1.1 | 1.12 | 1.12
1.0 | 1.12 | 1.12

Incorrect installation documentation under the release specific website are in bold. The non-matching Agones versions are: 1.22, 1.18, 1.16, 1.15, 1.12, 1.10, 1.5.

There are a few exceptions to the pattern where it's publishing the next-supported version of Kubernetes. Pattern exceptions: Agones versions 1.25, 1.8, 1.3, 1.1.

**Comment by markmandel** [comment]
I am wondering if https://github.com/googleforgames/agones/pull/2808 will help here, since @mangalpalli has already done the work to subtract a minor version from the current version -- we could pass that through as the version to actually be reported.

**Comment by igooch** [comment]
> So we don't publish with env HUGO_ENV=production so we don't have duplicate content on search engines (dev content is set to not be indexable). (This is a docsy setting, which I think [changed recently](https://www.docsy.dev/docs/deployment/#build-environments-and-indexing))

Based on the docsy link you listed, it looks like production is the default environment for hugo. I don't see that we're passing any other environment to hugo, unless I'm missing something?

**Comment by markmandel** [comment]
> Based on the docsy link you listed, it looks like production is the default environment for hugo. I don't see that we're passing any other environment to hugo, unless I'm missing something?

No, we don't pass anything else through - my suggestion in https://github.com/googleforgames/agones/issues/2279#issuecomment-930377644 would be to pass a different env values to `HUGO_ENV` and update the `k8s-version.html` shortcode to act on it.

We do now have a specific Make target to be used specifically at release time:

https://github.com/googleforgames/agones/blob/a4caaeb73ce07ce0146e7ed6c83562ed01d1caf4/build/includes/release.mk#L60-L66

So we could add this new variable / value in there and it would get passed all the way through.

This is the cloudbuild script that pushes to production for the canonical production version of the website:

https://github.com/googleforgames/agones/blob/a4caaeb73ce07ce0146e7ed6c83562ed01d1caf4/site/cloudbuild.yaml#L40-L48
