### ISSUE TITLE
CI builds should publish a multi-arch manifest for the agones-sdk image

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2280]
**Is your feature request related to a problem? Please describe.**

Right now our CI system creates linux and windows images for each build for the sidecar (the `agones-sdk` image), e.g. `1.17.0-87c0f7b-windows_amd64-ltsc2019` and `1.17.0-87c0f7b-linux_amd64`. However, we are not creating a multi-arch manifest tagged with the hash, which would look like `1.17.0-87c0f7b`. This means that if you install a release from CI following the instructions  on a pull request like:

To install this version:

* git fetch https://github.com/googleforgames/agones.git pull/xxxx/head:pr_xxxx && git checkout pr_xxxx
* helm install ./install/helm/agones --namespace agones-system --name agones --set agones.image.tag=1.17.0-87c0f7b

you will get a functional controller tagged with `1.17.0-87c0f7b` but the game servers will never become ready because the sidecar won't start. `kubectl logs` will show an error like

`Error from server (BadRequest): container "agones-gameserver-sidecar" in pod "cfg-1-4k2tf-8vd8b" is waiting to start: trying and failing to pull image`

**Describe the solution you'd like**

CI builds should publish a multi-arch manifest for the agones-sdk image so that we can run from a CI build the same way we run release candidates and release builds.

**Comment by roberthbailey** [comment]
I've removed the help wanted label because it looks like this won't be trivial for us to fix. From https://github.com/googleforgames/agones/pull/2037#discussion_r605032311

> I cannot figure out where but regardless GCB doesn't handle manifests all that well.

**Comment by markmandel** [comment]
If you manually push, it can create the multi-arch manifest, but I think if Cloud Build does it, it comes up short.

**Comment by roberthbailey** [comment]
I don't know if it was related to the switch to artifact registry, but when I look at the most recent builds of the agones-controller in `us-docker.pkg.dev/agones-images/ci` I see both arm64 and amd64 builds and a manifest that points to them. And when I look at the agones-sdk I see the windows builds listed in the manifest as well. 

So I'm going to mark this as fixed!
