### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by vaibhavp1964** [googleforgames/agones#2293]
Spelling error in the word - "available" - inside Agones documentation -> Overview -> Major Features. 
<img width="1440" alt="Screenshot 2021-10-06 at 12 00 00 PM" src="https://user-images.githubusercontent.com/5894831/136151756-b88195a9-e9a0-49e6-9c28-4ed409e93e02.png">
"Autoscaling capabilities to ensure players always have a game server availble to play on."

**Comment by roberthbailey** [comment]
Fixed by https://github.com/googleforgames/agones/pull/2294.
