### ISSUE TITLE
Flaky test: fleetautoscaler_test.go

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2296]
A spelling fix for the website failed e2e tests

```
--- FAIL: TestAutoscalerBasicFunctions (350.90s)
    fleetautoscaler_test.go:88: error waiting for fleet condition on fleet simple-fleet-5fxr4
FAIL
```

[Build log](https://console.cloud.google.com/cloud-build/builds/84cb8db2-1a11-4db3-a9e1-d9d51b9baf14?project=258182270954)

**Comment by markmandel** [comment]
I think we can close this now? Seems like we've fixed it!

**Comment by roberthbailey** [comment]
Looks like it.
