### ISSUE TITLE
Flaky test: CPP SDK Conformance tests

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2298]
A lint update that didn't touch the SDKs caused a test failure. 

```
make[2]: *** [run-sdk-conformance-no-build] Error 1
includes/sdk.mk:145: recipe for target 'run-sdk-conformance-no-build' failed
make[1]: *** [run-sdk-conformance-test] Error 2
includes/sdk.mk:152: recipe for target 'run-sdk-conformance-test' failed
includes/sdk.mk:156: recipe for target 'run-sdk-conformance-test-cpp' failed
make: *** [run-sdk-conformance-test-cpp] Error 2
```

[Build log](https://console.cloud.google.com/cloud-build/builds/60c2eed0-da79-4fda-8d27-c69399439db7?project=258182270954)

**Comment by markmandel** [comment]
...so I haven't seen this in a really long time. Ever since we moved the timeout to 40s to give the unit test a bit more room to maneuver.

Shall we close this?

**Comment by roberthbailey** [comment]
Works for me.
