### ISSUE TITLE
Consider using the new github release notes

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2299]
**Is your feature request related to a problem? Please describe.**

We current use the docker container `ferrarimarco/github-changelog-generator` to generate our release notes. It queries the github API for closed issues / merged PRs in the current milestone and generates our [CHANGELOG](https://github.com/googleforgames/agones/blob/main/CHANGELOG.md) which we use as the basis for the release notes in github as well as the blog post (e.g. [1.18.0-rc](https://agones.dev/site/blog/2021/10/05/1.18.0-release-candidate/)). 

Github recently announced that they have a new tool to help generate release notes: https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/

We should investigate their solution and see how it would work for our project. 

**Describe alternatives you've considered**
Keep our current release note generator. One downside of the current process is that the generator sends a large number of requests to the github API, which can fail if you hit throttling / rate limiting while running the tool. It also reviews the entire history of closed issues / merged PRs, which makes it more likely to hit these failures the longer our project exists.

**Comment by gongmax** [comment]
This is already fixed by #3022 , closing
