### ISSUE TITLE
Consider moving agones system images from gcr.io to GCP's artifact registry

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2358]
**Describe the solution you'd like**
GCP's [Artifact Registry](https://cloud.google.com/artifact-registry/) is an alternate way that we can store container images in Google Cloud (we currently store them in Google Container Registry - gcr.io). 

If we put images into the Artifact Registry, we can then take advantage of the recently announced [GKE image streaming for fast application startup and autoscaling](https://cloud.google.com/blog/products/containers-kubernetes/introducing-container-image-streaming-in-gke). This may not be a huge improvement for our linux images (which are pretty small containers) but our windows binaries (the example game server and sdk sidecar) are both pretty large and may see a larger benefit. 

**Describe alternatives you've considered**
* Keep the status quo.
* We can push images to both locations during a migration period.

**Comment by roberthbailey** [comment]
@markmandel reminded me that some of our example images are larger and we might see a more obvious benefit.  [Xonotic](https://github.com/googleforgames/agones/tree/main/examples/xonotic) is 1.9GB and [Supertuxkart](https://github.com/googleforgames/agones/tree/main/examples/supertuxkart) is 1.5GB.

**Comment by markmandel** [comment]
One advantage to Artifact registry is that you can have multiple registries. Right now we store dev images and production images in the same registry, because gcr.io only has the one.

This would make cleanup and management of dev images much safer, as we could have them in separate registries.

**Comment by markmandel** [comment]
Next, let's make copes of the `examples` images to artifact registry, and update our example yaml files, since CI and examples are the least risk.

**Comment by gongmax** [comment]
Example images has been moved to GAR: #2823
Reopen since we still need to move the "`release` for actual Agones releases"
