### ISSUE TITLE
Consider moving npm packages to GCP's artifact registry

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2359]
**Describe the solution you'd like**
GCP's [Artifact Registry](https://cloud.google.com/artifact-registry/) is an alternate way that we can store npm packages images in Google Cloud (we currently store them at https://www.npmjs.com/package/@google-cloud/agones-sdk). 

https://cloud.google.com/artifact-registry/docs/nodejs/quickstart describes how to get started. 

**Describe alternatives you've considered**
* Keep the status quo. 
* Store the packages in both locations during a migration period

**Comment by roberthbailey** [comment]
@steven-supersolid - I'm not familiar enough with the nodejs ecosystem to know if this is a terrible idea - do you think that the Artifact Registry is more intended for private packages and that our current npm package location makes more sense for the SDK?

**Comment by steven-supersolid** [comment]
I'd not seen the Artifact Registry before but yes it looks really well suited to private packages (good to see Maven support too). In the Node.js ecosystem the primary source of packages is npm so this is where developers will expect to find them without having to do any additional config, e.g. it's handy to find this in npm https://www.npmjs.com/package/@google-cloud/logging

**Comment by markmandel** [comment]
> In the Node.js ecosystem the primary source of packages is npm so this is where developers will expect to find them without having to do any additional config, e.g. it's handy to find this in npm https://www.npmjs.com/package/@google-cloud/logging

Pretty sure this is the same reason we moved off Github packages - it's just much easier for the end users to use npm as the package repository for NodeJs.

**Comment by roberthbailey** [comment]
Makes sense. I'll go ahead and close this.
