### ISSUE TITLE
panic in simple-game-server on second UNHEALTHY message

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2366]
**What happened**:

```
panic: close of closed channel

goroutine 24 [running]:
main.handleResponse({0xc00038c0b0, 0x9}, 0xc00009af08, 0xc000294870)
	/go/src/simple-game-server/main.go:153 +0x4f5
main.udpReadWriteLoop({0x8d83b0, 0xc0002ac040}, 0xc0002d2150, 0x83fde2)
	/go/src/simple-game-server/main.go:280 +0x117
main.udpListener(0xc00018a7b0, 0x6e18a6, 0xc0002d0000)
	/go/src/simple-game-server/main.go:270 +0x15f
created by main.main
	/go/src/simple-game-server/main.go:106 +0x725
```

First message of `UNHEALTHY` will stop sending Health checks. The second message of `UNHEALTHY` will cause the above panic and crash the `simple-game-server`

**What you expected to happen**:

If the `simple-game-server` has already stopped health pings, then the second message should be a no-op and not panic.

**How to reproduce it (as minimally and precisely as possible)**:

This showed up in a retry of the message sent to `TestHealthCheckDisable`.

**Anything else we need to know?**:

Line in question: https://github.com/googleforgames/agones/blob/main/examples/simple-game-server/main.go#L158

(I think some recent development has pushed things down slightly).

Suggestion: 
We could use a cancellable Context rather than a channel and it would solve this issue, as " After the first call, subsequent calls to a CancelFunc do nothing."

**Environment**:
- Agones version: dev
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):

https://console.cloud.google.com/cloud-build/builds/e34a1d12-45cb-4659-8660-0f7a292384df?project=258182270954
https://cloudlogging.app.goo.gl/KP6zxrc4onTZ5wL77

![image](https://user-images.githubusercontent.com/298370/141224633-f28f2fc9-a5a9-4e54-acce-21aeb64165a0.png)

- Others: N/A

**Comment by roberthbailey** [comment]
Culprit: https://github.com/googleforgames/agones/blob/main/examples/simple-game-server/main.go#L157-L158
