### ISSUE TITLE
Request Releaser role for Agones Repository

### ISSUE THREAD

**Issue by SaitejaTamma** [googleforgames/agones#2368]
### GitHub SaiTejaTamma
 @SaiTejaTamma

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have read the [contributor guide](../../../CONTRIBUTING.md)
- [x] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roberthbailey 
- @markmandel 

### List of contributions to the Agones project
- PRs reviewed / authored
    - https://github.com/googleforgames/agones/pull/2365
    - https://github.com/googleforgames/agones/pull/2362
    - https://github.com/googleforgames/agones/pull/2353
    - https://github.com/googleforgames/agones/pull/2345
- Issues responded to

**Comment by markmandel** [comment]
APPROVED!

**Comment by roberthbailey** [comment]
+1

**Comment by markmandel** [comment]
Done! Teja now has the requisite permissions needed to do this task! 👍🏻
