### ISSUE TITLE
Remove < Ready GameServers first when scaling down on the same node

### ISSUE THREAD

**Issue by highlyunavailable** [googleforgames/agones#2372]
**Is your feature request related to a problem? Please describe.**

I would like the Game Server de-scheduling logic to be more accurate based on GS states or tune-able in the context of a single node.

Given the following scenario:
1 hot game server exists and 0 sessions exist. A session is requested via the Matchmaker.
The matchmaker creates a GameServerAllocationRequest to set GS1 to `Allocated`
The matchmaker sets the Replicas of the Fleet to 2 (in my case, this could also be done using Fleet Autoscaling)
The Game Server Set starts to spin up GS2 in response to the replica change.

The game happens.

GS1 shuts down.
Since the replicacount is 2, the GSS spins up GS3 to replace GS1.

If the replica count is reduced to 1 as soon as GS1 shuts down because the session count is 0, the GameServerSet would kill the (ready) GS2. New Allocation requests would have to wait for for the brand new GS3 to spin up before GS3 could be allocated.

**Describe the solution you'd like**

The GameServerSet should be aware of the State of the gameserver and when it was created to be able to prioritize which servers are killed first in response to a scale-down request.

See: https://github.com/googleforgames/agones/blob/main/pkg/gameserversets/gameserversets.go#L29

Currently, in the Packed context, only the "fullness" of the node is considered. This is a good metric, but should be expanded on.

Ideally, we would keep Ready servers (to prioritize allocation success). If all servers are Ready, ideally we would terminate in a configurable(?) newest or oldest first manner. If some servers are < Ready (still pending, etc) then they should be removed first to preserve maximum Ready servers.

From Mark:
> when comparing GS's that are > Ready -- my thought was that the longer a GS is around, the more likely something has gone wrong, so better to keep around the newer ones

This is a good call _if_ all servers are ready, and at that point, ordering of which Game Servers to terminate doesn't matter. Maybe continue to kill oldest first, but only once all < Ready servers have been removed.

Whatever solution we land on should also be copied into Distributed downscaling as it makes sense.

**Describe alternatives you've considered**

I've implemented a custom "laggy" replica autoscaler into my matchmaker to work around this issue.

**Additional context**

Slack context: https://agones.slack.com/archives/C9DGM5DS8/p1636751994069400?thread_ts=1636709898.042100&cid=C9DGM5DS8

**Comment by markmandel** [comment]
Will do a proper response next week when I have a moment, but just noting this function will be useful I expect:

https://github.com/googleforgames/agones/blob/849ed6fa2acee72ba6c179283013e19ce73c6b74/pkg/apis/agones/v1/gameserver.go#L535-L552

**Comment by markmandel** [comment]
Huge +1 on this part:

> If some servers are < Ready (still pending, etc) then they should be removed first to preserve maximum Ready servers.

I think that makes straight sense. No point in wasting resources recreating something that is already there.

> If all servers are Ready, ideally we would terminate in a configurable(?) newest or oldest first manner.

I'm less sure on newest/oldest here. I feel like this may depend on each type of game 🤔 

My thought: Let's do the prioritisation of removal of `< Ready` GameServers when sorting within a single node, and see how that impact things. If we need more optimisation from there (i.e. oldest vs newest), we can revisit. My intuition is that time alive won't actually matter on scale down, but I'd like to see some real world consequences before drawing a strong conclusion 😄 

How does that sound?

**Comment by highlyunavailable** [comment]
> 
> 
> Huge +1 on this part:
> 
> > If some servers are < Ready (still pending, etc) then they should be removed first to preserve maximum Ready servers.
> 
> I think that makes straight sense. No point in wasting resources recreating something that is already there.
> 
> > If all servers are Ready, ideally we would terminate in a configurable(?) newest or oldest first manner.
> 
> I'm less sure on newest/oldest here. I feel like this may depend on each type of game 🤔
> 
> My thought: Let's do the prioritisation of removal of `< Ready` GameServers when sorting within a single node, and see how that impact things. If we need more optimisation from there (i.e. oldest vs newest), we can revisit. My intuition is that time alive won't actually matter on scale down, but I'd like to see some real world consequences before drawing a strong conclusion 😄
> 
> How does that sound?

My primary driver of newest or oldest was to make it a _very_ clear ordering and priority system rather than "whatever iteration order is" which is partially my problem now. We _do_ have differences: Iteration order implies oldest first right now, HOWEVER for the Distributed packing method, we kill _newest_ first. We should make up our minds and standardize on a single ordering.

However, I am fine with starting out with unready-only to start with. Let's deliver that, then we can consider other additions after we do that.

**Comment by markmandel** [comment]
> My primary driver of newest or oldest was to make it a very clear ordering and priority system rather than "whatever iteration order is" which is partially my problem now. We do have differences: Iteration order implies oldest first right now, 

I'm also trying to find in the code what is making it oldest first for Packed. I haven't been able to find it so far... I'm wondering if that is the order that comes out of a client-go Lister by default???? 🤔 

> HOWEVER for the Distributed packing method, we kill newest first. We should make up our minds and standardize on a single ordering.

Packed and Distributed may well need to have different sorting strategies because they have different optimisation patterns. The easy option for Distributed is to select the newest first, as it's a good enough approximation of randomisation/distribution across the cluster (since they are spun up distributed across the cluster) while also keeping in mind not wasting resources spinning up new GameServers (which we are looking to solve in Packed).

So I don't think we need to align on ordering between the two patterns. They are separate for a reason.

**Comment by highlyunavailable** [comment]
> I'm wondering if that is the order that comes out of a client-go Lister by default????

They're probably stored in insertion order yeah. You have no guarantee this will ever continue to be the case though, but it doesn't matter.

I'm not going to fight over this though! Let's just optimize for keeping as many Readies around no matter what.
