### ISSUE TITLE
error: unable to recognize "dev-gameserver.yaml": no matches for kind "GameServer" in version "agones.dev/v1"

### ISSUE THREAD

**Issue by podluzhnyi** [googleforgames/agones#2375]
I tried to create game server with:
``kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-1.18.0/examples/simple-game-server/gameserver.yaml``
And got error:
``error: unable to recognize "gameserver.yaml": no matches for kind "GameServer" in version "agones.dev/v1"``

This bug was closed here: https://github.com/googleforgames/agones/issues/985 but it is actual

Env:
Mac OS (M1), Minikube v1.24.0, kubectl v1.22.3

**Comment by aLekSer** [comment]
First of all you are running the version which is ahead of supported :
Usage Requirements
Kubernetes cluster version 1.20
https://agones.dev/site/docs/installation/
Could you try with supported version if the issue still persists?

**Comment by aLekSer** [comment]
You should have :
```
 kubectl get crds
NAME                                                   CREATED AT
fleetautoscalers.autoscaling.agones.dev                2021-11-16T13:08:12Z
fleets.agones.dev                                      2021-11-16T13:08:12Z
gameserverallocationpolicies.multicluster.agones.dev   2021-11-16T13:08:12Z
gameservers.agones.dev                                 2021-11-16T13:08:12Z
gameserversets.agones.dev                              2021-11-16T13:08:12Z
```

**Comment by roberthbailey** [comment]
@podluzhnyi - how did you install Agones? It's possible that your install didn't succeed. 

Please take a look at https://agones.dev/site/docs/installation/confirm/ to verify that Agones has been successfully installed.

**Comment by roberthbailey** [comment]
This may be an issue with k8s 1.22 (which we don't yet support and have not tested).

**Comment by markmandel** [comment]
Checking if you resolved this issue? I'm going to mark it as stale since we haven't had a response in a while.

**Comment by markmandel** [comment]
Closing, since no response.
