### ISSUE TITLE
Gameserver allocation error: `the server was unable to return a response in the time allotted`

### ISSUE THREAD

**Issue by iffyio** [googleforgames/agones#2378]
**What happened**:
We recently started seeing the following error show up intermittently when trying to create a `GameServerAllocation` using the go sdk.

```
the server was unable to return a response in the time allotted, but may still be processing the request (post gameserverallocations.allocation.agones.dev)
```

Its not really clear why this started happenning as we hadn't made any changes to agones/client-go/gke. My understanding is that the api server thinks Agones api handler is taking too long to process its request but there are no errors or warnings in the Agones controller either, looking at the allocation controller code, the POST handler seems it runs fine unless there's a chance that it keeps running as usual even after the api server cancels the request? 
Wondering if you folks have any ideas what the issue might be? or if it could be an environment issue?

**What you expected to happen**:
Allocation requests should not timeout

**How to reproduce it (as minimally and precisely as possible)**:
Unclear - the issue shows up suddenly in our clusters (a reinstall of Agones doesn't help)

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.16.0
- Kubernetes version (use `kubectl version`): 1.19 GKE 1.19.14-gke.1900
- Cloud provider or hardware configuration: gke
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Just to confirm, this is the through creating a `GameServerAllocation`, not through the Allocation gRPC/REST service?

I'm fairly sure this is through `GameServerAllocation`, as this is what happenswhen the K8s API can't return a response within the timeout period (I can't remember if it's 30s or 60s these days) when looking to get a response from an `APIService` extension.

Either:
a) Something went wrong with the Agones installation (controller has gone down for example, which runs the webhook this talks to)
b) Something has gone wrong with the K8s control plane.

**Comment by iffyio** [comment]
> Just to confirm, this is the through creating a GameServerAllocation, not through the Allocation gRPC/REST service?

Yes, its creating a `GameServerAllocation` directly via the k8s client

Right, the controller itself _seems_ fine (its definitely not down at least, some requests time out while others go through, no errors/warnings) - so the only things I could think of was there's a chance the controller is hiding the error or its an env issue like something weird with gke (e.g if it really was a time out, I would've expected a context cancelled type error in the controller logs)

**Comment by markmandel** [comment]
🤔 I am genuinely unsure! I'm also not sure if that is an error message that comes out of `client-go` (I assume you are using `client-go`?) - or if it is returned from the k8s api server.

When this happens, does it return to normal? Is it a periodic blip, or once in that state it stops working? (do other interactions with K8s stop working?)

**Comment by iffyio** [comment]
> thinking I am genuinely unsure! I'm also not sure if that is an error message that comes out of client-go (I assume you are using client-go?) - or if it is returned from the k8s api server.

yeah its client-go. I'm not sure either, I've suspected its coming from the api server [since its a 5xx response](https://github.com/kubernetes/kubernetes/blob/1d9d530ee1b672acb9f2ba089123b5350d64dc3b/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L480). It fails partially, some requests succeed immediately while others go through eventually via retries but everything else k8s api wise seems fine

**Comment by iffyio** [comment]
Closing this, since the issue disappeared after we did a GKE upgrade
