### ISSUE TITLE
Update golang version used in App Engine 

### ISSUE THREAD

**Issue by SaitejaTamma** [googleforgames/agones#2382]
**Is your feature request related to a problem? Please describe.**
Update the go runtime used in App Engine for the website. 

**Describe the solution you'd like**
Updating the version of go will remove the warning printed while running `make site-deploy` during the release process. 

**Describe alternatives you've considered**
Ignore the warning until things break.

**Additional context**
`WARNING: Go 1.13 is no longer supported by the Go community as of August 2020. We recommend you to upgrade to the latest version of Go runtime as soon as possible. For details on upgrading, see https://cloud.google.com/appengine/docs/standard/go/runtime.
`

**Comment by markmandel** [comment]
For context: Which make command did you run that resulted in this message?

**Comment by roberthbailey** [comment]
Offending line: https://github.com/googleforgames/agones/blob/ec15511150d26c168d6ffae94be4d25f3fc17f32/site/app.yaml#L15

**Comment by roberthbailey** [comment]
I updated the issue with more context. This happens during the release process while deploying the website.

**Comment by roberthbailey** [comment]
From https://cloud.google.com/appengine/docs/standard/go/runtime it looks like we can choose go 1.12, 1.13, 1.14, 1.15, or 1.16. 

Given that we've been using 1.13 for a long time and it's been deprecated for a year and a half, I think we should jump to 1.16 (unless that breaks something) to give ourselves the maximum amount of time before we need to update again.
