### ISSUE TITLE
use Agones with nodes without external IP's

### ISSUE THREAD

**Issue by freegroup** [googleforgames/agones#2387]
We use https://gardener.cloud to provision our k8s clusters. 

Unfortunately gardener do not provide external IP's for the nodes - no public IP's. We can't reach our nodes via service of type NodePort.

Any way to access a GameServer on a different way? e.g. envoy routing,....

This is not a good use case for "games". But we want to use Agones to scale our REST services with google game service across multiple k8s cluster and regions. We have the very same problems likes games for blue green deployment, availability, scale,....but with a little bit less requirements in the latency. Our hope is, that we can use Agones to scale our business app in the same way :-)

**Comment by markmandel** [comment]
If you don't have direct access to nodes, you will need to use some sort of proxy that is publicly exposed.

Something like [Quilkin](https://github.com/googleforgames/quilkin) for game server UDP traffic, or some kind of Load Balancer (either Kubernetes native, or a different proxy like Envoy, Nginx, etc) for TCP related traffic.

**Comment by freegroup** [comment]
thanks for your support. I will check  Quilkin and https://github.com/Octops/gameserver-ingress-controller . Maybe one of them solves my problem.
