### ISSUE TITLE
Proposal move 1.20.0 release by a week

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2388]
Proposing that we move the 1.20.0 RC and Stable releases by a week.

They are currently on the 28th of December until January 4th respectively, which seems like an inopportune time to do it.

I'd suggest moving all releases by a week, so that RC lands on the 4th of January and then stable the week after that.

The 1.21.0 release should then happen 6 weeks after that as per normal (so we'll need to edit the rest of the releases on the calendar at this point).

**Comment by roberthbailey** [comment]
That sounds great. Since there haven't been any comments in the last 4 days, I've gone ahead and moved the calendar reminders by a week.
