### ISSUE TITLE
generateTLS with lookup of existing secret when using agones chart as dependency

### ISSUE THREAD

**Issue by gorylpe** [googleforgames/agones#2389]
**Is your feature request related to a problem? Please describe.**
I would like to include agones as dependency When using agones as a dependency subchart there is problem as described in [Install agones using Helm](https://agones.dev/site/docs/installation/install-agones/helm/#controller-tls-certificates) with regenerating certs within any `helm upgrade`, even when nothing changes. 

The alternative is to use `certs.sh` and `generateTls: false`, but it is additional step to remember when deploying agones, and pain when using agones as dependency - has to pull dependency independently and extract script from `tgz`.

**Describe the solution you'd like**
There is possibility to use `lookup` template function introduced in `Helm 3.1` to check if secret with cert exists and use it when upgrading.
[Helm issue 3053](https://github.com/helm/helm/issues/3053#issuecomment-782837107)
```
apiVersion: v1
kind: Secret
metadata:
  name: foobar-secret
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace "foobar-secret" }}
data:
  {{- if $previous }}
  foobarPassword: {{ $previous.data.foobarPassword }}
  {{- else if .Values.foobarPassword }}
  foobarPassword: {{ .Values.foobarPassword | b64enc | quote }}
  {{- else }}
  foobarPassword: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
```

**Describe alternatives you've considered**
It is also possible to use annotation `"helm.sh/hook": "pre-install"` as described here [https://medium.com/nuvo-group-tech/move-your-certs-to-helm-4f5f61338aca](https://medium.com/nuvo-group-tech/move-your-certs-to-helm-4f5f61338aca), but it seems to be older solution

**Additional context**

**Comment by roberthbailey** [comment]
That sounds like a useful improvement. Do you have any interest in creating a pull request to implement this enhancement?

**Comment by gorylpe** [comment]
Yes, I could do this within the next week

**Comment by roberthbailey** [comment]
Given that the linked PR has been closed (and not merged) I'm also going to close this issue. Feel free to reopen it if you'd still like to see this feature get added to Agones.
