### ISSUE TITLE
Add documentation for the https://agones.dev/site/docs/advanced/allocator-service/ REST API

### ISSUE THREAD

**Issue by freegroup** [googleforgames/agones#2390]
I want to use the AllocationService but unfortunately I'm unable to find any API (open-api) documentation for the AllocationService. Maybe I miss something.

OpenMatch is using this API - but even on the OpenMatch project I'm unable to find anything how to interact with the AllocationService.

(the CRD's for the k8s API are well documented - perfect)

**Comment by roberthbailey** [comment]
The Allocator Service exposes a gRPC and REST API.

gRPC uses the [protobuf definiton](https://github.com/googleforgames/agones/blob/release-1.19.0/proto/allocation/allocation.proto) (used for gRPC) and we have examples in go and c# that compile it in. 

We also have a [swagger definition](https://github.com/googleforgames/agones/blob/release-1.19.0/pkg/allocation/go/allocation.swagger.json). that you can use for REST. Does that help you out or are you specifically looking for open-api?

**Comment by freegroup** [comment]
This is exactly what I need. Just a pity that this is not mentioned or linked in the documentation. Should be changed - or?

**Comment by roberthbailey** [comment]
A documentation update makes sense. Do you want to put together a pull request?

**Comment by freegroup** [comment]
I will try my hand at it.

**Comment by roberthbailey** [comment]
Based on the diff in your PR, it looks like those two links were already on the allocator service page (way at the bottom in the [API Reference section](https://agones.dev/site/docs/advanced/allocator-service/#api-reference)) but somehow we both missed them.

**Comment by freegroup** [comment]
you are right. One good reason to make this reference a little clearer or more prominent in the documentation.

**Comment by roberthbailey** [comment]
Since the linked PR has been closed as stale, I'm also going to close this tracking ticket. Please feel free to reopen it if you still believe that this should be addressed in the documentation.
