### ISSUE TITLE
Fleet RollingUpdate gets stuck when Fleet has high number of allocated GameServers

### ISSUE THREAD

**Issue by WVerlaek** [googleforgames/agones#2397]
**What happened**:

Fleet rolling update gets stuck when the Fleet continuously gets new allocations and maintains a high number of Allocated GameServers. The old `GameServerSet` doesn't fully scale down and remains up with Ready replicas, such that some allocations keep going to the old GSS.

Context: made a change to the CPU request of a live Fleet (~70% Allocated GameServers) and the update got stuck at two `GameServerSet`s, each having their own buffer of Ready replicas. This also resulted in a ~2x higher buffer of Ready gameservers than specified in the `FleetAutoscaler`. The GameServerSets remained stuck in this state for at least 30-40 minutes, after which the old GSS was manually set to 0 replicas to force it to scale down.

**What you expected to happen**:

A RollingUpdate to complete on a busy Fleet.

**How to reproduce it (as minimally and precisely as possible)**:

* Create `Fleet` with 10 replicas, no `FleetAutoscaler`. 
	* Use default `RollingUpdate` values (25% surge/unavailable).

Get two `GameServerSet`s in a similar state as:

<table>
<tr>
	<td>GSS
	<td>Desired
	<td>Current
	<td>Allocated
	<td>Ready
<tr>
	<td>New (=Active)
	<td>7
	<td>7
	<td>4
	<td>3
<tr>
	<td>Old (=Rest)
	<td>4
	<td>4
	<td>3
	<td>1
</table>

GSSs are stuck in this state, the Ready replicas of the old GSS aren't shut down/replaced by the new GSS. The old GSS keeps Ready replicas up, which get Allocated, causing the GSS's to remain in this state even if gameservers get deallocated/shutdown.

The issue can also be reproduced in the following scenario:
* Again have a fleet of 10 replicas (with supertuxkart)
* Repeatedly allocate a gameserver every 3 seconds
* Shut down the allocated GS after 15s (so on avg, ~5 allocated GS will be up at any time)
* Make an update to the fleet spec to trigger a RollingUpdate
* Old GSS never shuts down, and keeps serving allocation requests

**Anything else we need to know?**:

Could reproduce in Agones 1.16 with `RollingUpdateOnReady` disabled, although needed a higher amount of Allocated GameServers to get the rolling update to get stuck.

**Environment**:
- Agones version: 1.18
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): -
- Others: -

**Comment by WVerlaek** [comment]
Have been looking through the Fleet controller logic for applying rolling updates to GSSs, _think_ it's to do with the scaling logic not handling Allocated gameservers well in determining how much to scale up/down GSSs. 

E.g. in the scenario from above:
<table>
<tr>
	<td>GSS
	<td>Desired
	<td>Current
	<td>Allocated
	<td>Ready
<tr>
	<td>New (=Active)
	<td>7
	<td>7
	<td>4
	<td>3
<tr>
	<td>Old (=Rest)
	<td>4
	<td>4
	<td>3
	<td>1
</table>

in `pkg/fleets/controller.go#rollingUpdateRestFixedOnReady` the amount to scale down the old GSS is `maxScaledDown = allPodsCount - minAvailable - newGSSUnavailablePodCount = 11 - 8 - 4 = -1`, which is `<= 0` so it won't scale down the old GSS any further (https://github.com/googleforgames/agones/blob/main/pkg/fleets/controller.go#L535)

## Potential solution?

in the code above, `newGSSUnavailablePodCount` is calculated as follows:
```
newGSSUnavailablePodCount := active.Spec.Replicas - active.Status.ReadyReplicas
```
I'm thinking this should also subtract the new GSS's number of Allocated replicas to get the nr of unavailable pods? Something like this:
```
newGSSUnavailablePodCount := active.Spec.Replicas - active.Status.ReadyReplicas - active.Status.AllocatedReplicas
```
That would result in 
```
newGSSUnavailablePodCount := 7 - 3 - 4 = 0
maxScaledDown = allPodsCount - minAvailable - newGSSUnavailablePodCount = 11 - 8 - 0 = 3
```
which would cause the old GSS to be scaled down further.

Not very confident that this is the right solution though, the scaling logic is complex so might easily be missing some edge cases here

**Comment by aLekSer** [comment]
When I was fixing this, I was using Kubernetes original code for Deployments.
https://github.com/kubernetes/kubernetes/blob/770847e6b06d89326f0f2d42c26487cc7f9eae06/pkg/controller/deployment/rolling.go#L129
They have some problems with comments here is my PR trying to fix comments:
https://github.com/kubernetes/kubernetes/pull/92543/files
I might return to this bug later, but left some links with code I was using as a reference so you can also take a look.

**Comment by WVerlaek** [comment]
Thanks for the links, didn't know the logic originates from to the deployment/replicaset rolling update, makes sense! Think the solution above to remove Allocated GameServers from the unavailable count is the right one then.

The main difference between a deployment and a fleet here is that a fleet also has Allocated gameservers, which aren't available, but also not "unavailable" (i.e. these are successfully spun up pods). So probably makes sense to subtract Allocated pods from the number of unavailable pods. Wdyt?

**Comment by markmandel** [comment]
🤔 haven't seen this one myself, but I am wondering if it's related or caused by #2360 - but I am thinking it might be unrelated, as that has to do with shutdowns.

A suggestion for a first step, see if you can replicate it in an e2e test - at least then if there is a draft PR with the failing e2e test (even if it's only sometimes), we can collaborate on a fix (and confirm the issue doesn't happen again).

Maybe something akin to , or part of:
https://github.com/googleforgames/agones/blob/6c92eb0959978cd9388e44131c4e2ef28359a445/test/e2e/fleet_test.go#L734-L740

How does that sound?

**Comment by WVerlaek** [comment]
Don't think it's related to #2360, there's no GS getting stuck in a shutdown state here

Will try to come up with an e2e test 👍

**Comment by WVerlaek** [comment]
@markmandel bit of a delay but managed to reproduce this issue in an e2e test here: https://github.com/googleforgames/agones/pull/2420

**Comment by markmandel** [comment]
@WVerlaek awesome!!!. Look forward to digging into it. I'm focusing on #2385 right now, but will definitely swing past this if someone else doesn't beat me to it.

**Comment by ivotimev** [comment]
@runtarm I believe you are describing a different issue, one which does not require a consistent rate of reservations to occur  and wasn't resolved by https://github.com/googleforgames/agones/pull/2420. I've raised it as a separate issue https://github.com/googleforgames/agones/issues/2574
