### ISSUE TITLE
Display the player count in a column.

### ISSUE THREAD

**Issue by Davidnovarro** [googleforgames/agones#2398]
It's a bit tedious right now to get info about tracked players on the game servers, usually find myself calling "kubernetes describe gs" on each allocated instance just to see how many players are on them.

A nice solution would be to display the player count in a separate column when calling "kubernetes get gs" like this
[https://i.imgur.com/0LwdIqT.png](https://i.imgur.com/0LwdIqT.png)

**Comment by roberthbailey** [comment]
I'm not sure if it's possible with CRDs, but with built in k8s resources you can sometimes see an expanded table if you pass the `-o wide` flag (I like with `kubectl get nodes` or `kubectl get pods`). That might be another way to do this if we don't want to change the default table output.

**Comment by roberthbailey** [comment]
Also note that you can customize your own table output by passing in `-o=custom-columns` so even now in the current state you could create a command to make your own table output with the columns that you care about.

**Comment by cindy52** [comment]
We should be able to add additional printer columns to CRD according to this [pr](https://github.com/openshift/machine-api-operator/pull/148).

**Comment by markmandel** [comment]
Maybe this is something that we could add to a wide output:
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#priority

https://github.com/googleforgames/agones/blob/c3fdf24e8f9ac361d416ce56e23598d84a4dfa5c/install/helm/agones/templates/crds/gameserver.yaml#L40-L55

Implementation wise, would need to work out how to enable the feature flag in the helm template though.


> Also note that you can customize your own table output by passing in `-o=custom-columns` so even now in the current state you could create a command to make your own table output with the columns that you care about.

Heh - I used to do this all the time when doing demos, before you could define your own columned output for CRDs! 😃
