### ISSUE TITLE
0.3 seconds interval required for health check with REST interface

### ISSUE THREAD

**Issue by freegroup** [googleforgames/agones#2401]
I have generated the Swagger definition binding for Python. Which is ok. However the "watch" does not work, because the OpenAPI generator cannot generate streams. Here you have to do it yourself.

The real problem is that with the REST interface I have to choose an extremely small interval for the health check. This is currently 0.3 seconds.

If I set it higher, e.g. 1 second, then the GameServer terminates after a short time. Obviously the SideCar has terminated, because it thinks that it does not get any Health messages in the required timeframe. What surprises me - the gRPC Variant with Go or NodeJS has here a much larger interval. Here are 2 seconds are good to go.

**Comment by roberthbailey** [comment]
Are you defining a non-default value for the `spec.health.periodSeconds` interval?

Health checking is described in https://agones.dev/site/docs/guides/health-checking/#sdk-api and I'm wondering if that documentation helps you at all.

**Comment by freegroup** [comment]
Hi,

yes - the documentation helps a lot and I'm reading it. I know the rtfm :-)

I set the the parameter in the fleet 
```yaml
.
.
.
      health:
        initialDelaySeconds: 20
        periodSeconds: 10
```

But if I increment the period of the health call, the pod get unhealthy and agones remove them. Numbers bigger than 0.7 second do not work.

**Comment by markmandel** [comment]
Random thought: @domgreen when using the Unreal engine integration, you use the REST interface. Do you see the same behaviour?

**Comment by markmandel** [comment]
@freegroup when you use what you expect to work as the interval, can you [turn on debug logging](https://agones.dev/site/docs/guides/troubleshooting/#enable-debug-level-logging-for-the-sdk-server) and show us the output of the sdk sidecar please? I wonder if it will give us some insight into what might be happening here.
