### ISSUE TITLE
unable to set a label with client SDK which contains a "/"

### ISSUE THREAD

**Issue by freegroup** [googleforgames/agones#2406]
I want to set a label for my GameServer like `key='octops-nginx.ingress.kubernetes.io/configuration-snippet'` and `value='return 401;'`

Unfortunately this is not possible because the SDK-Sidecar adds a prefix `agones.dev/sdk-` to all annotations. At this point the annotation key contains two `/`, which is not allowed by k8s.

Any reason why this is done? my assumption was actually that exactly the annotation I specify is set.

https://github.com/googleforgames/agones/blob/e048859c6ff3da0d4b299f915113993aa49c7865/pkg/sdkserver/sdk.go#L25
https://github.com/googleforgames/agones/blob/849ed6fa2acee72ba6c179283013e19ce73c6b74/pkg/sdkserver/sdkserver.go#L395

Error Log from SDK Sidecar
```json
{
   "message":"GameServer.agones.dev \"facedetector-fq6sf-dmmb9\" is invalid: metadata.annotations: Invalid value: \"agones.dev/sdk-octops-nginx.ingress.kubernetes.io/configuration-snippet\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')",
   "severity":"error",
   "time":"2021-12-21T17:17:23.504522919Z"
}
```

**Comment by markmandel** [comment]
This is covered in the documentation: https://agones.dev/site/docs/guides/client-sdks/#setlabelkey-value

> To maintain isolation, the key value is automatically prefixed with the value “agones.dev/sdk-". This is done for two main reasons:

> * The prefix allows the developer to always know if they are accessing or reading a value that could have come, or may be changed by the client SDK. Much like private vs public scope in a programming language, the Agones SDK only gives you access to write to part of the set of labels and annotations that exist on a GameServer.
> * The prefix allows for a smaller attack surface if the GameServer container gets compromised. Since the game container is generally externally exposed, and the Agones project doesn’t control the binary that is run within it, limiting exposure if the game server becomes compromised is worth the extra development friction that comes with having this prefix in place.

**Comment by freegroup** [comment]
thanks for the explanation - sometimes I don't have the big picture view and the attack surface thing is indeed correct. 

I also want to mention how good I think the project is. We already have several scenarios in mind which we want to implement with it. I'm curious how the roadmap of Agones goes on....   :-)
