### ISSUE TITLE
Mac OS With Agones and Minikube

### ISSUE THREAD

**Issue by devprog-dev** [googleforgames/agones#2416]
In Mac OS, udp communication with minikube is not available.
I tried to test using nc -u ip port, but ping with that ip does not work.
https://docs.docker.com/desktop/mac/networking/
It seems that ping does not work in Mac OS.

The nc test also doesn't work.
I opend node port as a service, but I checked that there was no response from udp through minikube.

Is it normal for udp communication not to work through minikube on MacOS?
If do it, please let me know how you did it.

**Comment by roberthbailey** [comment]
@devprog-dev - thanks for filing this issue. 

Have you read through https://agones.dev/site/docs/installation/creating-cluster/minikube/#local-connection-workarounds yet? If nothing there helps, we should make sure to update that section with any new workarounds that we find here.

**Comment by devprog-dev** [comment]
> @devprog-dev - thanks for filing this issue.
> 
> Have you read through https://agones.dev/site/docs/installation/creating-cluster/minikube/#local-connection-workarounds yet? If nothing there helps, we should make sure to update that section with any new workarounds that we find here.
-----------------------------------------------------------------------------------------------------------------

I read already. And I Opened a service NodePort because As I know minikube do not use 'Loadblance'.
I haven't tried other clusters, but minikube seems to need a different explanation. 
Looking at the contents, only the cloud cluster is focused.

I've tried everything I could. 
1. open service node port
2. check firewall
3. Inside the minikube, it was checked that it worked well.
    but, not connect udp.     ex) local pc(mac_os)  -> minikube on local pc(mac_os) 
please need video tutorial on minikube.  not a cloud cluster.

**Comment by roberthbailey** [comment]
Unfortunately I don't have minikube on a mac laptop to try and reproduce your issues. 

I'm wondering what version of MacOS you are running and if you are running on an Intel or M1 chip.

**Comment by roberthbailey** [comment]
Also - what driver are you using? There was a report in slack that using the hyperkit driver (via the --driver flag) worked and the default driver (docker) may not allow udp connectivity.

**Comment by devprog-dev** [comment]
> Unfortunately I don't have minikube on a mac laptop to try and reproduce your issues.
> 
> I'm wondering what version of MacOS you are running and if you are running on an Intel or M1 chip.

I have an Intel chip.
I worked docker driver.

I think , It doesn't seem to work because I'm using docker.

Thanks, Replay.
Happy new year to come. :)

**Comment by markmandel** [comment]
@devprog-dev did you get this working? Just wondering if we can close this issue now?

**Comment by devprog-dev** [comment]
Still not working,

**Comment by XiDianJiale** [comment]
May 19 ,2026:
here macos and minukube ping works well , but cant nc -u 
i have checked kubectl logs and there is no response for this package for sure

the final choice i have made:
run minikube ssh -p agones ,
nc -u <IP> <port>
it respone ACK,  so I test in minukube ssh

plus i tried minikube tunnel , did not work out though
