### ISSUE TITLE
DiscoveryCheck and Webhook failures on GKE

### ISSUE THREAD

**Issue by samvanryssegem-qz** [googleforgames/agones#2428]
**Environment**:
- Agones version: 1.19
- Kubernetes version (use `kubectl version`): v1.21.5-gke.1302
- Cloud provider or hardware configuration: GCP
- Install method (yaml/helm): helm/argocd

I've installed Agones on GKE using argo cd, but it looks like the controller service is failing to come up.

running `kubectl get pods --namespace agones-system` outputs
`NAME                                 READY   STATUS    RESTARTS   AGE`
`agones-allocator-6fc76c6cbf-gcb98    1/1     Running   0          155m`
`agones-allocator-6fc76c6cbf-gsngf    1/1     Running   0          155m`
`agones-allocator-6fc76c6cbf-mpwbs    1/1     Running   0          155m`
`agones-controller-6bd75b6c9b-s8tmz   1/1     Running   0          155m`
`agones-ping-8759bb58c-4hkxr          1/1     Running   0          3h41m`
`agones-ping-8759bb58c-x8g26          1/1     Running   0          3h41m`

but argo is pointing out this on the controller
`FailedDiscoveryCheck: failing or missing response from https://10.180.64.202:8081/apis/allocation.agones.dev/v1: Get "https://10.180.64.202:8081/apis/allocation.agones.dev/v1": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`

when trying to stand a gameserver up it fails with the following message
`_Internal error occurred: failed calling webhook "mutations.agones.dev": Post "https://agones-controller-service.agones-system.svc:443/mutate?timeout=10s": dial tcp 10.180.64.202:8081: i/o timeout_
`

**Comment by samvanryssegem-qz** [comment]
Controller logs:
> {"filename":"/home/agones/logs/agones-controller-20220113_190945.log","message":"logging to file","numbackups":99,"severity":"info","source":"main","time":"2022-01-13T19:09:45.744820987Z"}
{"logLevel":"info","message":"Setting LogLevel configuration","severity":"info","source":"main","time":"2022-01-13T19:09:45.744868034Z"}
{"ctlConf":{"MinPort":7000,"MaxPort":8000,"SidecarImage":"gcr.io/agones-images/agones-sdk:1.19.0","SidecarCPURequest":"30m","SidecarCPULimit":"0","SidecarMemoryRequest":"0","SidecarMemoryLimit":"0","SdkServiceAccount":"agones-sdk","AlwaysPullSidecar":false,"PrometheusMetrics":false,"Stackdriver":false,"StackdriverLabels":"","KeyFile":"/home/agones/certs/server.key","CertFile":"/home/agones/certs/server.crt","KubeConfig":"","GCPProjectID":"","NumWorkers":100,"APIServerSustainedQPS":400,"APIServerBurstQPS":500,"LogDir":"/home/agones/logs","LogLevel":"info","LogSizeLimitMB":10000},"featureGates":"CustomFasSyncInterval=false\u0026Example=true\u0026NodeExternalDNS=true\u0026PlayerAllocationFilter=false\u0026PlayerTracking=false\u0026SDKGracefulTermination=false\u0026StateAllocationFilter=true","message":"starting gameServer operator...","severity":"info","source":"main","time":"2022-01-13T19:09:45.745040449Z","version":"1.19.0"}
W0113 19:09:45.745188       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"maxPort":8000,"message":"Starting","minPort":7000,"severity":"info","source":"*gameservers.PortAllocator","time":"2022-01-13T19:09:45.746489323Z"}
{"groupKind":{"Group":"agones.dev","Kind":"GameServer"},"message":"Added webhook handler","op":"CREATE","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.74688498Z"}
{"groupKind":{"Group":"agones.dev","Kind":"GameServer"},"message":"Added webhook handler","op":"CREATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.746956508Z"}
{"groupKind":{"Group":"agones.dev","Kind":"GameServerSet"},"message":"Added webhook handler","op":"CREATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.74711486Z"}
{"groupKind":{"Group":"agones.dev","Kind":"GameServerSet"},"message":"Added webhook handler","op":"UPDATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.747155448Z"}
{"groupKind":{"Group":"agones.dev","Kind":"Fleet"},"message":"Added webhook handler","op":"CREATE","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.747261533Z"}
{"groupKind":{"Group":"agones.dev","Kind":"Fleet"},"message":"Added webhook handler","op":"CREATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.747296397Z"}
{"groupKind":{"Group":"agones.dev","Kind":"Fleet"},"message":"Added webhook handler","op":"UPDATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.747316947Z"}
{"groupKind":{"Group":"autoscaling.agones.dev","Kind":"FleetAutoscaler"},"message":"Added webhook handler","op":"CREATE","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.747680437Z"}
{"groupKind":{"Group":"autoscaling.agones.dev","Kind":"FleetAutoscaler"},"message":"Added webhook handler","op":"UPDATE","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.747723173Z"}
{"groupKind":{"Group":"autoscaling.agones.dev","Kind":"FleetAutoscaler"},"message":"Added webhook handler","op":"CREATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.747745887Z"}
{"groupKind":{"Group":"autoscaling.agones.dev","Kind":"FleetAutoscaler"},"message":"Added webhook handler","op":"UPDATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2022-01-13T19:09:45.747771313Z"}
{"message":"Starting http server...","severity":"info","source":"main","time":"2022-01-13T19:09:45.748065508Z"}
{"message":"https server started","server":{"Mux":{}},"severity":"info","source":"*https.Server","time":"2022-01-13T19:09:45.749210398Z"}
{"crd":"fleetautoscalers.autoscaling.agones.dev","message":"custom resource definition established","severity":"info","source":"*fleetautoscalers.Controller","time":"2022-01-13T19:09:45.785615153Z"}
{"message":"Starting workers...","queue":"autoscaling.agones.dev.FleetAutoscalerController","severity":"info","source":"*fleetautoscalers.Controller","time":"2022-01-13T19:09:45.785683296Z","workers":100}
{"crd":"gameserversets.agones.dev","message":"custom resource definition established","severity":"info","source":"*gameserversets.Controller","time":"2022-01-13T19:09:45.84490411Z"}
{"message":"Starting workers...","queue":"agones.dev.GameServerSetController","severity":"info","source":"*gameserversets.Controller","time":"2022-01-13T19:09:45.844976165Z","workers":100}
{"crd":"fleets.agones.dev","message":"custom resource definition established","severity":"info","source":"*fleets.Controller","time":"2022-01-13T19:09:45.849850274Z"}
{"message":"Starting workers...","queue":"agones.dev.FleetController","severity":"info","source":"*fleets.Controller","time":"2022-01-13T19:09:45.849905831Z","workers":100}
{"message":"Starting workers...","queue":"agones.dev.AllocationCache","severity":"info","source":"*gameserverallocations.AllocationCache","time":"2022-01-13T19:09:45.850204765Z","workers":1}
{"crd":"gameservers.agones.dev","message":"custom resource definition established","severity":"info","source":"*gameservers.Controller","time":"2022-01-13T19:09:45.857811038Z"}
{"message":"Starting workers...","queue":"agones.dev.GameServerControllerDeletion","severity":"info","source":"*gameservers.Controller","subqueue":"deletion","time":"2022-01-13T19:09:45.858119617Z","workers":100}
{"message":"Starting workers...","queue":"agones.dev.HealthController","severity":"info","source":"*gameservers.HealthController","time":"2022-01-13T19:09:45.858170258Z","workers":1}
{"message":"Starting workers...","queue":"agones.dev.GameServerController","severity":"info","source":"*gameservers.Controller","time":"2022-01-13T19:09:45.858245648Z","workers":100}
{"message":"Starting workers...","queue":"agones.dev.MigrationController","severity":"info","source":"*gameservers.MigrationController","time":"2022-01-13T19:09:45.858193435Z","workers":1}
{"message":"Starting workers...","queue":"agones.dev.GameServerControllerCreation","severity":"info","source":"*gameservers.Controller","subqueue":"creation","time":"2022-01-13T19:09:45.858307537Z","workers":100}
{"message":"Starting workers...","queue":"agones.dev.MissingPodController","severity":"info","source":"*gameservers.MissingPodController","time":"2022-01-13T19:09:45.858150958Z","workers":1}
2022/01/13 20:51:37 http: TLS handshake error from 10.180.64.203:42702: local error: tls: bad record MAC
2022/01/13 20:51:55 http2: panic serving 10.180.64.203:42802: runtime error: invalid memory address or nil pointer dereference
goroutine 5254 [running]:
net/http.(*http2serverConn).runHandler.func1()
	/usr/local/go/src/net/http/h2_bundle.go:5825 +0x125
panic({0x1807da0, 0x2ac6f40})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
agones.dev/agones/pkg/util/webhooks.(*WebHook).handle(0xc000638ae0, {0x1a5edf2, 0x7}, {0x1cdd6e0, 0xc00119a5a8}, 0xc000d40800)
	/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:88 +0x25b
agones.dev/agones/pkg/util/webhooks.(*WebHook).AddHandler.func1({0x1cdd6e0, 0xc00119a5a8}, 0xc000d40800)
	/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:63 +0x69
net/http.HandlerFunc.ServeHTTP(0xc000601800, {0x1cdd6e0, 0xc00119a5a8}, 0x8)
	/usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc000acfec8, {0x1cdd6e0, 0xc00119a5a8}, 0xc000d40800)
	/usr/local/go/src/net/http/server.go:2424 +0x149
net/http.serverHandler.ServeHTTP({0xc00091b5b0}, {0x1cdd6e0, 0xc00119a5a8}, 0xc000d40800)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.initALPNRequest.ServeHTTP({{0x1ce36b0, 0xc000b1cb10}, 0xc000d82700, {0xc0000301c0}}, {0x1cdd6e0, 0xc00119a5a8}, 0xc000d40800)
	/usr/local/go/src/net/http/server.go:3479 +0x245
net/http.(*http2serverConn).runHandler(0x698dee, 0xc00045cc80, 0x1ce36b0, 0xc000693a40)
	/usr/local/go/src/net/http/h2_bundle.go:5832 +0x78
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5562 +0x510
2022/01/13 20:52:03 http2: panic serving 10.180.64.203:42854: runtime error: invalid memory address or nil pointer dereference
goroutine 5279 [running]:
net/http.(*http2serverConn).runHandler.func1()
	/usr/local/go/src/net/http/h2_bundle.go:5825 +0x125
panic({0x1807da0, 0x2ac6f40})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
agones.dev/agones/pkg/util/webhooks.(*WebHook).handle(0xc000638ae0, {0x1a5edf2, 0x7}, {0x1cdd6e0, 0xc000ada378}, 0xc0004d1d00)
	/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:88 +0x25b
agones.dev/agones/pkg/util/webhooks.(*WebHook).AddHandler.func1({0x1cdd6e0, 0xc000ada378}, 0xc0004d1d00)
	/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:63 +0x69
net/http.HandlerFunc.ServeHTTP(0xc000601800, {0x1cdd6e0, 0xc000ada378}, 0x203000)
	/usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0006c6470, {0x1cdd6e0, 0xc000ada378}, 0xc0004d1d00)
	/usr/local/go/src/net/http/server.go:2424 +0x149
net/http.serverHandler.ServeHTTP({0x0}, {0x1cdd6e0, 0xc000ada378}, 0xc0004d1d00)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.initALPNRequest.ServeHTTP({{0x1ce36b0, 0xc000ae2300}, 0xc000b68700, {0xc0000301c0}}, {0x1cdd6e0, 0xc000ada378}, 0xc0004d1d00)
	/usr/local/go/src/net/http/server.go:3479 +0x245
net/http.(*http2serverConn).runHandler(0x1cada00, 0xc000793fd0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:5832 +0x78
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5562 +0x510
{"error":"error decoding decoding json for path /mutate: EOF","message":"","severity":"error","source":"*webhooks.WebHook","time":"2022-01-13T20:54:35.950487057Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/mutate","RawPath":"","ForceQuery":false,"RawQuery":"timeout=10s","Fragment":"","RawFragment":""}}
{"message":"error decoding decoding json for path /mutate: EOF","severity":"error","stack":["agones.dev/agones/pkg/util/webhooks.(*WebHook).handle\n\t/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:81","agones.dev/agones/pkg/util/webhooks.(*WebHook).AddHandler.func1\n\t/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:63","net/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046","net/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2424","net/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878","net/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3479","net/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5832","runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"],"time":"2022-01-13T20:54:35.950818134Z"}
{"error":"error decoding decoding json for path /mutate: EOF","message":"","severity":"error","source":"*webhooks.WebHook","time":"2022-01-13T20:54:39.517559735Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/mutate","RawPath":"","ForceQuery":false,"RawQuery":"timeout=10s","Fragment":"","RawFragment":""}}
{"message":"error decoding decoding json for path /mutate: EOF","severity":"error","stack":["agones.dev/agones/pkg/util/webhooks.(*WebHook).handle\n\t/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:81","agones.dev/agones/pkg/util/webhooks.(*WebHook).AddHandler.func1\n\t/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:63","net/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046","net/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2424","net/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878","net/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3479","net/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5832","runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"],"time":"2022-01-13T20:54:39.51769666Z"}
{"error":"error decoding decoding json for path /mutate: EOF","message":"","severity":"error","source":"*webhooks.WebHook","time":"2022-01-13T20:55:27.903490058Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/mutate","RawPath":"","ForceQuery":false,"RawQuery":"timeout=10s","Fragment":"","RawFragment":""}}
{"message":"error decoding decoding json for path /mutate: EOF","severity":"error","stack":["agones.dev/agones/pkg/util/webhooks.(*WebHook).handle\n\t/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:81","agones.dev/agones/pkg/util/webhooks.(*WebHook).AddHandler.func1\n\t/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:63","net/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046","net/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2424","net/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878","net/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3479","net/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5832","runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"],"time":"2022-01-13T20:55:27.903637586Z"}
2022/01/13 20:55:30 http2: panic serving 10.180.64.203:44024: runtime error: invalid memory address or nil pointer dereference
goroutine 5465 [running]:
net/http.(*http2serverConn).runHandler.func1()
	/usr/local/go/src/net/http/h2_bundle.go:5825 +0x125
panic({0x1807da0, 0x2ac6f40})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
agones.dev/agones/pkg/util/webhooks.(*WebHook).handle(0xc000638ae0, {0x1a5edf2, 0x7}, {0x1cdd6e0, 0xc000ada170}, 0xc00067d600)
	/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:88 +0x25b
agones.dev/agones/pkg/util/webhooks.(*WebHook).AddHandler.func1({0x1cdd6e0, 0xc000ada170}, 0xc00067d600)
	/go/src/agones.dev/agones/pkg/util/webhooks/webhooks.go:63 +0x69
net/http.HandlerFunc.ServeHTTP(0xc000601800, {0x1cdd6e0, 0xc000ada170}, 0x203001)
	/usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0000db8c8, {0x1cdd6e0, 0xc000ada170}, 0xc00067d600)
	/usr/local/go/src/net/http/server.go:2424 +0x149
net/http.serverHandler.ServeHTTP({0x43e971}, {0x1cdd6e0, 0xc000ada170}, 0xc00067d600)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.initALPNRequest.ServeHTTP({{0x1ce36b0, 0xc000c3b800}, 0xc000d83c00, {0xc0000301c0}}, {0x1cdd6e0, 0xc000ada170}, 0xc00067d600)
	/usr/local/go/src/net/http/server.go:3479 +0x245
net/http.(*http2serverConn).runHandler(0x1cb1940, 0xc0010d87d0, 0x68e0e6, 0xc000692660)
	/usr/local/go/src/net/http/h2_bundle.go:5832 +0x78
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5562 +0x510

**Comment by markmandel** [comment]
To repeat my question before - what happens if you install straight via helm rather than argocd?

Also, do you have anything else installed in the cluster - such as a service mesh?

**Comment by markmandel** [comment]
I'm also noting a lot of "error decoding decoding json for path /mutate" from what looks like:
https://github.com/googleforgames/agones/blob/2723a2590790c6804b004da5373f02637150601c/pkg/util/webhooks/webhooks.go#L78-L82

Seems like something is in there sending weird/intercepting the requests that normally go to the controller from the K8s api?

Not seen this one before.

**Comment by samvanryssegem-qz** [comment]
We wiped agones from our existing cluster and tried to install using helm:

`helm install manual-install --namespace agones-system --create-namespace agones/agones                                                                                     
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1", unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1", unable to recognize "": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1", unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1", unable to recognize "": no matches for kind "PriorityClass" in version "scheduling.k8s.io/v1", unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1"]`

Will try to install on a bare GKE cluster next.

**Comment by markmandel** [comment]
Something very bad has happened to that cluster. I don't know what, but it's gone very, very bad. 👻

**Comment by samvanryssegem-qz** [comment]
Cleared this up by setting firewall rules correctly.
