### ISSUE TITLE
Initial GameServer state is not sent on watch with local SDK server

### ISSUE THREAD

**Issue by Scrayos** [googleforgames/agones#2437]
**What happened**:
The [local SDK server](https://github.com/googleforgames/agones/blob/main/pkg/sdkserver/localsdk.go) that can be used to test and develop client SDKs has a different behaviour than the [original SDK server](https://github.com/googleforgames/agones/blob/main/pkg/sdkserver/sdkserver.go) when it comes to  [WatchGameServer(function(gameserver){…})](https://agones.dev/site/docs/guides/client-sdks/#watchgameserverfunctiongameserver). It does not send the initial state of the GameServer when executing `WatchGameServer` over gRPC.

**What you expected to happen**:
The local SDK server should also send the initial state so that integration tests can check that this behaviour is supported. This is especially important since https://github.com/googleforgames/agones/pull/2353 (SDKWatchSendOnExecute) was merged. Currently the integration test is failing because only real updates will be sent.

The difference in the code can be seen here:
SDKServer (Original): https://github.com/googleforgames/agones/blob/main/pkg/sdkserver/sdkserver.go#L528
LocalSDKServer (Local Testing): https://github.com/googleforgames/agones/blob/main/pkg/sdkserver/localsdk.go#L336

**How to reproduce it (as minimally and precisely as possible)**:
1. Start the Agones SDK docker image (`gcr.io/agones-images/agones-sdk:1.20.0`) with `--local`
2. Invoke `WatchGameServer(function(gameserver){…})` within the Sdk service
3. See that no initial GameServer state will be sent (even after some wait)

**Anything else we need to know?**:
Everything else seems to be working according to the documentation. This should be aligned as well (it was even more confusing because it was mentioned within the [SDK documentation](https://1-18-0.agones.dev/site/docs/guides/client-sdks/#watchgameserverfunctiongameserver) until 1.19 \[search for `SDKWatchSendOnExecute`\]).

**Environment**:
- Agones version: 1.20
- Kubernetes version,  cloud provider etc. don't apply because it's for local development

**Comment by markmandel** [comment]
Ah, that is an excellent catch! That's a valid bug we should fix.
