### ISSUE TITLE
Release Automation: Create a script to set versions on the calendar

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2454]
**Is your feature request related to a problem? Please describe.**
Right now there is a step in the [release process](https://github.com/googleforgames/agones/blob/main/docs/governance/templates/release_issue.md):

- [ ] Ensure the next RC and stable releases in the Google Calendar have the correct version number.

and a pre-requisite:

- [ ] Edit access to the [Agones Release Calendar](https://calendar.google.com/calendar/u/0?cid=Z29vZ2xlLmNvbV84MjhuOGYxOGhmYnRyczR2dTRoMXNrczIxOEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

**Describe the solution you'd like**
Instead of manually updating the calendar each release, we should write a script to set the versions going forward automatically. Mark said he thought apps script would be a good way to do this.

**Comment by markmandel** [comment]
@Kalaiselvi84 @geetachavan1 WDYT, do we still want to do this? Or is manually changing the next release in the calendar fine?

**Comment by Kalaiselvi84** [comment]
@markmandel, Does the script need to be run just once?

**Comment by markmandel** [comment]
Good Question - probably yes 😄 I'm sure 10 years of releases would do the job 😁

**Comment by Kalaiselvi84** [comment]
sounds good! will work on it👍🏻

**Comment by markmandel** [comment]
Save a step on the release checklist 😄
