### ISSUE TITLE
Update from golang/protobuf to google.golang.org/protobuf

### ISSUE THREAD

**Issue by JohnnyS318** [googleforgames/agones#2462]
**Is your feature request related to a problem? Please describe.**
I am trying building my project with bazel and there is a problem with the go package github.com/golang/protobuf that is imported implicitly by agones. I know this isn't the place for this issue, but i think it is stil relevant because github.com/golang/protobuf is deprecated in favour of the new google.golang.org/protobuf package. This isn't even a feature nor is it a bug with agones

**Describe the solution you'd like**
Upgrade to the new golang.org/protobuf package. I know that the old was superseeded with a new api but i don't know the effort to convert.

**Describe alternatives you've considered**
Building with the standard go compiler still runs fine.

**Additional context**
None

**Comment by markmandel** [comment]
🤔 Do we know which library is bringing in that package? I assume it's gRPC? And if so, do we know which version that gRPC switched over to the newer `protobuf` package?

**Comment by JohnnyS318** [comment]
I think it's because we use the github.com/golang/protobuf/protoc-gen-go tool in tools.go. In grpc [quickstart](https://grpc.io/docs/languages/go/quickstart/) it looks like the new package has a similar compiler

**Comment by JohnnyS318** [comment]
```sh 
$ go mod why -m github.com/golang/protobuf
# github.com/golang/protobuf
agones.dev/agones/pkg/allocation/go
github.com/golang/protobuf/descriptor
```

So it seems like no other dependency is used, but the api chaned quite a bit (e.g. ptypes removed and changed to types) e.g. Though it should have feature parity.I will try to convert it on my fork and see how it goes...

**Comment by markmandel** [comment]
Let us know how it goes.

`make gen-sdk-grpc` is the target we use to generate grpc code for each SDK.

https://github.com/googleforgames/agones/blob/main/build/README.md#make-gen-sdk-grpc
