### ISSUE TITLE
YAML template parameters?

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2483]
Is there any way to have template parameters for the yaml files, for things like the image version for deploying? Or do we just need to edit the yaml file in the CICD process?

**Comment by markmandel** [comment]
You will want to use Helm if you need to parameterise anything:
https://agones.dev/site/docs/installation/install-agones/helm/

**Comment by roberthbailey** [comment]
If you don't want to use helm to install into your cluster, you can use it to generate a yaml file using the `helm template` command as described in https://agones.dev/site/docs/installation/install-agones/yaml/.

**Comment by emrys90** [comment]
I got it working in bash with this command. It replaces the environment variables in the yaml file, and I set the environment variables in my deploy scripts before running it.
```
(envsubst < ./ci/kubernetes/fleet.yaml | kubectl apply -f - --kubeconfig kubeconfig) || (echo ERROR && exit 1)
```
