### ISSUE TITLE
Failed to build CPP SDK

### ISSUE THREAD

**Issue by junekhan** [googleforgames/agones#2486]
**What happened**:
When I tried building the CPP SDK, I got an error:
```
  /opt/agones-1.21.0/sdks/cpp/build/gRPC/src/src/core/lib/gpr/log_linux.cc:43:13:
  error: ambiguating new declaration of 'long int gettid()'
     43 | static long gettid(void) { return syscall(__NR_gettid); }
        |             ^~~~~~
  In file included from /usr/include/unistd.h:1170,
                   from /opt/agones-1.21.0/sdks/cpp/build/gRPC/src/src/core/lib/gpr/log_linux.cc:41:
  /usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old
  declaration '__pid_t gettid()'
     34 | extern __pid_t gettid (void) __THROW;
        |                ^~~~~~
  make[2]: *** [CMakeFiles/gpr.dir/build.make:232:
```

**What you expected to happen**:
Successfully build.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: 
- v1.21.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by roberthbailey** [comment]
How are you trying to build the SDK? As part of your own project?
