### ISSUE TITLE
Installing Agones creates Linode NodeBalancers. Can this be disabled?

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2488]
I do not require contacting the Agones API from outside of the cluster, so I don't believe I have any need for these, I would like to know if there's a way I can disable this feature so that I am not getting charged for it.

**Comment by roberthbailey** [comment]
Yes. You can customize your install if you use the instructions to install with [helm](https://agones.dev/site/docs/installation/install-agones/helm/). 

That page lists a _ton_ of options, but for what you are asking in particular, `agones.ping.install` can be used to disable the ping service and `agones.allocator.install` can be used to disable the allocator service. Disabling both should prevent the installation from creating any load balancers in your cloud provider.

**Comment by emrys90** [comment]
Thank you! Just got that implemented and I no longer see the load balancers being created.
