### ISSUE TITLE
Upgrade to Kubernetes 1.22

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2494]
List of items to do for upgrading to 1.22:

- [x] Update terraform submodules
  - [x] GKE
  - [x] Azure
  - [x] EKS
- [x] Update prow cluster to use 1.22 (even though we aren't using it yet, we should keep it in sync)
  - [x] Recreate cluster with new scripts: `cd build/terraform/prow; terraform apply -var project=agones-images`
- [x] Update e2e cluster to run against 1.22
  - [x] Recreate cluster with new scripts: `cd build/terraform/e2e; terraform apply -var project=agones-images`
- [x] Update kubectl in dev tooling
  - [x] Update kubectl in `build/build-image/Dockerfile`
  - [x] Update kubectl in `build/e2e-image/Dockerfile`
- [x] Update documentation for creating clusters to 1.22
  - [x] Config.toml `supported_k8s` and related (do `dev_` before main)
- [x] Update the dev tooling to create 1.22 clusters
  - [x] Minikube
  - [x] Kind
- [x] Update client-go
- [x] Update CRD API reference 
  - [x] Update links to k8s documentation in site/assets/templates/crd-doc-config.json
  - [x] Regenerate crd api reference docs - `make gen-api-docs`
- [ ] Regenerate Kubernetes resource includes (e.g. ObjectMeta, PodTemplateSpec)
  - [ ] Start a cluster with `make gcloud-test-cluster`, uninstall agones using `helm uninstall agones -n agones-system`, and then run  `make gen-embedded-openapi` and `make gen-install`

**Comment by 1804devs** [comment]
1. I edited  terraform submodules but i have a older chromebook so i wont be able to run terrform apply etc ..
2. I'll like to work on all 22 issues will i be able to without a ide

**Comment by 1804devs** [comment]
> markmandel

Thanks for reaching back. Im looking into github/ codespace to help . I'll keep you up todate

**Comment by roberthbailey** [comment]
@1804devs - if you are looking for a good issue to get started, you might want to check out the [open issues labeled "good first issue"](https://github.com/googleforgames/agones/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Comment by roberthbailey** [comment]
Trying to recreate the e2e-test-cluster I get the following error from our terraform script:

```
$ terraform apply -var project=agones-images
module.gke_cluster.null_resource.test-setting-variables: Refreshing state... [id=231080905775840212]
module.gke_cluster.google_container_cluster.primary: Refreshing state... [id=projects/agones-images/locations/us-west1-c/clusters/e2e-test-cluster]
helm_release.consul: Refreshing state... [id=consul]
╷
│ Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
│ 
│   with helm_release.consul,
│   on module.tf line 59, in resource "helm_release" "consul":
│   59: resource "helm_release" "consul" {
│ 
```

**Comment by roberthbailey** [comment]
It turns out that it was a red herring. I'd run terraform init / apply before deleting the cluster (to see the diff) and since I had an existing .tfstate file it had cached some information about the current state of the world. After deleting and re-running terraform init things are working as expected.
