### ISSUE TITLE
Add a multi-cluster allocation example solution to leverage GCP resources to connect to multiple Agones clusters

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#2495]
**Is your feature request related to a problem? Please describe.**
Agones has a multi-cluster allocation solution. However, there are two main problems that Agones users are facing adopting it: 

1. Keeping track of multiple clusters and their allocation service IP does not scale. Agones cluster upgrade requires updating matchmaker service to start using the new clusters.
2. Requests from Matchmaker to `agones-allocator` service is complicated as it requires mTLS and therefore certificate management;

**Describe the solution you'd like**
A terraform module that brings up resources in GCP with a proxy that is connected to multiple clusters and redirects allocation requests to clusters. 

As the first step, the solution should be added to the [Agones/examples folder](https://github.com/googleforgames/agones/tree/main/examples) for the community to try it out and collect feedback.

**Comment by tmokmss** [comment]
Hi we also created a Terraform sample to deploy Agones multi-cluster allocation configuration on Amazon EKS. (it's just using multi-allocation as-is though 😅 )
Hope this helps for Agones users :)

https://github.com/aws-samples/multi-cluster-allocation-demo-for-agones-on-eks

**Comment by roberthbailey** [comment]
@tmokmss - Would you be interested in adding a link to that to the agones documentation (so that it doesn't get lost with this issue)? I think putting a link on https://agones.dev/site/docs/third-party-content/libraries-tools/ would make the most sense.

**Comment by roberthbailey** [comment]
This specific issue was fixed by https://github.com/googleforgames/agones/pull/2499

**Comment by tmokmss** [comment]
Hi @roberthbailey, thanks for the offer! I submitted a PR. Hope you can check it when you get a chance.
