### ISSUE TITLE
Support for two values in fleet autoscaler buffer size

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2504]
**Is your feature request related to a problem? Please describe.**
From my understanding, at this time you can specify a minimum fleet buffer size either as a percentage (ie 20% of current capacity), or an absolute value of say 6. The issue I see with this is when the game is smaller, then a percentage value won't always make sense because it would have to be a very large percentage to have a decent number of servers in reserve.

In my case, I'm going to set a buffer size of 6. During off-hours with only having say 5-10 servers online, the percentage would have to be around 50-100% high to reach 6. That percentage would then be far too high during peak hours.

**Describe the solution you'd like**
My proposal would be to support having two buffer size values, and it using whichever is greater. Then I could set an absolute value of 6, and a dynamic value of 20%. Basically this would be setting a floor to the percentage value so it can not be smaller than X.

**Describe alternatives you've considered**
I considered some kind of service I run in the backend that would check number of instances and edit the fleet autoscaler appropriately, but this seems like it would be a useful feature to have as part of Agones.

**Additional context**
I would prefer to be able to use a percentage value so that it scales as the grows larger, but without a floor value for a minimum buffer size, it just won't work well for my needs.

**Comment by roberthbailey** [comment]
That's an interesting idea. I'm curious if you think it's generally applicable or only suited to your use case.

**Comment by emrys90** [comment]
> That's an interesting idea. I'm curious if you think it's generally applicable or only suited to your use case.

I think its applicable to any game that has the possibility to scale from a small number of servers to a larger number. That can happen from most of your player base being in one particular timezone, or from having a sudden spike of new players.

**Comment by markmandel** [comment]
Curious - I take it that `minReplicas` on the [buffer policy](https://agones.dev/site/docs/reference/agones_crd_api_reference/#autoscaling.agones.dev/v1.BufferPolicy) won't do what you need here?

**Comment by emrys90** [comment]
> Curious - I take it that `minReplicas` on the [buffer policy](https://agones.dev/site/docs/reference/agones_crd_api_reference/#autoscaling.agones.dev/v1.BufferPolicy) won't do what you need here?

Min replicas would work for larger games, but for smaller games, it would cost too much extra money. For example, to reach a min buffer size of 6 with 20% that would require 30 servers as the min number of replicas. I plan on setting my minimum to 10.

**Comment by markmandel** [comment]
That's fair.

For now, I would advocate the use of a [webhook](https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/) to power your needs. I'd like to see if we get more people also claiming this is a solution that would work for them, before looking to implement this as a feature.

**Comment by emrys90** [comment]
That's understandable, thanks
