### ISSUE TITLE
Unity SDK should log API failures as errors, and log regardless of logEnabled

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2507]
**Is your feature request related to a problem? Please describe.**
In production it seems like logEnabled should be set to false so you're not getting lots of debug logs. However, API errors are not logged without that enabled, and also they are logged as debug messages instead of using Debug.LogError.

**Describe the solution you'd like**
I would like API failures to be logged using Debug.LogError, and to always be logged instead of conditionally.

**Additional context**
I disabled the debug logging to not clutter the logs, but I had an Allocate API call fail. I have no information on why it failed since the errors aren't logged. So now I have to enable it and hope a repro case happens again to get this resolved in beta testing before releasing to production.

**Comment by emrys90** [comment]
As an additional bit of info on this, it just happened again and here's what Agones logged:
Agones SendRequest failed: /allocate Cannot connect to destination host

Any ideas what could be the issue? The API calls were working correctly a few seconds before the Allocate call

**Comment by roberthbailey** [comment]
This sounds like a great improvement for the unity sdk. Would you be interested in sending a pull request to make the proposed changes?
