### ISSUE TITLE
Randomly unable to connect to a pods API

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2511]
I run a rest server on my game servers. Occasionally a pod will be created that the rest API cannot be called on it, it just times out as if it cannot connect to the server. I've verified its trying to connect to the correct url and port. I do not see any errors in the game server logs. This issue only appears to happen on my Agones game servers, as it does not happen on my production servers that are just running on regular VPS instances. Killing the node its running on gets the issue to go away I believe, maybe the pod too. Haven't checked yet as I still have it running to try and find any debug info needed.

Any ideas on what to check/how to resolve this?

**Comment by roberthbailey** [comment]
To clarify - the rest API is part of your _game server_ container right (not the rest API between game server and sidecar)?

Where are you running Agones? And have you tried running your game server in a container on Kubernetes without Agones (when you say it works fine on VPS instances I'm assuming you mean on VMs directly (without containers or Kubernetes)?

**Comment by emrys90** [comment]
It's part of the game server, its hosted in the Unity game instance. This is running on DigitalOcean. I was previously using Vultr, and not using docker/kubernetes, and never had any issues. Unfortunately there isn't an easy way I can test this outside of Agones as its a rare issue and I have no idea how to reproduce it. Just sometimes a pod is created that is unable to be contacted through its API using the IP address and port assigned.

**Comment by emrys90** [comment]
I do also randomly have issues contacting the sidecar though, but I filed that as a separate issue here:
https://github.com/googleforgames/agones/issues/2507

**Comment by emrys90** [comment]
I have more information now, and the issue seems to be getting weirder. When a server starts up I have it calls its own API, and it returns successfully. I just had this issue happen again to a server an hour ago. I do not see any errors in the server logs. According to Agones the pod has been running for 62 minutes. The first API error was reported 58 minutes ago. So it seems like somehow a few minutes after the pod is created the API randomly stopped working.

Any ideas?

**Comment by roberthbailey** [comment]
>  According to Agones the pod has been running for 62 minutes.

If you look at the pod itself, does it have the same lifetime as Agones reports for the game server? 

> I do not see any errors in the server logs.

This would be expected if there is a connectivity issue (e.g. a firewall or missing route) that would cause the client to not be able to reach the server. Do you have logs from the client & server that you can correlate? As Mark mentioned above, this sounds more like an issue with your Kubernetes environment / cloud provider than with Agones.

**Comment by emrys90** [comment]
Okay so the issue is getting weirder. I have a self health check API that I am pinging every 5 seconds from within the game server using its external ip address and port, and it works every time without error. I cannot call the self health check API from outside the server with the same ip and port though. This is an issue randomly with some pods that are created. Any ideas what that could be?

**Comment by markmandel** [comment]
Just following up on this - did you get this resolved with your cloud provider?

**Comment by emrys90** [comment]
I suspect that its related to the SIGTERM issue on Unity. Once I get that issue fixed I will see if it resolves this issue or not.

**Comment by gongmax** [comment]
Follow up on this - is this still an ongoing issue?

**Comment by emrys90** [comment]
It is, I haven't had time to setup the SIGTERM yet to see if it fixes the issue or not.
