### ISSUE TITLE
Flaky Test: TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2522]
**What happened**: Multiple test failures in CI (including on the 1.22.0 RC pull request)

**What you expected to happen**: Test pass consistently.

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:

Example failure:

```
--- FAIL: TestFleetRollingUpdate (0.00s)
    --- FAIL: TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true (102.40s)
        fleet_test.go:320: 
            	Error Trace:	fleet_test.go:320
            	Error:      	Condition never satisfied
            	Test:       	TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true
FAIL
```

**Comment by markmandel** [comment]
`go test -v -count 100 -run TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true`

To run the test lots of time.

**Comment by markmandel** [comment]
I haven't seen this in a really long time - I think we can close this one?

**Comment by markmandel** [comment]
Closing this, since we haven't seen this in forever.
