### ISSUE TITLE
find a bug in the doc for ue4 plugin

### ISSUE THREAD

**Issue by goace** [googleforgames/agones#2523]
doc url:  https://agones.dev/site/docs/guides/client-sdks/unreal/

"Add Plugin (in your own .uplugin file)" 

SHOUD BE  

"Add Plugin (in your own **.uproject** file)"

**Comment by roberthbailey** [comment]
@goace - Do you want to send a pull request to fix the documentation?

This would be a pretty simple change, but if you need some guidance you can check out https://github.com/googleforgames/agones/blob/main/CONTRIBUTING.md and https://agones.dev/site/docs/contribute/
