### ISSUE TITLE
Foreground deletion of a fleet managed by fleet autoscaler results in infinite pod recreation loop

### ISSUE THREAD

**Issue by estebangarcia** [googleforgames/agones#2524]
**What happened**:

Deleting a fleet managed by a fleet autoscaler with foreground cascading deletion results in an infinite pod recreation loop.

This was found when using ArgoCD to try to manage fleet manifests as it uses foreground deletion of resources.

**What you expected to happen**:

Fleet and all related resources (gameserverset, gameservers, pods) are deleted without recreation.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the following manifest: [fleet.yaml.txt](https://github.com/googleforgames/agones/files/8383060/fleet.yaml.txt)

Then execute:
`$ kubectl delete fleet simple-game-server --cascade=foreground`

Pods will be terminated and recreated indefinitely until the gameserverset is manually removed with background cascading.

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.21.0
- Kubernetes version (use `kubectl version`): 1.21.5
- Cloud provider or hardware configuration: AWS EKS
- Install method (yaml/helm):  Helm

**Comment by roberthbailey** [comment]
I'm not sure we have tested with [foreground cascading deletion](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion); it sounds like it behaves differently enough from [background cascading deletion](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#background-deletion) that it might require some code changes in the agones controller to work properly.

**Comment by estebangarcia** [comment]
I can confirm that without the FleetAutoscaler foreground deletion works fine.

**Comment by estebangarcia** [comment]
I think my statement of an "infinite loop" might not be entirely true, as the fleet at some point got deleted but it took several minutes and there were at least 20 pods recreated during that.

```
Events:
  Type    Reason            Age                   From                      Message
  ----    ------            ----                  ----                      -------
  Normal  SuccessfulCreate  3m5s                  gameserverset-controller  Created gameserver: simple-game-server-xm8hw-lk87w
  Normal  SuccessfulCreate  3m5s                  gameserverset-controller  Created gameserver: simple-game-server-xm8hw-j9xwr
  Normal  SuccessfulCreate  2m25s                 gameserverset-controller  Created gameserver: simple-game-server-xm8hw-lskzw
  Normal  SuccessfulCreate  2m25s                 gameserverset-controller  Created gameserver: simple-game-server-xm8hw-jc9wp
  Normal  SuccessfulCreate  2m25s                 gameserverset-controller  Created gameserver: simple-game-server-xm8hw-55rfp
  Normal  SuccessfulCreate  2m25s                 gameserverset-controller  Created gameserver: simple-game-server-xm8hw-jsc2b
  Normal  SuccessfulCreate  2m25s                 gameserverset-controller  Created gameserver: simple-game-server-xm8hw-cx4ff
  Normal  SuccessfulCreate  2m25s                 gameserverset-controller  Created gameserver: simple-game-server-xm8hw-t6xcv
  Normal  SuccessfulCreate  2m23s                 gameserverset-controller  Created gameserver: simple-game-server-xm8hw-nhfwn
  Normal  SuccessfulCreate  54s (x11 over 2m23s)  gameserverset-controller  (combined from similar events): Created gameserver: simple-game-server-xm8hw-2cbk2
```

**Comment by roberthbailey** [comment]
In that case, is this WAI? I'm curious about the use case for deleting the fleet but not the fleet autoscaler. Are you then replacing that fleet with a new one using the same name and don't want to delete / re-create the fleet autoscaler?

**Comment by estebangarcia** [comment]
Sorry that wasn’t clear in my example. But when I found the issue ArgoCD was deleting the autoscaler as well.

In any case I think that the set shouldn’t recreate/scale while the resource is marked for deletion.
