### ISSUE TITLE
How do fleet autoscalers interact with multi-cluster allocation?

### ISSUE THREAD

**Issue by hach-que** [googleforgames/agones#2525]
I'm trying to figure out if a particular design approach will work before I go down a certain path.

Let's say I have two clusters:
- Cluster A consists of fixed size of bare metal nodes.
- Cluster B consists of a Kubernetes cluster running in the cloud - we want to keep this at 0 node while-ever there remains capacity in Cluster A.

In Cluster A, I set up a GameServerAllocationPolicy to connect it to Cluster B, and I also set up the appropriate certificates/trust. I set cluster B to have a lower priority than cluster A (local).

In Cluster A, I set up a fleet with autoscaling, with a given buffer size. I allocate a bunch of game servers from the fleet in Cluster A, until it starts running low on capacity (i.e. the buffer can no longer be entirely provided for on Cluster A). Does the fleet autoscaler start provisioning game servers on Cluster B to meet the buffer requirements?

**Comment by markmandel** [comment]
There is no cross cluster communication here. 

So you will need Fleet Autoscalers on both clusters to adjust the load as allocations are sent to either, and then each will buffered independently.

So if you want to scale to 0 in the cloud, you will need some kind of monitoring system across your clusters that can identify when you are about to burst, and scale your cloud cluster(s) appropriately to handle the initial load.

(Auto scale to 0 is just hard, so we don't support it out of the box with Agones).

**Comment by markmandel** [comment]
Closing this question, as I believe it was answered.
