### ISSUE TITLE
any eta on unreal 5 sdk ?

### ISSUE THREAD

**Issue by patalbansishashank** [googleforgames/agones#2538]
has anyone started working on unreal 5 sdk ?

**Comment by markmandel** [comment]
Thanks for the inquiry? Have you had any issues integrating our current Unreal SDK?

**Comment by goace** [comment]
It works on UE5. @patalbansishashank

**Comment by markmandel** [comment]
Sounds like this should be an update to our documentation to confirm this, to avoid further confusion.
