### ISSUE TITLE
Disable mTLS for multi cluster.

### ISSUE THREAD

**Issue by dzmitry-lahoda** [googleforgames/agones#2544]
**Is your feature request related to a problem? Please describe.**

Fully disable public IP and mTLS for Allocator, being called and calling. 

**Describe the solution you'd like**

I want a configuration that allows mTLS free multi-cluster allocation. As I see these are not possible now.

**Describe alternatives you've considered**

Enable mTLS. But I dislike it as need to provide different public credentials to cluster, different from what I provide to OpenMatch and Control Plane.

**Additional context**

I will set up a policy using k8s tunnels. So do not need mTLS.

https://agones.slack.com/archives/C9DGM5DS8/p1650033519379489

**Comment by pooneh-m** [comment]
Using [Helm configuration](https://agones.dev/site/docs/installation/install-agones/helm/) you can disable mTLS and change the service type to disable public IP. Here is an example:
```
helm install my-release \
  --set agones.allocator.disableMTLS=true \
  --set agones.allocator.service.serviceType=NodePort 
```

**Comment by dzmitry-lahoda** [comment]
yeah, but as per pr i have seen it does not work with multi cluster. i mean when cluster would allocate on clusterb, i will callit with mtls.

**Comment by pooneh-m** [comment]
Correct. Agones multi-cluster allocation only works with mTLS. There is [another solution](https://github.com/googleforgames/agones/tree/main/examples/allocation-endpoint) that puts a Google Cloud LoadBalancer in front of Agones clusters for mutli-cluster allocation with no mTLS required. It leverages Google Cloud Service Accounts for multi cluster connections and Google issued server TLS for Load Balancer.

**Comment by dzmitry-lahoda** [comment]
As I see allocation policies and allocation requests allow me to choose cluster and fleet to allocate with wights and selector. It is very nice. I get gitops of this and also if agones will improve allocation strategies i will benefit.

Example with endpoints suggests doing manual allocation policies and selectors. I would like to avoid that.

What I ask for disable mTLS for mutlicloud  (i see that policy has non optional mTLS parameters). I will create service and endpoint, but endpoint will be behind wireguard https://www.cncf.io/blog/2021/04/12/simplifying-multi-clusters-in-kubernetes/  and https://kilo.squat.ai/docs/multi-cluster-services/ .
