### ISSUE TITLE
How to move pods when no players online?

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2592]
With autoscaling nodes, I want to keep the total number of servers as low as possible. I have beta servers that frequently have no players online as its just for testing purposes. The issue is that it appears once a pod is up, it stays up. So its possible for pods to be spread across multiple nodes and prevent the nodes from shutting down, when I only need 1 node when all players are offline.

**Comment by markmandel** [comment]
See https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/ for how we pack resources tightly to ensure the least used number of nodes is utilised for exactly this reason.

**Comment by emrys90** [comment]
I don't believe this answers the question. Here's an example scenario of the issue:
Node A has servers A1, A2, and A3. Server A1 gets allocated and node B gets started with server B1. A1 gets terminated and now servers A2, A3, and B1 are still in waiting. Servers do not get moved around after they are started, so now there's permanently 2 nodes up when only 1 is needed, and it stays that way forever until new players come online that use the servers.

**Comment by markmandel** [comment]
You are correct in your assessment, however it is mitigated by the use of a Fleet Autoscaler.

Have a look at: https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/#fleet-scale-down-strategy-1

> **Fleet Scale Down Strategy** 
> With the “Packed” strategy, Fleets will remove Ready GameServers from Nodes with the least number of Ready and Allocated GameServers on them. Attempting to empty Nodes so that they can be safely removed.

**Comment by markmandel** [comment]
Also to note, with a Fleet, A1 is terminated, it will be replaced by a GameServer back on Node A - which will also be priority allocated (since the most items are on that node), and thereby working in conjunction with the Fleet Autoscaler, this also mitigates the issue.

**Comment by emrys90** [comment]
Sorry, but I think this still does not answer the question. I understand as new game servers are spinned up it will even out and nodes will be consolidated, but that only happens if players are online allocating servers. For a beta server that has no one online, then additional nodes that are unneeded are forever in use raising the monthly server hosting costs.

This isn't a theoretical issue I am discussing. It's something I see happening right now on my beta servers.
![image](https://user-images.githubusercontent.com/20632855/169912693-ca88af7d-9ce4-4737-abae-5efdbdfb1086.png)

**Comment by markmandel** [comment]
Gotcha. I would suggest two thing at this point:

1. Use a Fleet Autoscaler (I'm not sure if you are?)
2. Use the webhook system to tie it into your matchmaking system, which I assume would be player aware - and if you haven't got players for that particular beta test for a while, drop your fleet size down to 1 (or even zero).

We've had a few informal chats about having a "cleanup agent" that looks at resource limits per node, and deletes GameServers over time, but that can get really complicated, as we have to essentially recreate having a scheduler - and that's a thing you want to get 100% correct, so it was debatable if the effort was worth it.

**Comment by emrys90** [comment]
Would it not be possible to do something like using kubernetes own system for moving pods around? Something like if you see pods on separate nodes for a while, then mark that pod as being able to be moved. That way you don't have to implement a scheduler like system yourself.

**Comment by markmandel** [comment]
It's not that simple though - you have to look at all your nodes, calculate if there is space, if deleting GameServer would actually make a difference, manage race conditions (because there would be quite a few), make sure you aren't deleting things you shouldn't - because at scale (thousands of GameServers in a cluster), the extra churn can impact throughput, and also potentially slow things down if you are too aggressive and/or GameServer spin up time is slow -- it gets very complicated fast. So a potential optimisation at the smaller scale has pretty broad repercussions at the larger scale.

Hence I would recommend tying your custom scaling to a system that has better insights than Agones has - i.e. your matchmaker, via a webhook system (it's what it's for after all).

**Comment by emrys90** [comment]
Okay thank you.
