### ISSUE TITLE
Any way to handle the SIGTERM for Unity game servers on Linux?

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2594]
From what I am finding online, apparently OnApplicationQuit is not called on Linux when receiving a SIGTERM command. I need to contact my master server when a game server is being shutdown so I can say this server is no longer online.

**Comment by markmandel** [comment]
Best answer I could find: https://sdumetz.github.io/2017/07/01/handle-unix-signals-unity.html

**Comment by emrys90** [comment]
Okay thanks!
