### ISSUE TITLE
Agones controller on update does not restart existing gameservers

### ISSUE THREAD

**Issue by dzmitry-lahoda** [googleforgames/agones#2601]
**What happened**:

1. apply agones 1.22
2. wait gameservers with agones sdk 1.22 running
3. apply agones 1.23
expected: agones tear downs gameservers depending on 1.22 sdk
actual: gameservers pods trying to repeat start with errors because 1.22 sdk image is not existing
notes:
- all application is done via flux + kustomize
- all gameservers run from fleets
- on windows nodes

**What you expected to happen**:
- when contoller of different version of sdk than running game servers, it should run new gameservers and teardown old

**How to reproduce it (as minimally and precisely as possible)**:

Actually see `What happened`. So I can apply new agones and it upgrades nice, but not teardowns old gameservers.

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.22 -> 1.23
- Kubernetes version (use `kubectl version`): 1.23.3
- Cloud provider or hardware configuration: Azure Windows nodes
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s): no logs, I just deleted pods and agones contoller started new correct. without kill, old nodes were running for hour and restarting
- Others:

**Comment by markmandel** [comment]
Worth noting that our current update strategy includes a section on removing all `GameServers` first:
https://agones.dev/site/docs/installation/upgrading/#upgrading-agones-single-cluster

Our helm installation will delete everything on uninstall for this reason as well.

Not sure if this is a bug, maybe a feature?

We've generally tended to shy away from supporting in-cluster updates, because it's a straight nightmare of complexity to test.

**Comment by dzmitry-lahoda** [comment]
yes. you are right. i think in cluster is bad. good it is documented. i think it is not an issue than. so for use. 1. create new cluster. 2. switch gameplay to new cluster. 3. teardown old.

**Comment by dzmitry-lahoda** [comment]
Our pods where not Allocated/Reserved, and not Ready too. In case of Fleet update (example, flux updates image version of gameserver), such gameservers are teared down. Agones is like parent of Fleet and if it essentially updates Fleet (it updates image running inside gameserver) it could behave the way Fleet behaves.

But generally destroying down cluster and launching new one is good as it takes less than 2 hours with all resources for us. And there are other hard to upgrade things.

But overall it could be option to make Agones behave like Fleet in some cases if people not designed for new cluster upgrades.
