### ISSUE TITLE
Add metric for number of reserved replicas in a fleet

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2609]
**Is your feature request related to a problem? Please describe.**
The current metrics for fleets include total game servers, allocated game servers, ready game servers, and desired game servers. Since the reserved game server state was added in https://github.com/googleforgames/agones/pull/766 we haven't updated the metrics to count game servers in this state. 

**Describe the solution you'd like**
Update the `recordFleetReplicas` function to include reserved game servers: https://github.com/googleforgames/agones/blob/418aff0c6a4fdd702c6f0b7ad72f4accc1c0ee91/pkg/metrics/controller.go#L256-L268

**Describe alternatives you've considered**
None. We should totally do this.

**Additional context**
_n/a_

**Comment by govargo** [comment]
I'd like to try this issue.
I'll send PR fot this.

**Comment by roberthbailey** [comment]
Awesome!
