### ISSUE TITLE
Unable to scale fleet if a game server is allocated from an older version

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2617]
**What happened**: Tried to scale a fleet to zero after going through the [Create a Game Server Fleet Quickstart](https://agones.dev/site/docs/getting-started/create-fleet/).

**What you expected to happen**: Fleet to scale to zero.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a fleet
2. Allocate a game server
3. Update the fleet (I changed the container port as per the quickstart guide)
4. Scale the fleet to zero

In step 4 the ready game servers do not disappear. If the allocated game server exits (e.g. by connecting to the simple game server and typing `EXIT`) then the ready game servers disappear immediately.

Logs from the controller:

```
{"error":"error updating replicas for gameserverset for fleet simple-game-server: GameServerSet.agones.dev \"simple-game-server-2jnk7\" is invalid: [spec.replicas: Invalid value: -1: spec.replicas in body should be greater than or equal to 0, .spec.replicas: Invalid value: -1: should be a non-negative integer]","fleetKey":"default/simple-game-server","message":"","queue":"agones.dev.FleetController","severity":"error","source":"*fleets.Controller","time":"2022-06-08T16:46:49.442837332Z"}
{"message":"error updating replicas for gameserverset for fleet simple-game-server: GameServerSet.agones.dev \"simple-game-server-2jnk7\" is invalid: [spec.replicas: Invalid value: -1: spec.replicas in body should be greater than or equal to 0, .spec.replicas: Invalid value: -1: should be a non-negative integer]","severity":"error","stack":["agones.dev/agones/pkg/fleets.(*Controller).upsertGameServerSet\n\t/go/src/agones.dev/agones/pkg/fleets/controller.go:345","agones.dev/agones/pkg/fleets.(*Controller).syncFleet\n\t/go/src/agones.dev/agones/pkg/fleets/controller.go:304","agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).processNextWorkItem\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:180","agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).runWorker\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:156","agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).run.func1\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:215","k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155","k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156","k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133","k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90","agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).run\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:215","runtime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1133"],"time":"2022-06-08T16:46:49.442910812Z"}
```

**Anything else we need to know?**:
This may be the same issue as in https://github.com/googleforgames/agones/issues/2574 but since I hit it with scaling and not rolling update I thought I'd file a separate issue in case other people run across this and are searching for a bug report.

**Environment**:
- Agones version: 1.24.0-aa5bf80 (built from head after 1.23 release)
- Kubernetes version (use `kubectl version`): v1.23.5-gke.2400
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): `make install`
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Going by the logs, this looks like a duplicate of https://github.com/googleforgames/agones/issues/2509 - which I expect @danieloliveira079 's fix to work.

Maybe one of us should take it over?

**Comment by govargo** [comment]
If anyone doesn't work on now, I'd like to contribute this.
Of course, if anyone already works on, I don't add any change.

**Comment by roberthbailey** [comment]
Fixed by https://github.com/googleforgames/agones/pull/2623
