### ISSUE TITLE
The version specification pattern in the Unity SDK installation document does not match the actual release tag

### ISSUE THREAD

**Issue by kt81** [googleforgames/agones#2622]
**What happened**:

When installing the SDK using the Unity Package Manager, I get a "Not found" error when I enter the version specification string according to the [documentation](https://agones.dev/site/docs/guides/client-sdks/unity/#:~:text=If%20you%20want,sdks%2Funity%231.19.0%22%2C).

Added to `manifest.json`:
```
"com.googleforgames.agones": "https://github.com/googleforgames/agones.git?path=/sdks/unity#1.19.0",
```

Result on console:
```
[Package Manager Window] Unable to add package [https://github.com/googleforgames/agones.git?path=/sdks/unity#1.19.0]:
  Could not clone [https://github.com/googleforgames/agones.git]. Revision [1.19.0] could not be found.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

**What you expected to happen**:

Installed specific version of Client Server SDK for Unity.

The example on the document should have the version along with the "**v**" (`v1.19.0`)

**How to reproduce it (as minimally and precisely as possible)**:

Copy the line from the document to `manifest.json` or input `https://github.com/googleforgames/agones.git?path=/sdks/unity#1.19.0` using **Add package from git URL...** in UPM.

**Anything else we need to know?**:

**Environment**:
- Agones version: `>= 1.19.0`
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: 
- Install method (yaml/helm): 
- Troubleshooting guide log(s): 
- Others: `Unity 2020.3.8f1`

**Comment by markmandel** [comment]
If someone goes in and fixes this, would probably be good to use the [shortcode](https://github.com/googleforgames/agones/blob/main/site/layouts/shortcodes/release-version.html) for the [current release version](https://github.com/googleforgames/agones/blob/main/site/layouts/shortcodes/release-version.html), that way it will automatically increment with each release.

**Comment by oniku-2929** [comment]
I'll fix it.
