### ISSUE TITLE
Move CustomFasSyncInterval to Beta

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2646]
**Is your feature request related to a problem? Please describe.**
The "Custom resync period for FleetAutoscaler" feature for the Fleet Autoscaler has been in Alpha since 1.17.0.

It did have some initial stability issues, but have [since been rectified](https://github.com/googleforgames/agones/pull/2422) and has been stable in e2e tests since then.

**Describe the solution you'd like**

Seems like an appropriate time to move to Beta to get some more testing on the feature before moving it to Stable.

**Describe alternatives you've considered**

Remove the functionality, but it seems useful, so I suggest keeping it.

**Additional context**

Original issue: https://github.com/googleforgames/agones/issues/1955
Reference docs: 
* https://agones.dev/site/docs/reference/fleetautoscaler/
* https://agones.dev/site/docs/reference/agones_crd_api_reference/#autoscaling.agones.dev/v1.FleetAutoscaler

**Comment by markmandel** [comment]
Checking with everyone related to the original issue - see how the feature has been going for you? @RY-2718 , @jie-bao, @toVersus?

**Comment by jie-bao** [comment]
The original version in 1.17.0 worked well in my environment. I didn't have a chance to use a later version since I changed my job after that. But I'm glad to see it being moved to Beta if others are happy with it.

**Comment by toVersus** [comment]
Sorry, we (@RY-2718  and I) didn't have time to verify this feature yet, but we are happy to try this feature on latest Agones and give you some feedback. I’m asking our internal team to raise the priority to work on this.
This is not a blocker to move this feature to beta if someone already adopted and satisfied with the current implementation.

**Comment by govargo** [comment]
/assign @govargo 
I'd like to work on this.

**Comment by RY-2718** [comment]
@markmandel @govargo 

Sorry for the late reply, we are working on verifying this feature to give our feedback by the end of July, so it would be appreciated if you could wait for merging the PR (#2654).
We are planning to share our thoughts about the API shape and report back whether the situation is improved by adjusting the resync interval or not.
If we don't give any feedback by the end of July, we don't mind merging the PR (#2654).

**Comment by markmandel** [comment]
🤔 I'm wondering if we need to block on this by end of July?

Reasons being:
1. It's a good feature, so I don't see any reason not to include it.
2. Do we expect the config structure to need to change?

If the resync period works better to your specific use case could be handled totally separately, as if it didn't, we'd have to include a different feature as anyway.

WDYT?

**Comment by toVersus** [comment]
> If the resync period works better to your specific use case could be handled totally separately, as if it didn't, we'd have to include a different feature as anyway.

It totally makes sense. Sorry, we shouldn’t have suggested to block the merging process.
We were wondering if it would be fine to forward the feature stage to beta even if this feature couldn’t resolve the issue we initially reported.
But in response to your comment, we agree that this configuration knob is useful for other users regardless of the result of our verification.

**Comment by markmandel** [comment]
> It totally makes sense. Sorry, we shouldn’t have suggested to block the merging process.

All good! Appreciate your willingness to take it for a spin, and setting expectations appropriately! 😄
