### ISSUE TITLE
Gameserver on Azure Kubernetes stuck on scheduled 

### ISSUE THREAD

**Issue by shafackit** [googleforgames/agones#2657]
**What happened**:

We are trying to deploy our own unity server on Agones.

We first tested on our local Agones instance in WSL. It worked fine and we can get the expected response. Our Unity client also showed that Agones responed OK to our requests.

However, when we try to deploy the same configurations to Azure Kubernetes, the gameservers got stuck at scheduled state and never moves to ready state. This does not happen for the demo official docker images.

| NAME| STATE| ADDRESS| PORT | NODE | AGE
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
|our-fleet-5w62l-p55q6  | Scheduled |  some.ip |  7558 |  aks-nodepool1-number-vmss000001 |  76m
|our-fleet-5w62l-pzt98  | Scheduled  | some.ip |  7599  | aks-nodepool1-number-vmss000001  | 76m
|our-fleet-5w62l-wrxzl  | Scheduled  | some.ip |  7044 |  aks-nodepool1-number-vmss000001  | 76m
|our-server-6qx88     |   Unhealthy  | some.ip |  7631 |  aks-nodepool1-number-vmss000001  | 9m19s

**What you expected to happen**:
Expect server to be at ready state.

**How to reproduce it (as minimally and precisely as possible)**:

We have tried to fix according to possible duplicates, such as increasing health check timeout, re-installing agones. All does not work.

Our Unity server Docker image
```
FROM ubuntu:18.04

WORKDIR /unity

COPY Builds/linux64/ ./

RUN sleep 2

CMD ["./our-server-binary.x86_64", "-batchmode", "-nographics"]
```

Our modified gameserver.yaml
```
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "our-server-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7777
  template:
    spec:
      containers:
      - name: unityserver
        image: image-above-deployed-to-acr
        imagePullPolicy: Always
      imagePullSecrets:
      - name: our-secret
```

Gameserver logs on Azure
```
Defaulted container "agones-gameserver-sidecar" out of: agones-gameserver-sidecar, unityserver
{"ctlConf":{"Address":"localhost","IsLocal":false,"LocalFile":"","Delay":0,"Timeout":0,"Test":"","TestSdkName":"","GRPCPort":9357,"HTTPPort":9358},"featureGates":"CustomFasSyncInterval=false\u0026Example=true\u0026NodeExternalDNS=true\u0026PlayerAllocationFilter=false\u0026PlayerTracking=false\u0026SDKGracefulTermination=false\u0026StateAllocationFilter=false","message":"Starting sdk sidecar","severity":"info","source":"main","time":"2022-07-06T05:06:28.836371289Z","version":"1.24.0"}
{"gsKey":"default/our-server-6qx88","message":"Created GameServer sidecar","severity":"info","source":"*sdkserver.SDKServer","time":"2022-07-06T05:06:28.839662089Z"}
{"grpcEndpoint":"localhost:9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2022-07-06T05:06:28.840493389Z"}
{"httpEndpoint":"localhost:9358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2022-07-06T05:06:28.842493489Z"}
{"gsKey":"default/our-server-6qx88","message":"Starting workers...","queue":"agones.dev.default.our-server-6qx88","severity":"info","source":"*sdkserver.SDKServer","time":"2022-07-06T05:06:28.940068077Z","workers":1}
{"failureCount":1,"gsKey":"default/our-server-6qx88","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2022-07-06T05:06:38.948611032Z"}
{"failureCount":2,"gsKey":"default/our-server-6qx88","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2022-07-06T05:06:43.949113462Z"}
{"failureCount":3,"gsKey":"default/our-server-6qx88","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2022-07-06T05:06:48.950125492Z"}
```

Local gameserver logs
```
user@DESKTOP-G00LFFK:~$ curl -X POST "http://localhost:9358/ready" -H "accept: application/json" -H "Content-Type: application/json" -d "{}"
{}
user@DESKTOP-G00LFFK:~curl -GET "http://localhost:9358/gameserver" -H "accept: application/json"
{"object_meta":{"creation_timestamp":"-62135596800"},"spec":{"health":{}},"status":{"state":"Ready"}}
```

Thank you very much in advance.

**Environment**:
- Agones version: v1.24.0
- Kubernetes version (use `kubectl version`): v1.22.6
- Cloud provider or hardware configuration: Azure
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Please go through our [Troubleshooting Guide](https://agones.dev/site/docs/guides/troubleshooting/) 

Also do you have log debugging on with the Unity SDK, and can see it's output?

**Comment by roberthbailey** [comment]
The logs for the sdkserver look like it's functioning correctly. To echo Mark's comment, I'd suggest following the instructions to "Introspect with Kubernetes tooling" in the troubleshooting guide.

**Comment by shafackit** [comment]
Thank you team. Indeed the pod does not start is because of some bugs found in the docker file.
For our unity server, we need to make sure to add `chmod +x ./unity-server.x86_64`.
Although the server will still marked as unhealthy sometime, the workaround is to disable health check in the k8s yaml file.

I will close the issue. Thanks for the swift support.
