### ISSUE TITLE
Warning in Unreal 5

### ISSUE THREAD

**Issue by abyrd-phx** [googleforgames/agones#2659]
The Agones plugin for Unreal causes a small warning from UnreaBuildTool. It references the HTTP module as a dependency and the case doesn't match. The Agones plugin refers to "Http" and the module is "HTTP".

> Warning		Module 'Http' (referenced via Target -> Agones.Build.cs) has incorrect text case. Did you mean 'HTTP'?	Project	D:\Project\Engine\Intermediate\ProjectFiles\UnrealBuildTool	1

https://github.com/googleforgames/agones/blob/6889d0e9af0fa8f909d94798c7389194393afc5f/sdks/unreal/Agones/Source/Agones/Agones.Build.cs#L27

**Comment by markmandel** [comment]
Just checking:

https://github.com/googleforgames/agones/blob/7080208f0dd0c820e97404fd6826201994545347/sdks/unreal/Agones/Source/Agones/Agones.Build.cs#L27

Closing, as I believe this has been fixed in #2760
