### ISSUE TITLE
Support UDP Load Balancers to allow Agones to work with GKE Autopilot mode

### ISSUE THREAD

**Issue by isaac-mcfadyen** [googleforgames/agones#2687]
**Is your feature request related to a problem? Please describe.**
- Currently, Agones uses Kubernetes' `hostPort` to allocate ports on the nodes themselves.
- This is [incompatible with GKE's Autopilot mode](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#host_options_restrictions), where it manages the nodes for you (and so doesn't allow `hostPort` or `hostNetwork` to be used).
- Autopilot mode is incredibly useful because you are only billed for the resources your pods use (great for indie devs/startups who are prototyping/developing with a low budget). 

**Describe the solution you'd like**
- Instead, there should be a way to enable GCP's GKE UDP Load Balancers to route traffic directly to the required pods without using `hostPort`.

**Describe alternatives you've considered**
- Unsure, not certain about the technical issues around removing/alleviating the `hostPort` requirement in favor of, or together with GCP's Load Balancers.

**Additional context**

**Comment by isaac-mcfadyen** [comment]
Closing as I just noticed https://github.com/googleforgames/agones/issues/2249 which has some comments about why Autopilot will never be possible with Agones.

Sorry about that 🙂

**Comment by markmandel** [comment]
You are right, right now we can't do much to support Autopilot - but as a suggestion, feel free to add a note to the GKE/Autopilot bug tracking system to register your desire to have the features in Autopilot that would enable Agones to work:
https://cloud.google.com/kubernetes-engine/docs/getting-support#bugs_and_frs
