### ISSUE TITLE
Move StateAllocationFilter to Beta

### ISSUE THREAD

**Issue by katsew** [googleforgames/agones#2688]
Let's track down the issues that are blocking the StateAllocationFilter from moving to Beta in here.

**Additional context**

- https://agones.dev/site/docs/guides/feature-stages/#feature-gates
- https://agones.dev/site/docs/integration-patterns/high-density-gameservers/
- https://agones.dev/site/docs/integration-patterns/player-capacity/

**Comment by markmandel** [comment]
So I didn't realise, but `StateAllocationFilter` has been `alpha` since 1.14.0 - which is quite a while!

I've not heard of any issues with it - seems to be working well. So I'm not seeing anything blocking in moving it to beta?

@roberthbailey any thoughts on your end?

**Comment by roberthbailey** [comment]
I had been under the impression that we needed to promote the player tracking feature out of alpha to be able to promote this one but it looks like it is the other way around (player tracking depends on state allocation filtering) and this feature should be promoted first. 

With that understanding, I think it sounds like it's time to get this feature promoted.

**Comment by markmandel** [comment]
Go for it!!!
