### ISSUE TITLE
Unity Alpha SDK Player Tracking responds with 500 codes

### ISSUE THREAD

**Issue by aaronchapin-tocaboca** [googleforgames/agones#2709]
We've been interested in using the Player Tracking feature with our Unity game. I saw that it had become available as part of the Alpha SDK with the latest release, and tried it out. Initial results looked fairly decent - when running with a sidecar locally I could send connect/disconnect messages and they would show up in the logs

<img width="1673" alt="Screen Shot 2022-08-12 at 1 31 06 PM" src="https://user-images.githubusercontent.com/73110636/184348558-e1fc94f0-425a-4f43-83a9-21af162a7cfb.png">

However, on the Unity side these calls were being returned with 500 errors, despite seemingly making it through onto the sidecar.

<img width="628" alt="Screen Shot 2022-08-12 at 1 40 48 PM" src="https://user-images.githubusercontent.com/73110636/184348681-ce4146fb-2001-428e-bc08-204718606b10.png">

Is this normal/expected/part of the Alpha functionality? If so, that's acceptable for now. If not, I may need to dive deeper to find out exactly what is going on.

**What happened**:

The Agones sidecar responded to the Unity Alpha SDK with 500 responses to player connect/disconnect messages

**What you expected to happen**:

For it it respond with a 200 response if the request makes it through to the sidecar.

**How to reproduce it (as minimally and precisely as possible)**:

Send player connect/disconnect messages from a Unity instance to the agones sidecar

**Anything else we need to know?**:

If the answer is just "this is what happens with an alpha feature", that's fine

**Environment**:
- Agones version: 1.25
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): N/A
- Troubleshooting guide log(s): N/A
- Others: Local agones sidecar `sdk-server.darwin.amd64` + local unity gameserver

**Comment by markmandel** [comment]
Is the PlayerTracking feature enabled on the Agones installation on the cluster you are testing on?

**Comment by aaronchapin-tocaboca** [comment]
There wasn't an Agones installation that was being tested. I was just testing the connection between the game server and the sidecar.

**Comment by markmandel** [comment]
How were you doing that?

**Comment by markmandel** [comment]
Closing this issue as Counters and Lists has been released. Please move over to using Counters and Lists - would love you to test the new functionality!
