### ISSUE TITLE
Unity SDK Local Dev Gameserver exception due to name

### ISSUE THREAD

**Issue by aaronchapin-tocaboca** [googleforgames/agones#2710]
**What happened**:

When trying to connect a local gameserver to a local sidecar instance, the connect fails when trying to parse the name of the server

<img width="632" alt="Screen Shot 2022-08-12 at 2 25 06 PM" src="https://user-images.githubusercontent.com/73110636/184354949-48966908-fe9b-4964-8319-20e8770eefdb.png">
<img width="628" alt="Screen Shot 2022-08-12 at 2 25 43 PM" src="https://user-images.githubusercontent.com/73110636/184354973-5d4ab971-1759-459f-bf7f-48c624693211.png">

**What you expected to happen**:

That this doesn't throw an exception

**How to reproduce it (as minimally and precisely as possible)**:

Run a local Unity game server instance with 1.25 SDK, and try to connect to a local sidecar

**Anything else we need to know?**:

I tried when both using the Alpha and the default non-Alpha versions of the SDK

**Environment**:
- Agones version: 1.25
- Kubernetes version (use `kubectl version`): N/A - was local
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): Local
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Just wanted to check if this is still an issue (or did you fix it yourself?) It's been a few years, so wanted to check in.
