### ISSUE TITLE
C# SDK Passing CancellationTokenSource as a constructor argument raises a NullReferenceException.

### ISSUE THREAD

**Issue by g2-ochiai-yuta** [googleforgames/agones#2713]
**What happened**:
```C#
       public AgonesSDK(double requestTimeoutSec = 15.0, SDK.SDKClient sdkClient = null, CancellationTokenSource cancellationTokenSource = null, ILogger logger = null)
        {
            _logger = logger;
            RequestTimeoutSec = requestTimeoutSec;
            if (cancellationTokenSource == null)
            {
                cts = new CancellationTokenSource();
                ownsCts = true;
            }
            else
            {
                ownsCts = false;
            }

            // NullReferenceException is raised because the cts variable is not initialized.
            ctoken = cts.Token;
            channel = new Channel(Host, Port, ChannelCredentials.Insecure);
            client = sdkClient ?? new SDK.SDKClient(channel);
            alpha = new Alpha(channel, requestTimeoutSec, cancellationTokenSource, logger);
        }
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```C#
IAgonesSDK sdk = new AgonesSDK(cancellationTokenSource: new CancellationTokenSource());
```

**Anything else we need to know?**:
https://github.com/googleforgames/agones/commit/60545e03ce3f45a629ab7f05d8000e383c05d4c9
![image](https://user-images.githubusercontent.com/7463440/186244694-7fa0a67b-fe96-4472-995d-30ba51cead37.png)

**Environment**:
- Agones version:  1.25
- Kubernetes version (use `kubectl version`): v1.23.5
- Cloud provider or hardware configuration: local (kind)
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
This was implemented in #2714 - not sure why it's open. Closing.
