### ISSUE TITLE
Access Agones via the Kubernetes API Get Game Server List is Nil.

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [googleforgames/agones#2715]
**What happened**:

```
restConfig, err := k8sio.GetK8sRestConfig()
	if err != nil {
		log.Fatalln("restConfig Error,", err)
	}

	agonesClient, err := agones.GetAgonesClient(restConfig)
	if err != nil {
		log.Fatalln("Could not create the agones api clientset", err)
	}

	serverLists, err := agonesClient.AgonesV1().GameServers("agones-system").List(
		context.TODO(),
		metav1.ListOptions{
			LabelSelector: "",
		},
	)
	if err != nil {
		log.Fatalln("option error,", err)
	}

	log.Println(serverLists)
```

but the log is
```
2022/08/24 11:17:50 &{{ } { 1148934  <nil>} []}
```

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/11493796/186321649-96129229-c997-4022-a294-40d6ad61a57c.png)
I want to get this list 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: agones-1.25.0
- Kubernetes version (use `kubectl version`):  GitVersion:"v1.24.2",
- Cloud provider or hardware configuration:
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
- Others:

**Comment by roberthbailey** [comment]
It looks like you were able to figure this out on your own. Please reopen and add some extra details if you are still encountering this issue.
