### ISSUE TITLE
Helm Agones terraform module crds.CleanupOnDelete setting is missing agones prefix

### ISSUE THREAD

**Issue by john-haven** [googleforgames/agones#2718]
**What happened**:
When installing Agones in a cluster using the [Helm terraform module](https://github.com/googleforgames/agones/blob/release-1.25.0/install/terraform/modules/helm3/), the `crds.CleanupOnDelete` setting is missing the `agones` prefix.

**What you expected to happen**:
The `crds.CleanupOnDelete` setting should have the `agones` prefix.

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Anything else we need to know?**:
The offending line:
<https://github.com/googleforgames/agones/blob/release-1.25.0/install/terraform/modules/helm3/helm.tf#L52>
The docs correctly list the setting as `agones.crds.cleanupOnDelete`:
<https://agones.dev/site/docs/installation/install-agones/helm/#configuration>
And the helm chart itself uses the `agones` prefix for this setting:
<https://github.com/googleforgames/agones/blob/release-1.25.0/install/helm/agones/templates/hooks/pre_delete_hook.yaml#L1>

**Environment**:
- Agones version: `1.25`
- Kubernetes version (use `kubectl version`): `1.22`
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): n/a
- Others: n/a

**Comment by roberthbailey** [comment]
Great catch! Do you want to send a pull request to fix this bug?

**Comment by john-haven** [comment]
Unfortunately I'm not currently able to contribute a PR as I need to get employer authorization first, but if/when that situation changes I would be happy to create a PR.

**Comment by roberthbailey** [comment]
No worries. I've created a PR to fix this.
