### ISSUE TITLE
allow passing Helm values directly to the Terraform module

### ISSUE THREAD

**Issue by rahil-p** [googleforgames/agones#2729]
**Problem**

The Terraform module for Agones has a variable called `values_file`, which allows you to pass a file with custom values for installing the Agones Helm chart.  

When using continuous deployment flows (like Terraform Cloud), it isn't always convenient to pass a file to the module.  For example, with Terraform Cloud's VCS-based workflows, the only way to make this work seems to be pushing locked-in configuration files to version control.

**Solution**

It would be nice to be able to directly pass Helm values as HCL variables to the Agones Terraform module. If I'm not mistaken, I think something like the following should be backward compatible and work:

Variables:
```hcl
variable "values" {
  type = set(object({
    name  = string
    type  = string
    value = string
  }))
  default     = []
  description = "Values to apply to the release"
}

variable "values_sensitive" {
  type = set(object({
    name  = string
    type  = string
    value = string
  }))
  default     = []
  description = "Sensitive values to apply to the release"
}
```

In the `helm_release` resource:
```hcl
dynamic "set" {
  for_each = tolist(var.values)
  iterator = set_item

  content {
    name  = set_item.value.name
    type  = set_item.value.type
    value = set_item.value.value
  }
}

dynamic "set_sensitive" {
  for_each = tolist(var.values_sensitive)

  content {
    name  = set_sensitive.value.name
    type  = set_sensitive.value.type
    value = set_sensitive.value.value
  }
}
```

If this seems like something worth doing, I'll gladly submit a PR.

**Comment by markmandel** [comment]
Sorry about the late reply - if this is something you still want or have written, will gladly take a PR.

**Comment by Pierca7** [comment]
Hey, I created a PR to solve this issue https://github.com/googleforgames/agones/pull/3665
