### ISSUE TITLE
Return game server labels and annotations from allocator service

### ISSUE THREAD

**Issue by austin-space** [googleforgames/agones#2734]
**Is your feature request related to a problem? Please describe.**
When allocating using the allocator api, we would like to get some information provided by the server itself(for example, an auth token that connecting clients should provide on connection). Right now, the allocator only provides the node name, server name, address, and ports so returning any information like that requires subsequently hitting the k8s API to get additional information about the game server.

**Describe the solution you'd like**
The allocator should return the labels and annotations(or even just annotations) of the game server that was allocated. That way we can set annotations(or labels) using the [`SetAnnotation`](https://agones.dev/site/docs/guides/client-sdks/#setannotationkey-value) api provided by the sdk. Also, as repeated fields, these would even be backwards compatible with the current allocator protobuf. 

**Describe alternatives you've considered**
I also saw #2716 which would be amazing, but player tracking is already not represented in the allocator service api, so it's unlikely that the allocator would see any of that anytime soon either. Also, this issue would be more about much more static values needed at connection time that are generated by the game server itself, and that issue seems to be more about values that change relatively often.

**Additional context**
I can probably knock out this change myself, I just wanted to make sure that I wasn't missing something before going off and doing it.

**Comment by markmandel** [comment]
I 99% sure this is duplicate to https://github.com/googleforgames/agones/issues/2396 ? Can you confirm?

Just wanted to check before marking as duplicate and closing.

**Comment by austin-space** [comment]
Yep, dupe. I somehow didn't surface that when looking for duplicates. I'll follow up in that thread.
