### ISSUE TITLE
Will this modify in anyway our current kubernetes?

### ISSUE THREAD

**Issue by satishdsb** [googleforgames/agones#2745]
I see when I was reading config, it looks like modifying our current kubernetes. Please show your light on this. Thanks!

**Comment by zmerlynn** [comment]
Can you perhaps clarify what you mean by "modify our current Kubernetes"?

The installation naturally includes controllers, webhooks, etc, that are custom built for the Agones API objects, but Agones can be installed on any k8s cluster.

**Comment by zmerlynn** [comment]
Hey - please reopen with more details when you get a chance!
