### ISSUE TITLE
[GKE] - Should we enable image streaming everywhere?

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2746]
**Is your feature request related to a problem? Please describe.**

Suggesting that we update our installation guide for GKE, and Terraform scripts to default to using [image streaming](https://cloud.google.com/kubernetes-engine/docs/how-to/image-streaming).

**Describe the solution you'd like**

Update everything to use the node image type of `COS_CONTAINERD` and `enable-image-streaming` on each node in the cluster.

**Describe alternatives you've considered**

Leave it alone, and let user work it out for themselves.

**Additional context**

Came up because we were talking in Slack about large image sizes, and I recommended it as best practice.

**Comment by roberthbailey** [comment]
Our [current instructions for creating a GKE cluster](https://agones.dev/site/docs/installation/creating-cluster/gke/#creating-the-cluster) creates a default node pool with `COS_CONTAINERD` node images - it appears to be the default. So I think we only need to add the flag to enable image streaming.

**Comment by gongmax** [comment]
Seconding Robert's comments, `COS_CONTAINERD` is the [default node images](https://cloud.google.com/kubernetes-engine/docs/how-to/node-images#specifying_a_node_image) since GKE version 1.19
