### ISSUE TITLE
When my fleet scaled up some clients unexpectedly disconnected from the running game server

### ISSUE THREAD

**Issue by andreyshade** [googleforgames/agones#2749]
**What happened**:
When my fleet scaled up some clients unexpectedly disconnected from the running game server. Could anyone give me a clue how to deal with it?

**Environment**:
- Agones version: 1.23
- Kubernetes version (use `kubectl version`): v1.22.12
- Cloud provider or hardware configuration: Amazon EKS

**Comment by markmandel** [comment]
Is this a UDP connection?

**Comment by andreyshade** [comment]
Yes it's UDP connection (running on Unity netcode for gameobjects with Unet transport). I have got an advice to update VPC CNI plugin to latest version and check again. So I will write notes after tests with updated plugin.

**Comment by markmandel** [comment]
I had seen this happen in an older version of Calico, sounds like you may have run into something similar (or the same thing), where any change to the udp routes on the node would drop all connections.

**Comment by andreyshade** [comment]
I have updated VPC CNI plugin on my Amazon EKS to v1.11.4-eksbuild.1 version and disconnects has been disappeared.

**Comment by andreyshade** [comment]
I have updated VPC CNI plugin on my Amazon EKS to v1.11.4-eksbuild.1 version and disconnects has been disappeared. I think we could close this issue, thanks.
