### ISSUE TITLE
Agones running on IBM Cloud Kubernetes Service.

### ISSUE THREAD

**Issue by ddiiwoong** [googleforgames/agones#275]
Hi. I'm cloud native platform engineer in Korea. 

I installed Agones on the IBM Cloud Kubernetes Service (ICKS) and it seems to work fine. 
Also, I have completed the Fleet and fleetallocation deployment test. 
There are some limitations, but I was able to play xonotic with my co-worker.
If you are interested, can I pull request installation guide?

**Comment by markmandel** [comment]
Sounds good. PR away!

**Comment by ddiiwoong** [comment]
Maximum effort!!!

**Comment by thisisnotapril** [comment]
Hi @ddiiwoong; just checking in if you're still interested in this? No pressure; just wanted to close any issues that we weren't focused on still. Let me know if I can help!

**Comment by roberthbailey** [comment]
I'm going to close this since it hasn't been active in a while. But feel free to reopen if you plan to work on it.
