### ISSUE TITLE
Failed to create fleet

### ISSUE THREAD

**Issue by laivu266** [googleforgames/agones#2750]
I installed agones with helm chart. I got the error when creating fleet as below:

**What happened**:
```
Error from server (InternalError): error when creating "fleet.yaml": Internal error occurred: failed calling webhook "mutations.agones.dev": failed to call webhook: Post "https://agones-controller-service.agones-system.svc:443/mutate?timeout=10s": Address is not allowed
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.26.0
- Kubernetes version (use `kubectl version`): 

> Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:36:49Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: EKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
If you `helm ls` in the namespace you installed it in, what do you see?

If you do a `kubectl get pods` and/or `kubectl get services` in the same namespace what do you see?

**Comment by roberthbailey** [comment]
On a working cluster, when I run `kubectl get svc -n agones-system` I see
```
...
agones-controller-service          ClusterIP      10.5.129.186   <none>           443/TCP,8080/TCP   68d
...
```


Also, have you followed the steps to [Confirm installation of Agones](https://agones.dev/site/docs/installation/confirm/)? If so (and you are still seeing this error), then we can look at adding further instructions to that page.

**Comment by laivu266** [comment]
Hi @roberthbailey and @markmandel ,
This is result to confirm installation of agones. As you can see, it's still getting error.
```
➜  ~ kubectl get pods -nagones-system
NAME                                   READY   STATUS      RESTARTS   AGE
agones-allocator-584c9f6d69-d9ct8      1/1     Running     0          2m9s
agones-allocator-584c9f6d69-s6smz      1/1     Running     0          2m8s
agones-allocator-584c9f6d69-vz2zv      1/1     Running     0          2m8s
agones-controller-55d4845b7d-pgs7d     1/1     Running     0          2m8s
agones-delete-agones-resources-6wjq2   0/1     Completed   0          4m24s
agones-ping-c6d4f7747-8dqhz            1/1     Running     0          2m8s
agones-ping-c6d4f7747-kq9lb            1/1     Running     0          2m8s
➜  ~ kubectl get svc -nagones-system
NAME                               TYPE           CLUSTER-IP       EXTERNAL-IP                                                                    PORT(S)            AGE
agones-allocator                   LoadBalancer   172.20.90.71     <my-elb>   443:30308/TCP      2m16s
agones-allocator-metrics-service   ClusterIP      172.20.173.152   <none>                                                                         8080/TCP           2m16s
agones-controller-service          ClusterIP      172.20.228.85    <none>                                                                         443/TCP,8080/TCP   2m16s
agones-ping-http-service           LoadBalancer   172.20.138.39    <my-elb>  80:32066/TCP       2m16s
agones-ping-udp-service            LoadBalancer   172.20.162.69    <pending>                                                                      50000:31140/UDP    2m16s
➜  ~ kubectl apply -f https://raw.githubusercontent.com/googleforgames/agones/release-1.26.0/examples/simple-game-server/fleet.yaml

Error from server (InternalError): error when creating "https://raw.githubusercontent.com/googleforgames/agones/release-1.26.0/examples/simple-game-server/fleet.yaml": Internal error occurred: failed calling webhook "mutations.agones.dev": failed to call webhook: Post "https://agones-controller-service.agones-system.svc:443/mutate?timeout=10s": Address is not allowed
```

**Comment by laivu266** [comment]
Hi @markmandel and @roberthbailey ,
I already fixed this issue. Because of my EKS cluster is using cilium as CNI so I need to change hostNetwork and dnsPolicy of agones-controller as below:
```
 hostNetwork: true
 dnsPolicy: ClusterFirstWithHostNet
```
The issue is gone.
I think you need to add this guide to agones document if another user using other CNI instead of AWS default VPC CNI.

Thanks.

**Comment by markmandel** [comment]
@laivu266 if you could file a PR on the documentation, that would be appreciated.

I have no way of testing on AWS, so appreciate the input from the community.

**Comment by VINNUSAURUS** [comment]
> Hi @markmandel and @roberthbailey , I already fixed this issue. Because of my EKS cluster is using cilium as CNI so I need to change hostNetwork and dnsPolicy of agones-controller as below:
> 
> ```
>  hostNetwork: true
>  dnsPolicy: ClusterFirstWithHostNet
> ```
> 
> The issue is gone. I think you need to add this guide to agones document if another user using other CNI instead of AWS default VPC CNI.
> 
> Thanks.

i am getting same in GKE and where to change this ?

**Comment by VINNUSAURUS** [comment]
> Hi @markmandel and @roberthbailey , I already fixed this issue. Because of my EKS cluster is using cilium as CNI so I need to change hostNetwork and dnsPolicy of agones-controller as below:
> 
> ```
>  hostNetwork: true
>  dnsPolicy: ClusterFirstWithHostNet
> ```
> 
> The issue is gone. I think you need to add this guide to agones document if another user using other CNI instead of AWS default VPC CNI.
> 
> Thanks.

hi, where should i change it in the yaml ?

**Comment by zmerlynn** [comment]
Why would `agones-controller` need to run as `hostNetwork`? I'm not following why that change makes sense.

@VINNUSAURUS What are you seeing in GKE? What Agones version, GKE version?

**Comment by aimuz** [comment]
The issue looks like a cluster network malfunction, more logs should be available in the kube-apiserver

**Comment by markmandel** [comment]
@kylesomers tagging  you in EKS related issues, although this is an older one.
