### ISSUE TITLE
Metric to distinguish normal from failures shutdown.

### ISSUE THREAD

**Issue by sisso** [googleforgames/agones#2758]
**Is your feature request related to a problem? Please describe.**

Running 500 game servers with short live time (30 minutes). You have a constant rate of Ready/Allocated/Shutdown values on agones_fleets_replicas_count metric. 

Unfortunately we had a bug that cause every single to stop to produce agones health check beats in the middle of game. Agones then correctly start to kill all game servers after a while.

From the agones_fleets_replicas_count everything looks normal, the shutdown rate was normal. But many players tart to complain about disconnects. Only after looking into agones controller logs we found 8k logs like:

`game server container for GameServer fleet-v39664-vp68p-2gl8j in namespace default is not currently running, try again
`
Indicating that all pods were getting killed by agones by failing health checks, not by players finishing to play.

**Describe the solution you'd like**
Any metric (gauge, incremental, rate) that help to distinguish normal shutdowns from shutdowns caused by a failed health check.

A simple count +1 for every server that fails health checks will already enough to hint operation that something is wrong and easy to create an alert.

**Describe alternatives you've considered**
My current solution is count logs in agones-controller.

**Comment by markmandel** [comment]
As a note, "game server container for GameServer fleet-v39664-vp68p-2gl8j in namespace default game server container for GameServer fleet-v39664-vp68p-2gl8j in namespace default is not currently running, try again" - is a verbose log that should be moved to `Debug` level. It's perfectly normal for the Pod to be missing sometimes as the system starts up. (just to avoid anyone seeing this as the definitive source of truth for failures).

See ##2665 for the tracking for moving this logging level.

That being said, having a count of how many GameServer have moved to Unhealthy is useful, maybe something like: `agones_unhelathy_gameservers_total : count`

We can probably implement this in / near:
https://github.com/googleforgames/agones/blob/acf760b572c5748e9829f181e00a9d5dbc93f07c/pkg/metrics/controller.go#L342

And +1 the counter when we see the state change to Unhealthy. We may miss some as they move through states/etc, but it's likely a good enough tracking method.

**Comment by sisso** [comment]
The `gameservers_total ` metric of type 'Unhealth' is enough to hint that the shutdowns were caused by issues. Closing it.
