### ISSUE TITLE
Add Document for IPv6 network connectivity

### ISSUE THREAD

**Issue by govargo** [googleforgames/agones#2767]
**Is your feature request related to a problem? Please describe.**

I often heard from game company engineers that the iOS application connects with IPv6 network according to the specifications, while GameServer is listening with IPv4.
iOS IPv6-Only Networks: https://developer.apple.com/support/ipv6/

Currently Agones has feature called `NodeExternalDNS`.
And we have the FAQ page `How do I use the DNS name of the Node?`.
https://agones.dev/site/docs/faq/#how-do-i-use-the-dns-name-of-the-node

However, even if the user who use GKE turned on NodeExternalDNS, the user cannot get the ExternalDNS for node because GKE Node has only InternalIP/ExternalIP/InternalDNS.

So GKE users have to devise in order to connect IPv6 network.
Currently there is not a document for the user can refer to.

**Describe the solution you'd like**

It would be nice that we add the document for IPv6 connectivity.

**Describe alternatives you've considered**

None

**Additional context**

I read the following articles(These are japanese).
* https://speakerdeck.com/dena_tech/kubernetestoagonesniyoruriarutaimugemusabayun-yong-dena-techcon-2022?slide=54
* https://mixi-developers.mixi.co.jp/stble-voicechat-with-agones-aec5cbebe4a4

**Comment by govargo** [comment]
I talked with game company engineers about IPv6 connectivity with Agones some times.
Agones returns IPv4 ExternalIP when allocation. In order to connect with IPv6, the system have to convert using DNS64/NAT64. DNS64/NAT64 requires domain name to generate IPv6 address.
But GKE Node doesn't have a domain name.

**1. Client Side Implementation**

Client library can resolve this issue.

In case of Android, Android have [464XLAT](https://www.rfc-editor.org/rfc/rfc6877) as the standard.
464XLAT is a method that enables efficient sharing of IPv4 addresses with IPv6.

In case of iOS, [Pref64::/n Discovery](https://datatracker.ietf.org/doc/html/rfc8781) with `getaddrinfo` method.
In apple developer site, that says `you can use getaddrinfo to synthesize an IPv6 address from an IPv4 address`.
`Grpc.Core` library calls `getaddrinfo` inside it.

reference: [iOS Supporting IPv6 DNS64/NAT64 Networks](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1)

**2. Use PTR record**

GKE Node, GCE has PTR record.
For example, GCE has ExternalIP `34.1.1.1`, the PTR record is `34.1.1.1.bc.googleusercontent.com`.
This is used as domain name.
※ This information is undocumented.

If you have any ideas, welcome your opinions.

**Comment by markmandel** [comment]
Maybe a page here: https://agones.dev/site/docs/integration-patterns/

Where we can list out all the different options?

**Comment by govargo** [comment]
Integration Patterns would be good for this topic.

**Comment by markmandel** [comment]
@zmerlynn do we still need to do any more work here?

**Comment by zmerlynn** [comment]
Nope, I think we're good!
