### ISSUE TITLE
Add a FAQ entry describing when you would use Agones vs. StatefulSets

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2770]
**Is your feature request related to a problem? Please describe.**
A common question with Agones is to understand when you would use it vs. using StatefulSets. We should add a FAQ entry that answers this question that we can point people to.

**Comment by zmerlynn** [comment]
tbh, I feel like `GameServers` are closer to [Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/) than `StatefulSets`.

**Comment by roberthbailey** [comment]
They have a "run to completion" semantics similar to jobs, but there isn't the same notion of "N need to complete" that jobs do. 

But maybe your point is that we should compare them to built-in workloads types (also deployments) more generally.

**Comment by zmerlynn** [comment]
> They have a "run to completion" semantics similar to jobs, but there isn't the same notion of "N need to complete" that jobs do.

Sure, but at N=1, a `Job` and `GameServer` are very similar. Similar enough that I wonder if we _could_ use `Job`.

> But maybe your point is that we should compare them to built-in workloads types (also deployments) more generally.

That's a fair summary: I think it would be valuable for people to understand why this type exists and can't be served by types with broader support.
