### ISSUE TITLE
Update example allocation yaml files to use selectors instead of required

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2771]
**Is your feature request related to a problem? Please describe.**
[examples/gameserverallocation.yaml](https://github.com/googleforgames/agones/blob/main/examples/gameserverallocation.yaml) uses the newer `selectors` but a lot of the yaml files under the `/examples` directory still use `required` (e.g. [examples/simple-game-server/gameserverallocation.yaml](https://github.com/googleforgames/agones/blob/main/examples/simple-game-server/gameserverallocation.yaml) and [examples/xonotic/gameserverallocation.yaml](https://github.com/googleforgames/agones/blob/main/examples/xonotic/gameserverallocation.yaml) but probably others as well).

**Describe the solution you'd like**
Search through the game server allocation yaml files checked into the repository and change the spec to use `selectors` instead of `required`

**Describe alternatives you've considered**
_n/a_

**Comment by markmandel** [comment]
I have the updates for STK example in a branch, I'd just forgotten about it. I'll publish this one.
