### ISSUE TITLE
AgonesBot helm install instructions incorrect

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#2796]
**What happened**:

I tried to use a helm template from an @agones-bot CI build and encountered image pull issues.

**What you expected to happen**:

Images should be pullable.

**How to reproduce it (as minimally and precisely as possible)**:

Try the helm install in https://github.com/googleforgames/agones/pull/2789#issuecomment-1308044793. Instead of just `--set agones.image.tag=1.28.0-f3ebf4e-amd64`, it needs:

```
  --set agones.image.registry=us-docker.pkg.dev/agones-images/ci \
  --set agones.image.tag=1.28.0-f3ebf4e-amd64 \
  --set agones.image.sdk.tag=1.28.0-f3ebf4e-linux-amd64 \
```

**Comment by roberthbailey** [comment]
I'd forgotten that until we can build the container manifests in CI, we have to specify the architecture for the sdk... ugh. I wonder if we can create those yet?

x-ref: https://github.com/googleforgames/agones/issues/2280
