### ISSUE TITLE
Is it essential to update Agones when Kubernetes is updated?

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2798]
DigitalOcean is forcing a required update on me to update Kubernetes from 1.22 to 1.23. I am currently on Agones vs 1.23 and not ready to release a new game update yet. How critical is it that I adjust development plans and update Agones before Kubernetes gets updated?

**Comment by markmandel** [comment]
> DigitalOcean is forcing a required update on me to update Kubernetes from 1.22 to 1.23

Wheee! Fun.

> I am currently on Agones vs 1.23 and not ready to release a new game update yet.

As a note - if you update Agones, the SDK is backward compatible with previous versions, so the current version of your game server shouldn't need changing.

So if you are taking a maintenance window for a K8s upgrade, you could potentially also do Agones at the same time, and redeploy your Fleet and be good to go again (but always test in dev/staging first! 😄 )

> How critical is it that I adjust development plans and update Agones before Kubernetes gets updated?

In theory, everything should still work between K8s versions, but we only currently test one version of Agones against one version of Kubernetes, so we can't _guarentee_ that everything works (and if anything fails, the first thing we'll tell you to do is get into compliance).

Side note: This is an area of pain we are aware of, and am looking to improve on (allow support for multiple k8s versions).

Does that help?

**Comment by emrys90** [comment]
So you are saying there's a way I can update the cluster somehow, without having to update the Unity integration of it?

**Comment by markmandel** [comment]
Yeah, exactly -- the stable SDK API doesn't break between releases.

**Comment by emrys90** [comment]
Okay, thank you!
