### ISSUE TITLE
Agones Unity SDK version 1.27 no longer supports older versions of C#

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2800]
**What happened**:
Version 1.23 works fine, but after attempting to update to version 1.27 there is now compiler errors in Unity 2020.3.38f1. These compiler errors are caused by using new C# features ("is not string" in AgonesAlphaSdk). Your documentation mentions that the minimum required Unity version is 2018 here: https://agones.dev/site/docs/guides/client-sdks/unity/
https://agones.dev/site/docs/guides/client-sdks/unity/

As far as I am aware, the "is not" operator isn't available until in Unity 2021.

**What you expected to happen**:
I expect there to not be any compiler errors when importing this package.

**How to reproduce it (as minimally and precisely as possible)**:
Import this package into a Unity project using a version older than Unity 2021.

**Comment by emrys90** [comment]
Any news on this being able to get fixed?

**Comment by markmandel** [comment]
Would love some help on this if you are interested!

**Comment by emrys90** [comment]
Sorry, I'm under a lot of deadlines right now and wouldn't be able to fix that for a while.
