### ISSUE TITLE
Add metrics for player tracking

### ISSUE THREAD

**Issue by JJhuk** [googleforgames/agones#2827]
**Is your feature request related to a problem? Please describe.**

We use agones in the production environments for multiplay contents. as documents say, 'to advice the k8s scheduler how many game server processes it is able to fit into a given node in the cluster' is important. I conservatively set our game servers' resources limit and live environment well. (agones allocator 2.3k per request)
but the result is that the production environment is too leisurely than I expected, so I want to set fasten resource limitation base metrics.

we using player tracking feature for re-using game server but there are no metrics for player tracking in agones.
we want to see the grafana dashboard for how many users in the gameserver. 

**Describe the solution you'd like**
please add metrics for player tracking feature like `agones_fleet_player_count`

**Comment by markmandel** [comment]
Did https://github.com/googleforgames/agones/pull/2765 solve your problem? I _think_ it does, but wanted to check to see if there was anything missing from that PR.

**Comment by JJhuk** [comment]
@markmandel 
Oh, I missed that pull request.
I checked that pull request, that is satisfied my needs. :)
