### ISSUE TITLE
Graduate SDKGracefulTermination to beta

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#2831]
I propose graduating `SDKGracefulTermination` to Beta. I would like to rely on this in #2794, and the gate combinatorics may get complicated.

In support of graduation:
* It has been in `Alpha` since 1.18
* It's been correctly e2e tested since #2661 
* It's received no user feedback
  * The only reference I can find in issues is #2683 (which shows up because it's encoded as false in a config string) and #2647 
  * A Slack search did not uncover any issues

cc @roberthbailey @markmandel for thoughts and @bennetty @theminecoder as original authors.

**Comment by roberthbailey** [comment]
+1 to promoting for the next release.

**Comment by markmandel** [comment]
+1 from me too. Let's do it!

**Comment by theminecoder** [comment]
Yay!
