### ISSUE TITLE
Request for zmerlynn to become Approver

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#2833]
### GitHub Username

zmerlynn

### Requirements
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have read the [contributor guide](../../../CONTRIBUTING.md)
- [X] I am actively contributing to Agones
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markmandel 
- @roberthbailey 

### List of contributions to the Agones project
[full search](https://github.com/googleforgames/agones/issues?q=zmerlynn)

- PRs authored
  - #2782
  - #2789 
  - #2790 
  - #2791 / #2812
  - #2792 
  - #2795 
  - #2807 
- PRs reviewed
  - #2740
  - #2786 
  - #2811
  - #2813
  - #2824 
  - #2829 
- Issues responded to
  - #2648 
  - #2739 
  - #2781
  - #2815

**Comment by markmandel** [comment]
LGTM! I approve!

**Comment by roberthbailey** [comment]
LGTM. Approve!

**Comment by markmandel** [comment]
![knighted](https://media.tenor.com/M0kRIpxrEukAAAAM/anakin-skywalker-knight-anakin-sywalker-knighted.gif)

You have write access! Welcome to approver status!
