### ISSUE TITLE
Request for gongmax to become Approver

### ISSUE THREAD

**Issue by gongmax** [googleforgames/agones#2834]
### GitHub Username
@gongmax 

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have read the [contributor guide](../../../CONTRIBUTING.md)
- [x] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roberthbailey 
- @markmandel 

### List of contributions to the Agones project
[full search](https://github.com/googleforgames/agones/issues?q=gongmax)

PRs authored
#2823 
#2799 
#2764 
#2762 
#2756 
#2752 
#2751 
#2743 

PRs reviewed
#2829 
#2825 
#2819 
#2813 
#2795 
#2783 
#2785 
#2784 
#2780 
#2768 

Issues responded to
#1636 
#2810 
#2746 
#2748

**Comment by roberthbailey** [comment]
LGTM. Approve!

**Comment by markmandel** [comment]
LGTM!

You now have write access to the repo, and are an approver!

![when one of us shines all of us shine](https://media.tenor.com/XdUC15zlvPQAAAAd/one-of-us-shines-all-of-us-shine-catherine-o-hara.gif)
