### ISSUE TITLE
Support smooth upgrade

### ISSUE THREAD

**Issue by aimuz** [googleforgames/agones#2843]
**Is your feature request related to a problem? Please describe.**
After reading the [upgrade](https://agones.dev/site/docs/installation/upgrading/) documentation, I was frustrated, 
I found that he doesn't support smooth upgrades, which I think is a big flaw in the feature. I think we should support non-stop upgrades that，

When using k8s, we will consider deploying different services inside a cluster if we want to 
If we have to migrate the whole cluster for agones upgrade, I think this may be a drawback. In order to use agones, we have to build a cluster dedicated to agones, so that we can avoid migrating other applications and other services when upgrading agones.

The cluster where agones is located it has a lot of things, such as monitoring, persistence, host optimization, etc., then these means that it needs to be done again, although there are quite a few tools to simplify this part of the work. But I think this is still unnecessary. That's why we should support smooth upgrades. Avoid migrating clusters in a way.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Perhaps, the way to upgrade we can refer to istio 

**Additional context**

https://agones.dev/site/docs/installation/upgrading/

**Comment by zmerlynn** [comment]
To clarify, I think you're asking for smooth Agones upgrades. In #2777 we're working towards smooth _Kubernetes_ upgrades, so part of this should be solved soon.

**Comment by roberthbailey** [comment]
For Agones upgrades, we have https://github.com/googleforgames/agones/issues/1742 open. I'm going to copy your comment onto that issue and close this one as a duplicate.

**Comment by aimuz** [comment]
Thank you
