### ISSUE TITLE
Update Kubernetes to 1.24

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2867]
As discussed during [last week's community meeting](https://docs.google.com/document/d/1wbCU-wGy-_d5HawHJPTRP-dvL2h432cpcd4_SVp003o/edit#heading=h.p65oqavl2nbb), it's time to upgrade to the next version of Kubernetes!

List of items to do for upgrading to 1.24:

- [x] Update terraform submodules
    - [x] GKE
    - [x] Azure
    - [x] EKS
- [x] Update prow cluster (even though we aren't using it yet, we should keep it in sync)
    - [x] Recreate cluster with new scripts: `cd build/terraform/prow; terraform apply -var project=agones-images`
- [x] Update e2e cluster
    - [x] Recreate cluster with new scripts: `cd build/terraform/e2e; terraform apply -var project=agones-images`
- [x] Update kubectl in dev tooling
    - [x] Update kubectl in `build/build-image/Dockerfile`
    - [x] Update kubectl in `build/e2e-image/Dockerfile`
- [x] Update documentation for creating clusters
    - [x] Config.toml `supported_k8s` and related (do `dev_` before main)
- [x] Update the dev tooling to create clusters
    - [x] Minikube
    - [x] Kind
- [x] Update the k8s image used in the helm [pre-delete-hook](https://github.com/googleforgames/agones/blob/main/install/helm/agones/templates/hooks/pre_delete_hook.yaml)
- [x] Update client-go
- [x] Update CRD API reference
    - [x] Update links to k8s documentation in `site/assets/templates/crd-doc-config.json`
    - [x] Regenerate crd api reference docs - `make gen-api-docs`
    - [x] Regenerate crd client libraries - `make gen-crd-client`
- [x] Regenerate Kubernetes resource includes (e.g. ObjectMeta, PodTemplateSpec)
    - [x] Start a cluster with `make gcloud-test-cluster`, uninstall agones using `helm uninstall agones -n agones-system`, and then run  `make gen-embedded-openapi` and `make gen-install`
- [x] If client-go pulled in a new version of gRPC, then also
    - [x] Update the SDK [base image grpc version](https://github.com/googleforgames/agones/blob/main/build/includes/sdk.mk#L30) and rebuild the image. Note that this can take a while and in the past we have had to manually push it to gcr because cloud build doesn't like how long it takes.
    - [x] Regenerate allocated API endpoints: [make gen-allocation-grpc](https://github.com/googleforgames/agones/blob/main/build/includes/allocation.mk#L55)
    - [x] Regenerate all client sdks: [make gen-all-sdk-grpc](https://github.com/googleforgames/agones/blob/main/build/README.md#make-gen-all-sdk-grpc)
    - [x] Update the version number in C++ Cmake scripts [here](https://github.com/googleforgames/agones/blob/main/sdks/cpp/CMakeLists.txt#L100) and [here](https://github.com/googleforgames/agones/blob/main/sdks/cpp/cmake/prerequisites.cmake#L34)

**Comment by 1804devs** [comment]
I did a pull request  it didn't pass im using github codespace. if anyone can help out

**Comment by roberthbailey** [comment]
@1804devs - Thanks for your interest in this ticket and contributing to Agones! 

This may not be the easiest ticket to tackle for you first contribution. Have you read the [contributing guide](https://github.com/googleforgames/agones/blob/main/CONTRIBUTING.md) and [Developing, Testing and Building Agones](https://github.com/googleforgames/agones/blob/main/build/README.md)? Those should help with your development workflow and help you figure out why CI isn't passing on your pull request. It is also helpful if you can run the build locally to replicate what is failing in the CI system to speed up the debugging cycle. 

I would suggest trying to pick up a ticket with the ["good first issue" label](https://github.com/googleforgames/agones/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to make your first contribution. Those issues tend to be simpler and require a lot less understanding of the internals of the project.

**Comment by gongmax** [comment]
This update doesn't introduce new version of `google.golang.org/grpc` so there is not need to update the SDK base image grpc version and the version number in C++ Cmake scripts (steps 1 and 4 of the last task in the list above). I also run [`make gen-allocation-grpc`](https://github.com/googleforgames/agones/blob/main/build/includes/allocation.mk#L55) and [`make gen-all-sdk-grp`](https://github.com/googleforgames/agones/blob/main/build/README.md#make-gen-all-sdk-grpc) to confirmed they didn't generate any change.
