### ISSUE TITLE
Remove the github.com/pkg/errors dependency from the repo

### ISSUE THREAD

**Issue by aimuz** [googleforgames/agones#2870]
**Is your feature request related to a problem? Please describe.**

`github.com/pkg/errors` The archive is no longer being updated, and std errors provides the ability to do so, so I want to remove `github.com/pkg/errors` and switch back to using the standard library.

What do you think? I will do this if you agree

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by markmandel** [comment]
std errors doesn't provide all the functionality of `github.com/pkg/errors` - particularly capturing a stack trace with an error. So I'd be against this for now.

From `github.com/pkg/errors`:

> With the upcoming [Go2 error proposals](https://go.googlesource.com/proposal/+/master/design/go2draft.md) this package is moving into maintenance mode.

So it is maintenance mode, but waiting to be replaced by the Go2 proposal. So I would argue we shouldn't switch out until that lands.

**Comment by aimuz** [comment]
Thank you

https://github.com/pkg/errors/issues/245

errors has gone into read-only mode due to lack of new maintainers.

If we are currently relying on stack trace, then we can indeed wait a bit longer, as all the features have been largely implemented except for stack trace

**Comment by markmandel** [comment]
Cleaning up as wontfix. We can revisit if the state of error management in Go changes.
