### ISSUE TITLE
ARM64 image and charts

### ISSUE THREAD

**Issue by RedstoneWizard08** [googleforgames/agones#2878]
**Is your feature request related to a problem? Please describe.**

I'm trying to set up XREngine on an ARM64 server, but I can't, since it relies on this and the charts are only AMD64.

**Describe the solution you'd like**

ARM64 images and charts.

**Describe alternatives you've considered**

Doing it myself - it's not going very well.

**Additional context**

N/A

**Comment by markmandel** [comment]
Agones should work without issue on arm64 Kubernetes clusters:
https://agones.dev/site/docs/installation/#supported-container-architectures

I've tested it without issue - can you explain specifically what you are trying to do, and what errors you are facing?
