### ISSUE TITLE
Specify port range for gameserver pods specific to a node

### ISSUE THREAD

**Issue by SomendraDev** [googleforgames/agones#2882]
Hello,

I have a node running microk8s and a static IP from ISP, using port forwarding we point to that node.
Now we want to add two more node. But we have only one static ip.

So, it is possible to specify port range that gameserver pod will use if it is instantiated in a specific node.
Example : node A gameservers pod will have port 7000 to 8000
                node B gameservers pod will have port 8001 to 9000
                node C gameservers pod will have port 9001 to 10000

So, that we can port forward port range from 7000 to 8000 to node A, 
port forward port range from 8001 to 9000 to node B
and port forward port range from 9001 to 10000 to node C

Is there any alternative to solve this issue, then please let me know.

Thanks

**Comment by SomendraDev** [comment]
Hello all,

Please let me know how to solve this issue, or there is any alternative way to it.

Thanks

**Comment by markmandel** [comment]
I think it might be time to move to a 3 node cluster on some kind of cloud provider 😃 

There's no way to specify a node range per node, and I don't think it would be something we would support as it's going to be very complicated at scale.

**Comment by markmandel** [comment]
I'm going to close this as `wontfix`, as it is out of scope for this project.
