### ISSUE TITLE
Graduate `SafeToEvict` to Beta

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#2931]
I propose graduating `SafeToEvict` to Beta: It was Alpha in 1.29, with documentation in #2924.

The reasoning for the fast promotion is discussed in #2794: 

> Graduation to Beta should be relatively rapid as the feature has broad backward compatibility. The only situation where backward compatibility is violated is if the user is negatively impacted by a PDB on the game server pods, e.g. the user is relying on the default `safe-to-evict=false` pod annotation, but _also_ is assuming that node drain (e.g. via cluster upgrade) will evict. Given that our existing documentation doesn't allow for node drains, we think this is a safe case for backwards incompatibility. To be conservative about it, though, when we graduate `SafeToEvict` to `Beta`, we will flag it a potentially breaking change in Release Notes to call attention to it. To allow this situation, the user simply needs to set `eviction: safe: OnUpgrade`. 

I recognize that this feature was relatively undocumented as of yet (hence #2924) and the contract might be not quite right, but I think the risk to graduation is minimal.

Towards #2777

**Comment by markmandel** [comment]
For me - as long as it has sufficient documentation, I have no strong objections 👍🏻

**Comment by roberthbailey** [comment]
> I recognize that this feature was relatively undocumented as of yet (hence https://github.com/googleforgames/agones/pull/2924) and the contract might be not quite right, but I think the risk to graduation is minimal.

I'm biased, but I think the contract is pretty good, and also that we are unlikely to get much feedback until we graduate it to beta. 

I think it makes sense to get this turned on sooner as folks can still disable it if necessary, it's backwards compatible in the defaults, and the new field was designed to be extensible if we need to make changes (and don't want to completely upend the new api).
