### ISSUE TITLE
Local Game Server - documentation confusing

### ISSUE THREAD

**Issue by jamesw6811** [googleforgames/agones#2951]
`To register your local game server you’ll need to know the IP address of the machine running it and the port. With that you’ll create a game server config like the one below.`

I'm confused about this. If I'm running my game server locally, aren't I always at "localhost"? I'm unable to get the local functionality up and running for troubleshooting, so i'd love to know the details of running in this mode. Are there any examples?

**Comment by markmandel** [comment]
> I'm confused about this. If I'm running my game server locally, aren't I always at "localhost"?

You are for you! But if you are working on a team, it might not be the case for anyone else trying to connect to that instance of your game server.

**Comment by jamesw6811** [comment]
Thanks! I see now.

**Comment by markmandel** [comment]
Awesome. I'll close this ticket then. Thanks for trying out Agones!
