### ISSUE TITLE
`To install this version` instructions should include helm updates

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#2952]
[Example "To install this version" instructions from an unrelated PR](https://github.com/googleforgames/agones/pull/2949#issuecomment-1418635901). These instructions are deficient in a couple of ways:

* If you've made helm changes, these aren't reflected at all. It would be straightforward for us to use `helm package` to generate a Chart for a particular CI version and dump them somewhere. An example I just manually did from the tip of `main` is here: https://storage.googleapis.com/agones-chart-ci/agones-1.30.0-fa32a31.tgz (but that was manual).

* The instructions seem off right now anyways - I don't believe `--agones.image.release=us-docker.pkg.dev/agones-images/ci` is a Helm option, this seems to be missing the `--set`.

**Comment by gongmax** [comment]
I fixed the broken helm command https://source.cloud.google.com/agones-images/build/+/master:functions/index.js;l=214;bpv=1

**Comment by markmandel** [comment]
@gongmax did you redeploy the function, or do I need to do that? (hopefully it still works 🤞🏻 )

**Comment by gongmax** [comment]
@markmandel I already redeployed the function. It worked!

**Comment by markmandel** [comment]
Awesome! Shall we close this ticket?

**Comment by gongmax** [comment]
I will sync up with @zmerlynn about the first item. I didn't quite get it so haven't fixed it yet.

**Comment by markmandel** [comment]
Aaah, I missed the first line 👍🏻

**Comment by zmerlynn** [comment]
> I didn't quite get it so haven't fixed it yet.

I realized I didn't word the first bullet quite right. Right now you have to have a clone of the agones repo and then check out the PR, e.g.:

```
> git fetch https://github.com/googleforgames/agones.git pull/3151/head:pr_3151 && git checkout pr_3151
> helm install agones ./install/helm/agones [...]
```

I was trying to give instructions for a repro internally and it's kind of an extra burden to need a git repo as well. It seems like  we could just package the helm chart for the PR as part of the build, which would make this a single step. I guess this isn't a huge deal, though.
