### ISSUE TITLE
Add `make gen-crd-clients` to the CI suite

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2972]
**Is your feature request related to a problem? Please describe.**
`make gen-crd-clients` broke in a recent commit without anyone noticing. 

**Describe the solution you'd like**
If we run this command in CI then we will prevent PRs from merging that break it. 

**Describe alternatives you've considered**
_n/a_

**Additional context**
_n/a_

**Comment by markmandel** [comment]
We should also find a way to compare output - much like we do for `gen-install`.

**Comment by markmandel** [comment]
We finished this in #3196, so closing.
