### ISSUE TITLE
Add support for dynamic port ranges

### ISSUE THREAD

**Issue by victor-prodan** [googleforgames/agones#299]
Currently, we can describe only one port at a time.
There are servers that use a continuous range of ports (i.e. 7000-7010).
When using dynamic port allocation, if we specify each port independently, they will be shuffled across the allocation range and will not be continuous anymore.
We need thus a dynamic allocation method for a range of ports that randomizes only the beginning of the range, keeping the range together (i.e. 7000-7010 becomes 4124-4134)

**Comment by victor-prodan** [comment]
Actually, I guess there should support for static port ranges as well...

**Comment by victor-prodan** [comment]
Actually, I guess there should support for static port ranges as well...

**Comment by markmandel** [comment]
Reopening - looks like a bug in the bot. Should still be stale though.
