### ISSUE TITLE
Ensure `agones-extensions` is HA

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#2999]
While debugging #2992, I think we basically proved that `SplitControllerAndExtensions` can still result in short service flickers for the webhook. Hard to say as @chiayi was never able to repro locally (only @agones-bot repro'd).

My guess is that unless `kube-apiserver` retries webhook calls (we don't think it does), there will always be opportunities for the Agones webhooks to fail when a pod fails, suggesting calls should be retried. However, we should understand this and prove it one way or another.

**Comment by zmerlynn** [comment]
Noting specific error seen in #2992:

```
Internal error occurred: failed calling webhook "validations.agones.dev": failed to call webhook: Post "https://agones-controller-service.agones-system.svc:443/validate?timeout=10s": EOF
```

I'm more or less certain there's no retry here: https://github.com/kubernetes/kubernetes/blob/fb57080e069fe2efe11734a4570a92873e673c35/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go#L279

c.f. https://hackmd.io/@MA1u8XBlRc2mDt7E5cWviQ/HyRmzCXNc, which traces this vicinity as well (though for mutating - the above error is for validating).

So, ok, that means we're left with ensuring that _voluntary_ disruptions (which the Pod delete in this test is, or a Cluster Autoscaler eviction would be) are handled appropriately.

I suspect that we need to add a readiness probe and a `/ready` handler, then intercept `SIGTERM`, go unready, and wait on termination long enough that our readiness probe will fail. That should drain traffic for the voluntary disruption cases.

**Comment by markmandel** [comment]
> I suspect that we need to add a readiness probe and a /ready handler, then intercept SIGTERM, go unready, and wait on termination long enough that our readiness probe will fail. That should drain traffic for the voluntary disruption cases.

100% agree. Minor thought - we should be specific about graceful termination as well such that it aligns with our readiness probes as well, giving them time to fail.
