### ISSUE TITLE
CI improvement: And steps to cancel a previous running build upon a new commit in the same branch.

### ISSUE THREAD

**Issue by gongmax** [googleforgames/agones#3001]
**Purpose**
To save build minutes and cost, the CI process should be able to automatically cancel a previous running build upon a new commit in the same branch. 

**Describe the solution you'd like**
Since Cloud Build doesn't support this out of box, we should probably implement some custom builder step similar as https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/cancelot. i.e. Canceling any previous build with same branch name and trigger. The sub e2e tests build will be handled by https://github.com/googleforgames/agones/blob/main/cloudbuild.yaml#L273-L280

**Comment by markmandel** [comment]
I _think_ the official Cloud Build + GitHub integration does this. We should double check, but might give us enough impetus to finally move everything over.

**Comment by gongmax** [comment]
I did some search but didn't see anything related in the official Cloud Build docs. I also looked into all the fields to setup a trigger but didn't find anything related. I will go ahead and implement some custom builder step to achieve this.

**Comment by markmandel** [comment]
I'm sure we can find someone to ask internally, just to double check.

I can also try it on Quilkin, since we use it there.

**Comment by zmerlynn** [comment]
We already have the `BRANCH_NAME` on the main build. I was thinking an easy/cheap solution here was just to cancel any build with the same `BRANCH_NAME`, if that build was started before the `BUILD_ID` that's running.

The e2e builds will then just get cancelled by https://github.com/googleforgames/agones/blob/main/cloudbuild.yaml#L273-L280

**Comment by gongmax** [comment]
Yes, that was basically what other people did such as https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/cancelot, i.e. canceling any previous build with same branch name and trigger. Should be straightforward enough.
