### ISSUE TITLE
Support Multiple Cluster spanning the globe

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#301]
Agones should make supporting multiple Agones clusters around the world, and provide tools for streamlining these processes.

I see this come under two main feature sets:

## Cluster Registries
- Be able to add/remove clusters from a single registry
- Be aware of the health of a registry
- That registry should be queryable in some way as well.

There should be existing work, most likely coming out of [sig-multicluster](https://github.com/kubernetes/community/blob/master/sig-multicluster/README.md), that we can take advantage of - as many applications have this need.

### Research
- https://github.com/kubernetes/cluster-registry
- [SIG Multi-Cluster Intro](https://www.youtube.com/watch?v=vGZo5DaThQU)
- [SIG Multi-Cluster Deep Dive](https://www.youtube.com/watch?v=q27rbaX5Jis)
- https://github.com/kubernetes-sigs/federation-v2
- https://github.com/admiraltyio/multicluster-controller
- https://istio.io/docs/setup/kubernetes/multicluster-install/
- https://github.com/kubernetes-sigs/federation-v2
- https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/federating_crds.md
- https://kubernetes.io/blog/2018/12/12/kubernetes-federation-evolution/

## Standard Ping/Latency tooling

We should integrate some tooling into each cluster and accompanying tooling that can be incorporated into game clients, such that determining ping time to clusters is an out of the box solution (or as out of the box as we can make it)

**Comment by victor-prodan** [comment]
I think it would be useful to be able to define spillover rules - when one cluster is full to redirect allocation requests to another one.

**Comment by markmandel** [comment]
Ooh, that's an interesting idea. Kind of like a global fleet allocation load balancer. Nice :+1:

**Comment by Maxpain177** [comment]
+1. I'm really looking forward to it

**Comment by Kuqd** [comment]
@markmandel Question: is it out of scope cluster creation ? I personally think so, also this makes it easier to handle multiple clusters by using a single mean of connection the kubeconfig/service account. We should however add a tool that help to register kubeconfig for each provider.

**Comment by markmandel** [comment]
@Kuqd yeah, I would agree that cluster creation is out of scope - but yes, we need some kind of tool for managing kubeconfig -- I wonder if cluster-registry will help?

**Comment by Kuqd** [comment]
no it's something else basically endpoints and authinfo (bearer token from sa). 

However looking at the code base there is nothing else than the CRD and generated code for it, so this is very early. At the end of the day you need a [rest.Config](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L51)

**Comment by markmandel** [comment]
@Kuqd although nobody uses Federation anymore - it's pretty much been determined to be a failed experiment.

Although maybe there are pieces we can lift out of it that are useful.

**Comment by Oleksii-Terekhov** [comment]
We also interested in multi-cluster Agones.
But selecting best cluster - in our project it's Matchmaking goal  - due minimal ping for all users, costs and similar reasons for maximize UX and profit. 
So any "logic to select cluster for Gameserver" must be switchable - we want explicit select fleet+cluster in FleetAllocation manifest...
Maybe, as side-effect, must be quick and trusted metrics API in Agones controller about current load (free/allocated/total/unhealthy/available GameServers....)

**Comment by markmandel** [comment]
I've started researching this as the next big ticket item to tackle.

The thing I'm trying to decide is what is the first item that should be tackled.

Maybe having a registry of clusters, and a standard way to ping each of them for round trip time? Would that be a good starting point?

**Comment by EricFortin** [comment]
I am not convinced about the registry. Unless we want to offer that as a separate project, where would this leave? As stated before allocation strategy is bound to change a lot based on multiple criteria. So if we only delivers a simple registry, I feel most already have some form of service to return configuration where they could store that list.

That being said, having a setup to ping each cluster so we can send this data to our matchmaking service is definitely worth it. It also requires client code so we need to think about how we will deliver this since this code will need to run on consoles too.

**Comment by victor-prodan** [comment]
> 2. Client side code - I'm thinking that we both need to do a C# and a C++ sdk for this

Do you mean game client code? If yes, I don't think it's necessary. I think that each game has its own way of pinging a HTTP (or maybe UDP) endpoint, so we just need a way to create those endpoints.

Here is how Amazon is doing it: https://www.cloudping.info/.
I imagine a similar thing for Agones.

**Comment by markmandel** [comment]
Also similar to: http://www.gcping.com/ :smile: 

Is a HTTP endpoint good enough, or does it have to be a UDP endpoint? (or maybe both?)

Here's an interesting question - should this be behind a loadbalancer? A LB will mean that we can do redundancy, and scale up the pinger (if it's needed), but does a LB introduce a layer that otherwise wouldn't be there.

**Comment by victor-prodan** [comment]
A LB is needed, yes, and this is why it sounds like an independent service hosted in the same cluster. Something like this already exists, maybe?

About udp... Yes, it might be helpful to detect packet loss for example.

IT also depends on the protocol used by the game... If it's based on smth like websocket than they wouldnt need udp.

Http is easier to implement by both sides and it's a must. Udp is nice to have.

**Comment by markmandel** [comment]
That makes lots of sense.

For the HTTP request - I'm assuming this would need to return an "ok" and HTTP 200, and the client would want to track the round trip time themselves.

For UDP - would it return a empty packet back to the sender? Does it need to contain any information, like an id/hash? (or echo what has been sent) Since it's async, I would assume this would be required - unless there is a better way.
- Another fun question - do we have any concerns about someone using this for a reflection DDOS attack of some kind? (spoofing the "from" address, to forward the attack to another location? Sounds like we should rate limit these requests).

**Comment by victor-prodan** [comment]
> For the HTTP request - I'm assuming this would need to return an "ok" and HTTP 200, and the client would want to track the round trip time themselves.

:+1: 

> For UDP - would it return a empty packet back to the sender? Does it need to contain any information, like an id/hash?

UDP is tricky, as the production would use its own protocol. Maybe it would be better to let the user supply the binary? They would also be responsible for any throttling in this case.

**Comment by EricFortin** [comment]
@markmandel 

> Another fun question - do we have any concerns about someone using this for a reflection DDOS attack of some kind? (spoofing the "from" address, to forward the attack to another location? Sounds like we should rate limit these requests).

For a reflection attack to be effective, you usually want to provoke a bigger response than the request you sent. If we simply echo back the packet we received, there is not much to gain from hitting us instead of the target directly.

Rate limiting is still a good thing though.

**Comment by markmandel** [comment]
I think we can also close this one, since we have https://agones.dev/site/docs/advanced/multi-cluster-allocation/ @pooneh-m WDYT?

**Comment by pooneh-m** [comment]
Makes sense. I closed it.
