### ISSUE TITLE
Review: Quickstart: Edit a Game Server

### ISSUE THREAD

**Issue by scozirge** [googleforgames/agones#3030]
**What happened**:
I follow the tutorial Quickstart: Edit a Game Server
https://agones.dev/site/docs/getting-started/edit-first-gameserver-go/
but fail to build docker image on windows, it says
 => ERROR [builder 5/5] RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server

**What you expected to happen**:
It shoud build image success

**How to reproduce it (as minimally and precisely as possible)**:
1. pull the porject
2. open \examples\simple-game-server by vs code
3. follow the tutorial here https://agones.dev/site/docs/getting-started/edit-first-gameserver-go/
4. when setting the environment, it will fail since I am using windows (GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/server -a -v main.go)
so I change cmd like below:
set GOOS=linux && set GOARCH=amd64 && set CGO_ENABLED=0 && go build -o bin/server -a -v main.go
5. when building image, it fail. docker build -t gcr.io/[PROJECT_ID]/agones-simple-game-server:modified .

**Anything else we need to know?**:

**Environment**:
- Agones version: v1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
This falls because we use simple game server to test with, so it imports from the parent gopath, which the tutorial doesn't (shouldn't???) cover.

We should adjust the tutorial to work a different way (possibly?), Or build from the root of the project like we do in the project, or maybe part of the tutorial is editing the go.mod file to point to released SDKs?

**Comment by scozirge** [comment]
sorry, I am new to docker. I fail to build an image and have no idea how to fix it. I post my question on slack and you suggest me file an issue here. Back to the question, how to fix this error

ERROR [builder 5/5] RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server
 [builder 5/5] RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server .:
#14 0.315 no Go files in /go/src/agones.dev/agones/examples/simple-game-server

**Comment by markmandel** [comment]
On review, https://github.com/googleforgames/agones/pull/3776 fixes this, so closing 👍🏻
