### ISSUE TITLE
arm64 clean install: 1 of 3 allocator pods in CrashLoopBackoff state (with exec /home/agones/allocator: exec format error)

### ISSUE THREAD

**Issue by gotchipete** [googleforgames/agones#3031]
**What happened**:

I installed agones (on my arm64 EKS cluster) as per https://agones.dev/site/docs/installation/install-agones/helm/ and all pods are running fine except one of the three allocator pods; `k get logs (crashing allocator pod name) -n agones-system` yields `exec /home/agones/allocator: exec format error` 

**What you expected to happen**:
I expect all pods to start and run fine 

**How to reproduce it (as minimally and precisely as possible)**:
1. Spin up arm cluster on eks
2. `k create ns agones-system`
3. `helm install agones-release --namespace agones-system agones/agones`
4. (when the install is done) - `kubectl get pods -n agones-system`
5. Observe e.g.:
```NAME                                 READY   STATUS             RESTARTS      AGE
agones-allocator-64fd9df7f8-ndnwj    1/1     Running            0             6m40s
agones-allocator-64fd9df7f8-p67gj    0/1     CrashLoopBackOff   6 (45s ago)   6m40s
agones-allocator-64fd9df7f8-xb6rg    1/1     Running            0             6m40s
agones-controller-857c666c94-rsd94   1/1     Running            0             6m40s
agones-ping-54c465d74f-5jdz7         1/1     Running            0             6m40s
agones-ping-54c465d74f-wwdz8         1/1     Running            0             6m40s
```

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.30.0
- Kubernetes version (use `kubectl version`): 1.25.4
- Cloud provider or hardware configuration: EKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): 
- Others:

**Comment by markmandel** [comment]
Quick silly question -- I assume you mean version 1.30.0?

Also if your `get logs -p` do you get any additional details?

**Comment by gotchipete** [comment]
However... I can run the simple gameserver fine.. and the allocator service is handling the one pod being in the crash state fine as it should.. 👍

**Comment by markmandel** [comment]
That's so weird. It's almost as if most Pods have the arm image, but one has the Intel image?

Can you describe the pod that's failing and see the events, and compare to a working one?

**Comment by markmandel** [comment]
The other working Pod, same `Docker ID` on both I assume?

**Comment by gotchipete** [comment]
> The other working Pod, same `Docker ID` on both I assume?

Only see Container ID and Image ID, and they're different..

Working: 
```
Container ID:   docker://dc18273c4a2415fd1715a26620d95cb03ee3a15b43b7277e3949d3c66da9d421
Image:          us-docker.pkg.dev/agones-images/release/agones-allocator:1.30.0
Image ID:       docker-pullable://us-docker.pkg.dev/agones-images/release/agones-allocator@sha256:ef3041eabd8190f32f0b5e13391640ef7d62b46738a0ab9c218e0f2cc95848af
```

Not working (CrashLoopBackoff):
```
Container ID:   docker://e9a9d09a014975328e6a2dddea07288fe94cad15699cbb0a85dae3a8b8cab94f
Image:          us-docker.pkg.dev/agones-images/release/agones-allocator:1.30.0
Image ID:       docker-pullable://us-docker.pkg.dev/agones-images/release/agones-allocator@sha256:b7b9ad8e744d44a1f7e93036272e2b56db1be06f3c734a3126e77ef97cb70fc7
```

**Comment by gotchipete** [comment]
I'll just delete the offending replicaset..?

**Comment by gotchipete** [comment]
Not sure if this helps but found it interesting, seems it's creating 2 replicasets.. one on arm, one on amd?

```
kas describe deploy agones-allocator | grep -i replica
Replicas:               2 desired | 1 updated | 3 total | 2 available | 1 unavailable
  Available      True    MinimumReplicasAvailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  agones-allocator-64fd9df7f8 (2/2 replicas created)
NewReplicaSet:   agones-allocator-9fbfb54cc (1/1 replicas created)
  Normal  ScalingReplicaSet  32s (x3 over 106m)  deployment-controller  Scaled up replica set agones-allocator-9fbfb54cc to 1
```
The `9fbfb54cc` replicaset is the crashing one

**Comment by zmerlynn** [comment]
@markmandel Did we .. re-push 1.30?

![image](https://user-images.githubusercontent.com/4942464/225398465-610166c7-83e7-48fa-a820-8c9f649368ee.png)

**Comment by markmandel** [comment]
We actually did - we had an accidental push mid sprint. I wonder if that did something that was something weird to the manifests.

**Comment by gotchipete** [comment]
Hmm just did a clean helm uninstall and reinstall - now I just have two amd64 pods trying to execute on our arm nodes :D - should I try something other than the `stable` (`https://agones.dev/chart/stable`) repo?

**Comment by gotchipete** [comment]
Well, all good if I set `image.tag` to `1.30.0-arm64` - apologies if I was supposed to do that in the first place...

**Comment by markmandel** [comment]
Not your fault, you shouldn't have to. Something got messed in our manifests. Will have to look into what it was.

**Comment by zmerlynn** [comment]
@markmandel We fixed this didn't we?

**Comment by markmandel** [comment]
Yeah, this should be fixed in 1.310 -- @gotchipete any chance you can confirm on your end?

**Comment by gotchipete** [comment]
Been a while but yes I am fairly certain I remember it being fixed.

**Comment by markmandel** [comment]
Awesome - closing!
