### ISSUE TITLE
Create a controller example

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#3036]
**Feature Request**
We currently link out to some [Third Party Libraries and Tools](https://agones.dev/site/docs/third-party-content/libraries-tools/) that are examples of writing controllers that do something based on the Agones CRDs. But it would be nice to have a simple, minimalistic in-tree controller example under https://github.com/googleforgames/agones/tree/main/examples to serve as a starting point for anyone that wants to build their own controller.

**Comment by Kalaiselvi84** [comment]
@roberthbailey, To make sure I understand correctly, do we need to include a README file in https://github.com/googleforgames/agones/tree/main/examples that shows an example of a simple game server implementation using simple-game-server, CPP Simple, and Node.js etc..?

**Comment by markmandel** [comment]
Some reading up on "Kubernetes controllers" to provide context:

* https://kubernetes.io/docs/concepts/architecture/controller/
* https://github.com/kubernetes-sigs/controller-runtime is a framework we should use for the controller.

Here are a couple of examples (of different complexity)
* https://github.com/Octops/gameserver-ingress-controller/tree/main
* https://github.com/Octops/agones-event-broadcaster

For an example, I would do something simple - like log `GameServer` details on insert, update or delete, with a message of what type of event it is.

Unless @roberthbailey you have any other ideas for a controller?

**Comment by roberthbailey** [comment]
What we want is a stand-alone program (with a Makefile, Dockerfile, and README) that you could deploy into an Agones cluster. 

I think Mark's idea is good - if someone wanted to write custom code, they would essentially just need to replace the log line with what they want to do instead (e.g. write to redis, send an API call, etc). Watching just one resource seems reasonable for an example, in which case the `GameServer` seems like the best choice.

**Comment by Kalaiselvi84** [comment]
Update:
I have reviewed this (controller documentation)[https://kubernetes.io/docs/concepts/architecture/controller/] as well as the `Medium` series on controller-runtime. Will begin implementing the code to `log GameServer details on insert, update or delete, with a message of what type of event it is`.

**Comment by Kalaiselvi84** [comment]
@markmandel, I attempted to implement a solution provided [here](https://gist.github.com/Kalaiselvi84/f9f8d8dccfa50a42ef4485fcbf3d7a61), as referenced in the article at https://nakamasato.medium.com/kubernetes-operator-series-1-controller-runtime-aa50d1d93c5c. Am I on the right track? Could you please provide the usual checklists for this task?

**Comment by markmandel** [comment]
This looks really good to me! I assume it all works 😄 but I like it! (we can also get some people who are more familiar with controller-runtime to review once we have a PR).

We should follow the other examples we have, similar to what we have for the [crd-client](https://github.com/googleforgames/agones/tree/main/examples/crd-client) example:

* A Dockerfile to turn this into an image
* A `Makefile` with the usual targets
* Make sure `gar-check` and `echo-image-tag` are impelemented
* A cloudbuild.yaml to build this in a project.
* a `deployment.yaml` which deploys the image into a cluster (also how you can test that this works!)
* Add this directory to https://github.com/googleforgames/agones/blob/42b1a9289df3c0f81960d56a9819a695303f0659/build/includes/examples.mk 

I think that will cover it!

**Comment by Kalaiselvi84** [comment]
Thank you, Mark! This is really helpful👍🏻

> I assume it all works

I haven't tested it yet because I'm not sure of the best approach to testing; I simply followed the controller-runtime example🙈. Could you please provide me with some guidance on the testing steps as well?

**Comment by markmandel** [comment]
The crd-client is actually a really good example (Although the deployment is different) - you'll need to make the image with the steps above, deploy it to the cluster, create a Fleet of some kind (simple-game-server should suffice), and see what the log output looks like, and see what the label changes are that you implemented!
