### ISSUE TITLE
Agones SDK Plugin for Unreal Engine no longer supports 4.27 or earlier.

### ISSUE THREAD

**Issue by DevChagrins** [googleforgames/agones#3037]
**What happened**: Agones SDK Release 1.30 doesn't compile for Unreal Engine 4.26 or 4.27 because of the use of Unreal Engine 5 only features.

**What you expected to happen**: Agones SDK Release 1.30 to compile for Unreal Engine 4.26 and 4.27.

**How to reproduce it (as minimally and precisely as possible)**: Create a project in Unreal Engine 4.26 or 4.27 and add the Agones Client SDK plugin to the project. Attempt to compile.

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.30
- Others: Unreal Engine 4.26 and Unreal Engine 4.27

**Comment by markmandel** [comment]
@DevChagrins can you prove the output that Unreal 4.26 and/or 4.27 is providing you when you try and compile, so we can identify where the issue is?

It's quite likely older versions will work fine. We may need to split this out per unreal version 😬

**Comment by DevChagrins** [comment]
I don't have the error on hand, I'll have to repull the plugin. But I've got my solution on hand.
The issue is that FUTF8ToTCHAR in UE4 uses ANSICHAR and not UTF8CHAR. Also there is use of TArray::IsEmpty(), which only exists in UE5 but replacing it with just a call to Num() and checking it against 0 accomplishes the same thing.

```
#if ENGINE_MAJOR_VERSION > 4
typedef UTF8CHAR UTF8FromType;
#else
typedef ANSICHAR UTF8FromType;
#endif

void UAgonesComponent::HandleWatchMessage(const void* Data, SIZE_T Size, SIZE_T BytesRemaining)
{
	if (BytesRemaining <= 0 && (WatchMessageBuffer.Num() == 0))
	{
		FUTF8ToTCHAR Message(static_cast<const UTF8FromType*>(Data), Size);
		DeserializeAndBroadcastWatch(FString(Message.Length(), Message.Get()));
		return;
	}

	WatchMessageBuffer.Insert(static_cast<const UTF8CHAR*>(Data), Size, WatchMessageBuffer.Num());
	if (BytesRemaining > 0)
	{
		return;
	}

	FUTF8ToTCHAR Message((const UTF8FromType*)WatchMessageBuffer.GetData(), WatchMessageBuffer.Num());
	DeserializeAndBroadcastWatch(FString(Message.Length(), Message.Get()));
	WatchMessageBuffer.Empty();
}
```

**Comment by markmandel** [comment]
Thanks for the fix! Would you be interested in submitting this as a PR please?
