### ISSUE TITLE
Detect allocated gameservers more then X-time via metrics

### ISSUE THREAD

**Issue by bolom009** [googleforgames/agones#3041]
Hello everyone, I'm wondering if I could via Agones metrics detect allocated gameservers more then 1 hour? I have average gamesession ~1 hour, sometimes my gameservers stucking (seems never shutdown) and I wanna detect them. So how to detect allocated gameservers more then 1 hour via metrics? Is it possible with this doc https://agones.dev/site/docs/guides/metrics/#metrics-available?

**Comment by markmandel** [comment]
Sorry, not sure how this slipped through the cracks - 

Metrics by their very nature are aggregate, therefore they cannot be used to query individual game server entries.

If you want to query the K8s API, the docs are here: https://agones.dev/site/docs/guides/access-api/
