### ISSUE TITLE
The images and instructions around the helm test seem incomplete

### ISSUE THREAD

**Issue by charles-mersereau** [googleforgames/agones#3042]
The image shown for the tests running and being passed doesn't show up for me. I get this image:

![image](https://user-images.githubusercontent.com/69366885/227620563-a4050382-5545-4012-a74d-bfd3b8ffc957.png)

Also, the tip afterwards about the --cleanup flag are totally random. It isn't mentioned previously when you are supposed to use that flag, so how could we miss or skip it when it's nowhere to be seen?

**Comment by markmandel** [comment]
Just providing documentation context: https://agones.dev/site/docs/installation/install-agones/helm/#helm-test

Not sure if anyone has run these steps in a very long time. Worth checking, and if they no longer work, delete them.
