### ISSUE TITLE
GSA selector for active/inactive gsSet

### ISSUE THREAD

**Issue by foriequal0** [googleforgames/agones#3087]
We use Agones for short multiplay sessions (~10m per sessions)
Naturally, we wanted to a rolling update plan like this:
1. Keep scaling down old non-Allocated gs (buffers), while scaling up new gsSet when the Fleet is updated.
2. Incoming users are allocated to new active gameservers.
3. Sessions are short, so old gsSet is fully drained soon.

But we found that we can't do 2. using current selectors of GSA.
We might be able to do that by manually labeling gsSet and GSA, but it is cumbersome and prone to error.

**Comment by markmandel** [comment]
I think this is duplicate of:

* https://github.com/googleforgames/agones/issues/2682

Which is currently underway. (I have the code, I need to finish submitting it all -- sorry, GDC got in the way).

Please let me know if I'm wrong in this though, and you want something different.

**Comment by markmandel** [comment]
🤔 interesting question. It probably depends what the end user wants to optimise on: Infrastructure packing or speed of moving to a new version - and that might go either way I feel.

**Comment by gongmax** [comment]
Interesting, we might be able try the best to learn end user's preference, i.e. if the `scheduling` is packed, then they may prefer infrastructure packing.
