### ISSUE TITLE
Graduate `ResetMetricsOnDelete` to Beta

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#3100]
I propose that we graduate the `ResetMetricsOnDelete` feature to beta. It has been in alpha since 1.26.0. 

Context:
https://development.agones.dev/site/docs/guides/feature-stages/#feature-gates

**Comment by markmandel** [comment]
@rcreasey did you end up taking this feature for a spin? Wanted to check before promoting to beta.

**Comment by markmandel** [comment]
I think this is okay to upgrade, since it's behind a gate and can be turned off.
