### ISSUE TITLE
Publish the CRD OpenAPI schemas

### ISSUE THREAD

**Issue by clrxbl** [googleforgames/agones#3113]
**Is your feature request related to a problem? Please describe.**
https://github.com/googleforgames/agones/issues/3112

In addition to this, it would be great to have these schemas available as .json files somewhere in the Git repository, as Kustomize can read from URLs.

**Describe the solution you'd like**
Publish CRD OpenAPI schemas in the Github repository.

**Describe alternatives you've considered**
Exporting schemas locally.

**Additional context**
N/A

**Comment by markmandel** [comment]
Bumping to keep open a while longer. Would love more feedback.
