### ISSUE TITLE
Slow node address update results in spurious migration event

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#3115]
Reported [on Slack](https://agones.slack.com/archives/C9DGM5DS8/p1681897403607789):

On a GKE private cluster with autoscaling, user is seeing "mass migration events" of `GameServers`, with `Node migration occurred` in the event stream. The problem is here: https://github.com/googleforgames/agones/blob/a5af67743f1ff0dbc21b8d1d19c207a8fd505499/pkg/gameservers/migration.go#L182-L188

The `address()` derived here is identical to how it was populated in the `GameServer` in the first place: https://github.com/googleforgames/agones/blob/3c38876382d505244af68489211d8916dce07596/pkg/gameservers/gameservers.go#L37-L43

But for some reason (that I haven't reproduced yet), on the user's cluster, the `InternalDNS` entry is late-bound on the `Node` object, meaning that when the `GameServerController` populates the `GameServer` address, it sometimes populates the `InternalIP` and sometimes populates the `InternalDNS`, but then later the `address()` call in `MigrationController` picks up `InternalDNS` and thinks it's a migration.

I haven't quite found the set of conditions to repro this, but there is a relatively simple fix: In `MigrationController`, tolerate any address we find on the `Node`.

**Comment by markmandel** [comment]
> But for some reason (that I haven't reproduced yet), on the user's cluster, the `InternalDNS` entry is late-bound on the `Node` object

That seems like a bigger issue - as otherwise there's no guarantee which type of address you would get on the node.

#3089 might actually be the answer?

**Comment by zmerlynn** [comment]
#3089 is definitely _an_ answer, but I don't see a compelling reason we can't make the MigrationController robust to this scenario in the first place.

In my repro attempts we almost always assign an IP and DNS name together, so I haven't narrowed down where that delay is coming from.

**Comment by markmandel** [comment]
From memory the migration controller checks name and address, as there no guarantee that a node _won't_ get the same name as a previously created and then deleted node - so better to check both name and address details (although addresses could be reused as well - but getting both seems very rare) -- maybe we should look at a node UID or something instead.

Also... how is a node getting new addresses? That's a neat trick.

**Comment by zmerlynn** [comment]
@markmandel The MigrationController checks for the address the same way it's generated, which has a preference order. See #3116 for a proposed fix by @luckyswede. :)

**Comment by markmandel** [comment]
That's a clever approach - check all the addresses 😄
