### ISSUE TITLE
GKE Autopilot  no endpoints available for service "agones-controller-service"

### ISSUE THREAD

**Issue by VINNUSAURUS** [googleforgames/agones#3122]
**What did you do**:

kubectl create -f fleet-autoscaler.yaml 

**What happened**:

Error from server (InternalError): error when creating "fleet-autoscaler.yaml": Internal error occurred: failed calling webhook "mutations.agones.dev": failed to call webhook: Post "https://agones-controller-service.agones-system.svc:443/mutate?timeout=10s": no endpoints available for service "agones-controller-service"

**How to reproduce it**:

install Agones on GKE , wait for install to complete then apply "kubectl create - fleet-autoscaler.yaml"

**Anything else we need to know?**:

the command "kubectl get apiservices" gives this
![Screenshot from 2023-04-23 21-54-15](https://user-images.githubusercontent.com/13611461/233963300-74d0db75-e5de-4828-8271-385512fd843c.png)
**Environment**:
- Agones version: 1.31.0

- Kubernetes version (use `kubectl version`): 1.24
- Cloud provider or hardware configuration: GKE Autopilot
- Install method (yaml/helm): YAML and HELM

**Comment by aimuz** [comment]
It seems to be an installation exception, some components are not installed successfully

```bash
kubectl get all -n agones-system
```

**Comment by VINNUSAURUS** [comment]
Everything is installed, i have checked, may be it is autopilot problem in creating resources ?

**Comment by VINNUSAURUS** [comment]
> It seems to be an installation exception, some components are not installed successfully
> 
> ```shell
> kubectl get all -n agones-system
> ```

Everything is installed, i have checked, may be it is autopilot problem in creating resources ?

**Comment by aimuz** [comment]
You can execute this again and see 

```bash
kubectl get ep -n agones-system
```

If the ENDPOINTS of agones-controller-service is present, then you can execute the creation again to see

```
kubectl create -f fleet-autoscaler.yaml
```

**Comment by VINNUSAURUS** [comment]
> 

i got this for kubectl get ep -n agones-system

![controller-service](https://user-images.githubusercontent.com/13611461/233990166-387af684-2af0-4b92-b3cb-69fbc57e8254.png)

and this is status in the allocator pod 

![status](https://user-images.githubusercontent.com/13611461/233990433-105e52c9-3a18-40b6-a2a3-beaf6522284c.png)
