### ISSUE TITLE
Inconsistent/flaky test causing cloud builds to fail 

### ISSUE THREAD

**Issue by chiayi** [googleforgames/agones#3144]
**What happened**:
Cloud build e2e step 24 "submit-e2e-test-cloud-build" fails due to flaky tests and causing builds to fail. Tests in questions are inconsistent and is different every time. This is blocking PRs from being merged. 

**How to reproduce it (as minimally and precisely as possible)**:
Running any cloud builds multiple times will most likely result in multiple cloud build failures.

**Comment by chiayi** [comment]
PR https://github.com/googleforgames/agones/pull/3142 has fix for flaky test `TestAllocatorAfterDeleteReplica`

**Comment by zmerlynn** [comment]
This has been mostly resolved.
