### ISSUE TITLE
Deleting a gameserver with kubectl delete causes the gs to be stuck in the same state for terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by steven-supersolid** [googleforgames/agones#3159]
**What happened**:
A Ready gs remained Ready for the duration of `terminationGracePeriodSeconds` after executing `kubectl delete gs gsId` despite the application container receiving a SIGTERM and exiting

**What you expected to happen**:
The gs should have shut down as soon as the application container exited

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable eviction safe: Always
2. Add a terminationGracePeriodSeconds long enough to observe the problem e.g. 600
3. Have a gs that exits on SIGTERM and with logging
4. Have the gs in the Ready state with id gsId
5. Execute on the command line `kubectl delete gs gsId`
6. Note that the gs will remain in the Ready state when shown via `kubectl get gs` for 10 minutes
7. Note that the pod will be in the terminating state when shown via `kubectl get pods` for 10 mintes

**Anything else we need to know?**:
In the logs we can see the sidecar container is stopped before the gameserver and this may be the cause
Example pod logs
```
INFO 2023-05-16T18:30:47Z [resource.labels.podName: game-9jshz-9jf8r] Stopping container agones-gameserver-sidecar
INFO 2023-05-16T18:30:47Z [resource.labels.podName: game-9jshz-9jf8r] Stopping container game
INFO 2023-05-16T18:30:47.467529165Z [resource.labels.containerName: game] SIGTERM received
INFO 2023-05-16T18:30:47.617353965Z [resource.labels.containerName: game] Shutdown complete
```
10 minutes later the gs pod is removed and a replacement is launched
```
INFO 2023-05-16T18:40:49Z [resource.labels.podName: game-9jshz-vxs7t] Container image "us-docker.pkg.dev/agones-images/release/agones-sdk:1.30.0" already present on machine
INFO 2023-05-16T18:40:49Z [resource.labels.podName: game-9jshz-vxs7t] Created container agones-gameserver-sidecar
INFO 2023-05-16T18:40:49Z [resource.labels.podName: game-9jshz-vxs7t] Started container agones-gameserver-sidecar
INFO 2023-05-16T18:40:49Z [resource.labels.podName: game-vxs7t] Container image "game:1234" already present on machine
INFO 2023-05-16T18:40:49Z [resource.labels.podName: game-9jshz-vxs7t] Created container game
INFO 2023-05-16T18:40:49Z [resource.labels.podName: game-9jshz-vxs7t] Started container game
INFO 2023-05-16T18:40:49.634976696Z [resource.labels.containerName: agones-gameserver-sidecar] Starting sdk sidecar
INFO 2023-05-16T18:40:49.635927705Z [resource.labels.containerName: agones-gameserver-sidecar] Created GameServer sidecar
INFO 2023-05-16T18:40:49.639231058Z [resource.labels.containerName: agones-gameserver-sidecar] Starting SDKServer grpc service...
INFO 2023-05-16T18:40:50.056759602Z [resource.labels.containerName: game] Starting up
```

**Environment**:
- Agones version: 1.30.0
- Kubernetes version (use `kubectl version`): v1.25.8
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

**Comment by zmerlynn** [comment]
I discovered this bug while working on something else, but forgot to file it as an issue. If you're willing to test a dev build, are you willing to try out #3157 to see if it fixes your issue?

**Comment by zmerlynn** [comment]
Huh, that's a new one. I forgot to warn you about #2796, but that issue doesn't mentioned any issue with `agones.image.release`. @gongmax any ideas? (I'm OoO next week, tagging you in for continuity.)

**Comment by zmerlynn** [comment]
Oh, it is #2796, I just didn't note the release/registry discrepancy there but did call out the right options.

@steven-supersolid To install #3157, try: `helm upgrade agones ./install/helm/agones --namespace agones-system --set agones.image.registry=us-docker.pkg.dev/agones-images/ci --set agones.image.tag=1.32.0-64b227b-amd64 --set agones.image.sdk.tag=1.32.0-64b227b-amd64` (or `install` if it's a fresh cluster).

**Comment by steven-supersolid** [comment]
Great, thanks. I think the image expired but I'll try a newer one from main seeing as the PR is merged

**Comment by steven-supersolid** [comment]
It works! The gs shuts down as soon as the application pod exits and a replacement is launched
Also not seeing any errors with calls to the sdk server during the shutdown phase, e.g. our application still calls allocate and then shutdown when receiving a SIGTERM although this may not be necessary now

**Comment by steven-supersolid** [comment]
I've checked again on Agones 1.32.0 and the issue is resolved 🎉
