### ISSUE TITLE
`make site-server` is failing with a git error about dubious ownership of files

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#3169]
**What happened**: Running `make site-server` failed with the error:

```
Failed to read Git log: fatal: detected dubious ownership in repository at '/go/src/agones.dev/agones'
To add an exception for this directory, call:

    git config --global --add safe.directory /go/src/agones.dev/agones
```

**What you expected to happen**: It used to work without any complaints from git; it would be super handy if it still did as iterating on the docs locally is a whole lot faster than sending a PR to let the CI system generate the website. 

**How to reproduce it (as minimally and precisely as possible)**: `make site-server` (I'm on a linux machine)

**Anything else we need to know?**:

**Environment**:
- Agones version: development
- Kubernetes version (use `kubectl version`): _n/a_
- Cloud provider or hardware configuration: Running locally on a linux machine. 
- Install method (yaml/helm): _n/a_
- Troubleshooting guide log(s): _n/a_
- Others: _n/a_

**Comment by roberthbailey** [comment]
I was able to temporarily work around the issue by modifying the `site-server` target in https://github.com/googleforgames/agones/blob/main/build/includes/website.mk to run `git config --global --add safe.directory /go/src/agones.dev/agones` prior to running `hugo server ...`. But running `make shell` and fixing the permissions didn't help because it only fixes it for that particular instantiation of the image and not future executions. 

Possible fixes:

1. Commit my local hack that fixes it
2. Modify the dev container creation to include the above hack
3. See if there is a way to more persistently fix permissions in the dev container

@igooch found [an article](https://jtreminio.com/blog/running-docker-containers-as-current-host-user/) that explains an approach for fixing permissions that I think might work well. We can determine the host system's user/group id easily in the Makefile and pass that into the docker commands that we run. I'm a bit concerned that this will be a pretty invasive change to our build files, since we execute docker in a whole lot of places.

**Comment by Kalaiselvi84** [comment]
The command `make site-server` is still encountering an issue and producing the error message: "Error: Error building site: open /go/src/agones.dev/agones/site/resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.json: permission denied."

**Comment by Kalaiselvi84** [comment]
The permission issue was resolved by running the `sudo chown -R userID:groupID /path/to/agones/` command.
