### ISSUE TITLE
Collaborator Request

### ISSUE THREAD

**Issue by nickschuetz** [googleforgames/agones#3185]
If you'd like to become a collaborator of the Agones repo on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join. Once accepted you'll be able to have issues assigned to you! 

### GitHub user id
- List your GitHub user id

nickschuetz

### Company affiliation
- List your company name, or indicate Individual if you're not affiliated with a company

Red Hat

### Requirements

- [X] I have reviewed the [contribution guidelines](https://github.com/googleforgames/agones/blob/main/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Agones Slack workspace](https://join.slack.com/t/agones/shared_invite/enQtMzE5NTE0NzkyOTk1LWU3ODAyZjdjMjNlYWIxZTAwODkxMGY3YWEyZjNjMjc4YWM1Zjk0OThlMGU2ZmUyMzRlMDljNDJiNmZlMGQ1M2U)

**Comment by markmandel** [comment]
@nickschuetz thanks for your application.

I'm not seeing much engagement with this project yet, but we're excited to have you come and join the project.

Could you provide some thoughts on what you would be interested in working on, if you are looking at any specific issues, etc?

**Comment by markmandel** [comment]
Sorry this ended up languishing for so long. There was an implicit requirement to have done some work (i.e. have a PR that's been merged or similar) before becoming a collaborator on the project -- but it wasn't documented, which it should have been.

I just documented it with #3922 so I'm going to close this -- but if you ever want to swing back around and start contributing, we'd love to have you.
