### ISSUE TITLE
How many Agones versions should we keep on the website.

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#3222]
This is what we currently have:

![image](https://github.com/googleforgames/agones/assets/298370/eaf27741-a825-4ce8-a151-c302f1330b76)

Which is ... a lot, and for many people, the list flows off their screen, so they can't even see it.

Also, many older versions of K8s aren't even supported anymore. 1.5.0 is on Kubernetes 1.15.0.

My initial suggestion would be to keep the past 2 years of releases (so 16/17 of them depending on how you round), and remove one every time we add one at release time.

**Comment by markmandel** [comment]
Since nobody has commented - let's do 17.

Will also need updates to the release checklist.

**Comment by Kalaiselvi84** [comment]
Should we only delete the old version before 17 from this file https://github.com/googleforgames/agones/blob/main/site/layouts/partials/navbar.html, or should the release blogs be removed as well?

**Comment by markmandel** [comment]
Just delete them from the dropdown, I don't think we need to remove historical blogs for any reason.
