### ISSUE TITLE
Bug in the ServiceMap config of the SplitControllerAndExtensions feature

### ISSUE THREAD

**Issue by erickuiper** [googleforgames/agones#3244]
**What happened**:
While deploying The Agones Helmchart (v1.32.0) and dashboards (from main) I was unable to display any data.

**What you expected to happen**:
Metrics would come in to Prometheus and data would be shown on the Grafana dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Agones and prometheus-stack charts, and deploy the the dashboard configmaps.

**Anything else we need to know?**:
Have resolved the issue by adding the following featureGate setting.
`agones.featureGates: "SplitControllerAndExtensions=false"`

**Environment**:
- Agones version: 1.32.0
- Kubernetes version (use `kubectl version`): v1.27.1
- Cloud provider or hardware configuration: AKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
I have traced the issue back to SplitControllerAndExtensions featureGate, this feature updates the agones-controller-service label to use 'agones.dev/role: extensions' instead of 'agones.dev/role: controller'. While the ServiceMonitor 'agones-controller-monitor' still remains configured with the matchLabels 'agones.dev/role: controller'. This prevents Prometheus of finding any service to scrape, so no data is gathered. After adding the override `agones.featureGates: "SplitControllerAndExtensions=false"` to the helm values, the label of the service reverted to controller and Prometheus was able to discover the service and scrape metrics.
- Others:

**Comment by aimuz** [comment]
https://github.com/googleforgames/agones/pull/3242

In process

**Comment by aimuz** [comment]
ref: https://github.com/googleforgames/agones/issues/3190

**Comment by markmandel** [comment]
Should we close this as duplicate to #3190 or is this different? - @chiayi ?

**Comment by chiayi** [comment]
@markmandel Yes, this is a duplicate to https://github.com/googleforgames/agones/issues/3190.

**Comment by markmandel** [comment]
Cool - closing as duplicate, so we have one point of reference to track.
