### ISSUE TITLE
Golang SDK `WatchGameServer` logs error on shutdown

### ISSUE THREAD

**Issue by clairesc** [googleforgames/agones#3245]
**What happened**:

I have a GameServer that uses the Golang SDK. For this GameServer I register a callback using `WatchGameServer`.

When the GameServer shuts down, for example on Fleet scale down, I often get error logs that I believe are not really errors.

More specifically here https://github.com/googleforgames/agones/blob/main/sdks/go/sdk.go#L142C3-L142C3
and here https://github.com/googleforgames/agones/blob/main/sdks/go/sdk.go#L145

**What you expected to happen**:

1. In the first case, when `err == io.EOF` I think the log should not be an error at all, as `EOF` signals that the stream was closed gracefully.

2. In the second case, the full error is `error watching GameServer: rpc error: code = Unavailable desc = error reading from server: EOF`. I am not sure why the error is wrapped here and not directly `io.EOF` but in this case, as the GameServer is shutting down, it make sense to get an EOF and maybe it should not be considered an error. 
Maybe we could record the GameServer state in the callback loop, and if the last state was shutdown, then do not log this message as error?

3. This leads me to another question: messages here are logged directly to `os.Stderr`. It would be great if some logger was used instead so it is more configurable. I've seen logrus used in agones implementation. Would it make sense to use it here too? Maybe passing a `*logrus.Entry` as input parameter to `NewSDK()`?

**How to reproduce it (as minimally and precisely as possible)**:

Write a GameServer using Golang SDK and register a callback using `WatchGameServer`. Trigger the GameServer shutdown and check the GameServer logs.

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.32.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
🤔 I think you are right -- but also, I think there might be some context needed for when to log and when not to.

Basically, if GameServer.ObjectMeta.DeletionTimeStamp() is nonzero (i.e. the GameServer is being actively being shut down), we don't log anything.

But if we are still up and running, then getting either of those lines' errors would be a legitimate error I think.

It's possible we could end up in a race condition where the GameServer info has yet to propagate to the sdkserver , so we may get a false positive on an error log, but it would definitely mitigate getting it every time.

WDYT?

**Comment by clairesc** [comment]
Yes you're right, it still makes sense to log an error if EOF happens during normal GameServer runtime.

What about my question regarding the option to use a logger instead of directly writing to stderr?

**Comment by markmandel** [comment]
> What about my question regarding the option to use a logger instead of directly writing to stderr?

Everyone uses different loggers. I wonder if what we really need is a pluggable logger / error handler function that was overwritable.- with the default being what we have now.

Something like (bad go off the top of my head):

```go
type ErrorLog func(error err, msg string)

var Logger ErrorLog = func(error err, msg string) {
  fmt.Fprintf(os.Stderr, msg: %s\n", err)
}
```

Then on init() of a package that uses it, it could be overwritten. 

Another  option could be to make a Logger function part of the SDK object as well.

But something in that vein I think. WDYT?

**Comment by clairesc** [comment]
Yes that would work. My concern is the logs being written directly to stderr/stdout, without customizable formatting, which would be solved.

**Comment by markmandel** [comment]
Handing this over to @Kalaiselvi84 to work on.

**Comment by clairesc** [comment]
Sorry I was away last week and just came back. I see there is a PR already with some comments, I can review once the PR is updated or even pick up the work if that helps. @Kalaiselvi84 let me know.

**Comment by Kalaiselvi84** [comment]
@clairesc can you please review this open PR - https://github.com/googleforgames/agones/pull/3271
