### ISSUE TITLE
Switch Helm Cleanup job to use bitnami/kubectl image

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#3251]
Doing some cleanup, noticed in https://github.com/googleforgames/agones/blob/88c38faa01921adaf9bf0a043b6e8c79ee015a28/install/helm/agones/templates/hooks/pre_delete_hook.yaml#L39-L47

That we are using a personal docker image for `kubectl`. Also doesn't look like it's been updated in 7 months.

We should probably move to https://hub.docker.com/r/bitnami/kubectl or some other organisation supported image for this.

**Comment by aimuz** [comment]
bitnami/kubectl

+1
