### ISSUE TITLE
Cloud Build script for each Example Image

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#3281]
**Is your feature request related to a problem? Please describe.**

Whenever there is an example image to update, our current process is to build locally and then pushed to production. This has a few inherent issues:

1. Sometimes installed Docker versions are different, and have different commands that work (especially about multi-arch).
2. Internet speeds etc.
3. Which version of the base image do you have on your machine
4. It can take a long time to push a windows image.
5. The image tag also has the production name in it, which can be risk for accidental overwrites.

**Describe the solution you'd like**

1. The Makefile default image name has no registry info in it, so that local builds don't have the registry info in them.
2. Replace `make push` (maybe update the name?) to instead submit a cloudbuild.yaml that will run the Makefile, to build the image with the details of the project it is in (so `us-docker.pkg.dev/${PROJECT_ID}/examples`) so it pushes the image to that project's repository. 
**Describe alternatives you've considered**

Leave this alone, and keep it as is. But gives a consistent experience for managing and pushing images.

**Additional context**

1. This also provides the added benefit is that it's easier to do testing on your GCP project without having to pass in your own arguments to the `make push` command.
1. You should still be able to set the REPOSITORY value if you want in `make build`, but it will default to ``
2. Targets `gar-check` and `echo-image-tag` functionality should stay the same, as those are part of our automated release processes, so they will need to be adjusted with this new update.

**Examples checklist**

(I just copied the directories. If there is no image or it's not possible to do (I'm looking at you `unity-simple`), check as done and move on).

* [x] unity-simple
* [x] rust-simple
* [x] allocator-client-csharp
* [x] cpp-simple
* [x] supertuxkart
* [x] allocation-endpoint
* [x] crd-client
* [x] nodejs-simple
* [x] allocator-client
* [x] terraform-submodules
* [ ] simple-game-server
* [x] xonotic
* [x] autoscaler-webhook

**Comment by markmandel** [comment]
@Kalaiselvi84 WDYT? We've been doing a bunch of example image updates recently, figured for future endeavours this would make things easier.

**Comment by Kalaiselvi84** [comment]
> The Makefile default image name has no registry info in it, so that local builds don't have the registry info in them.

I'm a little confused about the requirement here, sorry. Just to clarify, we are using the 'local-includes' directory to provide the REGISTRY information specific to our own project, right

**Comment by markmandel** [comment]
Sorry I meant in each `./example` directory, so for example:
https://github.com/googleforgames/agones/blob/4c07151e15d0caf0abe6bcd5667422bbbc9892f7/examples/xonotic/Makefile#L26

So by default this should be "" so that if built locally it would be "xonotic-example:1.1" , then we could overwrite REPOSITORY when submitting through Cloud Build.

Does that make sense?

**Comment by Kalaiselvi84** [comment]
Could you kindly confirm if the below sample code represents the expected behavior?

Makefile:
```
REPOSITORY ?= ""
push: build
	gcloud builds submit . --config=cloudbuild.yaml --substitutions=_SERVER_TAG=$(server_tag)
```

examples/cloudbuild.yaml:
```
steps:
  # build
  - name: 'make-docker'
    args: ['build']

  # Step to push the Docker image to the Google Container Registry
  - name: 'make-docker'
    args: ['push', '$_SERVER_TAG']

substitutions:
  _SERVER_TAG: us-docker.pkg.dev/${PROJECT_ID}/examples/$(server_tag)


```

**Comment by markmandel** [comment]
Yep - that looks like a good direction 👍🏻

**Comment by markmandel** [comment]
Notes from today's meeting:

1. One cloudbuild.yaml per folder in the `examples` directory (rather than one central one).
1. A separate PR per checkbox is good 👍🏻 
2. If there is no Dockerfile in the example repository, then mark as done and move on (no work needed!)
3. If there is no `push` target in the Makefile, please add it (it should be the same as every other example).

**Comment by markmandel** [comment]
Reopening, since not yet complete.

**Comment by Kalaiselvi84** [comment]
script for `simple-game-server` image is pending in the task list
