### ISSUE TITLE
Verify `make gen-all-sdk-grpc` has been run

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#3303]
#3302 exposes an issue in our CI: We don't verify that `make gen-all-sdk-grpc` has been run. We should enforce that any SDK API (proto, etc) changes regenerate the gRPC, and we should enforce we can still build with the new generation.

cc @markmandel

**Comment by markmandel** [comment]
@Kalaiselvi84 this may be a good job for you, since you've done many of the other ones.

**Comment by Kalaiselvi84** [comment]
I need to add below step in agones/cloudbuild.yaml, when there are any changes to the SDK API, and the system should still be buildable with the updated gRPC code?

- name: "make-docker"
  id: gen-all-sdk-grpc
  waitFor:
    - pull-build-image
  dir: "build"
  args: ["gen-all-sdk-grpc"]

**Comment by zmerlynn** [comment]
@Kalaiselvi84 My thinking was that this would be similar to how `test-gen-api-docs` works, a CI check. It's actually easier than `gen-api-docs` because at least as far as I can tell `gen-all-sdk-grpc` is stable - I.e. you can just run it and see if there's a diff. It's possible this is not the case over time (I.e. something may be non-hermetic in the process), but we can work through that later.

**Comment by zmerlynn** [comment]
This was done in #3349
