### ISSUE TITLE
Unable to view agones_gameservers_state_duration metric 

### ISSUE THREAD

**Issue by pcloud06** [googleforgames/agones#3344]
No

**What happened**: Unable to view agones_gameservers_state_duration metric in our prometheus. We have multiple environments running and all the environments have same issue.

**What you expected to happen**: See metric  agones_gameservers_state_duration in prometheus

**How to reproduce it (as minimally and precisely as possible)**: We have installed using helm from a stable repo and haven't done any change from our end. So a straight forward installation should work. 

**Anything else we need to know?**: We can see other metric like agones_gameservers_state_duration_total, agones_gameservers_state_duration_bucket, agones_gameservers_state_duration_count

**Environment**:
- Agones version: 1.29.0-dev
- Kubernetes version (use `kubectl version`): 1.26.5-gke.1400
- Cloud provider or hardware configuration: GCP
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:
![image](https://github.com/googleforgames/agones/assets/139532019/8ed92684-bf74-4a60-bfa0-030e836bd939)

**Comment by ashutosji** [comment]
Hi @pcloud06,
Could you check the controller log? You can refer this [link](https://agones.dev/site/docs/guides/metrics/#troubleshooting). Also, have you started the gameserver?

**Comment by markmandel** [comment]
`agones_gameservers_state_duration` is a histogram metric, so this looks to be working as expected:

https://prometheus.io/docs/practices/histograms/

Unless there is something missing, I think we can close this issue.

**Comment by pcloud06** [comment]
As I mentioned in Slack thread, we are trying to derive an expression to find the pods which were in allocated state for more than 10 minutes. We are unable to get that from the available metrics.

**Comment by markmandel** [comment]
Metrics by their very nature can't give you information about a specific GameServer - you will need to query the Kubernetes API.

**Comment by pcloud06** [comment]
Is there a link to any documentation or blog post that I can refer to?

**Comment by markmandel** [comment]
I'm going to close this as answered, but please feel free to drop into Slack if you have follow up questions.
