### ISSUE TITLE
Duplicate name collision for Agones events delegates in Unreal engine plugin

### ISSUE THREAD

**Issue by fraglab-admin** [googleforgames/agones#3347]
AgonesComponent.h in Unreal plugin exposes list of delegates with generic names. These names are potentially can be collided with other similar plugins. For example our project uses Agones and Unity Mulitplay plugin which has the same naming for similar events. Particularly the problem is in FAllocateDelegate which is the same Unity Multiplay plugin delegate.

It would be nice to add some kind of code separation to isolate events, for example namespace Agones or Agones prefix.

As temporary solution we have changed FAllocateDelegate to FAgonesAllocateDelegate

It is reproducible in 1.32 version. File AgonesComponent.h. Delegate FAllocateDelegate.

**Comment by markmandel** [comment]
Asking this question as someone who has no idea about Unreal engine 😄 Is there a way we can do this while also being backward compatible? Or would we need to break an API surface?
