### ISSUE TITLE
Possibility to toggle SDKGracefulTermination

### ISSUE THREAD

**Issue by clrxbl** [googleforgames/agones#3405]
**Is your feature request related to a problem? Please describe.**
I set my gameserver terminationGracePeriodSeconds value to something quite high so my gameserver has time to finish any games and other custom logic. With SDKGracefulTermination not existing in older Agones version, this isn't an issue, but after 1.33.0, this causes a behaviour issue where the gameserver container could cease existing while the Agones SDK sidecar will continue to always run until the terminationGracePeriod ends.

**Describe the solution you'd like**
I would like the ability to be able to turn SDKGracefulTermination off.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by markmandel** [comment]
Any reason your game server binary can't call `SDK.Shutdown()` at termination time, so everything will terminate appropriately?

**Comment by clrxbl** [comment]
> Any reason your game server binary can't call `SDK.Shutdown()` at termination time, so everything will terminate appropriately?

You're quick to respond! I was mid-edit on the initial issue.
This is something that I could do but I realize that this is not always an option in the event that the gameserver crashes before it hits this logic.
