### ISSUE TITLE
Please update Unreal Engine Plugin

### ISSUE THREAD

**Issue by fafato1** [googleforgames/agones#3410]
Please update Unreal Engine Plugin!

Unreal Engine it's a little outdated!

**Comment by markmandel** [comment]
Sorry, can you expand - update it how?

**Comment by SpaceBoy27** [comment]
The plugin seems to be incompatible with Unreal Engine 5.2, which is a fairly recent version, so I imagine it needs to be updated to support the latest versions of Unreal.

**Comment by markmandel** [comment]
Closing due to lack of information. Please feel free to reopen a new ticket if there's a specific improvement we can do to the Unreal plugin 👍🏻
