### ISSUE TITLE
GKE KCP upgrade triggered Agones webhook flicker

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#3449]
Still collecting data but user upgraded their KCP on 2023-10-10 and saw an error from our webhook:

```
    "lastTimestamp": "2023-10-09T11:56:05Z",
    "reason": "AutoScalingFleetError",
    "type": "Warning",
    "message": "Error on scaling fleet  from 1 to 0. Error: Internal error occurred: failed calling webhook \"validations.agones.dev\": failed to call webhook: Post \"[https://agones-controller-service.agones-system.svc:443/validate?timeout=10s](https://agones-controller-service.agones-system.svc/validate?timeout=10s)\": no endpoints available for service \"agones-controller-service\"",
```

Trying to understand now why that would be the case.

**Comment by zmerlynn** [comment]
I looked at KCP logs, and I think rather this error is from the middle of a `helm` upgrade of Agones: 
![image](https://github.com/googleforgames/agones/assets/4942464/4cb9ca61-4d00-41aa-aac4-c523a250e3d0)
 (look for highlighted Helm user-agent). (Screenshot timezones are in PT, timestamp above is equivalent of `2023-10-09 04:56:05-07:00`).

That is consistent with our lack of support today for in-place upgrade, sadly. :/

**Comment by kevin-hoog** [comment]
With in-place upgrade, do you mean that there is no support to upgrade Agones in-place and instead we have to uninstall and reinstall it?
