### ISSUE TITLE
Support appProtocol

### ISSUE THREAD

**Issue by hangyoun** [googleforgames/agones#3485]
**Is your feature request related to a problem? Please describe.**
we want to use a gke's gateway for the allocator, so we want to support appProtocol.

**Additional context**

We are using grpc protocol to connect to allocator.
gke's gateway does not support `networking.gke.io/app-protocol`.
https://cloud.google.com/kubernetes-engine/docs/how-to/secure-gateway

Therefore, to connect grpc with gke gateway, you need to set `appProtocol: HTTP2`

**Comment by markmandel** [comment]
Just so I'm clear, you're looking to be able to specify the `appProtocol` on the Allocator gRPC and/or HTTP `Service` records?

So the solution would be to add configuration options to https://agones.dev/site/docs/installation/install-agones/helm/#allocator-service ? Is that what you are looking for?

**Comment by hangyoun** [comment]
That's right.
Adding the appProtocol setting to allocator-service（https://agones.dev/site/docs/installation/install-agones/helm/#allocator-service）will solve the problem
