### ISSUE TITLE
Type is a reserved word in rust

### ISSUE THREAD

**Issue by cm2054** [googleforgames/agones#3547]
**What happened**:
Using the rust SDK I fetch the gameserver object. Inside the Status object gameserver there is an object called Address. Address has a field called type. Type is a reserved word in rust making it impossible to use as a field.

`print!("{}", address.type);
                                 ^^^^ expected identifier, found keyword`

https://github.com/googleforgames/agones/blob/main/sdks/rust/proto/sdk/sdk.proto#L154

**What you expected to happen**:
I expect to be able to access the type field on the address object.

**How to reproduce it (as minimally and precisely as possible)**:
`
let mut sdk = agones::Sdk::new(None, None).await.expect("failed to connect to SDK server");
let gameserver = sdk.get_gameserver().await;
if let Some(status) = gameserver.status {
  for address in status.addresses {
        print!("{}", address.type);
  }
}
`

**Anything else we need to know?**:
Related issue with possible solutions https://github.com/rust-lang/style-team/issues/84

**Environment**:
- Agones version: 1.36.0
- Kubernetes version (use `kubectl version`): v1.28.2
- Cloud provider or hardware configuration:
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Not in front of my computer to see the generated code, but did you try `r#type` ?

https://stackoverflow.com/questions/69871539/is-it-possible-to-define-a-field-use-the-keywords-in-rust

What does the generated code for Address look like?

**Comment by cm2054** [comment]
Ah, yes looks like r#type works around the issue.
