### ISSUE TITLE
gameServerSetCacheEntry doesn`t return updated gs

### ISSUE THREAD

**Issue by keisni** [googleforgames/agones#3554]
https://github.com/googleforgames/agones/blob/69efac2751b124ec3cf7e7d0ad97731195ff126d/pkg/gameserversets/gameserver_state_cache.go#L69-L72

when deletion timestamp detecd, the gs from list is the updated value,  having newer version than d in pendingDeletion. so gs should be apended to the result in this case.

**Comment by markmandel** [comment]
Thanks for filing this issue.

Are you able to provide context on what the user issue is here with Agones, and how to reproduce it.

Unfortunately I'm not sure if we have enough actionable information here to action this ticket.

**Comment by keisni** [comment]
In fact, I didn`t meet any trouble coused by this. I just thought the code here did something obviouslly different from the comment. Even if it really coused instant unconsistency, i thought it wil be fixed eventually. Just misleading code.

**Comment by markmandel** [comment]
Agreed, the comment is confusing - I didn't write the code but I _think_ the point was to return the GameServer with the deletion timestamp when initially set in the cache, rather than when it ultimately hit the Kubernetes control pane.

Not sure if practically it makes any difference.

If you change the code, does anything break?

**Comment by keisni** [comment]
I made the change to my fork and nothing wrong these days.

**Comment by markmandel** [comment]
> I made the change to my fork and saw nothing wrong these days.

Do the unit and integration tests pass?

**Comment by keisni** [comment]
Sorry, may I ask you how to do unit and integration tests? Is there a document I can read?

**Comment by markmandel** [comment]
https://github.com/googleforgames/agones/blob/main/build/README.md
