### ISSUE TITLE
Service account permissions for logging 

### ISSUE THREAD

**Issue by hugosvirak** [googleforgames/agones#3564]
I'm trying to set up cloud logging on my GKE autopilot cluster in Node.js in the game server. Therefore I require the Logs Writer role on the service account.

From what I understand, Agones overrides the default service account and provides an account with specific permissions.

I tried to use a custom service account by setting serviceAccountName yet no pods were created. I assume my custom service account were missing some important roles / permissions.

How can I create a custom service account for Agones? Is this the best approach to use Winston logging in Agones?

**Comment by markmandel** [comment]
Maybe a silly question - does Cloud Logging give you something more over standard foreground logging collection?

if you want to [use your own service account](https://agones.dev/site/docs/advanced/service-accounts/), this is the Agones default service account here: https://github.com/googleforgames/agones/blob/main/install/helm/agones/templates/serviceaccounts/sdk.yaml

(we should link it on that page!)
