### ISSUE TITLE
SDK server does not remove items from lists ( new 1.37 feature )

### ISSUE THREAD

**Issue by jlory** [googleforgames/agones#3593]
**What happened**:

I'm currently heavily testing the new counters and lists feature from Agones 1.37, I noticed that removing an item from a list does not remove the item on the GameServer CRD.

**What you expected to happen**:

I assume that it should be be possible to remove an item from a list and that it will be reflected in the CRD status object.

**How to reproduce it (as minimally and precisely as possible)**:

Create a fleet with a list, add an item to that list, then remove it ( from an sdk so it goes to the sdk server ), describe the GameServer object with kubectl, the item is still in the list.

**Anything else we need to know?**:

I digged into the sdk server and I believe I found the issue, the sdk server holds a list of updates that need to go out https://github.com/googleforgames/agones/blob/v1.37.0/pkg/sdkserver/sdkserver.go#L132 later on we have the function that update the CRD to the k8s api, if it's a success we then clean the counters update buffer but not the list one: https://github.com/googleforgames/agones/blob/v1.37.0/pkg/sdkserver/sdkserver.go#L1233

I did test locally and it's a one liner change minus unit tests:

```go
// Clear the gsCounterUpdates and gsListUpdates
s.gsCounterUpdates = map[string]counterUpdateRequest{}
s.gsListUpdates = map[string]listUpdateRequest{}
```

If the issues is ack by you, I will submit a PR very soon.

**Environment**:
- Agones version: 1.37
- Kubernetes v1.26.11-eks-8cb36c9
- Cloud provider or hardware configuration: AWS
- Install method (yaml/helm): Helm
- Troubleshooting guide log(s):

**Comment by jlory** [comment]
Will re-create that issue~~

**Comment by igooch** [comment]
Thanks for trying it out and catching that! @markmandel can review the PR.

**Comment by jlory** [comment]
Closing this issue since it was fixed by: https://github.com/googleforgames/agones/pull/3606
