### ISSUE TITLE
Request for igooch to become Approver

### ISSUE THREAD

**Issue by igooch** [googleforgames/agones#3600]
### GitHub Username
@igooch 

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have read the [contributor guide](../../../CONTRIBUTING.md)
- [x] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markmandel
- @zmerlynn 

### List of contributions to the Agones project
- PRs reviewed 
  #3560 
  #3552 
  #3549 
  #3548 
  #3545 
  #3541 
  #3537 
  #3536 
  #3529
  #3527
  #3443
  #3358
  #3335
  #3308
  #3280
  #3264
  #3260
  #3259
  #3252
  #3139
  #2982

- PRs authored
  #3546
  #3544
  #3528
  #3524
  #3521
  #3519
  #3516
  #3510
  #3507
  #3505
  #3504
  #3500
  #3488
  #3487
  #3484
  #3445
  #3440
  #3418
  #3407
  #3400
  #3399
  #3396
  #3381
  #3379
  #3378
  #3373
  #3372
  #3322
  #3296
  #3282
  #3211
  #3198
  #3180
  #3150
  #3138
  #3137
  #3117
  #3091
  #3065
  #3040
  #3039
  #3002
  #2983
  #2965
  #2946
  #2914
  #2898
  #2883
  #2819

- Issues responded to
  #3593
  #3579
  #3362
  #2716
  #2279
  #2018

**Comment by zmerlynn** [comment]
You have my approval!

**Comment by markmandel** [comment]
Approved as well! You now have the ability to approve PRs!
