### ISSUE TITLE
GameServer namespace missing from allocation response

### ISSUE THREAD

**Issue by jlory** [googleforgames/agones#3617]
**Is your feature request related to a problem? Please describe.**

I noticed that the allocation response from the allocator does not contains the namespace to which the gameserver belongs.

Example of a response:

```json
{
    "gameServerName": "test-jxoztjwcmaqf-btsdc-m6674",
    "ports": [
        {
            "name": "default",
            "port": 7684
        }
    ],
    "address": "1.2.3.4",
    "addresses": [
        {
            "type": "InternalIP",
            "address": "192.168.22.107"
        },
        {
            "type": "ExternalIP",
            "address": "1.2.3.4"
        },
        {
            "type": "InternalDNS",
            "address": "ip-192-168-22-107.ec2.internal"
        },
        {
            "type": "Hostname",
            "address": "ip-192-168-22-107.ec2.internal"
        }
    ],
    "nodeName": "ip-192-168-22-107.ec2.internal",
    "source": "local",
    "metadata": {}
}
```

**Describe the solution you'd like**
 
Ideally we should have a field for the namespace:

```json
{
    "gameServerName": "test-jxoztjwcmaqf-btsdc-m6674",
    "gameServerNamespace": "default",
    "ports": [
        {
            "name": "default",
            "port": 7684
        }
    ],
    "address": "1.2.3.4",
    "addresses": [
        {
            "type": "InternalIP",
            "address": "192.168.22.107"
        },
        {
            "type": "ExternalIP",
            "address": "1.2.3.4"
        },
        {
            "type": "InternalDNS",
            "address": "ip-192-168-22-107.ec2.internal"
        },
        {
            "type": "Hostname",
            "address": "ip-192-168-22-107.ec2.internal"
        }
    ],
    "nodeName": "ip-192-168-22-107.ec2.internal",
    "source": "local",
    "metadata": {}
}
```

**Describe alternatives you've considered**

 None?

**Additional context**

One of the reason it would be usefull is that for some use cases you need to get / describe a ```GameServer``` on the k8s api server after an allocation, if your ```GameServer``` is running outside of ```default``` it's difficult to find it.

**Comment by ashutosji** [comment]
Hi @jlory,

It is returning the `namespace`.
I described GameServer when it was in ready state and got the same response as mentioned here: https://agones.dev/site/docs/getting-started/create-gameserver/#2-fetch-the-gameserver-status
Also, it's returning the `namespace` once the GameServer is `allocated` as you can see gameserver details here: https://agones.dev/site/docs/getting-started/create-fleet/#4-allocate-a-game-server-from-the-fleet

**Comment by markmandel** [comment]
Maybe you mean from the Allocation Service?

https://github.com/googleforgames/agones/blob/1eb72bc68601725c2138dd5e54e4d1e3052bb4e3/proto/allocation/allocation.proto#L42-L45

So the reason we never returned the `namespace` is the namespace is included in the `AllocationRequest` - Allocations can't go cross `namespace` - so you know what your namespace is when you send it 😄

**Comment by markmandel** [comment]
Just checking in on this question. I thinks it's answered and we can close things - but lemme know if not, and we can dig deeper. Otherwise I'll give this a close shortly.

**Comment by jlory** [comment]
We can close this, I guess we can keep the namespace from the original call, it seems good enough.
