### ISSUE TITLE
[FeatureRequest]: GameServer can run on aws fargate?

### ISSUE THREAD

**Issue by GStones** [googleforgames/agones#3633]
**Is your feature request related to a problem? Please describe.**
Agones can create `GameServer` on [AWS fargate](https://docs.aws.amazon.com/zh_cn/eks/latest/userguide/fargate.html).
Now  create `GameServer` will be pending, because `Pods running on Fargate can't specify HostPort or HostNetwork in the Pod manifest.`

**Describe the solution you'd like**
 With Fargate, we don't have to provision, configure, or scale groups of virtual machines on our own to run containers.    

**Additions**
Or do we have other solutions for this use case?

**Comment by zmerlynn** [comment]
@GStones We did a fair amount of work to support GKE Autopilot (see #2777), which has similar characteristics to Fargate (and opinions about `HostPort`). That said, it required me collaborating directly with the GKE Autopilot team. If you have a contact at AWS that is willing to help with this, or you can figure out some way you'd like to see it implemented yourself, we will accept PRs gladly. But unfortunately, we are not AWS developers.

> With Fargate, we don't have to provision, configure, or scale groups of virtual machines on our own to run containers.
> Or do we have other solutions for this use case?

Yes, you can run on GKE Autopilot. [[blog](https://cloud.google.com/blog/products/containers-kubernetes/auto-scale-your-game-back-end-to-save-time-and-money)][[docs](https://agones.dev/site/docs/installation/creating-cluster/gke/#create-an-autopilot-mode-cluster-for-agones)] :)

**Comment by GStones** [comment]
Thanks for your detailed suggestion.
