### ISSUE TITLE
 runtime.boundsError from watchGameServer

### ISSUE THREAD

**Issue by qhyun2** [googleforgames/agones#3640]
**What happened**:

Sidecar process crashes

**What you expected to happen**:

Sidecar process never crashes, regardless of input

**How to reproduce it (as minimally and precisely as possible)**:

I am interacting with agones using the NodeJS sdk. I am reusing the same gameserver across multiple restarts. My game server code exits, gets restarted then connects to the same gameserver again. This game server might still be allocated from the last finished game, so it needs to be set to ready again. Let me know if there is a better way to ensure that the gameserver is in a ready state.

```
    // wait for ready state to be committed before continuing to premature allocation where the state of the previous server gets carried over and server gets instantly allocated
    // awaiting ready() doesn't necessarily mean the state has been committed, watchGameServer needs to report ready
    // https://agones.dev/site/docs/guides/client-sdks/#function-reference
    const clientSDK = this.clientSDK;
    const readyPromise = new Promise<void>((resolve) => {
      clientSDK.watchGameServer(
        (g) => {
          if (g.status.state === "Ready") resolve();
        },
        () => {}
      );
    });
    await clientSDK.ready();
    await readyPromise;
```

**Anything else we need to know?**:
n/a

**Environment**:
- Agones version: 1.36.0
- Kubernetes version (use `kubectl version`):
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde
- Cloud provider or hardware configuration: AWS, Amazon Linux 2
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
```
{"ctlConf":{"GameServerName":"medium-4bs9s-zgb8b","PodNamespace":"servers","Address":"localhost","IsLocal":false,"LocalFile":"","Delay":0,"Timeout":0,"Test":"","TestSdkName":"","KubeConfig":"","GracefulTermination":true,"GRPCPort":9357,"HTTPPort":9358},"featureGates":"CountsAndLists=false\u0026Example=false\u0026FleetAllocationOverflow=false\u0026PlayerAllocationFilter=false\u0026PlayerTracking=false\u0026PodHostname=true\u0026ResetMetricsOnDelete=true\u0026SplitControllerAndExtensions=true","message":"Starting sdk sidecar","severity":"info","source":"main","time":"2024-02-09T18:34:19.434921673Z","version":"1.36.0"}
W0209 18:34:19.435123       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"gsKey":"servers/medium-4bs9s-zgb8b","message":"Created GameServer sidecar","severity":"info","source":"*sdkserver.SDKServer","time":"2024-02-09T18:34:19.435485156Z"}
{"gsKey":"servers/medium-4bs9s-zgb8b","message":"Connection to Kubernetes service established","severity":"info","source":"*sdkserver.SDKServer","time":"2024-02-09T18:34:19.446843136Z","try":0}
{"grpcEndpoint":"localhost:9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2024-02-09T18:34:19.448284832Z"}
{"httpEndpoint":"localhost:9358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2024-02-09T18:34:19.448979335Z"}
{"gsKey":"servers/medium-4bs9s-zgb8b","message":"Starting workers...","queue":"agones.dev.servers.medium-4bs9s-zgb8b","severity":"info","source":"*sdkserver.SDKServer","time":"2024-02-09T18:34:19.548261609Z","workers":1}
{"error":"context canceled","gsKey":"servers/medium-4bs9s-zgb8b","message":"stream closed with error","severity":"error","source":"*sdkserver.SDKServer","time":"2024-02-09T18:48:24.742620632Z"}
{"error":"context canceled","gsKey":"servers/medium-4bs9s-zgb8b","message":"stream closed with error","severity":"error","source":"*sdkserver.SDKServer","time":"2024-02-09T18:48:24.778610652Z"}
{"error":"context canceled","gsKey":"servers/medium-4bs9s-zgb8b","message":"stream closed with error","severity":"error","source":"*sdkserver.SDKServer","time":"2024-02-09T19:07:49.493424215Z"}
E0209 19:07:49.494045       1 runtime.go:79] Observed a panic: runtime.boundsError{x:2, y:1, signed:true, code:0x3} (runtime error: slice bounds out of range [2:1])
goroutine 71 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d56400?, 0xc0006f2528})
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0003642c0?})
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1d56400, 0xc0006f2528})
	/usr/local/go/src/runtime/panic.go:884 +0x213
agones.dev/agones/pkg/sdkserver.(*SDKServer).sendGameServerUpdate(0xc0003641e0, 0xc00017ec00)
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:1248 +0x7da
agones.dev/agones/pkg/sdkserver.NewSDKServer.func2({0x406ad8?, 0xc00010d2c0?}, {0x1e75f80?, 0xc00017ec00?})
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:184 +0x36
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/src/agones.dev/agones/vendor/k8s.io/client-go/tools/cache/controller.go:250
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/agones.dev/agones/vendor/k8s.io/client-go/tools/cache/shared_informer.go:971 +0xfc
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000583f38?, {0x22df9c0, 0xc0005ad380}, 0x1, 0xc00010dda0)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x405d3d?, 0x3b9aca00, 0x0, 0x0?, 0xc000583f88?)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000594bd0)
	/go/src/agones.dev/agones/vendor/k8s.io/client-go/tools/cache/shared_informer.go:967 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0x85
panic: runtime error: slice bounds out of range [2:1] [recovered]
	panic: runtime error: slice bounds out of range [2:1]

goroutine 71 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0003642c0?})
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1d56400, 0xc0006f2528})
	/usr/local/go/src/runtime/panic.go:884 +0x213
agones.dev/agones/pkg/sdkserver.(*SDKServer).sendGameServerUpdate(0xc0003641e0, 0xc00017ec00)
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:1248 +0x7da
agones.dev/agones/pkg/sdkserver.NewSDKServer.func2({0x406ad8?, 0xc00010d2c0?}, {0x1e75f80?, 0xc00017ec00?})
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:184 +0x36
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/src/agones.dev/agones/vendor/k8s.io/client-go/tools/cache/controller.go:250
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/agones.dev/agones/vendor/k8s.io/client-go/tools/cache/shared_informer.go:971 +0xfc
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000583f38?, {0x22df9c0, 0xc0005ad380}, 0x1, 0xc00010dda0)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x405d3d?, 0x3b9aca00, 0x0, 0x0?, 0xc000583f88?)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000594bd0)
	/go/src/agones.dev/agones/vendor/k8s.io/client-go/tools/cache/shared_informer.go:967 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0x85
```

**Comment by roberthbailey** [comment]
Have you disabled healthchecking? I've tried to reproduce this scenario, but if my game server container exists after being allocated, it moves to the `Unhealthy` state as per the third item in https://agones.dev/site/docs/guides/health-checking/#health-failure-strategy.

**Comment by roberthbailey** [comment]
One other thing I found while looking into this is that https://github.com/googleforgames/agones/issues/2781 implies that to change this requires a code change in Agones - so I'm not sure how I can even reproduce what you are seeing. 

Do you have a minimal game server example that you could share?

**Comment by markmandel** [comment]
So I was looking into the panic on the stacktrace path, and branch, and I'm not sure its related to the reconnect, although maybe?:

```
agones.dev/agones/pkg/sdkserver.(*SDKServer).sendGameServerUpdate(0xc0003641e0, 0xc00017ec00)
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:1248 +0x7da
```

The specific piece of code that panics is:
https://github.com/googleforgames/agones/blob/3e72a6c2d36392baa7b8eef42f75c1c6ab6dac7d/pkg/sdkserver/sdkserver.go#L1248

As part of the function `sendGameServerUpdate(...)`.

This was done to drop disconnected streams from the `SDK.WatchGameServer(...)` operations -- but it really shouldn't panic like this when and if a Watch disconnection happens. At first glace, I'm not sure if this is a race condition, or a bug in the code.

@qhyun2  a couple of quick questions to help us narrow things down:
1. Does this happens all the time with your code above, or only sometimes?
2. My node is super super bad -- it looks like you are disconnecting from the Watch operation once the promise is over? Is that correct? (not sure I understand the code 100%).

If I'm correct on No. 2 and you are disconnecting, a workaround while we investigate is to keep the Watch operation open throughout the lifetime of your `GameServer`, rather than do it as a "one and done" operation (although we should also fix the bug).

**Comment by markmandel** [comment]
Chatting offline with another user - they ran into the same issue. For them, it only happened sporadically.  Makes me wonder if there is a race condition where access/manipulation of the watch channels isn't locked appropriately.

**Comment by qhyun2** [comment]
I can give quite a bit more context now.

> How have you configured healthchecking? I've tried to reproduce this scenario, but if my game server container exists after being allocated (or ready), it moves to the Unhealthy state as per the third item in https://agones.dev/site/docs/guides/health-checking/#health-failure-strategy. Even when I disable healthchecking, I still see my gameserver becomes Unhealthy after exiting.

I do not have health checking on. My game server is wrapped in a script so the agones server never sees it exit, so it never becomes unhealthy.
```
#!/bin/bash

until ! node ./server.js; do
    echo -e "\\n\\nServer exited with code 0, will be restarted...\\n\\n"
    sleep 1
done
```

> One other thing I found while looking into this is that https://github.com/googleforgames/agones/issues/2781 implies that to change this requires a code change in Agones - so I'm not sure how I can even reproduce what you are seeing.
> 
> Do you have a minimal game server example that you could share?

I seem to be doing option 1 of what #2781 is describing. The code snippet I originally posted basically ensures that old state doesn't get reused.

Here is a reproduction of the bug:
https://github.com/qhyun2/agones/commit/0bf7d2262d308dd1c14a232bf1184a5ecdff7926

> 1. Does this happens all the time with your code above, or only sometimes?

In the reproduction above it happens every time. Outside of the reproduction, wasn't happening every time, possibly because process.exit wasn't always being called. It seems like a race condition. My guess is the side car tries to send and update but the watch grpc stream is closed.

> 2. My node is super super bad -- it looks like you are disconnecting from the Watch operation once the promise is over? Is that correct? (not sure I understand the code 100%).

The watch operation is being left open. New events are seen and ignored (additional calls to resolve have no effect). There doesn't seem to be a way to cleanup with the provided API.

**Comment by qhyun2** [comment]
> If I'm correct on No. 2 and you are disconnecting, a workaround while we investigate is to keep the Watch operation open throughout the lifetime of your GameServer, rather than do it as a "one and done" operation (although we should also fix the bug).

**WORKAROUND**

for those coming here from googling the issue

My current work around is to avoid using multiple watch calls. Everything is hooked into a single watch and the crash no longer happens.

**Comment by markmandel** [comment]
> My current work around is to avoid using multiple watch calls. Everything is hooked into a single watch and the crash no longer happens.

Thanks for continuing to dig in - all the information helps us try and work out what's going on.

**Comment by roberthbailey** [comment]
Thank you for the reproduction. I was unable to reproduce using a go game server (based on the simple game server), even after wrapping the crashing game server in a bash script to restart it without triggering Agones' healthchecking and also creating multiple watches. But using your node code I can now see a panic in the sdkserver.
