### ISSUE TITLE
Agones SDK for Unity Client Server  example

### ISSUE THREAD

**Issue by wowSheldon** [googleforgames/agones#3641]
**What happened:**
Encountering compilation errors in the Agones SDK Unity example (release 1.38) with Unity Editor version 2023.2.9f1 on Windows 11. Despite attempting to use Unity Editor version 2018.4.12f1 as recommended in the Agones SDK documentation for Unity, compilation errors persist with the latest Unity installation on Windows 11.

**What you expected to happen:**
Expecting successful compilation with the official latest released version of the Unity editor on Windows 11 and the ability to run the example as expected, considering the SDK's support for Unity.

How to reproduce it (as minimally and precisely as possible):
Attempt to run the Agones SDK Unity example on the official latest released version of the Unity editor on Windows 11.
 
**Anything else we need to know?**:

**Environment**:
Since we are talking about compilation issue following environment variables are not  NA.
- Agones version: using laest version of Agones as on today  
- Kubernetes version (use `kubectl version`):
- kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.9-dispatcher
Kustomize Version: v5.0.1
Server Version: v1.27.3-gke.100
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Is this the same as https://github.com/googleforgames/agones/issues/2800 ? Also - can you share what the compilation errors are?

The Unity plugin unfortunately is tested manually, because licencing (yay lawyercats), so it can definitely fall out of date. Any extra help you can provide here is appreciated.

**Comment by markmandel** [comment]
As an aside: https://github.com/mbychkowski/agones/tree/example/unity-netcode/examples/unity-netcode does exist, although still needs to be pulled into it's own repo 

@mbychkowski not sure if you would be interested in helping update our basic example? or @wowSheldon that would also be appreciated!

**Comment by wowSheldon** [comment]
Hi Mark,

Thank you for your swift response.

Below are the compilation errors encountered for both Unity Editor 2018.4.12f1 and 2023.2.9f1. I'm exploring the integration with Unity and Mirror networking, so it's possible that the issues align with #2800.

Additionally, it's worth noting that the latest 2023 version of Unity opens in safe mode to address compilation errors before fully loading the project. While I attempted to resolve these errors, it resulted in the emergence of more issues (given my limited expertise in C#). Unfortunately, I may not be able to provide substantial assistance with the project at this time.

Your help is appreciated.

**Here are the compilation errors from Unity Editor version 2023.2.9f1:**
**Note: All errors are  mentioning semicolon expected but once you add that it leads to further errors**
##### Output
Assets\Scripts\Agones\AgonesSdk.cs(1,39): error CS1002: ; expected

Assets\Scripts\Agones\model\GameServer.cs(1,49): error CS1002: ; expected

Assets\Scripts\Agones\model\GameServerObjectMeta.cs(1,59): error CS1002: ; expected

Assets\Scripts\Agones\model\GameServerSpec.cs(1,53): error CS1002: ; expected

Assets\Scripts\Agones\model\GameServerStatus.cs(1,55): error CS1002: ; expected

Assets\Scripts\Agones\model\SpecHealth.cs(1,49): error CS1002: ; expected

Assets\Scripts\Agones\third_party\MiniJSON.cs(1,53): error CS1002: ; expected


**Here are the compilation errors from Unity Editor version 2018.4.12f1, as recommended in the Agones SDK documentation for Unity:**

-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp.dll
Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
Copyright (C) Microsoft Corporation. All rights reserved.

Assets\Scripts\Agones\model\GameServer.cs(1,47): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\AgonesSdk.cs(1,37): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\GameServerObjectMeta.cs(1,57): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\GameServer.cs(1,1): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServer.cs(1,23): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\AgonesSdk.cs(1,1): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerObjectMeta.cs(1,1): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServer.cs(1,29): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServer.cs(1,35): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\AgonesSdk.cs(1,20): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServer.cs(1,19): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\GameServerObjectMeta.cs(1,23): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\AgonesSdk.cs(1,26): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\AgonesSdk.cs(1,16): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\GameServerObjectMeta.cs(1,29): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerObjectMeta.cs(1,35): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerObjectMeta.cs(1,19): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\GameServerSpec.cs(1,51): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\GameServerSpec.cs(1,1): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerSpec.cs(1,23): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerSpec.cs(1,29): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerSpec.cs(1,35): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerSpec.cs(1,19): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\GameServerStatus.cs(1,53): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\GameServerStatus.cs(1,1): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerStatus.cs(1,23): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerStatus.cs(1,29): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerStatus.cs(1,35): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\GameServerStatus.cs(1,19): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\SpecHealth.cs(1,47): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\StatusPort.cs(1,47): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\third_party\MiniJSON.cs(1,51): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\model\StatusPort.cs(1,1): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\SpecHealth.cs(1,1): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\StatusPort.cs(1,23): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\SpecHealth.cs(1,23): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\third_party\MiniJSON.cs(1,1): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\StatusPort.cs(1,29): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\SpecHealth.cs(1,29): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\StatusPort.cs(1,35): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\SpecHealth.cs(1,35): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\StatusPort.cs(1,19): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\third_party\MiniJSON.cs(1,23): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\model\SpecHealth.cs(1,19): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Scripts\Agones\third_party\MiniJSON.cs(1,29): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\third_party\MiniJSON.cs(1,41): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Scripts\Agones\third_party\MiniJSON.cs(1,19): error CS0116: A namespace cannot directly contain members such as fields or methods
-----CompilerOutput:-stderr----------
-----EndCompilerOutput---------------

**Comment by markmandel** [comment]
> @markmandel thanks for linking to this. I've since pulled it into a separate repository: https://github.com/mbychkowski/unity-netcode-agones

Oh nice, we should link in https://agones.dev/site/docs/third-party-content/examples/ ! 👍🏻 

> Is there an issue for this to work off of? Happy to take a look to see what needs to be updated here.

This is the issue 😄

**Comment by wowSheldon** [comment]
Hi @markmandel and @mbychkowski ,

Thank you for your continued assistance.

As I explore the Netcode (however I am planning to use Mirror Networking)  for multiplayer game development with Kubernetes/Agones, I've encountered an issue while attempting to run the provided example. I've successfully built both the client and server and managed to run the server image.

However, the client, when executed on Windows, failed to establish a connection with the server, yielding the following error:

Error while running client
Failed to connect to server.
UnityEngine.Debug:LogError (object)
Unity.Netcode.Transports.UTP.UnityTransport:ProcessEvent () (at ./Library/PackageCache/com.unity.netcode.gameobjects@1.7.1/Runtime/Transports/UTP/UnityTransport.cs:889)
Unity.Netcode.Transports.UTP.UnityTransport:Update () (at ./Library/PackageCache/com.unity.netcode.gameobjects@1.7.1/Runtime/Transports/UTP/UnityTransport.cs:938)

To facilitate troubleshooting, I'd like to share details about my game server, including its coordinates. For security reasons (I guess not to give server IP details, where game server is running) could you kindly provide a suitable channel for one-on-one communication where I can share this information securely? Additionally, if you could attempt a connection at your end or provide insights into potential issues, it would be immensely helpful.

Moreover, I understand this may be an extensive request, but if possible, I would greatly appreciate a Unity-Mirror Networking sample, as it could serve as an invaluable reference.

Thank you once again for your support.

**Comment by wowSheldon** [comment]
@markmandel  and @mbychkowski 
As mentioned earlier, I am currently exploring the deployment of a Unity Netcode example on Agones within a Kubernetes environment. However, I am facing some challenges, and I believe my limited knowledge might be the cause for above mentioned issue.

**Suspected Problem:**
I suspect that the issue lies in my attempt to run a simple game server on Agones, following the installation instructions provided on Agones installation douments. I executed the following command to create a game server:

bash
kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-1.38.0/examples/simple-game-server/gameserver.yaml

While the Agones installation was successful, I suspect that the game server might not be correct to run the Netcode example. The port I used for the Netcode example is from this game server might be causing the issue.

Current Status:
After following your instructions to test on a dedicated game server, I found myself lost at a point where I believe I haven't installed the Agones SDK on Kubernetes. I have a Docker image based on your provided steps and an Agones setup on Kubernetes with an Autopilot cluster.
While trying to see what's on Kubctl, I could not find any directory or files like gameserver.yaml or any other SDK files

Objective:
My goal is to connect these two components seamlessly and address the missing links. I am seeking stepwise instructions, presented in layman's terms, to ensure that the built Docker image successfully deploys to Kubernetes.

**Current Platforms/Tools:**

Operating System: Windows 11
Agones installed on Kubernetes cluster (Autopilot)
Unity with Netcode (intending to replace with Mirror networking)
Unity Build module support for Linux (Mono, IL2CPP)
Docker for Windows desktop/laptop

**Steps Completed:**
I have reached a point in your Unity Netcode example (https://github.com/mbychkowski/unity-netcode-agones) where I executed the following Docker build command:

docker build -t agones-example/unity-netcode:latest .
The output from the command is as follows:
[Output Snippet]
C:\Unity_NW\Projects\UnityNetcode\agones-example-unity-netcode\agones-example-unity-netcode\examples\unity-netcode>docker build -t agones-example/unity-netcode:latest .
[+] Building 4.7s (12/12) FINISHED                                                                              docker:default
 => [internal] load build definition from Dockerfile                                                                      0.0s
 => => transferring dockerfile: 648B                                                                                      0.0s
 => [internal] load metadata for docker.io/unitymultiplay/linux-base-image:1.0.1                                          2.4s
 => [auth] unitymultiplay/linux-base-image:pull token for registry-1.docker.io                                            0.0s
 => [internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 2B                                                                                           0.0s
 => [1/6] FROM docker.io/unitymultiplay/linux-base-image:1.0.1@sha256:9f5e156dfcba4dd0587558ff7be8c599f7975c7c5c7613972f  0.0s
 => [internal] load build context                                                                                         2.1s
 => => transferring context: 44.24MB                                                                                      2.1s
 => CACHED [2/6] RUN apt-get update && apt-get install -y                                                                 0.0s
 => CACHED [3/6] WORKDIR /game                                                                                            0.0s
 => CACHED [4/6] COPY Builds/Server/Server_Data/ ./Server_Data/                                                           0.0s
 => CACHED [5/6] COPY Builds/Server/Server.x86_64 .                                                                       0.0s
 => CACHED [6/6] COPY Builds/Server/UnityPlayer.so .                                                                      0.0s
 => exporting to image                                                                                                    0.0s
 => => exporting layers                                                                                                   0.0s
 => => writing image sha256:2bbad6d79991857302361146702703714867fa08541d21e5a05fabdbcc626b9b                              0.0s
 => => naming to docker.io/agones-example/unity-netcode:latest                                                            0.0s

View build details: docker-desktop://dashboard/build/default/default/skie1778u5fg2dpwri4rox5pe

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview

====END===


**Request for Assistance:**
Now, I am seeking guidance on the necessary tools and commands, specific to my platforms, to successfully run this example on Agones. I'm using Windows 11 with a Cloud Shell terminal and need step-by-step instructions to bridge the gap and achieve a functional deployment on the game server.

I appreciate your support and look forward to your assistance.

**Comment by mbychkowski** [comment]
@wowSheldon I am linking this issue to the repository directory. Since I think it might be out of the scope for this Agones repository. Unfortunately, I have not been able to test this solution myself on Windows. I will try to get around to test this.

we can limit this issue to the basic unity example.

Were you able to resolve the issue of running this locally mentioned in https://github.com/googleforgames/agones/issues/3641#issuecomment-1941538642? And now working on a deployment to Kubernetes?

As far as next steps you will need to push your build image to a repository if you plan on having a cluster in the cloud. The [unity-netcode-example](https://github.com/mbychkowski/unity-netcode-agones) uses [Artifact Registry](https://cloud.google.com/artifact-registry),  but you can use Docker Hub or any other repository as long as your Kubernetes cluster has access to pull images from. If you are still testing all this locally, there are some resources on running [Mini Kube](https://agones.dev/site/docs/installation/creating-cluster/minikube/)

**Comment by wowSheldon** [comment]
Hi @mbychkowski 

Thank you for your prompt response. To address your questions:
Here is the clarification on Local Testing and Artifact Registry Creation in Kubernetes Deployment

**Local Testing:**
I haven't tested the Unity Netcode example locally yet, and my current focus is on deploying it to Kubernetes. As I already have Agones installed on Kubernetes, I plan to skip the local testing phase and directly work towards achieving a functional deployment on the cloud.

**Minikube Usage:**
I understand that Minikube is commonly used for local testing; however, my intention is to leverage Agones on a Kubernetes cluster for a scalable, multiplayer Unity game on the cloud. Therefore, I'm not planning to use Minikube in this context.

Regarding the creation of an Artifact Registry, I have some uncertainties:

**Google Cloud Organization:**
As mentioned in Readme.md file regarding **Google Cloud Organization:**, I'm unsure whether I have a Google Cloud Organization. Since I'm working with Kubernetes and Agones, could you clarify whether having a Kubernetes cluster implies having a Google Cloud Organization?

Execution of 'gcloud' Command:
The command provided for creating an Artifact Registry is:

gcloud artifacts repositories create $_ARTIFACT_REPO_NAME \
    --repository-format=docker \
    --location=us \
    --async
I'm uncertain where I should execute this 'gcloud' command. Is it the same place where 'kubectl' commands are executed in the Cloud Shell, or is there a specific context or environment where this should be run?

I appreciate your guidance on these matters and look forward to progressing further with your assistance.

**Comment by markmandel** [comment]
So I'm going to step in here with my contributor hat 👷🏻 on and put a polite end to the back and forth -- this bug is about an issue with compilation of the Unity example, so let's please keep it on topic.

GitHub issues aren't for general back and forth and education - if you wish to continue the discussion, may I suggest either heading over the example repository in question, taking advantage of the [Agones community resources](https://agones.dev/site/community/), and/or taking some time to go through [Prerequisite Knowledge](https://agones.dev/site/docs/prerequisite-knowledge/) documentation section to get comfortable with the foundational technologies.

Thanks!

**Comment by wowSheldon** [comment]
OK Thank you Mark. Closing the issue as there are no compilation issues with Netcode example.

**Comment by markmandel** [comment]
Reopening, as there is still an issue with our other Unity example, that we should definitely fix.
