### ISSUE TITLE
Unable to start simple-game-server on windows node

### ISSUE THREAD

**Issue by 100156994** [googleforgames/agones#3675]
I installed agones with helm chart on eks（CNI：calico）. We encountered a problem when creating the gameserver. The problem was that the container could not be started.
In addition, I tried other images, such as gcr.io/agones-images/simple-game-server:0.13-windows_amd64-ltsc2019, 0.14-windows_amd64-ltsc2019, but they failed to start.
At first I thought it was an incompatibility issue with Windows Server 2022. We tried to modify the node to Windows Server 2019, but this didn't work. （The CRI of our aws eks cluster is containerd://1.6.18.）

In addition, sometimes the pod has the following events:
`Error: failed to start containerd task "simple-game-server": hcs::System::CreateProcess simple-game-server: The system cannot find the file specified.: unknown`
![img_v3_028f_6d541356-bc76-4606-a5d1-a551e65a296g](https://github.com/googleforgames/agones/assets/16000892/2998e1c0-dc7d-48a5-9ae1-66956bf36fda)

The status of the pod is as follows:
![image](https://github.com/googleforgames/agones/assets/16000892/4c7b1279-3725-48e8-852b-31c3b54d7999)

![image](https://github.com/googleforgames/agones/assets/16000892/c511a966-780c-4c02-ab6e-cc394e048f20)

![image](https://github.com/googleforgames/agones/assets/16000892/e263b565-5e39-4539-bf49-92098bbfca55)

  
The status of the node is as follows:
![image](https://github.com/googleforgames/agones/assets/16000892/18f1b226-633c-4bef-bbb7-1b34b8319b03)

![image](https://github.com/googleforgames/agones/assets/16000892/0838e04c-3884-454b-a467-c95510925c7a)

my agones verison is 1.37.0

`helm ls -n agones-system
NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION
my-release agones-system 3 2024-01-23 16:13:46.511267 +0800 CST deployed agones-1.37.0 1.37.0`

My kube version is as follows

`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.12-eks-5e0fdde", GitCommit:"95c835ee1111774fe5e8b327187034d8136720a0", GitTreeState:"clean", BuildDate:"2024-01-02T20:34:50Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.26) exceeds the supported minor version skew of +/-1`

`kubectl get svc -n agones-system

NAME                                TYPE           CLUSTER-IP        EXTERNAL-IP   PORT(S)            AGE
agones-allocator                    LoadBalancer   192.168.123.167   <pending>     443:32047/TCP      34d
agones-allocator-metrics-service    ClusterIP      192.168.207.16    <none>        8080/TCP           34d
agones-controller-metrics-service   ClusterIP      192.168.123.69    <none>        8080/TCP           34d
agones-controller-service           ClusterIP      192.168.137.107   <none>        443/TCP,8080/TCP   34d
agones-extensions-metrics-service   ClusterIP      192.168.13.220    <none>        8080/TCP           34d
agones-ping-http-service            LoadBalancer   192.168.148.220   <pending>     80:30285/TCP       34d
agones-ping-udp-service             LoadBalancer   192.168.208.209   <pending>     50000:32741/UDP    34d`

**Comment by markmandel** [comment]
Thanks for testing this - it's been a while since we've tested things on Windows. It's possible this has broken over time.

**Comment by 100156994** [comment]
I tried modifying the dockfile and successfully ran the game server in the local windows container.
The previous error was that the corresponding file could not be found. I think the possible reason is that / was missing when copying the compiled product to the container in dockerfile.windows.
#COPY --from=builder /go/src/agones.dev/agones/examples/simple-game-server/simple-game-server.exe /server

**Comment by markmandel** [comment]
If you could submit a PR, that would be awesome 👍🏻
