### ISSUE TITLE
MaxSurge and MinAvailable calculated incorrectly

### ISSUE THREAD

**Issue by nrwiersma** [googleforgames/agones#3688]
**What happened**:

We see a very sharp decline in `Ready` GameServers when rolling over to a new GameServerSet, leading to having no `Ready` GameServers in the pool while the new version is stuck in `Scheduled` due to the nodes downloading images.

**What you expected to happen**:

A smooth rollout with `Ready` GameServers always available.

**How to reproduce it (as minimally and precisely as possible)**:

When we investigated this, it seems there is a difference between what the docs say here: https://agones.dev/site/docs/guides/fleet-updates/#rolling-update-strategy

> By default, a Fleet will wait for new GameSevers to become Ready during a Rolling Update before continuing to shutdown additional GameServers, only counting GameServers that are Ready as being available when calculating the current maxUnavailable value which controls the rate at which GameServers are updated.

and what we see in the calculation for `MinAvailable`:

https://github.com/googleforgames/agones/blob/main/pkg/fleets/controller.go#L555

It also stands to reason the `MaxSurge` is calculated in relation to how `MinAvailable` is, and should probably not be based on `fleet.Spec.Replicas` either.

With some real world numbers from one of our clusters, we have:

Replicas: 3.46K
ReadyReplicas: 194
AllocatedReplicas: 3.22K
MaxSurge: 10%
MinAvailable: 10%

With the current calculation it is allowed to terminate 346 GameServers in the first round, but we only have 194 `Ready`, so all `Ready` GameServers are terminated. Were this based on `Ready` GameServers, it would be allowed to terminate 19, which is a rather large difference.

**Anything else we need to know?**:

Another thing that struck me as odd in the calculation is `cleanupUnhealthyReplicas`:

https://github.com/googleforgames/agones/blob/main/pkg/fleets/controller.go#L529

This seems to consider everything that is not `Ready` as unhealthy but seems to ignore `Allocated` which strikes me as wrong.

It might also be a good idea to set `Replicas` to 0 on a non-active GameServerSet when `Allocated` == `Replicas`.

**Environment**:
- Agones version: 1.37.0
- Kubernetes version (use `kubectl version`): 1.27.3-gke.100
- Cloud provider or hardware configuration: GKE n2-custom-40-163840
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Need to dig in deeper, but feels like there is some overlap with https://github.com/googleforgames/agones/issues/3438 here.

**Comment by nrwiersma** [comment]
It is possible that it is a contributing factor, but the issue here stands alone, and the situation is its own issue. Where in #3438 the Rollout gets stuck, here we are removing way too many Ready GameServers, to the point of having none left if your buffers are too low. I would naively assume the Rollout will still get stuck were this fixed, it would be get stuck slower.

**Comment by markmandel** [comment]
I don't disagree - more I'm thinking if we dig in and solve one, should probably solve the other at the same time. I expect they'll cross paths in implementation.

**Comment by Reasonably** [comment]
This case is similar to issue #3438, and I believe that the feature in PR #3762 could also be beneficial here.

- If an update is made during live service in a game, new game server sets (GSS) will continuously receive allocations.
- In such cases, the new GSS will eventually match the `fleet.spec` value, maintaining a buffer amount of ready replicas.
- However, there can be scenarios where the old GSS remains, and the update gets stuck.
- According to [this section](https://github.com/googleforgames/agones/blob/main/pkg/fleets/controller.go#L598-L601) in the code, if the number of minAvailable is greater than the ready replicas, the update halts.
- Typically, the number of ready replicas of the new GSS will be close to the buffer. If the buffer is 20% and the max unavailable value is also 20%, then the min available will be 80% of the fleet, meaning ready replicas cannot exceed this number.
- Using the new feature would calculate based on the ready replicas, thus eliminating such cases.

Additionally, if the ready count for the old GSS drops to zero, setting the replicas to zero could also be beneficial. This would facilitate a quicker transition to new servers, particularly in cases where the update has already been completed or there is a shortage of game servers.
