### ISSUE TITLE
End to End test

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#37]
Write a end to end test - possibly, using make and kubectl, or maybe use code - what is the best option?
- installation
- Creating a GameServer
- Connecting

Will likely need to both check that a connection works with the go sample (edit to send a message via a flag, rather than stdin), but also will need to check the C++ sdk works as well.

I din't think there are any e2e integration test libraries that exist for Kubernetes platforms - but do have a look first. May be worth looking at how Kubernetes itself does it.

**Comment by addisonbair** [comment]
I am new to this project and haven't yet stood up the development environment yet, but it appears that Kubernetes itself uses Ginkgo, Gomega and the Kubernetes API itself for much of the end-to-end testing of a particular release.

https://github.com/kubernetes/kubernetes/tree/master/test/e2e

Here's a simpler example from the Prometheus Operator project:

https://github.com/coreos/prometheus-operator/tree/master/test/e2e

**Comment by Kuqd** [comment]
Should I start by some simple e2e go test and may be bring this later into an image to support in-cluster config.

I quite like the prom-operator example.

**Comment by markmandel** [comment]
The other option is using the Helm test tooling? Or maybe there is a combo option?

Or if I follow - you're saying, start with a simple binary we can run and point at a cluster, and then move forward from there? That would make sense (assuming that's what you are suggesting)

**Comment by Kuqd** [comment]
yes, I want to add the helm integration after, using a container.

**Comment by markmandel** [comment]
Sounds like a good approach to me!

**Comment by markmandel** [comment]
Got another one for you - if health checking is disabled, then the game server shouldn't be marked as unhealthy if no health pings are sent (just found this as a bug, and it's only going to get covered by e2e test)

But yes - we should prioritise, and we can work through them slowly each as a separate PR. Also happy to defer to your opinion on the order.

**Comment by markmandel** [comment]
Just updated this with what I completed on e2e tests.

**Comment by thisisnotapril** [comment]
Repo health check - should we keep this issue open?

**Comment by markmandel** [comment]
There are still a few left on the list (I cleaned things up a bit above) that would be good to have I think.

**Comment by markmandel** [comment]
I think this is actually good to close now. If anyone disagrees, please let me know, otherwise I'll close this next Monday.

**Comment by markmandel** [comment]
Closing!
