### ISSUE TITLE
Inaccurate examples for Counter/List in fleetautoscaler.md.

### ISSUE THREAD

**Issue by portlek** [googleforgames/agones#3701]
**What happened**:
I believe that counter/list examples in the document are not correct.

https://agones.dev/site/docs/reference/fleetautoscaler/#counter-and-list-autoscaling

The Counter's example uses 'players' key while describing it as counting of rooms, and the List's example uses 'rooms' key while talking about player names/list.

Either I didn't understand the concept of Counters/Lists or 'players' and 'rooms' keys should be replaced.

What made me suspicious is that while I'm reading the documentation for Counter/List autoscaling something didn't make sense to me. I believe that Lists can hold strings and Counters is just a simple counting number, I'm confused at that point because rooms have no names, but players can have, obviously. So it would make more sense to use a list of players than a count of players, no?

**Comment by markmandel** [comment]
You are 100% right - the fixes are in this PR:

* https://github.com/googleforgames/agones/pull/3649

Just been waiting on some other changes to land before merging.

**Comment by markmandel** [comment]
This should be fixed now - if you could take a peek and confirm, and we can close this issue.
