### ISSUE TITLE
Scale Down by Percent CounterPolicy or ListPolicy Can Lead to 0 Replicas

### ISSUE THREAD

**Issue by igooch** [googleforgames/agones#3715]
**What happened**:

Previously allowed behavior, scale to 0 replicas, was not updated. The percent buffer when there are no allocated Counters / Lists gets calculated as 0 https://github.com/googleforgames/agones/blob/732c075b90ae1f5b6da4810f05808496f612da3b/pkg/fleetautoscalers/fleetautoscalers.go#L318-L325 which is not allowed per https://github.com/googleforgames/agones/blob/732c075b90ae1f5b6da4810f05808496f612da3b/pkg/apis/autoscaling/v1/fleetautoscaler.go#L323-L325. 

**What you expected to happen**:

Do not let the fleetautoscaler buffer or desired replicas go to 0.

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/googleforgames/agones/blob/732c075b90ae1f5b6da4810f05808496f612da3b/pkg/fleetautoscalers/fleetautoscalers_test.go#L1895

**Anything else we need to know?**:

**Comment by markmandel** [comment]
Just adding a note for future reference - minimum on scale down should always be one (just in case that wasn't clear from above).
