### ISSUE TITLE
Helm Param Update: Default to agones.controller if agones.extensions is Missing

### ISSUE THREAD

**Issue by Kalaiselvi84** [googleforgames/agones#3772]
**What happened**:
The Helm chart uses old parameters under `.Values.agones.controller` which were supposed to be migrated to `.Values.agones.extensions`.

**What you expected to happen**:
Replace with new parameters under `.Values.agones.extensions`. The Helm chart should allow for backward compatibility by defaulting to old parameters if new ones are not set.

**Anything else we need to know?**:
This issue requires updating the Helm chart to include fallback mechanisms using `default` and or `empty` functions to ensure configurations using old parameters still function correctly.

https://helm.sh/docs/chart_template_guide/function_list/#default
https://helm.sh/docs/chart_template_guide/function_list/#empty

**Comment by markmandel** [comment]
Just a note - it's not _all_ the .Values.agones.controller values, it's just the items that were highlighted in:
https://github.com/googleforgames/agones/pull/3735/files

So basically the things that affect the extensions - controller should stay the same.

**Comment by GOOFY635273529** [comment]
ok
