### ISSUE TITLE
Configurable Allocator HTTP status codes on failure

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#3780]
**Is your feature request related to a problem? Please describe.**

Right now, the Allocator HTTP Service returns a HTTP `429: Too Many Requests` if there is no `GameServer` available:

https://github.com/googleforgames/agones/blob/4bb673186b2ee8431de00c5c564bd1daa1a356df/pkg/allocation/converters/converter.go#L484-L494

Which is quite reasonable!

I'm digging into various service meshes, and they each like different HTTP codes for things like circuit breaking and/or retries or rate limiting.

For example, Istio will not circuit break on 429 ([closed issue](https://github.com/istio/istio/issues/41105)), [only on 5xx errors](https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking/#configuring-the-circuit-breaker).

**Describe the solution you'd like**

As part of the helm config, allow the user to specify which HTTP code they would like on a non-allocation through the HTTP service. Then we are future proofed for any Service Mesh that is utilised.

**Describe alternatives you've considered**

Leave things alone, but that will make things harder for any service mesh people use.

There is https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRetry - and could redirect to another cluster on failure, but that means each cluster gets pinged once, rather than dropping the request to the full cluster for a time period.

**Additional context**

N/A

**Comment by markmandel** [comment]
One possible extra wrinkles - it may need to be grpc status codes, such as what you see here:
https://pkg.go.dev/google.golang.org/grpc/codes#pkg-types

See: 

https://github.com/grpc-ecosystem/grpc-gateway/blob/b9de2f20010f706d6efd4b726daa2746a017cb37/runtime/errors.go#L36-L77

For the mappings.

**Comment by Kalaiselvi84** [comment]
Shall I work on this task?

**Comment by markmandel** [comment]
@Kalaiselvi84 sounds good!

**Comment by Kalaiselvi84** [comment]
Could you please confirm if the following steps are the correct approach?
1. Add new entry[HTTP_STATUS_UNALLOCATED] under the allocator section in the values.yaml.
2. Reflect the new env variable in the allocation.yaml.
3. Implement a function to fetch the code from the env variable[HTTP_STATUS_UNALLOCATED] in  the converter.go file. 
4. Use `helm upgrade` to deploy the changes.

**Comment by markmandel** [comment]
> Add new entry[HTTP_STATUS_UNALLOCATED] under the allocator section in the values.yaml.

I'm thinking something like:

`agones.allocator.service.http.unallocatedStatus` ? 

Since I think that would be the right nesting and semantic position.

And then yes, that would need to be arg passed into the Allocator Service.

> Implement a function to fetch the code from the env variable[HTTP_STATUS_UNALLOCATED] in the converter.go file.

You can extend the existing `viper` code to do the parsing. By default it should be http code 429 as it is now, if it's not set.

I think we'll have to be clear in the docs, that we are specifying which gRPC status to return. which is defined here (best reference I could find), and shows how gRPC codes are matched to HTTP codes :

https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto#L32-L185

🤔  there's an interesting question on how we can e2e test this without some kind of custom install. Will need to think on that one.

**Comment by markmandel** [comment]
Just reopening, as I noticed the PR has no docs 😄 

Can we add some docs to the Helm configuration page please?
