### ISSUE TITLE
Fleet autoscaler scale down delay

### ISSUE THREAD

**Issue by ytkang** [googleforgames/agones#3826]
**Is your feature request related to a problem? Please describe.**
I'm using the players counter method to manage auto-scaling, but it seems there isn't an option to delay scaling down. This sometimes leads to frequent and rapid fluctuations between scaling up and down. Since we need to scale up quickly, the scaling interval must be kept short.

**Describe the solution you'd like**
If there were an option to delay scaling down, that would be more effective to use

**Comment by markmandel** [comment]
This sounds like a job for a webhook autoscaler? 😄
