### ISSUE TITLE
Add runAsUser, runAsGroup, and allowPrivilegeEscalation to helm chart for Agones containers

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#3848]
**Is your feature request related to a problem? Please describe.**

Allow `securityContext` fields such as `runAsUser`, `runAsGroup`, and `allowPrivilegeEscalation` to be set on `agones-{allocator,extensions,controller,ping,sidecar}`

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Describe the solution you'd like**
Helm chart change

**Describe alternatives you've considered**
You can do this with `kustomize`.

**Comment by markmandel** [comment]
Not very familiar with these fields - but does it need to be configurable, or is this something we could set ourselves and leave on always?

On Agones we set the user and group, so that probably shouldn't be configurable? And I can't think of a situation where we'd want an Agones Pod to enable `allowPrivilegeEscalation`?

**Comment by ThatDevopsGuy** [comment]
@markmandel - I can't think of a reason why a game server would require a _specific_ UID/GID. I could imagine that some clients might want to bind to a privileged port to offer a some sort of file serving in-client (e.g. downloading a missing asset), however. Perhaps it's best to let it be easily configurable with overrides, should they be needed, but the defaults comply with existing K8S security audits.

**Comment by jharris-** [comment]
Should be good to add `runAsNonRoot` to avoid needing to set the UID/GID.
In addition to the initial request, could you add the `agones-gameserver-sidecar` to the scope of work?

**Comment by zmerlynn** [comment]
@jharris- Sure, sounds good!

**Comment by markmandel** [comment]
> @markmandel - I can't think of a reason why a game server would require a _specific_ UID/GID. 

This ticket isn't for `GameServer` pods though - you can set whatever you like on there via the `GameServer.Spec.Template` -- this is for the Agones components themselves.

I'm trying to work out why they should be configurable. It seems like they should be set to optimal values, whatever that may be.

**Comment by ThatDevopsGuy** [comment]
> I'm trying to work out why they should be configurable. It seems like they should be set to optimal values, whatever that may be.

Another way to put it might be, is there any reason why `runAsNonRoot` wouldn't work? I think that might be all we need across the board, so the specific request might be better expressed as such.

**Comment by markmandel** [comment]
> Another way to put it might be, is there any reason why runAsNonRoot wouldn't work? I think that might be all we need across the board, so the specific request might be better expressed as such.

I believe we are in furious agreement 😃

**Comment by zmerlynn** [comment]
That's good, because we were going to start with just defaulting this to `runAsNonRoot`, which will assert that the container images is doing the right thing.

But it's easy enough to make the `securityContext` blob configurable with that as the default. Are you saying it should not be?
