### ISSUE TITLE
Distributed defaults to using ListSortedGameServersPriorities when CountsAndLists is enabled

### ISSUE THREAD

**Issue by igooch** [googleforgames/agones#3862]
**What happened**:

Counters and Lists moved to Beta, so it's now on by default. If the scheduling type is set to `Distributed` it will execute the logic for CountersAndLists instead of the logic for `Distributed`. https://github.com/googleforgames/agones/blob/aa390f9f83564b04db9abd6dc985ca106cfa286f/pkg/gameserverallocations/find.go#L54

**What you expected to happen**:

If there are Counters and Lists Priorities https://github.com/googleforgames/agones/blob/aa390f9f83564b04db9abd6dc985ca106cfa286f/pkg/apis/agones/v1/fleet.go#L83, the allocator should use the Counters and Lists logic. Otherwise, the Allocator should use the `Distributed` logic.

**Comment by igooch** [comment]
@ashutosji let me know if you have any questions

**Comment by ashutosji** [comment]
> @ashutosji let me know if you have any questions

Sure, I will check and let you know if there any question.
