### ISSUE TITLE
Using portPolicy None results in a gameserver's port being 0

### ISSUE THREAD

**Issue by KAllan357** [googleforgames/agones#3867]
**What happened**:

I attempted to use the new feature in v1.41.0 to set my `portPolicy` to None and when my gameserver started, the gameserver's port in its status was set to 0. My gameserver code was written to take the Address and Port from the gameserver's status and use them for connections. When the port is 0, this failed.

**What you expected to happen**:

My expectation is perhaps that when `portPolicy` is set to None, the Port field of the gameserver's status would become equal to the `containerPort` value. In other words, to connect to a gameserver Pod with a None `portPolicy`, I would use the PodIP and the `containerPort` to connect. 

**How to reproduce it (as minimally and precisely as possible)**:

Use any gameserver spec and set its `portPolicy` to None.

```
portPolicy:
  - name: game
    portPolicy: None
    protocol: UDP
    containerPort: 1234
```

Check the status once the gameserver is running:

![image](https://github.com/googleforgames/agones/assets/221009/fe7ed462-9a18-49e0-be27-53fa516f3f30)

**Anything else we need to know?**:

**Environment**:
- Agones version: v1.41.0
- Kubernetes version (use `kubectl version`): v1.30.0-eks-036c24b
- Cloud provider or hardware configuration: AWS EKS
- Install method (yaml/helm): Helm
- Troubleshooting guide log(s):
- Others:

**Comment by daniellee** [comment]
Just to double check, it is behind a feature gate - have you enabled it?

https://agones.dev/site/docs/installation/install-agones/helm/#configuration - the value should be something like:`"PortPolicyNone=true"`

And could you show a bit more of your gameserver spec (with the sensitive info removed)?

**Comment by KAllan357** [comment]
I think we can probably close this.

![image](https://github.com/googleforgames/agones/assets/221009/47dac0b2-b55f-4ea2-ae18-616c52c4be06)

It looks like enabling the feature gate gets it to function the way I expect.

**Comment by markmandel** [comment]
> Okay, I did not use the feature gate. I would maybe expect to receive an error if I was trying to use an gated feature.

That is a bug though, if the feature gate is not enabled, we should throw a validation error. I'll leave this open, as we should fix this part.

**Comment by markmandel** [comment]
https://github.com/googleforgames/agones/blob/27bf8a3427b3a8ba44548e670b72cd61967b99d3/pkg/apis/agones/v1/gameserver.go#L514-L532

Is where the validation should be added (in case people are looking).
