### ISSUE TITLE
Allow Custom KUBERNETES_SERVICE_HOST and PORT Configuration for Agones Sidecar

### ISSUE THREAD

**Issue by Rkrushanovskij** [googleforgames/agones#3879]
**Is your feature request related to a problem? Please describe.**
I have a setup where services need to communicate with the Kubernetes API server via the server's public IP. This setup requires me to set a custom `KUBERNETES_SERVICE_HOST` and `..._PORT` for Agones services, which works. However, when I start a GameServer, the agones-gameserver-sidecar attempts to reach the default 10.96.0.1, resulting in a "Connection to Kubernetes service failed" error.

**Describe the solution you'd like**
1. The most flexible solution would be the ability to configure the sidecar from the GameServer specification.
2. Alternatively, adjust the Agones controller to support creation environment variables that allow it to receive `SIDECAR_KUBERNETES_SERVICE_HOST` and `..._PORT`.
3. Another option is to have the Agones controller set `KUBERNETES_SERVICE_HOST` and `..._PORT` for the sidecar to the same values the controller itself uses.

**Describe alternatives you've considered**
I have not found any viable alternatives, except for attempting to make the default network configuration work.

**Additional context**
None

**Comment by markmandel** [comment]
...having a public IP for your Kubernetes Control Plane seems like a bad security decision? 🤔

**Comment by Rkrushanovskij** [comment]
@markmandel Perhaps, but even if it isn't public and I use my own custom IP, not the default 10.96.0.1, there seems to be no way to start using a customized IP. The SDK service always uses the default IP even if the controller has been set up with a custom KUBERNETES_SERVICE_HOST.
By the way, I managed to set up and get it working with the default networking settings. However, I think such a feature could still be useful for some custom systems.

**Comment by markmandel** [comment]
My understanding is from https://kubernetes.io/docs/concepts/containers/container-environment/#cluster-information that if you have a custom Kubernetes service, that those environment variables should be available to all Pods on startup.

Basically assuming the cluster is setup correctly, Agones should require no changes since the environment variable will pass to client-go automatically.
