### ISSUE TITLE
Cloud Build script for simple genai server Example Image

### ISSUE THREAD

**Issue by ashutosji** [googleforgames/agones#3903]
**Is your feature request related to a problem? Please describe.**

Whenever we try to push the image to production using `make push` we get an authentication error.

**Describe the solution you'd like**

Add `cloudbuild.yaml` that will run the Makefile, to build the image with the details of the project it is in (so `us-docker.pkg.dev/${PROJECT_ID}/examples`) so it pushes the image to that project's repository. 
**Describe alternatives you've considered**

Leave this alone, and keep it as is. But gives a consistent experience for managing and pushing images.

**Additional context**
NA
**Examples checklist**

* [x] simple-genai-server

**Comment by markmandel** [comment]
This is done
