### ISSUE TITLE
Docs: Add Option for Extensions Components to use Host Network and Configure Ports

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#3911]
Wrap up work from #3895

Basically this PR was required for Cillium on EKS - we got the functionality merged but no docs.

We should have documentation for the new helm fields here:
https://agones.dev/site/docs/installation/install-agones/helm/

And also an update to our EKS guide:
https://agones.dev/site/docs/installation/creating-cluster/eks/

**Comment by markmandel** [comment]
@Orza are you able to write these docs so we can wrap up this work please?

**Comment by Orza** [comment]
> @Orza are you able to write these docs so we can wrap up this work please?

yes, sure

**Comment by markmandel** [comment]
![you are awesome](https://i.giphy.com/dXckBa1HDG86RqUh19.webp)

https://agones.dev/site/docs/contribute/ has details on how to hide new content and how to preview locally.
