### ISSUE TITLE
Clarrification on the metric `gameserver_creation_duration`

### ISSUE THREAD

**Issue by ldufresnegs** [googleforgames/agones#3980]
Hi,

I wanted to ask for clarrification about the intention from the metric `gameserver_creation_duration`, because when I read the description of it, I either don't understand the intention or it doesn't behave as expected.

My understanding is that it would measure the times it takes for a gameserver from the moment it's requested by the user to the moment it's ready in seconds. But, the longest histogram bucket is 3 seconds and the data I get are not realistic. I tried to follow a bit the code and if I didn't made a mistake, it seems to measure the duration of [this function](https://github.com/googleforgames/agones/blob/f6d81e674e6c0520b7777df9efe4bbb75ddc8c5c/pkg/client/clientset/versioned/typed/agones/v1/gameserverset.go#L121-L132).

So, is the intention of the function to measure this post request or is it to also include the time it took for the gameserver to be in the ready state?

To give some additional details on the reason why I noticed that is that I wanted use the metric to track how often a new nodes ends up being created in order for the gameserver to be created which takes a significant amount of time.

Thanks

**Comment by gongmax** [comment]
@vicentefb You may want to take a look at this

**Comment by vicentefb** [comment]
The metric effectively captures the total time spent within the `addMoreGameServers` function: https://github.com/googleforgames/agones/blob/c26f7371980418b56b816b13d265c9cc9d092f32/pkg/gameserversets/controller.go#L515 Once the function completes and returns, the metric recording stops.

This aligns with the intention of measuring the performance of the server-side creation process handled by this specific function.

The latency.record() call specifically measures the time taken for this function to execute, which includes:
* Creating GameServer objects in Kubernetes.
* Potentially waiting for resources to become available.
* Updating internal state and event logs.

But it doesn't include time for the game server to be Ready. 

Additionally, there's a PR in review #3947 which adds a dashboard for `agones_gameserver_state_duration` which measures the average time spent in every stage of a game server.

**Comment by vicentefb** [comment]
Correct, it doesn't include the time needed to allocate a pod. You can see the detailed Game Server state diagram here: https://agones.dev/site/docs/reference/gameserver/ it shows the Creation state being independent from the Starting and Allocating the pod. 

If you'd like to, you can share with you us your current test setup details so that we can try and reproduce it.

**Comment by ldufresnegs** [comment]
Ok, thanks for the confirmation. It all make sense, though I wonder if the most interesting metrics isn't the actual "start to create game server" up to "game server can be joined", but that might just be in our case. I was able to get something along those line with using the metrics tracking time spent in states, but still not quite the same.

In any case, thank you and I believe the issue can be closed.
