### ISSUE TITLE
Request to become approver of Agone repo

### ISSUE THREAD

**Issue by peterzhongyi** [googleforgames/agones#4007]
### GitHub Username
@peterzhongyi

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have read the [contributor guide](../../../CONTRIBUTING.md)
- [x] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gongmax
- @markmandel 

### List of contributions to the Agones project
- PRs reviewed:
  - #3994 
  - #3988
  - #3985
  - #3981 
- PRs authored: 
  - #3964 
  - #3962 
  - #3959 
  - #3869 
  - #3856
- Issues responded to:
  - #4004

**Comment by gongmax** [comment]
LGTM, Approved!

**Comment by markmandel** [comment]
LGTM, also approved!

**Comment by gongmax** [comment]
Granted the write access.
