### ISSUE TITLE
Request to become approver of Agones repo

### ISSUE THREAD

**Issue by vicentefb** [googleforgames/agones#4017]
### GitHub username
- @vicentefb 

### Requirements

- [x] I am actively contributing to Agones
- [x] I have reviewed the [contribution guidelines](https://github.com/googleforgames/agones/blob/main/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Agones Slack workspace](https://join.slack.com/t/agones/shared_invite/zt-2mg1j7ddw-0QYA9IAvFFRKw51ZBK6mkQ)
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines

### Sponsors
* @gongmax 
* @markmandel 

### List of contributions to the Agones project

* PRs reviewed:
    *  #3880 
    * #3893 
    * #3929 
    * #3934 

* PRs authored: 
    * #3769 
    * #3776 
    * #3809 
    * #3833 
    * #3842
    * #3849 
    * #3916 
    * #3921 
    * #3927 
    * #3948 
    * #3950 

* Issues responded to:
    * #3980

**Comment by vicentefb** [comment]
@gongmax @markmandel

**Comment by gongmax** [comment]
LGTM, Approved!

**Comment by thisisnotapril** [comment]
Access granted, let me know if you have any issues!
