### ISSUE TITLE
Fleet Autoscaler spawn extra gs

### ISSUE THREAD

**Issue by Oleksii-Terekhov** [googleforgames/agones#443]
I create fleet with fas (min:0, buffer:2, max:20) and notice strange random behavior: 
Start situation: two Ready gs in fleet. One fleet in whole k8s cluster. 

Legend: R - Ready, A - Allocated, U - Unhealty

- RR -> i allocate one gs: RA ->fas spawn two(!) additional gs: RRRA -> fas kill one RRAU -> RRA ->...

- RR -> i allocate one gs: RA ->fas spawn one additional gs: RRA -> i stop play, gs stopped: RRU -> fas spawn new gs(!): RRR -> fas randomly kill one gs: RR ->...

I watch by command:
```
 watch "kubectl get gs -o=custom-columns=NAME:.metadata.name,STATUS:.status.state,IP:.status.address,PORT:.status.ports[0].port -n lds"
```

Without any error in controller log - just info about gs/fleet manipulations :(

Bug: extra activity in k8s cluster, extra cpu/disk/memory used

**Comment by aLekSer** [comment]
I can not reproduce this bug on my GCloud test cluster. I am making allocations using this command:
kubectl create -f https://raw.githubusercontent.com/GoogleCloudPlatform/agones/master/examples/fleetallocation.yaml 
@Oleksii-Terekhov  can you please provide your configuration files for Fleet, FleetAutoscaler, FleetAllocation.
Also some cluster details (versions) would be very nice to see.

**Comment by aLekSer** [comment]
I noticed a very strange behaviour if I run `kubectl delete gs --all`
Out of 7 GameServers from which 5 was in Allocated state. For some seconds the state of GSs could be:
2 Scheduled; 2 - Ready; 2 - PortAllocation and 1 - Starting
After waiting the status would be 2 GameServeres in the ready state as in FAS you used in a description

**Comment by Oleksii-Terekhov** [comment]
agones 0.6.0 release
k8s v1.12.3
kubectl edit fas -n lds fas
```
apiVersion: stable.agones.dev/v1alpha1
kind: FleetAutoscaler
metadata:
  creationTimestamp: 2018-12-17T16:18:37Z
  generation: 1
  labels:
    owner_namespace: XXX
  name: fas
  namespace: lds
  resourceVersion: "68274"
  selfLink: /apis/stable.agones.dev/v1alpha1/namespaces/lds/fleetautoscalers/fas
  uid: 68c6b986-0217-11e9-baa1-3ef97b66a92a
spec:
  fleetName: xeen-fleet
  policy:
    buffer:
      bufferSize: 2
      maxReplicas: 10
      minReplicas: 0
    type: Buffer
status:
  ableToScale: true
  currentReplicas: 2
  desiredReplicas: 2
  lastScaleTime: 2018-12-17T16:26:30Z
  scalingLimited: false
```

**Comment by markmandel** [comment]
Doing some cleanup. I _think_ this can be closed now. Unless anyone objects, I'll close it in 3 days.

**Comment by markmandel** [comment]
No objections. Closing!
