### ISSUE TITLE
Write a guide for setting up Agones with taints and tolerations

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#491]
We should write a guide for setting up Agones with taints and toleration, so that Agones (and likely prom + grafana, if you are running them) are on their own machine(s), and gameservers run on their on machines -- and never the two shall meet.

This is how people should run it in production, so we should make it easy with a tool.

Stretch Goal: Make our `build` tooling do this by default on GKE.

**Comment by markmandel** [comment]
Flip side - our `build` tooling already does this, and it's part of our helm template. But we just need to write the documentation.

@jkowalski I've never played with this stuff, from memory, you did this work, yes?

**Comment by markmandel** [comment]
We have this section here:
https://agones.dev/site/docs/installation/helm/#installing-the-chart

Does that mean we can close this ticket?

@jkowalski you wrote this section - wdyt?

**Comment by markmandel** [comment]
Closing this now. We can reopen / create a new ticket if this comes up again.

**Comment by roberthbailey** [comment]
I've moved the instructions to the installation page along with the example of how to do it on a GKE cluster. I don't have an easy way to test EKS / AKS and the directions don't apply to minikube which has only a single node. 

How do folks feel about closing this (or moving it out of the 1.0 milestone)? Or if anyone can provide similar updates to configure EKS / AKS prior to the next release that'd be even better.

**Comment by markmandel** [comment]
I was thinking about this - I think I would feel comfortable closing this, if the section 

> By default Agones prefers to be scheduled on nodes labeled with stable.agones.dev/agones-system=true and tolerates the node taint stable.agones.dev/agones-system=true:NoExecute. If no dedicated nodes are available, Agones will run on regular nodes, but that’s not recommended for production use.

Was hosted up in the install section (or somewhere near it) at the top, rather than buried in the GKE section.

At least then we are explaining what needs to be done for all installations, but not providing examples (yet).

WDYT?

**Comment by roberthbailey** [comment]
That sounds like a great idea. I'll send a PR over to move it up and slightly reword the GKE section to close this out.
