### ISSUE TITLE
Speed up e2e tests

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#511]
Two things for speeding up end to end tests:

1) We can increase the `-parallel` setting on the e2e test command for our cloud build run, since it's mostly bound by the speed K8s processes our game servers, rather than cpu on the machine
2) Since we're using more resources, running more in parrallel, we can set lower than the default requests and limits on all the gameservers we are creating. [fleet.yaml](https://github.com/GoogleCloudPlatform/agones/blob/master/examples/simple-udp/fleet.yaml) is a good example.

**Comment by jkowalski** [comment]
I can work on that. Parallelism can't really be increased too much, until #497 is merged, otherwise the test becomes quite slow.

**Comment by markmandel** [comment]
Point No.1 is complete. Still need to implement No.2

**Comment by aLekSer** [comment]
I will open a small PR for Point 2.
Actually `stress-test-e2e` can be run on smaller clusters. (To reduce insufficientCPU errors on GS creating).

**Comment by roberthbailey** [comment]
e2e tests are getting slow again.... tests on PRs are now consistently taking >40 minutes. We need to look at what is taking the most time and then we can decide what to try and optimize. 

I've generated a graph of the build step dependencies for our cloudbuild:

![buildgraph](https://user-images.githubusercontent.com/7751204/61358760-e75be780-a82f-11e9-9634-fd43894de372.png)

in case that helps.

**Comment by markmandel** [comment]
`make build` is now 20+ minutes to run. This is likely also a large culprit.

**Comment by markmandel** [comment]
Can we close this now?

**Comment by markmandel** [comment]
e2e tests are running at 4-5 minutes, so I think this can be closed now.

**Comment by markmandel** [comment]
Doing some cleanup. I am going to close this, since I mentioned I would do it in September :smile:
