### ISSUE TITLE
Use batching in GameServerAllocation controller to improve throughput.

### ISSUE THREAD

**Issue by jkowalski** [googleforgames/agones#536]
To get better throughput in GSA controller we could do batching: group together N allocation requests, assign GS to each of them and individually commit in parallel.

**Comment by markmandel** [comment]
As a first step, I'm going to look into moving `GameServerAllocation` into a Aggregate API so we can have ore control over what happens with the API.

In theory, there should be no/minimal change to how GSA's work -- at least that's the plan :smile:

**Comment by markmandel** [comment]
The good news is - I have (some cleanup to do) an API extension working to do gameserver allocations. 

I've only implemented and supported the CREATE (HTTP: Post) method on the API, as without storage, it's really the only one needed. If people request it, I could look into the Watch function as well, if people want to watch for create events.

The annoying news is - each create API call has 60s to provide a response (although can keep processing in the background) -- which makes one of the long term goals, having a SDK.Ack() function for blocking on Allocation return) -- a little trickier. Or at least, with a shorter timeout than I may have liked.

Asking the community for feedback on that aspect ([slack](https://agones.slack.com/archives/C9DGM5DS8/p1550311673053600)):
> I'm wondering if a 30 second timeout (to give everything else some buffer) for that ack() to come back is reasonable or not? I can't imaging you would want to keep your players waiting that long anyway -- or is that too short a time? (could probably bump that out to 40 or 50 second if need be, but 30 is super conservative)

> (Basically, we'd wait for 30 second, and if we didn't get the ack back, we'd either delete the gameserver, or maybe kick it back to ready - haven't decided. Probably delete -- it's cleaner)

Regardless, this will now also allow us to batch, skip storage for the GSA, etc. And also make it easier if we decide to also provide a gRPC interface as well for allocation.

**Comment by ilkercelikyilmaz** [comment]
What is the number of per second allocations do we need to reach? I am running some load tests against the recent allocation changes I did (haven't been checked-in yet). I run 60 concurrent clients and the system can allocate around 60 gs per sec (Allocated 2999 gs in 50 secs). 

![image](https://user-images.githubusercontent.com/17522001/52987154-e624ac80-33ae-11e9-902e-fc2725363512.png)

**Comment by markmandel** [comment]
@ilkercelikyilmaz that's a huge improvement over what we had previously :fire: @pm7h do you have those numbers on hand? I can't seem to find them). Once we also incorporate #600 - I wonder if we might be very close to what we might need to be.

**Comment by pm7h** [comment]
Yes, it's a huge improvement. Last I ran my load tests, it took over a minute for 100 allocations. You can see those results here: https://github.com/GoogleCloudPlatform/agones/issues/412#issuecomment-457405264

**Comment by ilkercelikyilmaz** [comment]
I made couple changes after talking to Jarek (use Update instead of patch to prevent multiple allocations) and random gs selection from the top N (=20) available list to reduce the number of collisions
.
I also changes the test client to increase the QPS of the kubernetes client. 
With these changed I ran the test few times. With 16 concurrent client, system can allocate around 100 gs per sec (2800  gs allocated in 28 seconds).

![image](https://user-images.githubusercontent.com/17522001/53070323-9ec41c00-3493-11e9-9ea6-a0552d89c6a9.png)

**Comment by ilkercelikyilmaz** [comment]
I think this can be a good improvement but there is no urgency so we should keep it open. Not a blovker for 1.X though.
@markmandel , did you see my comment/findings on the recent change on PodList improvement?

**Comment by markmandel** [comment]
> I think this can be a good improvement but there is no urgency so we should keep it open. Not a blovker for 1.X though.

Good call :+1: I've moved it off the next milestone, but leaving it open.

> @markmandel , did you see my comment/findings on the recent change on PodList improvement?

I did but hard to determine why that is happening - would be useful to have the performance testing suite in open source in some way, so we can all test things. Might be good to do CPU flame graph to see where the bottlenecks are.

**Comment by ilkercelikyilmaz** [comment]
I ill try to check-in my load test in 0.11.

**Comment by markmandel** [comment]
I think this can be closed now! if you have objections, please say so, otehrwise I will close on Tuesday!

**Comment by markmandel** [comment]
No response! Closing! :smile:
