### ISSUE TITLE
SDK Build/test pipeline separation from build-image

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#599]
As we add more SDKs the `build-image` is getting more and stuff installed in it.

My proposal would be to find a way to have a smaller build image for each of the SDKs, to compile and test each SDK individualy, rather than have rust, and node and go, and C++ all live in the same build image.

This would also allow us to build and test each sdk in parallel, which is nice as well -- and also means that if you want to add a dependency to the top of the build-image - we aren't recompiling rust every time.

It should hopefully also lower the barrier to entry for new SDK developers as well.

Some initial, vague ideas
1. Have a central Makefile include for all SDKs, that does much of what the build/Makefile does - tagging based on sha, create build image for the sdk if it doesn't exist, etc (maybe it could be shared across the project? Also set a standard set of targets: build, test, etc.
1. Have a base SDK build image -- that sets the gRPC version, and likely includes protoc installed already. SDK authors can extend this, install their language of choice and move forward from there.
1. Update Cloud Build to manage these images as well - might be able to integrate this into the  build/makefile ?

Then we can strip Rust, compiled protoc, and C++ out from the build image, and that will lower it's size considerably, as well as make faster to build when updates occur.

**Comment by Kuqd** [comment]
I'll work on this.

**Comment by Kuqd** [comment]
To close this we should improve the ci. Currently building images each times.

**Comment by markmandel** [comment]
Feels like we an close this. WDYT?

**Comment by markmandel** [comment]
Looks like no objections! Closing!
