### ISSUE TITLE
Create a pull request template

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#608]
Documentation: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

I normally put them into `.github/PULL_REQUEST_TEMPLATE.md`.

**Comment by markmandel** [comment]
We have a few template here: https://github.com/GoogleCloudPlatform/agones/tree/master/docs/governance/templates

Work for you?

**Comment by roberthbailey** [comment]
I was thinking something more along the lines of what @thisisnotapril did for issues in https://github.com/GoogleCloudPlatform/agones/pull/708. I find that having some default text (e.g. explain what the PR does, whether it fixes an issue, a release note, etc) can help people craft much nicer PR messages than just borrowing the git commit text.

**Comment by markmandel** [comment]
Oh nice! Yes - this sounds great!
