### ISSUE TITLE
Remove PodAffinity from Pods under Packed Scheduling

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#613]
[Here](https://github.com/GoogleCloudPlatform/agones/blob/master/pkg/apis/stable/v1alpha1/gameserver.go#L419) we add a PodAffinity to `GameServer` pods to attempt to make game servers appear on nodes that already have GameServers.

I've been thinking, that in a cloud environment we actually don't care, and the scheduling hit we take is not worth it.

Basically, in a cloud environment, we're going to fill a cluster until the brim game servers, which, without pod affinity will happen naturally. In an autoscaling scenario, the fleet will adjust to the cluster size, as we grow, so again, we end up with a full cluster.

Allocation continues to be tightly packed, and Fleet scale down deliberately takes UnAllocated gameservers from nodes that have the least number - so we still end up with empty nodes on scale down, as the Fleet controller is what controls which GameServers are removed.

So I vote we drop the PodAffinity from the GameServer entirely, and remove the scheduling overhead - which while it will drop in 1.12, still doesn't give us much (or work that well - as #484 shows).

What say you all?

**Comment by Kuqd** [comment]
So it's not behaving correclty and without it gamservers are still packed ?

If yes, I'm all in to remove it, specially because of the scaling need.

**Comment by markmandel** [comment]
Correct-ish? More correct than without? I have a feeling it decides if it can't be perfect in the time allotted, it falls back to regular distribution.

**Comment by roberthbailey** [comment]
We discussed this issue during the community meeting today. Since we are planning on setting the default k8s version for the next agones release to 1.12 which has scheduling improvements it isn't clear how necessary this will be to do. 

The next step is to do some performance testing to see if removing podaffinity gets us any speed improvements with k8s 1.12.

**Comment by markmandel** [comment]
I think that this can be closed. I don't think we see a need to do this.

**Comment by markmandel** [comment]
Looks like nobody has objected. Closing issue.
