### ISSUE TITLE
Proposal: Migrate Build Automation to k8s prow.

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/agones#649]
Proposal Document: https://docs.google.com/document/d/1BOhIKP3N9TjOEUSn28jZvLSTFWrE7DKg66LANNerLdg
Open Match Issue: https://github.com/GoogleCloudPlatform/open-match/issues/107

**Comment by markmandel** [comment]
What sort of things do we need? Prow seems _very_ complicated.

> There was discussion of the future of build automation and the decision was to move to Prow for Open Match and Agones.

Where was this discussion? I don't see it here on Github. I would like to see a design ticket on this before making any decisions.

**Comment by jeremyje** [comment]
The plan is to use the k8s prow so we are not managing the instance. We mainly need to provide the config.yaml and plugins.yaml files.

In the Agones case it seems like it'll remove the need to have agones-bot.

**Comment by markmandel** [comment]
Was thinking about this today - would it be useful to have a list of all the custom CI/build pipeline things that currently exist?

**Comment by roberthbailey** [comment]
Yes, having a list would be very helpful.

**Comment by roberthbailey** [comment]
@Kuqd - I saw your (old) note in Slack about cloud build e2e vs. prow and thought we should re-open the discussion. I think it'd be a great topic for the community meeting scheduled on the 25th. Could you take another pass over the document before then and add some comments?

**Comment by roberthbailey** [comment]
@heartrobotninja - did you have any other comments you wanted to leave on the doc? As I mentioned in the above comment, I think this would be a great topic to discuss at the next community meeting (on the 25th of this month).

**Comment by Kuqd** [comment]
Will do ! Thank you

**Comment by roberthbailey** [comment]
This topic was discussed at the community meeting today ([notes](https://docs.google.com/document/d/1wbCU-wGy-_d5HawHJPTRP-dvL2h432cpcd4_SVp003o/edit#heading=h.a53ton7n5n5s)) and the consensus was that we should move to prow.

Since not everyone who wants to give input may have had a chance to attend the meeting, we are going to initiate a lazy consensus process now where we will start moving to prow unless anyone raises objections before May 1st (next Wednesday).

**Comment by roberthbailey** [comment]
Cloud Build has definitely been working for what we need. At this point I'm not seeing a strong reason to change things around. 

I don't know enough about Github Actions to know whether that would be an improvement, but if so we should open a separate issue to track it.

I'm going to close this issue as obsolete.
