### ISSUE TITLE
Create a Security Best Practices/Design Document for Agones

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/agones#651]
As Agones expands we'll need to provide guidance to customers on how to securely deploy it. More importantly we'll need best practices to make security informed decisions during our future designs to make sure that Agones is secure by default.

I'll publish a draft for community review/edits once it's ready. As a preview it'll be simply just an index of all the best practices and recommendations for the dependencies of the project and how it relates to the project.

**Comment by aLekSer** [comment]
Do we need to also verify support of `Sandbox Pods` ?
 https://cloud.google.com/kubernetes-engine/docs/concepts/sandbox-pods

**Comment by roberthbailey** [comment]
Things we could document:
- Our RBAC rules
- Firewall / open ports for game servers
- General k8s & containerization security best practices
- Certificates - e.g. yaml file gives everyone the same certs for allocator service and webhooks
- How to customize allocator service certs
- How to disallow a game server pod access to k8s (by default they have access via our rbac rules)
- Use of namespaces

**Comment by markmandel** [comment]
Reopening - looks like a bug in the bot. Should still be stale though.
