### ISSUE TITLE
Proposal: Additional logic to determine GameServer IP on barmetal k8s

### ISSUE THREAD

**Issue by Oleksii-Terekhov** [googleforgames/agones#668]
Current schema - use Node External IP if exist, else use Node Internal IP

This behavior restrict using Agones with custom bare-metal cluster with gray in-cluster IPs behind firewall/NAT or with several interfaces on each node

Proposal: Enrich "get GS IP" logic by additional layer - use optional explicit "node label" (specified in fleet manifest or hard-coded to controller ???) to get "node external IP" from node label. Maybe even if External IP exist and specified.

**Comment by markmandel** [comment]
This is super interesting - I've also been thinking about scenarios in which we may have 1 or more UDP proxies in front of Agones, and how we can support that.

_Should_ the GameServer / Node be aware of the public facing NAT/Proxy/firewall IP address, or is that the responsibility of  an external system? If we hide the external/internal IP, is that a bad thing?

Should we expand out Address values to match something like what Node has now? (and basically copy it over), so we expose both external and internal IPs if people want them on our game servers?

How are you solving this problem now?

**Comment by Oleksii-Terekhov** [comment]
Now Agones - it's pain for custom k8s, but we motivated to polish it. Also we cannot use public clouds with k8s due costs and security concerns.

Current state - use Agones GS only from internal network for testing.

Near future - create custom micro-service to port/ip remapping, even on k8s nodes with white IP. We try avoid risks at project launch.

Good future - use Agones GS on white/gray IPs, with/without proxy or routers, use straight and simle way to determine IP/port without code writing.

**Comment by Oleksii-Terekhov** [comment]
Use https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/ for bare-metal

**Comment by markmandel** [comment]
Thanks for the update - that is interesting!
