### ISSUE TITLE
SDK conformance harness

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#672]
A way for developers who want to develop / bring their own SDK to know that their SDK implementation is compliant with what we need it to do.

Ideally, I think it would _not_ involve a full Kubernetes install, or e2e test, but likely could be run on it's own - maybe as a binary / docker container? Something simple.

We could then integrate this into our CI system to run against existing SDKs, and ensure that they always pass. Right now, this could fail for anything other than our Go sdk.

Would need to have a way to skip tests as well - since we often have SDKs that are partial implementations.

Open to suggestions on what this should look like?

**Comment by aLekSer** [comment]
As I understand we should generate single GRPC/RestAPI client which would be calling SDK implementations one by one (each with unique hostnames). Nice approach which I found is to write golang declarative tests of the API:
[example](https://github.com/verdverm/pomopomo/tree/master/test/api)

**Comment by aLekSer** [comment]
I make a draft proposal on how the system of harness test could look like:
https://docs.google.com/document/d/1Qjy-wXA1wsZB8PE_CP_GCgnyWktySm_ytZgRUZ2wtCo/edit?usp=sharing

**Comment by markmandel** [comment]
Added a bunch of notes - PTAL

**Comment by aLekSer** [comment]
I found an absence of new `Allocate()` method in Rust (fixed in a PR), CPP and Unreal Engine SDKs.
https://agones.dev/site/docs/guides/client-sdks/#allocate

**Comment by markmandel** [comment]
Can we close this now? We have the harness after all.

**Comment by aLekSer** [comment]
Yes, we can close this PR now.

**Comment by markmandel** [comment]
Closing!
