### ISSUE TITLE
Add About page

### ISSUE THREAD

**Issue by thisisnotapril** [googleforgames/agones#690]
We should have a page that explains who founded Agones, works on it, why we made it, etc.

**Comment by CarlDionne** [comment]
That’s a good idea.   In fact Mark and I were discussing this :-).   I can provide the ubisoft side of the story - and Mark the google side.

**Comment by CarlDionne** [comment]
If you think this is interesting, of course!

**Comment by markmandel** [comment]
Do we want this to be an about page, or do we want this to be incorporated into the [Overview page](https://agones.dev/site/docs/overview/) ?

(Which I have had had a todo to rewrite for eons).

No strong opinions, just throwing the idea out there.

**Comment by thisisnotapril** [comment]
I'm thinking it's a standalone page where we can also highlight top contributors, leads, etc. I would prefer Overview to stay focused on the tech/getting started aspect.

**Comment by markmandel** [comment]
Sounds fair enough!

**Comment by roberthbailey** [comment]
It would be nice to write this up before 1.0, since I think it's something we'd want to highlight as we announce that the project is stable and ready for production use.

**Comment by markmandel** [comment]
Do we still need to do this?

**Comment by markmandel** [comment]
This has been stale since April. Closing.
