### ISSUE TITLE
sdk/cpp cmake build fails on Linux

### ISSUE THREAD

**Issue by devjgm** [googleforgames/agones#718]
This issue came up during #713, but I'm moving the relevant details into an issue so it can be tracked separately.

My system:
*  Debian Linux, rolling release `#1 SMP Debian 4.19.28-2rodete1 (2019-03-18 > 2018)`
* cmake version 3.12.1
* grpc is not installed locally on my machine

Here are the commands I ran in this repo and the output:
```shell
$ cd sdks/cpp/
$ cd build_scripts/
$ bash build.sh 
-- git Version: v0.0.0-dirty
-- Version: 0.0.0
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
CMake Error at CMakeLists.txt:177 (install):
  install TARGETS given target "address_sorting" which does not exist in this
  directory.


CMake Error at CMakeLists.txt:195 (install):
  install TARGETS given target "address_sorting" which does not exist in this
  directory.


-- Configuring incomplete, errors occurred!
See also "/home/jgm/github/devjgm/agones/sdks/cpp/.build/CMakeFiles/CMakeOutput.log".
See also "/home/jgm/github/devjgm/agones/sdks/cpp/.build/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'install'.  Stop.
```

**Comment by markmandel** [comment]
Seem like that should be called from within the Makefile that we use for testing?
https://github.com/GoogleCloudPlatform/agones/blob/master/sdks/cpp/Makefile#L25

@dgkanatsios  ?

**Comment by dsazonoff** [comment]
For testing we are using sdks/cpp/Makefile, but it is very similar. It looks like gRPC was downloaded by CMake from git without updating submodules. But I'm not sure, take a look a bit later.
Tested both scripts on Mac, it works. Same as raw CMake.

@devjgm thanks for the feedback. Please, also add a version of git that you use.

**Comment by devjgm** [comment]
`git version 2.21.0`

**Comment by aLekSer** [comment]
I have tested that following set of commands works on Debian linux:
```
cd ./sdks/cpp
sudo make clean
sudo make build
```

**Comment by markmandel** [comment]
Sounds like we can close this issue?

**Comment by devjgm** [comment]
No, I think there's still a problem.

1. `make` should not require root permissions, so if it does, that seems like a bug.
2. It still doesn't work on my machine. I just created a new docker container from the debian image. I installed g++ and cmake version 3.14.3. Then I ran

```
cd ./sdks/cpp
make clean
make build
```
and the output is:
```
root@bec41d7ed7f1 /v# uname -a
Linux bec41d7ed7f1 4.19.28-2rodete1-amd64 #1 SMP Debian 4.19.28-2rodete1 (2019-03-18 > 2018) x86_64 GNU/Linux
root@bec41d7ed7f1 /v# make clean
rm -rf /v//.build
root@bec41d7ed7f1 /v# make build
mkdir /v//.build
cd /v//.build && cmake .. -DCMAKE_BUILD_TYPE=Release -DAGONES_SILENT_OUTPUT=ON -G "Unix Makefiles" -Wno-dev -DCMAKE_INSTALL_PREFIX=.install
CMake Error at CMakeLists.txt:30 (_message):
  CMake step for grpc failed: 1
Call Stack (most recent call first):
  /usr/share/cmake-3.14/Modules/FetchContent.cmake:903 (message)
  /usr/share/cmake-3.14/Modules/FetchContent.cmake:939 (__FetchContent_directPopulate)
  cmake/Fetch_gRPC.cmake:39 (FetchContent_Populate)
  CMakeLists.txt:97 (include)


-- Configuring incomplete, errors occurred!
See also "/v/.build/CMakeFiles/CMakeOutput.log".
Makefile:26: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by markmandel** [comment]
Curious - is your docker image able to access the internet?

**Comment by devjgm** [comment]
yes. I also did `apt update; apt upgrade -y; apt install g++ cmake`, then the installed cmake was too old, so I installed it from https://github.com/Kitware/CMake/releases/download/v3.14.3/cmake-3.14.3-Linux-x86_64.sh

**Comment by riimi** [comment]
I have the same issue. My system is windows with wsl ubuntu. I got the following error during make. `Error removing directory "/go/src/agones.dev/agones/sdks/cpp/.build/grpc/.src".
CMake Error at .subbuild/grpc/tmp/grpc-populate-gitclone.cmake:21 (message):
  Failed to remove directory:
  '/go/src/agones.dev/agones/sdks/cpp/.build/grpc/.src'


CMakeFiles/grpc-populate.dir/build.make:91: recipe for target 'grpc/src/grpc-populate-stamp/grpc-populate-download' failed`
I cannot remove `sdks/cpp/.src/src/boringssl/crypto_test_data.cc` !

**Comment by markmandel** [comment]
Coming back to this - 
We updated our cpp example to be a full docker build:
https://github.com/GoogleCloudPlatform/agones/blob/master/examples/cpp-simple/Dockerfile

Hopefully that will resolve some issues.

**Comment by dsazonoff** [comment]
@devjgm please, could you try to build this PR? - https://github.com/GoogleCloudPlatform/agones/pull/803

**Comment by ksimir** [comment]
Just as a side note, I was testing to build that docker image of the cpp example from the **cpp-simple** folder and it wasn't working because it was pointing to a folder outside the context.

Using the following build command from the **agones** (root) folder, it worked.
docker build -t cppsample -f examples/cpp-simple/Dockerfile .

**Comment by markmandel** [comment]
@ksimir true true, the [readme](https://github.com/GoogleCloudPlatform/agones/tree/master/examples/cpp-simple) needs updating. The `Makefile` takes care of this, but it's not explained anywhere :confused:

**Comment by dsazonoff** [comment]
@devjgm #803 should solve this problem, it is already merged. Could you check it in your build environment, please?

**Comment by devjgm** [comment]
Yes, it worked. Some comments that would have made it a little easier.

1. Add some build instructions to the README.md file. I saw a Makefile, so I typed `make`, and I guess that worked.

2. The cmake files say they require version 3.13.0, which is newer than most Linux distros come with. Requiring only cmake 3.5.0 should be fine would work on pretty much all distros.

**Comment by roberthbailey** [comment]
Can this issue be closed out now that we only require cmake 3.5? @devjgm - do you want to add any extra instructions to the README before we close it out?

**Comment by markmandel** [comment]
Sounds like this can be closed. If I don't hear anything by next Monday, I'll close the ticket.

**Comment by devjgm** [comment]
Closing SGTM

**Comment by markmandel** [comment]
Oops, look  like we didn't close this. Closing now!
