### ISSUE TITLE
NodeJS example needs a description in the README

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#728]
Context:
https://github.com/GoogleCloudPlatform/agones/tree/master/examples/nodejs-simple

There was some confusion about what this was an example _of_. We should have a description of it's purpose in the README.md.

Maybe something similar to what we see in the C++ example:
https://github.com/GoogleCloudPlatform/agones/tree/master/examples/cpp-simple

**Comment by BradfordMedeiros** [comment]
So this is tangental to the issue , but a good place for it, some questions: 
1. Are you sure you want to expose the client field externally ?  Seems like an implementation detail of the client, not something that should be publically accessible (best would be to solve via scope, but _ is fine too)

And 

2. How do you close the connection?  Can you provide a top level close or something equivalent ?  I'd rather not touch the internal client .  I don't feel I should need to touch that to use the client.

3.  Node.js land mainly uses npm.  Is the gameplan to publish the client to npm ?  If not when using the library I need to treat this lib special when in reality is should just work like all my other dependencies.


Thanks !

**Comment by markmandel** [comment]
Apologies - not sure this is the right place. Once the description has been added to the example, this ticket will be closed, and your questions will be lost for all eternity :smiley: 

If there are improvement to the Node SDK itself, please file individual tickets for each issue :+1:, then they can be individually tracked and improved on (looks like this is two tickets - or maybe 2 PRs?)

**Comment by aLekSer** [comment]
This example was really useful to create my SDK harness test on Node JS.
Also note that license is missing also:
[index.js](https://github.com/googleforgames/agones/blob/master/examples/nodejs-simple/src/index.js)
