### ISSUE TITLE
apiserver role binding is referencing an invalid system account

### ISSUE THREAD

**Issue by bbf** [googleforgames/agones#805]
While updating the charts for Marketplace Click to Deploy support, I noticed that we are referencing a system account for the apiserver role binding that doesn't exist:

https://github.com/googleforgames/agones/blob/9a528f76f7c5b33d6fdffda79e188473e4fb58ed/install/helm/agones/templates/serviceaccounts/controller.yaml#L102

I have no idea why this is even working, but we should probably patch it to be correct.

**Comment by markmandel** [comment]
Closing this, as I think this has been solved.

For future reference, you can write `Closes #<num` on a commit message in github, to automatically close a backing issue.

https://help.github.com/en/articles/closing-issues-using-keywords
