### ISSUE TITLE
Lightweight servers

### ISSUE THREAD

**Issue by Cretezy** [googleforgames/agones#859]
My game is very simple, which requires no world simulation. It's mostly a couple (up to ~12 players) connected to a lobby. Think of a card game.

I'm not too sure I understand some parts of the documentation and had a couple of questions:

- How lightweight is a "game server"? If the game server is very light, will it create multiple servers on a single node?
- When deploying an update, I assume it will not destroy currently in-game servers, however will it clear empty servers and start new ones?
  - By "empty", I mean severs which never called the `Allocate` method
- Is there a way to un-`Allocate` a server? For example a player joins the lobby (sets it as `Allocate`), then leaves (still allocated, but empty)
  - Should `Allocate` only be ran when the game starts?
- When can force shutdowns happen? Assuming I'm running on GKE (non-preemptive), what are the conditions where my players will be disconnected?
- When creating a game server through the API, how long does it take to be ready for use (assuming the actual game server starts instantly)?

**Comment by markmandel** [comment]
Thanks for the set of questions:

> * How lightweight is a "game server"? If the game server is very light, will it create multiple servers on a single node?

A gameserver is as heavy as you make it. We use the default Kubernetes scheduler, so if you want to dig more into this, I suggest going through some Kubernetes tutorials.

> * When deploying an update, I assume it will not destroy currently in-game servers, however will it clear empty servers and start new ones?
>   * By "empty", I mean severs which never called the `Allocate` method

Have a look at this section: https://agones.dev/site/docs/getting-started/create-fleet/#7-deploy-a-new-version-of-the-gameserver-on-the-fleet

> * Is there a way to un-`Allocate` a server? For example a player joins the lobby (sets it as `Allocate`), then leaves (still allocated, but empty)
>   

Call `SDK.Ready()`

>   * Should `Allocate` only be ran when the game starts?

I think that is game specific. Will that work for your game? Are there potential race conditions?

> * When can force shutdowns happen? Assuming I'm running on GKE (non-preemptive), what are the conditions where my players will be disconnected?

As long as nothing catastrophic happens, they won't get disconnected. (unless you turn on things that will cause node shutdown, like auto update, etc - but you have control over that)

> * When creating a game server through the API, how long does it take to be ready for use (assuming the actual game server starts instantly)?

Containers spin up very fast. The hosted process is the bottleneck.

**Comment by Cretezy** [comment]
@markmandel 

My game goes roughly like this:
- Server is created (`SDK.Ready()`?)
- Players join the lobby (should it `SDK.Allocate()` when the first play joins the lobby, or when the game starts?)
- Game starts (once enough players have joined/timer)
- Game finishes

My edge case is going from ready to allocated, to potentially empty. This would be the Ready state right?

**Comment by markmandel** [comment]
Personally, I wouldn't generally have my lobby system attached to the my game servers, I'd have it as a separate stateless system -- but that is just me, and may not fit your use case. 

Allocated makes sure game servers can't be shut down, and that's a game specific decision. So if you gameservers with players in the lobby can be deleted, then you don't need to allocate.

It's not the same scenario, but https://agones.dev/site/docs/guides/gameserver-lifecycle/ and https://agones.dev/site/docs/reference/gameserver/ may provide some more details to help you make decisions.

**Comment by markmandel** [comment]
Closing this as I think this is answered, but let me know if we need to be reopened :+1:
