### ISSUE TITLE
how to transfer the game streaming to client side? use VNC or other protocol?

### ISSUE THREAD

**Issue by hhuchzh** [googleforgames/agones#872]
how to transfer the game streaming to client side? use VNC or other protocol?

**Comment by markmandel** [comment]
Sorry, I don't think I understand the question. Agones doesn't provide any streaming capabilities.

**Comment by hhuchzh** [comment]
@markmandel 
I mean how agones transfer the game's UI to client? and how client user transfer the  control command to game server? just use UPD protocol?

**Comment by markmandel** [comment]
Sorry, I think you may be mistaken about Agones's capabilities.

May I suggest reviewing the [Overview](https://agones.dev/site/docs/overview/) documentation, or maybe watch one of the [presentations](https://agones.dev/site/docs/third-party-content/videos-and-presentations/)?

**Comment by markmandel** [comment]
I'm going to close this, as I think this is answered.
