### ISSUE TITLE
C# SDK

### ISSUE THREAD

**Issue by TimoSchmechel** [googleforgames/agones#884]
Would be great to have a C# SDK. Ideally this would support .NET Core, Framework and potentially also Unity.

I saw some discussion in #395 regarding using a C# client based on HttpClient in Unity. The idea was dismissed on the grounds of it not being supported for some platforms such as WebGL, I think it would still be worthwhile as most unity game servers will be targeting the Windows or Linux platforms. Either way its still useful for the non Unity C# servers out there.

**Comment by markmandel** [comment]
I don't think we should worry about Unity for the C# client - it has it's own client already, which has nice integrations with the editor and is a good experience for the Unity user.

The C# client is for modern C#, and therefore can be a gRPC implementation.
