### ISSUE TITLE
Update to opencensus v0.22

### ISSUE THREAD

**Issue by pjayara-g** [googleforgames/agones#892]
This is from #831 . @markmandel suggested updating the version of opencensus. This bug is to track that.

**Comment by markmandel** [comment]
This still would be great - just need to split things in the commit -- you can see details in the #893 PR.

**Comment by markmandel** [comment]
gRPC has been updated, so we can now do this work! :fire:

**Comment by aLekSer** [comment]
This should fix the following error on allocation Metrics:
`Failed to export to Prometheus: inconsistent label cardinality: expected 1 label values but got 0 in []string(nil)`
https://github.com/googleforgames/agones/issues/1330#issuecomment-584737095

**Comment by aLekSer** [comment]
We have updated OpenCensus to the most recent release:
https://github.com/census-instrumentation/opencensus-go/releases/tag/v0.22.3
