### ISSUE TITLE
gameserver-allocator: helm chart is missing tolerations

### ISSUE THREAD

**Issue by daplho** [googleforgames/agones#901]
While installing agones with helm, I discovered that the `gameserver-allocator` is missing tolerations. Thus the component can only run on untainted nodes.

**Comment by daplho** [comment]
PR here: https://github.com/googleforgames/agones/pull/902

**Comment by daplho** [comment]
here is a new pull request with the correct identity: https://github.com/googleforgames/agones/pull/910

**Comment by pooneh-m** [comment]
Thanks @daplho.
@markmandel it seems like there are test coverage missing for this case? Do you have any thoughts on how we could we detect it sooner?

**Comment by markmandel** [comment]
Ooh! That's a good question. So right now the e2e cluster doesn't actually have a nodepool split between system components and gameservers - it's just one big default nodepool.

So I see two options, basically as addition to e2e tests:
1. Create a nodepool specifically for everything in `agones-system`. Write an e2e test that checks that ever pod in `agones-system` namespace is in the right nodepool.
2. Check every pod in `agones-system` to ensure it has the correct toleration applied.

No.1 checks the result, No.2 checks the implementation. Maybe both?

**Comment by markmandel** [comment]
Closing - we will create a new ticket for testing toleration in our e2e tests.
