### ISSUE TITLE
Should we rebase images from alpine to gcr.io/distroless/static ?

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#909]
Kubernetes has moved to using gcr.io/distroless/static for most base images (see https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md#implementation-history). We should investigate whether it makes sense to move from alpine to gcr.io/distroless/static for Agones.

**Comment by markmandel** [comment]
Going through old issues :smile: 

https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md

Looks like we should be able to switch straight to `gcr.io/distroless/static` without any issue.

**Comment by markmandel** [comment]
I'd like to return to this one day. Distroless is very much the "google way" - so at some point we should probably move over.

**Comment by roberthbailey** [comment]
@igooch - FYI

**Comment by markmandel** [comment]
I'm shifting this to "awaiting-maintainer" - I think we should do it.

**Comment by aimuz** [comment]
I have time for this.

**Comment by markmandel** [comment]
Starting on this right now - Alphin 3.14 stopped getting security updates in May, so seemed like a good time to make the change across the board.
