### ISSUE TITLE
Building the rust sdk leaves untracked files

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#912]
**What happened**:  Running `make build` results in

```
$ git st
...
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test/sdk/rust/Cargo.lock
	test/sdk/rust/target/
```

**What you expected to happen**: No untracked files after running a build

**How to reproduce it (as minimally and precisely as possible)**: `make build`

**Anything else we need to know?**:

I'm wondering if these files should be inside of the agones-build-sdk-rust docker image instead of on my host machine. Alternatively, they could be added to the `.gitignore`. 

**Environment**:
- Agones version: master branch
- Kubernetes version (use `kubectl version`): _n/a_
- Cloud provider or hardware configuration: Building locally on Mac OS X 10.14.5
- Install method (yaml/helm): _n/a_
- Troubleshooting guide log(s): _n/a_
- Others:

/cc @aLekSer

**Comment by aLekSer** [comment]
The problem with leaving files after make build is in command `make run-sdk-command-rust COMMAND=build` the image itself is built and have an access to build-sdk-images folder. Only when we run bash script `build` from this image we have an access to Agones repo root.
I think making I could divide build.sh into to parts -  one for `make build`, another for SDK conformance test related build steps.

**Comment by roberthbailey** [comment]
I noticed that the nodejs sdk leaves around similar files. Will your approach help for that as well?

**Comment by markmandel** [comment]
Any reason to not add these to .gitignore? Seems like the simplest solution?

**Comment by roberthbailey** [comment]
The reason I was thinking to put them into the build image is that it looked like if I deleted them and re-ran the build they needed to be recreated (and weren't stored in the docker image) which slowed down the build, so I thought that maybe they should be kept with the build artifacts. 

But as I mentioned above, `.gitignore` is definitely a way to fix the issue.

**Comment by aLekSer** [comment]
Thanks for the comments,
Currently the build.sh which we have actually does not create some binary practically useful, this is the test scenario of SDK conformance test. That's why I think better way would be not touch them at `make build` step and run in a following sequence of make targets:
1. build 
1. run-sdk-conformance-test SDK_FOLDER=rust
1. clean all artificats
 I reflected my idea in the PR linked.
