### ISSUE TITLE
Approver access for @roberthbailey

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#914]
### GitHub Username
e.g. @roberthbailey 

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have read the [contributor guide](../../CONTRIBUTING.md)
- [x] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markmandel 
- @Kuqd 

### List of contributions to the Agones project
- PRs reviewed (16):
  - https://github.com/googleforgames/agones/pull/699
  - https://github.com/googleforgames/agones/pull/714
  - https://github.com/googleforgames/agones/pull/756
  - https://github.com/googleforgames/agones/pull/761
  - https://github.com/googleforgames/agones/pull/772
  - https://github.com/googleforgames/agones/pull/777
  - https://github.com/googleforgames/agones/pull/778
  - https://github.com/googleforgames/agones/pull/779
  - https://github.com/googleforgames/agones/pull/793
  - https://github.com/googleforgames/agones/pull/887
  - https://github.com/googleforgames/agones/pull/890
  - https://github.com/googleforgames/agones/pull/898
  - https://github.com/googleforgames/agones/pull/899
  - https://github.com/googleforgames/agones/pull/891
  - https://github.com/googleforgames/agones/pull/907
  - https://github.com/googleforgames/agones/pull/908
- [PRs merged](https://github.com/googleforgames/agones/pulls?utf8=✓&q=is%3Apr+author%3Aroberthbailey+merged%3A<2019-07-16+) (12): 
  - https://github.com/googleforgames/agones/pull/790
  - https://github.com/googleforgames/agones/pull/857
  - https://github.com/googleforgames/agones/pull/870
  - https://github.com/googleforgames/agones/pull/871
  - https://github.com/googleforgames/agones/pull/873
  - https://github.com/googleforgames/agones/pull/874
  - https://github.com/googleforgames/agones/pull/881
  - https://github.com/googleforgames/agones/pull/882
  - https://github.com/googleforgames/agones/pull/888
  - https://github.com/googleforgames/agones/pull/895
  - https://github.com/googleforgames/agones/pull/896
  - https://github.com/googleforgames/agones/pull/897
- Issues responded to (sample set from the [0.12.0 milestone](https://github.com/googleforgames/agones/issues?utf8=✓&q=is%3Aissue+milestone%3A0.12.0+)):
  - https://github.com/googleforgames/agones/issues/732
  - https://github.com/googleforgames/agones/issues/717
  - https://github.com/googleforgames/agones/issues/703
  - https://github.com/googleforgames/agones/issues/751
  - https://github.com/googleforgames/agones/issues/491
- Issues created (5): 
  - https://github.com/googleforgames/agones/issues/608
  - https://github.com/googleforgames/agones/issues/744
  - https://github.com/googleforgames/agones/issues/745
  - https://github.com/googleforgames/agones/issues/909
  - https://github.com/googleforgames/agones/issues/912

**Comment by roberthbailey** [comment]
FYI, https://github.com/googleforgames/agones/blob/master/docs/governance/community_membership.md says to label the issue with the `meta` tag but prior to having commit access to the repo that isn't actually possible (which is something I hope to be able to fix with prow).

**Comment by markmandel** [comment]
A big yes from me! :+1:

**Comment by Kuqd** [comment]
Yes, Welcome aboard !

**Comment by markmandel** [comment]
Done!
