### ISSUE TITLE
Missing SDK Functionality across languages/engines

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#927]
We have a variety of SDK functionality, but it isn't implemented across all languages and engines.

This is a work-list of SDK functionality that still needs to be implemented, so we can track it in a single place.

## C++
- [x] Allocate()
- [x] Reserve(seconds)
- [x] Conformance tests

## Node.js
- [x] Reserve(seconds)

## Rust
- [ ] Reserve(seconds)

## Unity
- [x] GameServer()
- [x] Reserve(seconds)
- [x] WatchGameServer(callback)
- [ ] Conformance tests

## Unreal
- [x] Allocate()
- [x] GameServer()
- [x] Reserve(seconds)
- [x] SetAnnotation(key, value)
- [x] SetLabel(key, value)
- [ ] WatchGameServer(callback)
- [ ] Conformance tests
- [ ] Simple example showing how to use the SDK

**Comment by roberthbailey** [comment]
Looking at https://github.com/googleforgames/agones/blob/master/build/includes/sdk.mk only node, go, and rust have conformance tests, so I've added a checkbox to each of the other SDKs to add them.

**Comment by roberthbailey** [comment]
I have a PR for the missing C++ functions.

**Comment by steven-supersolid** [comment]
I'll take a look at Node.js

**Comment by markmandel** [comment]
Updated C++ checklist, due to #948

**Comment by roberthbailey** [comment]
@whisper0077 - do you have time to add the remaining functions to the Unity SDK?

**Comment by roberthbailey** [comment]
@YannickLange - do you have time to add the remaining functions to the Unreal SDK?

**Comment by roberthbailey** [comment]
Updated node.js checklist, due to #955.

**Comment by markmandel** [comment]
Came up in Slack - does Unity & Unreal need some kind of blocking `Connect()` function basically so they can also block to wait for the sidecar to come up?

We could do a polling operation on the `/healthz` endpoint, or even do what I did on the Rust SDK, and poll `GameServer()` until we get a valid response (since it's read only, and a cached value).

WDYT?

**Comment by markmandel** [comment]
Should we add a conformance test for REST api?

**Comment by aLekSer** [comment]
If conformance tests for REST API is needed I can add the support for existent 3: Go, Rust and NodeJS.

**Comment by markmandel** [comment]
I don't think we need REST conformation for languages we don't support REST for. Still waiting on some kind of licence/legal review to see what is possible with Unity/Unreal.

**Comment by markmandel** [comment]
Doing Rust::Reserve, because then that is closed out. Also I get to write some more Rust, and that makes me happy.

**Comment by aLekSer** [comment]
For SDK conformance tests:
- [ ] We need to run sdk server on distinct ports to run all SDK tests in parallel
this was mentioned in another thread leave it there as a checkbox

**Comment by markmandel** [comment]
Currently working on Unity, SDK.GameServer() -- I used swagger to generate the model and hand editing it, so that should hopefully save me some work.

/assign
