### ISSUE TITLE
Unable to build the rust-simple example

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#935]
**What happened**: Unable to build the rust-simple example. 

**What you expected to happen**: Build completes successfully.

**How to reproduce it (as minimally and precisely as possible)**: `cd examples/rust-simple; make build-image`

**Anything else we need to know?**: Here's the last bit of output from docker where the build fails:

```
Step 9/22 : COPY sdk/Cargo.toml /home/builder/agones/sdks/rust/
 ---> Using cache
 ---> bd867547e2cc
Step 10/22 : COPY sdk/Cargo.lock /home/builder/agones/sdks/rust/
COPY failed: stat /var/lib/docker/tmp/docker-builder692801886/sdk/Cargo.lock: no such file or directory
make: *** [build-image] Error 1
```

This may be related to https://github.com/googleforgames/agones/issues/912 -- should `Cargo.lock` be committed into the repo? 

I could probably create the file by running `build` before running `build-image`, but I don't have `cargo` installed on my Mac and the point of doing the build in the docker container is to have as few tools installed locally as possible. 

**Environment**:
- Agones version: master branch
- Kubernetes version (use `kubectl version`): _n/a_
- Cloud provider or hardware configuration: Mac 10.14.5
- Install method (yaml/helm): _n/a_
- Troubleshooting guide log(s):
- Others:

/cc @aLekSer @Kuqd

**Comment by aLekSer** [comment]
I found this documentation.
It seems that we need to add `Cargo.lock` as we use docker with a binary https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Also I will prepare a fix of rust version in a `rust-simple/Dockerfile`.
