### ISSUE TITLE
GameServerSet validation on Update - able to point GameServerSet to another Fleet

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#940]
It is allowed to change label in GameServerSet to point into another fleet.
```
  labels:
    agones.dev/fleet: simple-udp22
```
Old fleet it was pointing at would create a new GameServerSet.
**What happened**:
Create two fleets `simple-udp` and `simple-udp2`.
Update one GameServerSet of a fleet simple-udp2 to a fleet `simple-udp` using labels["agones.dev/fleet"].
New GameServerSet was created and two GameServerSet becomes managing fleet `simple-udp`.
**What you expected to happen**:
No changes to this label should be allowed.

**How to reproduce it (as minimally and precisely as possible)**:
Create two fleets with different names.
```
kubectl get gss
kubectl edit gss simple-udp2-v74qw
```
Change the label to point to `simple-udp`

```
kubectl get gss | wc -l
```
You would get now 3 GameServerSets and 2 Fleets.
By reproducing all steps from second you can create any number of GameServerSets. 
But GameServerSets should be equal number as Fleets.

**Anything else we need to know?**:
Logs from `kubectl describe fleet simple-udp`
```
Events:
  Type    Reason                 Age    From              Message
  ----    ------                 ----   ----              -------
  Normal  CreatingGameServerSet  5m18s  fleet-controller  Created GameServerSet simple-udp22-djtm5
  Normal  CreatingGameServerSet  4m48s  fleet-controller  Created GameServerSet simple-udp22-rj9gc
  Normal  CreatingGameServerSet  4m1s   fleet-controller  Created GameServerSet simple-udp22-7p9lm
```
**Environment**:
- Agones version: 0.11
- Kubernetes version (use `kubectl version`): any
- Cloud provider or hardware configuration: any
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by aLekSer** [comment]
Also it is allowed to update label in GameServerSet to nonexistent Fleet.

**Comment by markmandel** [comment]
I don't know if this is a priority. If users decide to mess with this stuff, isn't it really up to them to determine if they are playing with fire or not? :man_shrugging: 

I don't think we need to control every edge case for the users.

**Comment by aLekSer** [comment]
Yes, this is low priority issue. 
We could left as is, just if someone met this issue he could find this ticket to know that he do things wrong.

**Comment by roberthbailey** [comment]
I think this is actually working correctly. If you manually tweak labels so that they no longer match, you are manually divorcing the game server set from the fleet that was managing it, so you would expect the fleet to notice that it is no longer managing a gss and create a new one. The old one is now no longer being managed by a controller, just as if you had created the gss directly instead of using a fleet to create it. 

Note that this technique (for gss, gs, pods, etc) is part of the reason that k8s uses labels in the first place. It allows dynamic binding between controllers and controllees and this exact scenario you tested can be used for things like quarantining a group of pods / game servers: removing them from active management and match making while leaving them running for debugging.

**Comment by aLekSer** [comment]
> Note that this technique (for gss, gs, pods, etc) is part of the reason that k8s uses labels in the first place. It allows dynamic binding between controllers and controllees and this exact scenario you tested can be used for things like quarantining a group of pods / game servers: removing them from active management and match making while leaving them running for debugging.
Thanks for clarification. If this is useful for debugging than it should stay as is and we should expect some event (warning) to be generated from a `Fleet` that it got new `GameServerSet` assigned to it?

**Comment by markmandel** [comment]
What does Kubernetes do if you do this with Pods and Fleets? (or maybe ReplicaSets?)

I don't feel like it's that useful tbh, if you are messing with those labels, you likely know what you are doing -- GameServerSets aren't particularly documented, as they really are more of an Agones implementation detail.

At least in my opinion anyway.

**Comment by markmandel** [comment]
I'm going to advocate we close this issue, unless anyone has objections?

Nobody is really messing with GameServerSets directly?

**Comment by roberthbailey** [comment]
Let's put this on the agenda for the next community meeting and if no one has objected we can close it then.

**Comment by markmandel** [comment]
This has been in a "let's talk about this before closing" since 2020 😄 . I'm going to close it, and clean things up.
