### ISSUE TITLE
Allocator service doesn't stay in the agones-system nodepool

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#946]
**What happened**:

```bash
$ kubectl get pods -o wide --namespace=agones-system
NAME                                   READY   STATUS      RESTARTS   AGE     IP           NODE                                           NOMINATED NODE
agones-controller-77457589f5-sdvb5     1/1     Running     0          101s    10.20.3.21   gke-test-cluster-agones-system-40c28823-0h52   <none>
agones-delete-agones-resources-w5wnf   0/1     Completed   0          3m29s   10.20.7.86   gke-test-cluster-default-382b8031-ttl8         <none>
agones-ping-7695d9c968-5c9ch           1/1     Running     0          101s    10.20.3.23   gke-test-cluster-agones-system-40c28823-0h52   <none>
agones-ping-7695d9c968-ddfwj           1/1     Running     0          101s    10.20.3.20   gke-test-cluster-agones-system-40c28823-0h52   <none>
gameserver-allocator-d9cb74cf5-blfkd   1/1     Running     0          101s    10.20.6.85   gke-test-cluster-default-382b8031-90w1         <none>
gameserver-allocator-d9cb74cf5-ngsjc   1/1     Running     0          101s    10.20.7.87   gke-test-cluster-default-382b8031-ttl8         <none>
gameserver-allocator-d9cb74cf5-zvgt8   1/1     Running     0          101s    10.20.3.22   gke-test-cluster-agones-system-40c28823-0h52   <none>
```

**What you expected to happen**:

All of the allocator pods should be in the `agones-system` nodepool.

**How to reproduce it (as minimally and precisely as possible)**:

Install Agones. do a `kubectl get pods -o wide --namespace=agones-system`

if it doesn't happen first time, delete some of the allocator pods, and see them eventually end up in the default nodepool.

**Anything else we need to know?**:

**Environment**:
- Agones version: development
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): N/A
- Others: I thought this was fixed in #910 , but apparently not :disappointed:

**Comment by roberthbailey** [comment]
The agones-system node pool is 1 node large, correct? I'm guessing what happens is that the pod is still terminating when the scheduler is looking for a node on which to run the replacement. And if there isn't sufficient headroom to run another allocator pod on the single node in the agones-system nodepool then it would run on a regular node, since it's preferentially placed on that node pool but isn't restricted from running on other nodes.

**Comment by markmandel** [comment]
Ah, that is a good question. I can look into this, see what is happening.

**Comment by daplho** [comment]
Correct @roberthbailey, https://github.com/googleforgames/agones/pull/910 added `affinity` and `tolerations` to the gameserver-allocator. Tolerations allow the workload to run on nodes with taints. Affinity asks the scheduler to prefer scheduling the workload on the indicated nodes but does not force that behavior. Are we interested in forcing the workload be scheduled on specific nodes?

**Comment by markmandel** [comment]
Yeah, I don't think we want to force it. I'll expand the size of that nodepool to make some room and see if there is a difference. Maybe this leads to an increase in size in the nodepool config for agones-system.

**Comment by daplho** [comment]
Cool. To add to my understanding, is the nodepool you're referring to a nodepool for some internal cluster you're using to test agones?

**Comment by markmandel** [comment]
> Cool. To add to my understanding, is the nodepool you're referring to a nodepool for some internal cluster you're using to test agones?

Yeah. Probably unsurprisingly, I tend to mostly test on GKE.

**Comment by markmandel** [comment]
Just tested this again with a bigger agones-system nodepool - worked as expected. Closing bug.
