### ISSUE TITLE
Local SDK Server should update internal GameServer on Ready(), Allocate() etc.

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#958]
**Is your feature request related to a problem? Please describe.**

When using the Local SDK Server, `Ready()`, `Allocate()`, `Shutdown()`, `Reserve(seconds)`, do not change the state of the local `GameServer`, and do not fire watch actions.

It would be really nice if they did - especially since `SetLabel(...)` and `SetAnnotation(...)` do do this - so there is precedent.

**Describe the solution you'd like**

`Ready()`, `Allocate()`, `Shutdown()`, `Reserve(seconds)` should update the underlying `GameServer` record as appropriate for their logic, and fire `WatchGameServer` events as well that can be intercepted by the game server SDK.

**Describe alternatives you've considered**
Leaving it as is - but that does leave an inconsistent user experience - and one that I believe is less smooth. 

Users can edit a YAML file directly to make the same thing happen, but its far less intuitive and smooth an experience. 

**Additional context**

[Code](https://github.com/googleforgames/agones/blob/master/pkg/sdkserver/localsdk.go)

**Comment by aLekSer** [comment]
You can assign this to me, that's really frustrating fo developers who want to test their code versus local sidecar.

**Comment by markmandel** [comment]
Assigned!

**Comment by markmandel** [comment]
@aLekSer can we close this ticket now?

**Comment by aLekSer** [comment]
Yes, I think we can close this as long as we don't need to implement Unhealthy state logic for local GameServer.

**Comment by markmandel** [comment]
Oh that's an interesting question. I would say - since that isn't covered by this ticket, we can close this ticket. If we have users that want this functionality as part of the local SDK, we can include it there as well. 

How does that sound?

That also being said - should we add documentation to: https://agones.dev/site/docs/guides/client-sdks/local/ ? I'm thinking probably. WDYT?

**Comment by aLekSer** [comment]
> If we have users that want this functionality as part of the local SDK, we can include it there as well.

For health check it could be helpful and we can turn it off (so could support both options).
> That also being said - should we add documentation to: https://agones.dev/site/docs/guides/client-sdks/local/ ?

Definitely yes, I will explain current behavior of Local SDK in upcoming PR.

**Comment by markmandel** [comment]
All of this sounds good! Okay, let's not close this ticket then :+1:

**Comment by aLekSer** [comment]
Returning back to this ticket, will add documentation to https://agones.dev/site/docs/guides/client-sdks/local/ .

**Comment by markmandel** [comment]
I assume we can close this now?

**Comment by aLekSer** [comment]
Yes, now it is done
