### ISSUE TITLE
Configurable log level for agones sidecar

### ISSUE THREAD

**Issue by andrehp** [googleforgames/agones#971]
**Is your feature request related to a problem? Please describe.**

Currently the agones sidecar logs all received Health Pings and GameServer events with the log level INFO

**Describe the solution you'd like**

A way to control the log level to be sent to stdout, logrus already has such a feature: SetLevel. This would allow us to set the log level to WARN or ERROR and avoid seeing these logs, which currently just make it more harder to spot relevant errors.

**Additional context**

I did find the issue related to logs in Stackdriver (https://github.com/googleforgames/agones/issues/335), but it doesn't apply directly to our usecase, as we forward all stdout to our logging system.

**Comment by roberthbailey** [comment]
@andrehp - where would you expect to configure the log level? Would it be a per-gameserver / per-fleet configuration or would you expect it to be a cluster-wide setting?

For the first option one idea would be to add a new optional field to the [GameServerSpec](https://github.com/googleforgames/agones/blob/master/pkg/apis/agones/v1/gameserver.go#L127-L140) for sidecar configuration. It might initially only have the loglevel, but it could be extended later to add other user-configurable options. 

For the second option, it could be an install time flag in the helm configuration.

Or maybe there is another place that would make more sense.

**Comment by andrehp** [comment]
Hi! Thanks for the quick reply.

I was thinking about a per-fleet configuration, this would allow for different configurations for different fleets and allow us to customize the log level according to the needs of the fleet.

**Comment by roberthbailey** [comment]
That was my first thought too, but I wanted to make sure I wasn't over-designing.

**Comment by aLekSer** [comment]
Currently working on this option to implement this feature:
>For the first option one idea would be to add a new optional field to the GameServerSpec for sidecar configuration. It might initially only have the loglevel, but it could be extended later to add other user-configurable options.
