### ISSUE TITLE
Allocation policy needs to expose namespace of the targeted cluster

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#980]
[Allocation policy CRD](https://github.com/googleforgames/agones/blob/master/pkg/apis/multicluster/v1alpha1/gameserverallocationpolicy.go) is currently only exposing the LoadBalancer service endpoint for allocator service and not the namespace. This works fine if there is an allocator service for each namespace that game servers are deployed to https://github.com/googleforgames/agones/issues/854.

However, currently, there is only one allocator service deployed to agones-system namespace and it is assumed that all clusters in multi-cluster scenario are using the same namespace name for deploying game servers.

The solution is to expose namespace in allocation policy.
[Bonus: This also enables A/B testing on the same cluster by deploying two version of game servers and setting weight on allocation policy to redirect a percentage of traffic to a namespace in the cluster.]

**Comment by roberthbailey** [comment]
Since this is still a v1alpha1 API group (indicating active development) I'm OK changing this between 0.12 and 1.0.

**Comment by markmandel** [comment]
Can this now be closed?

https://help.github.com/en/articles/closing-issues-using-keywords might be useful going forward as well.

**Comment by pooneh-m** [comment]
Thanks. Didn't know about the keyword. Next time :)
