### ISSUE TITLE
No matches for kind "GameServer" in version "agones.dev/v1"

### ISSUE THREAD

**Issue by dfunk006** [googleforgames/agones#985]
**What happened**:
While running the following command:
`kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-0.12.0/examples/simple-udp/gameserver.yaml` 
the following error occurs:
`no matches for kind "GameServer" in version "agones.dev/v1"`

**What you expected to happen**:
up until yesterday I was seeing the output similar to:
`gameserver "simple-udp" created`

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce the error, run the following command:
`kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-0.12.0/examples/simple-udp/gameserver.yaml`

**Anything else we need to know?**:
This was working fine before the latest commit "Preparation for the 1.0.0 next release"

**Environment**:
- Agones version: 0.11
- Kubernetes version (use `kubectl version`): 1.11
- Cloud provider or hardware configuration: Google Kubernetes Engine (GKE)
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
- Others:

**Comment by dfunk006** [comment]
nvm - re-installed Agones and Kubernetes (version 0.12 and 1.12 respectively) and it's working properly now. Closing issue.

**Comment by podluzhnyi** [comment]
On version v1.22.2 kubectl this bug is actual
