### ISSUE TITLE
Release the agones image and install.yaml for the pre-release versions automatically

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#989]
Currently to try out new features and bug fixes checked in to Agones, one should wait until release or get the code and build it to get the install.yaml with the new images.

Agones pre-release versions should be available to try before official release. There should be a job that runs every few days to create a new version of the install.yaml and publish it as pre-release.

**Comment by markmandel** [comment]
Technically - we have this already :+1: . Every PR we make images available (and there are links on each PR), and we build on master on every commit as well (although we don't report this anywhere).

If we can come up with a way to bubbling up the builds we make from master, would that solve this problem?

**Comment by pooneh-m** [comment]
Exactly. It would be nice to release on demand a pre-release version that has changes. For example, if a memory leak bug is fixed, agones v1.0.1 would be released on demand (instead of waiting for 6 weeks to officially release) and anyone interested could upgrade to it.

**Comment by roberthbailey** [comment]
That has been done in the past, see https://github.com/googleforgames/agones/releases/tag/v0.8.1

**Comment by markmandel** [comment]
So for a critical bug type issue - we have a hotfix process for stable hotfix releases. This feels to me like a separate thing from wanting to make it easier to take development images for a spin for testing purposes.

I guess, which purpose are we looking at here?

**Comment by pooneh-m** [comment]
Not all bug fixes categorize as hotfix, but could be useful for others if released as a minor version. If a status field or metrics logging is added that is useful or there is an improvement in latency or availability, 6 weeks release with no intermediate releases may be too long and one week trial may not give enough time for receiving feedback before official release.

**Comment by markmandel** [comment]
There sounds like there are lots of meta points in here:

1. If we're advocating that customers should use master builds to get the latest features, then we have to support each and every commit. This kind of scares me to be honest :slightly_frowning_face: 
I know we can _say_ that they are development builds, but if it becomes the norm to run a development build, then I think that's the reality is the user expectation comes along with it.
     1. If it's a critical enough issue that a large number of users start running a development build to solve a critical problem -- then that should be a hotfix I should think?
1. I've curious why you think 6 weeks is too long for any kind of release. This actually seems like a very short time to me, in the grand scheme of things. But open to discussion on this topic.
1. It feels like you think 1 week between RC and stable release is too short (please correct me if I'm wrong). Maybe the conversations should be around making a change to the sprint length and time between RC and stable. (admittedly, I just picked values at the beginning of the project that made sense in my head.) I believe there are other projects inside Google that do a 4 week spring/2 week feature freeze cycle. Would that be better? 4 weeks always felt a little short to get things done in, but maybe that's just me)

This all being said, I'm not against providing some kind of page with a list of commits and their images that currently exist (we currently keep them for 30 days) -- assuming of course they build successfully. The website is an app engine app after all, so we should be able to build an endpoint with some dynamic content.

**Comment by markmandel** [comment]
From the meeting today, it sounds like a good interim solution would be:
1. Add to the build steps in cloud build, if it's master, push a value to GCS with the details of what the latest master image is
2. Then we could expose this on the Agones website as well, so people could install the latest build
3. This would also be useful for @roberthbailey perf testing as well.

**Comment by markmandel** [comment]
Doesn't seem like there is much request for this anymore? Marking as stale, but let me know if we feel like we should revisit.

**Comment by markmandel** [comment]
Closing this ticket now, it's been stale for 23 days  now.
