### ISSUE TITLE
The fleets "simple-udp" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

### ISSUE THREAD

**Issue by Omegastick** [googleforgames/agones#993]
**What happened**:
Running the ["create a fleet" quickstart guide](https://agones.dev/site/docs/getting-started/create-fleet/) at `kubectl scale fleet simple-udp --replicas=5` I am getting the following error:
```
The fleets "simple-udp" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

**What you expected to happen**:
I expect the fleet to be upscaled without error.

**How to reproduce it (as minimally and precisely as possible)**:
After starting a Minikube server:
```
kubectl apply -f https://raw.githubusercontent.com/googleforgames/agones/release-0.12.0/examples/simple-udp/fleet.yaml
kubectl scale fleet simple-udp --replicas=5
```

**Anything else we need to know?**:
The "create a GameServer" guide ran without issue.

**Environment**:
- Agones version: 0.12.0
- Kubernetes version (use `kubectl version`): v1.12.10
- Cloud provider or hardware configuration: Minikube on Ubuntu 16.04
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s): https://pastebin.com/j5qxRkAu
- Others:

**Comment by markmandel** [comment]
What version of `kubectl` are you using?

**Comment by Omegastick** [comment]
1.15.2, do I need to use an older version?

**Comment by markmandel** [comment]
Yep. I've seen this a few times with the 1.15.x kubectl client with older k8s versions.

Ideally, line up your kubectl version with your k8s version.

**Comment by Omegastick** [comment]
That fixed it, thanks!

**Comment by roberthbailey** [comment]
Kubernetes promises compatibility skew for kubectl at +/- one version from your cluster. So far a 1.12 cluster you should be fine with 1.11, 1.12, or 1.13 kubectl. Anything newer than 1.13 isn't guaranteed to work.

**Comment by ykzj** [comment]
same issue here,
client: 1.15.11
cluster: 1.15.12

**Comment by markmandel** [comment]
@ykzj - this is a known issue in kubectl 1.15.x
https://github.com/kubermatic/kubeone/issues/593

Upgrade your client to 1.16 as a workaround.

**Comment by dtgkeithmarsh** [comment]
I'm using Agones 1.17 on 1.20.9 on DO via Helm.
In a `registry.hub.docker.com/alpine/k8s:1.20.4` container (on Gitlab), when I try to apply my fleet spec to a running version, I get

    The fleets "f-name" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
